### ISSUE TITLE
Fourier for BlockGfs

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#106]
Hi,

It would be quite useful to have a function to Fourier/InverseFourier a BlockGf in the same way as I can invert a BlockGf at the python level:

e.g. G_iw <<= Fourier(G_tau)

Thanks,
Pri

**Comment by pseth** [comment]
Michel is working on this.

**Comment by parcollet** [comment]
so ... @mferrero : what is the status of this ?

**Comment by Wentzell** [comment]
Closed by fd46993
