### ISSUE TITLE
G.transpose() does not work for tails

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#114]
G.tanspose() apparently works incorrectly in the case of matrix GF. While the data seems to be OK, the tail is screwed up. I attach a little test demonstrating this.

from pytriqs.gf.local import *
from pytriqs.archive import *

g=GfImFreq(indices = range(10), beta = 40, n_points = 1000, name = "g")
Gloc=BlockGf(name_list=('ud',),block_list=(g,),make_copies = False)
Gloc <<= inverse(Omega)
nn=10
str=' '
for i in range(nn):
    str +=' %4.1f'%(Gloc['ud'].tail.data[2,i,i].real)
print 'Gloc first moment: ',str

Gtemp=Gloc.transpose()
str=' '
for i in range(nn):
    str +=' %4.1f'%(Gtemp['ud'].tail.data[2,i,i].real)
print 'Gloc.tanspose() first moment: ',str

**Comment by parcollet** [comment]
Is the pb still open for the master branch ?

**Comment by parcollet** [comment]
Retested Leonid bug report : I get on master 
Gloc first moment:     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
Gloc.tanspose() first moment:     1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
Looks this is fixed now.
