### ISSUE TITLE
Complex Operators, gf

### ISSUE THREAD

**Issue by MHarland** [TRIQS/triqs#116]
The multiplication of a complex with an operator of `pytriqs.operators.operators2.Operator` has no c++ overload, although with the old operators it does. Has it been forgotten?
```
from pytriqs.operators.operators2 import *
2 * c('up', 0) # works
(2 + 1j) * c('up', 0) # no c++ overload
```

**Comment by parcollet** [comment]
G(tau) generalized in master.
Generalization of cthyb under way.
