### ISSUE TITLE
Enhancement: construct many_body_operator out of scalar_t

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#130]
Today I realized that it is not so easy to construct an identity operator. The best solution I came up with was to write
```
auto Id = many_body_operator<double>() + 1.0;
```
which is quite awkward.
Would you mind adding a (explicit?) constructor `many_body_operator(scalar_t x)`?

**Comment by parcollet** [comment]
Why not ?

**Comment by krivenko** [comment]
Good, then I'll do it when I have some time.

**Comment by parcollet** [comment]
The question is : do we want to wrap it too ?

**Comment by krivenko** [comment]
> The question is : do we want to wrap it too ?

If you have no objections, I would wrap it just for the sake of consistency.
