### ISSUE TITLE
Compile in RedHat

### ISSUE THREAD

**Issue by pdelamora** [TRIQS/triqs#155]
I am trying to install TRIQS into my computer with RedHat, 
I have installed c++
     sudo yum install gcc-c++
the computer has Python
    python: /usr/bin/python /usr/bin/python2.7 /usr/lib/python2.7 /usr/lib64/python2.7 /usr/include
    /python2.7 /usr/share/man/man1/python.1.gz
I have done the two first commands;
    $ git clone https://github.com/TRIQS/triqs.git src
    $ mkdir build && cd build
but with the third I get;
*******************************************************************
sudo cmake -DCMAKE_INSTALL_PREFIX=triqs ../
-- Installation directory is /home/Programas/TRIQS/build/triqs
CMake Warning at cmake/FindCompilerCheck.cmake:69 (MESSAGE):
  

  ************************** WARNING ************************************

    Compiler not recognized by TRIQS : TRIQS may compile .. or not 

  ************************** WARNING ************************************

Call Stack (most recent call first):
  CMakeLists.txt:63 (find_package)

-- Compiler is  with version 
-- Compiling in C++11 mode
-- DYNAMIC Built 
-- -------- Python detection -------------
-- Python interpreter /bin/python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
CMake Error at cmake/FindPython.cmake:43 (MESSAGE):
  The script : import numpy

   did not run properly in the Python interpreter. Check your python installation.
Call Stack (most recent call first):
  cmake/FindPython.cmake:58 (EXEC_PYTHON_SCRIPT)
  CMakeLists.txt:106 (find_package)

-- Configuring incomplete, errors occurred!
*******************************************************************
I do not know what is missing.
             Pablo de la Mora

**Comment by pdelamora** [comment]
Dear TRIQS developers and users,
	It's me again.

	I had an incomplete version of Red Hat and also an old version of Fedora (17) so I changed to Fedora 20.

	In Fedora 20 the packages to install (apt-get install=>yum install) had a better performance, only 5 packages were missing;

	g++			=>	gcc-c++(.x86_64)
	libgfortran3, gfortran	=>	gcc-gfortran(.x86_64)

the other two had no clear equivalence

	 openmpi-bin,  openmpi-com

I installed

	yum install  mpich-devel.x86_64 openmpi.x86_64 openmpi-devel.x86_64 

with the hope that the 'mpi' packages would be included

After this I continued the TRIQS installation;

	git clone https://github.com/TRIQS/triqs.git TRIQS

but in the build directory the command

	cmake ../

gave errors;
	 mako.template and scipy 
were not found, so I installed

	yum install python-mako.noarch  scipy.x86_64

after this

	cmake ../

gave the errors;
*****************
-- IPython NOT FOUND 
...
-- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
-- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
CMake Error at CMakeLists.txt:145 (message):
  TRIQS requires MPI
*****************
I searched for 'mpi_c' and 'mpi_cxx' packages

	yum search MPI_C
		No matches found

================
At the end many issues were solved for but
	cmake
did not work well
	IPython, MPI_C and  MPI_CXX
seem to be missing and no equivalents were found for Fedora 20
================

        Yours


                              Pablo de la Mora

**Comment by pdelamora** [comment]
Thank for your quick responses at the beginning.

At that time I did not know how to install many packages and I did many mistakes.
Now I think I have come a long way and installing TRIQS in Fedora 20 has given few errors, so I feel that I am not very far from the full installation.
*****************************************************
This time I have not received a comment.
*****************************************************
I would like to know if there are no 
      IPython, MPI_C and MPI_CXX
equivalents.
========================
On the other hand you feel that there is no hope or that I am hopeless.
========================

     Saludos

               Pablo

**Comment by pseth** [comment]
Hi,
There should be equivalents, perhaps undera different name. Unfortunately I think none of the developers/expert users actually use Fedora, so we won't be able to tell you what. Have you tried searching for equivalents? I imagine some forums will have discussions on this..

**Comment by aichhorn** [comment]
From your messages I understand that you have already installed openmpi. So in my understanding the problem is not a missing package, but that cmake cannot find it. Try to locate your mpicc compiler (if which mpicc returns nothing, you have to update your PATH variable such that mpicc is in your path), and add -DMPI_C=/path/to/your/mpicc and -CMPI_CXX=/path/to/your/mpic++ to youir cmake command. Normally, the configuration of mpicc and mpic++ tells cmake then also the correct libraries to link to. Remember, MPI_C is NOT the name of a package (bot in fedore, not in ubuntu, not in any linux dist.), but the name of an environmental variable!!
the issue with ipython, i am not so sure. Normally, if you do not intend to use it (meaning using ipytriqs instead of pytriqs), then there is no need to install ipython. On computing cluster I had this several times, that ipython is missing, but the installation works nevertheless.

**Comment by pdelamora** [comment]
Dear Pseth,
     Thanks for your comment, as far as I know Fedora is the open source of RedHat so the packages should be the same or very similar.

Dear Aichhorn,
    I will look into these issues.
        Thank you very much

**Comment by pdelamora** [comment]
Dear Aichhorn
I am trying the issues that you suggested, when I run in TRIQS/buil
***  cmake ../src

I obtain one comment and two errors:
***    -- IPython NOT FOUND 

***   -- -------- MPI detection -------------
***   -- Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
***   -- Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
***   CMake Error at CMakeLists.txt:145 (message):
***        TRIQS requires MPI

so I try to find MPI;
*** find / -name '*mpicc*'
***     /usr/lib64/mpich/bin/mpicc
***     /usr/lib64/openmpi/bin/mpicc

so I tried to put these libraries into the cmake in the following way;
*** cmake -DMPI_C=/usr/lib64/mpich/bin/  -DMPI_CXX=/usr/lib64/mpich/bin/ ../src/
*** cmake -DMPI_C=/usr/lib64/openmpi/bin/  -DMPI_CXX=/usr/lib64/openmpi/bin/ ../src/
*** cmake MPI_C_LIBRARIES=/usr/lib64/mpich/bin/ MPI_C_INCLUDE_PATH=/usr/lib64/mpich/bin/ MPI_CXX_LIBRARIES=/usr/lib64/mpich/bin/ MPI_CXX_INCLUDE_PATH=/usr/lib64/mpich/bin/ ../src/

But I get the same result as with
***  cmake ../src

So, my question is; How I can include these libraries into the "cmake"

**Comment by pdelamora** [comment]
Dear Aichhorn
With respect to:
*** -- IPython NOT FOUND 
I think that there is no problem, it is not found but is not needed

**Comment by aichhorn** [comment]
First of all, it seems you have two different MPI implementations installed, mpich and openmpi. This might work, but it also could cause problems (e.g. linking against mpich, but using mpirun from openmpi). You might think of getting rid of one of them.
For cmake, try the following:
cmake -DMPI_C=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX=/usr/lib64/openmpi/bin/mpic++ ../src/
You have to give the executable, not only the path to it, this was maybe not so clear in my message.

**Comment by pdelamora** [comment]
Thank you for your quick reply, but unfortunately including the executables did not change the response


        Pablo

________________________________
De: Markus Aichhorn <notifications@github.com>
Enviado: martes, 27 de enero de 2015 01:42 p. m.
Para: TRIQS/triqs
Cc: delamora
Asunto: Re: [triqs] Compile in RedHat (#155)


First of all, it seems you have two different MPI implementations installed, mpich and openmpi. This might work, but it also could cause problems (e.g. linking against mpich, but using mpirun from openmpi). You might think of getting rid of one of them.
For cmake, try the following:
cmake -DMPI_C=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX=/usr/lib64/openmpi/bin/mpic++ ../src/
You have to give the executable, not only the path to it, this was maybe not so clear in my message.

-

**Comment by aichhorn** [comment]
What about 
cmake -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpic++ ../src/

And you could try to add /usr/lib64/openmpi/bin to your PATH variable, and something like /usr/lib64/openmpi/lib to your LD_LIBRARY_PATH (you have to check where the .so files are). Then cmake should find the compiler automatically (I guess).

**Comment by pdelamora** [comment]
Thanks Markus, it worked.

Now it does not find

    Boost


        Pablo


cmake -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpic++ ../src/

-- -------- Boost detection -------------
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1138 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:177 (find_package)


________________________________
De: Markus Aichhorn <notifications@github.com>
Enviado: martes, 27 de enero de 2015 01:58 p. m.
Para: TRIQS/triqs
Cc: delamora
Asunto: Re: [triqs] Compile in RedHat (#155)


What about
cmake -DMPI_C_COMPILER=/usr/lib64/openmpi/bin/mpicc -DMPI_CXX_COMPILER=/usr/lib64/openmpi/bin/mpic++ ../src/

And you could try to add /usr/lib64/openmpi/bin to your PATH variable, and something like /usr/lib64/openmpi/lib to your LD_LIBRARY_PATH (you have to check where the .so files are). Then cmake should find the compiler automatically (I guess).

-

**Comment by pdelamora** [comment]
The reply was:
CMake Error at /usr/share/cmake/Modules/FindBoost.cmake:1138 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:177 (find_package)

**Comment by pdelamora** [comment]
The libraries that I find are
/usr/lib64/libboost_thread.so.1.54.0
/usr/lib64/libboost_date_time.so.1.54.0
/usr/lib64/libboost_system.so.1.54.0

**Comment by aichhorn** [comment]
You have an incomplete boost installation. From your previous messages I can see that you tried to get libboost1.48-all-dev from the package manager, but obviously it did not work. Instead, you have some boost fragments ffrom boost version 1.54.
Two options: First, you try to get boost from another package, you need boost.mpi, boost.serialization, and boost.system, at least. Second option: You download boost sources from their homepage, compile and install it yourself. Then you set the environmental variable BOOST_ROOT to the installation directory of boost, and include the lib subdirectory in LD_LIBRARY_PATH. 
The second option is more work, but at least it works.

**Comment by pdelamora** [comment]
Dear Markus,

Thank you for your help!!!


From your comments I thought that my installation was wrong and I decided to reinstall Fedora 20 from the start and put everything.


As you mentioned the boost installation was incomplete, I found that some of the libraries were in

**        /usr/lib64

but the mpich were in

**        /usr/lib64/mpich/lib


So I could not use

**        cmake -DBOOST_ROOT=/usr/lib64/ ../src/

I copied in /usr/lib64

**        cp mpich/lib/*


After this I tried

**        cmake -DBOOST_ROOT=/usr/lib64/ ../src/


and it worked better but the reference to

**        pthread_create

was 'undefined' and

**        -lpthreads

could not be found as the following messages show

*-*-*-*-*

CheckSymbolExists.c:(.text+0x16): referencia a `pthread_create' sin definir
collect2: error: ld devolvió el estado de salida 1
gmake[1]: *** [cmTryCompileExec3025671920] Error 1
gmake[1]: se sale del directorio `/home/pablo/TRIQS/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec3025671920/fast] Error 2

File /home/pablo/TRIQS/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
*-*-*-*-*
/usr/bin/ld: no se puede encontrar -lpthreads
collect2: error: ld devolvió el estado de salida 1
gmake[1]: *** [cmTryCompileExec2318560806] Error 1
gmake[1]: se sale del directorio `/home/pablo/TRIQS/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTryCompileExec2318560806/fast] Error 2

*-*-*-*-*


Do you have any suggestions????


Thanks again


            Pablo


________________________________
De: Markus Aichhorn <notifications@github.com>
Enviado: miércoles, 28 de enero de 2015 03:12 a. m.
Para: TRIQS/triqs
Cc: delamora
Asunto: Re: [triqs] Compile in RedHat (#155)


You have an incomplete boost installation. From your previous messages I can see that you tried to get libboost1.48-all-dev from the package manager, but obviously it did not work. Instead, you have some boost fragments ffrom boost version 1.54.
Two options: First, you try to get boost from another package, you need boost.mpi, boost.serialization, and boost.system, at least. Second option: You download boost sources from their homepage, compile and install it yourself. Then you set the environmental variable BOOST_ROOT to the installation directory of boost, and include the lib subdirectory in LD_LIBRARY_PATH.
The second option is more work, but at least it works.

-

**Comment by aichhorn** [comment]
That means that your linker does not find libpthreads.so. Normally, they are system libs, so try 
'locate libpthreads.so'. 
This is a strange error, I've never had problems with pthread.
BTW, the fact that you copied the mpich libs into your /usr/lib64 has nothing to do with boost. Okay, if it works...
And since you installed Fedora from scratch, why didn't you try Ubuntu?

**Comment by pdelamora** [comment]
Dear Markus,

        Thank you again. It seems that the path with Fedora does not seem lead anywhere, so, as you suggested, I will try Ubuntu.


                Pablo

________________________________
De: Markus Aichhorn <notifications@github.com>
Enviado: viernes, 30 de enero de 2015 05:03 a. m.
Para: TRIQS/triqs
Cc: delamora
Asunto: Re: [triqs] Compile in RedHat (#155)


That means that your linker does not find libpthreads.so. Normally, they are system libs, so try
'locate libpthreads.so'.
This is a strange error, I've never had problems with pthread.
BTW, the fact that you copied the mpich libs into your /usr/lib64 has nothing to do with boost. Okay, if it works...
And since you installed Fedora from scratch, why didn't you try Ubuntu?

-
