### ISSUE TITLE
.imag/.real for BlockGfs

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#159]
Often, one wishes to look at the imaginary or real parts of a GF, ie. for each block. It would be nice to be able to do write ```oplot(G_iw.imag)``` instead of the clumsier oplot(G_iw['down'].imag).

**Comment by pseth** [comment]
I just checked this, looks like there is something wrong with the RI options. See the gist notebook here: https://gist.github.com/pseth/adec0b4daddadf3d53fd

To be investigated.

**Comment by parcollet** [comment]
Fixed. .imag and.real is removed, use plot (... mode = 'R', 'I') instead...
