### ISSUE TITLE
Installation problems on MacOSX : h5 

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#174]
Hi,
I tried installing TRIQS on MacOSX (Yosemite), and followed exactly the steps described under http://ipht.cea.fr/triqs/1.2/installation/osx_install.html (note: the version of hdf5 is hdf5-1.8.14). I put all output files in https://gist.github.com/tayral/de9b6e8ece896865dc55.

1) the cmake step seems to work (see **first_cmake**: there is a warning at the end, but vecLib, in particular, is found), but...
2) then I get the error in **make_pb_with_include**
3) when adding a line "#include  " to triqs/h5/group.hpp, the compilation goes further but I get **make_fixed_include**

I suspect this had to do with the warning message from **first_cmake**?

4) Note that if I try to rerun cmake (cmake .) after step 1), oddly enough, I get the following message : **second_cmake** (note line 39: Found HDF5: debug;HDF5_hdf5_hl_LIBRARY_DEBUG-NOTFOUND;...)

Any ideas?

Thanks
Thomas

**Comment by krivenko** [comment]
Concerning missing `H5P_DEFAULT`... This macro has been moved from `H5public.h` to `H5Ppublic.h` in HDF5 version 1.8.14.

**Comment by parcollet** [comment]
Ok, thanks. I will add the include then...

**Comment by tayral** [comment]
The H5P_DEFAULT issue is now fixed but I still have the other two problems:
- pb with MACOSX_RPATH upon first running cmake
- vecLib not found upon first compilation (although cmake says it is found)
- HDF5_hdf5_hl_LIBRARY_DEBUG not found upon running cmake a second time (cmake .)

**Comment by parcollet** [comment]
cmake --version ?

**Comment by tayral** [comment]
$ cmake --version
cmake version 3.1.0

**Comment by parcollet** [comment]
cmake 3.x has not been tested...
Is it the brew default now ??

**Comment by tayral** [comment]
yes indeed

**Comment by parcollet** [comment]
1- cmake warning.
That is a new policy for cake, 3.x.
Cf http://www.kitware.com/blog/home/post/510
2- veclib seems deprecated, one should use -framework Accelerate, cf
https://developer.apple.com/library/mac/documentation/MacOSX/Conceptual/OSX_Technology_Overview/SystemFrameworks/SystemFrameworks.html
It is easy to change the cmake for both issues, but I can not test on my older mac.
So I push them on the OSX branch.
Can you retest ? 

3) The last issue : do you have hdf5 installed ? cmake does find it !

**Comment by tayral** [comment]
1) the warning MACOSX_RPATH is gone
2) I still have the vecLib issue
```
 Linking CXX shared library libtriqs.dylib
ld: framework not found vecLib
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
3) HDF5 is detected at the first run of cmake:
```
-- -------- HDF5 detection -------------
-- Found HDF5: /usr/local/Cellar/hdf5/1.8.14/lib/libhdf5_hl.dylib;/usr/local/Cellar/hdf5/1.8.14/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib  
--  HDF5_LIBRARIES = /usr/local/Cellar/hdf5/1.8.14/lib/libhdf5_hl.dylib;/usr/local/Cellar/hdf5/1.8.14/lib/libhdf5.dylib;/usr/local/opt/szip/lib/libsz.dylib;/usr/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib 
-- hdf5 version: 1.8.1
```
...but at the second, cmake still displays the error:
```
-- --------------------------------------------
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
HDF5_dl_LIBRARY_DEBUG (ADVANCED)
    linked by target "gf" in directory /Users/thomasayral/Work/TRIQS/sources/triqs/pytriqs/gf/local
    linked by target "lattice_tools" in directory /Users/thomasayral/Work/TRIQS/sources/triqs/pytriqs/lattice
    linked by target "operators" in directory /Users/thomasayral/Work/TRIQS/sources/triqs/pytriqs/operators
    linked by target "random_generator" in directory /Users/thomasayral/Work/TRIQS/sources/triqs/pytriqs/random_generator
```
(etc)

**Comment by parcollet** [comment]
2) should be ok, I forgot  vecLib somewhere...
3) Strange. What is HDF5_dl_LIBRARY_DEBUG from the CMakeList
after the first run of cmake ?

**Comment by tayral** [comment]
3) --> not found (from what I remember)

**Comment by parcollet** [comment]
version of hdf5 ? brew ?

**Comment by parcollet** [comment]
CmakeList , line 250. Try to remove the HL, somethings the HL is packaged with libhdf5...

**Comment by parcollet** [comment]
@tayral : is it still open ?
