### ISSUE TITLE
G.total_density() does not handle correctly complex phase

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#175]
Hi,

I need to handle GFs, which can be multiplied by a complex phase. I noticed that G.total_density() in this case incorrectly returns a real number. The example is 

from pytriqs.gf.local import *
import numpy
mu=0.0
e0=-1.0
beta=40.0
nfreq=1000
phase=numpy.exp(numpy.pi*1j/4.0)
print 'phase = ',phase
g = GfImFreq(indices = ['0'], beta = beta, positive_only=False, n_points = nfreq)
G=BlockGf(name_list = ['ud'], block_list = [g] ,make_copies = False)
for s,g in G:
    g << inverse(Omega-e0)
for s,g in G:
    g*=phase
dens=G.total_density()
print 'dens = ',dens

which returns

>pytriqs test_mesh_1.2.py
phase =  (0.707106781187+0.707106781187j)
dens =  0.707106781187

if I remove .real in def total_density of pytriqs/gf/local/block_gf.py the result is the same, apparently, it is forced to be real in g.density() or somewhere else

**Comment by parcollet** [comment]
Reproduced. The pb is that the multiplication by a complex should simply not be allowed.
G is the fourier transform on a G(tau) which is by assumption **real**.
Functions using this gf use this assumption.
The (to be written) complex g(tau) would handle properly.
The point is therefore : 
  - why do you need this ? 
  - don't you rather need a complex gf ?
  - should we forbid this operation for real g(tau) ?
@mferrero : your opinion ?

**Comment by leopo** [comment]
This pb appears when I calculate "Green's functions" like that
G_AB=-<A|T[cc*]|B>, where |A>, |B> are atomic levels from Hub-I. Those GF are easy to get in Hub-I, but, of course, |A>, |B> can be multiplied by arbitratry phases. 
Then I am extracting different superexchange interactions from  products of those G_AB at different sites. 
The pb is that density() does not handle correctly these GF. It is easy to fix,I think, one just needs to sum over both positive and negative iw_n,  I added this possibility to density() in v. 0.8

**Comment by leopo** [comment]
somehow the formula disappeared, I meant G_AB=-(A|T[cc*]|B)

**Comment by parcollet** [comment]
Yes, we need to sum positive and negative omega, but real g(tau) only have positive one.
The point is that g * = complex_number for a real g(tau) leave g in a undefined state, 
it is meaningless... 
It seems to me that the only correct solution is to implement and use complex g(tau), and of course
fix the density accordingly, It is not hard, and we have already decided to do it in the last meeting...
@mferrero: for cc

**Comment by leopo** [comment]
OK
In this particular calculation I work only in the w space. So I was just defining those G_AB on a mesh from -w_n to  w_n and then calculating them directly in Hub-I

**Comment by parcollet** [comment]
Fixed by recent change to g(tau) complex
