### ISSUE TITLE
Installation with python modules in non-standard location

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/triqs#177]
TRIQS does not install automatically when some python modules are in non-standard locations. For instance, I installed mako and h5py manually in my $HOME (I have no root access there), so it is in $HOME/lib/python2.7/site-packages. This path is in the $PYTHONPATH, so cmake finds the modules and the configuration works. But invoking 'make' leads to an import error 'no module mako.template'. The reason is simple. make re-defines the PYTHONPATH variable, that is why non-standard locations (such as /usr/lib/python*) are not in the search path any more. The work around is to symbolically link the python module directories into the build directory. This works, but is not clean and nice.

The same happens on computing clusters, where the 'module' package is used to switch between different compilers, packages, versions, and so on. For instance, we have two different versions of numpy located somewhere in /opt, and 'module load numpy/1.*' sets the environment variables correctly to be able to import the modules. But then, make does not work for exactly the reason I described above.

Happens with cmake version 2.8.9 and 2.8.12.

**Comment by parcollet** [comment]
Suggestion: use virtualenv, it is designed to do precisely this transparently
(use the system packages and your own installed packages together).
Reopen if needed.

**Comment by HugoStrand** [comment]
I have a one line fix for this.

I hit the same problem installing Triqs in a cluster environment using a module system for individual python modules. For this setup to work `$PYTHONPATH` must be set correctly whenever executing python. However in `FindPythonWrapperMacro.cmake` the `$PYTOHPATH` is modified to only contain triqs, leaving python only with its standard libraries when making the mako-magic. Appending a simple `$ENV{PYTHONPATH}` fixes the problem (as long as you have `mako` and `scipy` globally installed of course), see below:

```
diff --git a/cmake/FindPythonWrapperMacro.cmake b/cmake/FindPythonWrapperMacro.cmake
index a1f4d4b..85c2267 100644
--- a/cmake/FindPythonWrapperMacro.cmake
+++ b/cmake/FindPythonWrapperMacro.cmake
@@ -18,7 +18,7 @@ macro (triqs_python_extension ModuleName)
  # Adjust pythonpath so that pytriqs is visible and the wrap_generator too...
  # pytriqs needed since we import modules with pure python method to extract the doc..
  add_custom_command(OUTPUT ${wrap_name} ${converter_name} DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/${ModuleName}_desc.py
-  COMMAND PYTHONPATH=${CMAKE_BINARY_DIR}/pytriqs/c++2py:${CMAKE_BINARY_DIR}/ ${PYTHON_INTERPRETER} ${CMAKE_CURRENT_BINARY_DIR}/${ModuleName}_desc.py
+  COMMAND PYTHONPATH=${CMAKE_BINARY_DIR}/pytriqs/c++2py:${CMAKE_BINARY_DIR}/:$ENV{PYTHONPATH} ${PYTHON_INTERPRETER} ${CMAKE_CURRENT_BINARY_DIR}/${ModuleName}_desc.py
    ${CMAKE_SOURCE_DIR}/pytriqs/c++2py/mako/xxx_wrap.cpp
    ${wrap_name}
    ${CMAKE_SOURCE_DIR}/pytriqs/c++2py/mako/py_converter.hpp
```

**Comment by Titan-C** [comment]
Is it possible to use python setuptools or distutils to take over the installation of the python bindings instead of using cmake just to copy the files to a location?

**Comment by parcollet** [comment]
Decision:
- Merge the patch by HugoStrand
- No we do not use setuptools (it can not handle the C++ part well).
