### ISSUE TITLE
How to get triqs version 1.2?

### ISSUE THREAD

**Issue by xiaoyukaka** [TRIQS/triqs#178]
Dear developers,
How to get triqs version 1.2?  I just find the version 1.0 on https://github.com/TRIQS/triqs.

**Comment by xiaoyukaka** [comment]
@pseth Could you help me?

**Comment by tayral** [comment]
The master branch is now version 1.2. So you do not need to do anything. Make sure your source is up to date by doing "git pull".

**Comment by aichhorn** [comment]
If git pull messes up your tree (some branches disappeared), then just delete your local repository and do a fresh git clone.

**Comment by xiaoyukaka** [comment]
I have done 'git pull' and my source is up to date.
'cd src && git tag' shows 1.0 and 1.1. there is no version 1.2.  Is it right?

**Comment by pseth** [comment]
Yes, everything after 1.1 belongs to 1.2.
