### ISSUE TITLE
compilation error gfv2.cpp on scientific linux 6

### ISSUE THREAD

**Issue by Bert-Tijskens** [TRIQS/triqs#180]
hi I am getting  a compile error while compiling triqs for our cluster with gcc 4.8.2.
all help is more than welcome.
cmake output included belows the error
the error:
...
[ 71%] Built target gf_scalar
[ 71%] Building CXX object test/triqs/gfs/CMakeFiles/gfv2.dir/gfv2.cpp.o
In file included from /apps/antwerpen/ivybridge/sl6/GCC/4.8.2/include/c++/4.8.2/bits/stl_pair.h:59:0,
                 from /apps/antwerpen/ivybridge/sl6/GCC/4.8.2/include/c++/4.8.2/utility:70,
                 from /apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/include/boost/config/no_tr1/utility.hpp:21,
                 from /apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/include/boost/config/select_stdlib_config.hpp:37,
                 from /apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/include/boost/config.hpp:40,
                 from /apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/include/boost/utility/enable_if.hpp:17,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/utility/macros.hpp:25,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/./clef/./clef.c11.hpp:24,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/./clef/clef.hpp:27,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/clef.hpp:1,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/arrays/indexmaps/cuboid/./../../impl/common.hpp:24,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/arrays/indexmaps/cuboid/./../common.hpp:23,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/arrays/indexmaps/cuboid/./domain.hpp:22,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/arrays/indexmaps/cuboid/map.hpp:22,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/arrays/array.hpp:23,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/arrays.hpp:27,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/./tools.hpp:22,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/block.hpp:22,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs.hpp:26,
                 from /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/test/triqs/gfs/gfv2.cpp:2:
/apps/antwerpen/ivybridge/sl6/GCC/4.8.2/include/c++/4.8.2/bits/move.h: In instantiation of ‘constexpr _Tp&& std::forward(typename std::remove_reference<_From>::type&&) [with _Tp = const triqs::gfs::gfs_expr_tools::scalar_wrap<int>&; typename std::remove_reference<_From>::type = const triqs::gfs::gfs_expr_tools::scalar_wrap<int>]’:
/user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/././gf_expr.hpp:60:121:   required by substitution of ‘template<class L, class R> decltype (triqs::gfs::get_gf_data_shape(forward<L>(l))) triqs::gfs::gfs_expr_tools::combine_shape::operator()(L&&, R&&) const [with L = const triqs::gfs::gfs_expr_tools::scalar_wrap<int>&; R = const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&]’
/user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/././gf_expr.hpp:109:54:   required by substitution of ‘template<class Tag, class L, class R> decltype (triqs::gfs::gfs_expr_tools::combine_shape()(g.l, g.r)) triqs::gfs::get_gf_data_shape(const triqs::gfs::gf_expr<Tag, L, R>&) [with Tag = triqs::utility::tags::multiplies; L = triqs::gfs::gfs_expr_tools::scalar_wrap<int>; R = const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&]’
/user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/././gf_expr.hpp:61:54:   required from ‘decltype (triqs::gfs::get_gf_data_shape(forward<L>(l))) triqs::gfs::gfs_expr_tools::combine_shape::operator()(L&&, R&&) const [with L = const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&; R = const triqs::gfs::gf_expr<triqs::utility::tags::multiplies, triqs::gfs::gfs_expr_tools::scalar_wrap<int>, const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&>&; decltype (triqs::gfs::get_gf_data_shape(forward<L>(l))) = const triqs::utility::mini_vector<long unsigned int, 3>&]’
/user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/././gf_expr.hpp:109:54:   required from ‘decltype (triqs::gfs::gfs_expr_tools::combine_shape()(g.l, g.r)) triqs::gfs::get_gf_data_shape(const triqs::gfs::gf_expr<Tag, L, R>&) [with Tag = triqs::utility::tags::plus; L = const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&; R = triqs::gfs::gf_expr<triqs::utility::tags::multiplies, triqs::gfs::gfs_expr_tools::scalar_wrap<int>, const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&>; decltype (triqs::gfs::gfs_expr_tools::combine_shape()(g.l, g.r)) = const triqs::utility::mini_vector<long unsigned int, 3>&]’
/user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/triqs/gfs/./gf.hpp:533:44:   required from ‘void triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::operator=(RHS&&) [with RHS = triqs::gfs::gf_expr<triqs::utility::tags::plus, const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&, triqs::gfs::gf_expr<triqs::utility::tags::multiplies, triqs::gfs::gfs_expr_tools::scalar_wrap<int>, const triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::tail, void>&> >; Variable = triqs::gfs::imfreq; Target = triqs::gfs::matrix_valued; Singularity = triqs::gfs::tail; Evaluator = void]’
/user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/test/triqs/gfs/gfv2.cpp:76:6:   required from here
/apps/antwerpen/ivybridge/sl6/GCC/4.8.2/include/c++/4.8.2/bits/move.h:89:7: error: static assertion failed: template argument substituting _Tp is an lvalue reference type
       static_assert(!std::is_lvalue_reference<_Tp>::value, "template argument"
       ^
make[2]: *** [test/triqs/gfs/CMakeFiles/gfv2.dir/gfv2.cpp.o] Error 1
make[1]: *** [test/triqs/gfs/CMakeFiles/gfv2.dir/all] Error 2
make: *** [all] Error 2

cmake output:
-- Installation directory is /apps/antwerpen/ivybridge/sl6/TRIQS/1.0
-- Compiler is gcc with version 4.8.2
-- Compiling in C++11 mode
-- DYNAMIC Built 
-- -------- Python detection -------------
-- Python interpreter /apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/bin/python
/apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/lib/python2.7/site-packages/setuptools-1.4.2-py2.7.egg/pkg_resources.py:979: UserWarning: /user/antwerpen/201/vsc20170/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
-- Python interpreter and modules are ok : version 2.7.6
-- PYTHON_INCLUDE_DIRS =  /apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/include/python2.7
-- PYTHON_NUMPY_INCLUDE_DIR = /apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/lib/python2.7/site-packages/numpy/core/include
-- PYTHON_NUMPY_VERSION = 1.8.0
-- PYTHON_SITE_PKG = /apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/lib/python2.7/site-packages
-- PYTHON_LIBRARY = /apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/lib/python2.7/config/libpython2.7.a
-- PYTHON_EXTRA_LIBS =/apps/antwerpen/ivybridge/sl6/libreadline/6.3-foss-2014a/lib/libreadline.a /apps/antwerpen/ivybridge/sl6/ncurses/5.9-foss-2014a/lib/libncurses.a -ldl -lm -lpthread -lutil
-- IPython NOT FOUND 
-- --------------------------------------------
-- Numpy include in /apps/antwerpen/ivybridge/sl6/Python/2.7.6-foss-2014a/lib/python2.7/site-packages/numpy/core/include
-- Python modules will be installed in /apps/antwerpen/ivybridge/sl6/TRIQS/1.0/lib/python2.7/site-packages/pytriqs
-- Preparing the various scripts 
-- -------- MPI detection -------------
-- MPI CXX compiler : /apps/antwerpen/ivybridge/sl6/OpenMPI/1.6.5-GCC-4.8.2/bin/mpicxx
-- MPI_COMPILE_FLAGS :  -fexceptions; -fexceptions 
-- MPI_CXX_INCLUDE_PATH : /apps/antwerpen/ivybridge/sl6/OpenMPI/1.6.5-GCC-4.8.2/include
-- -------- Boost detection -------------
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   mpi
--   serialization
--   system
-- Boost include dir: /apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/include
-- Boost libraries: /apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/lib/libboost_mpi.so;/apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/lib/libboost_serialization.so;/apps/antwerpen/ivybridge/sl6/Boost/1.55.0-foss-2014a-Python-2.7.6/lib/libboost_system.so
-- Checked max_align_t. No workaround needed
-- 64 bit machine : Adding -fpic 
-- -------- Lapack detection -------------
-- Lapack libraries : /apps/antwerpen/ivybridge/sl6/OpenBLAS/0.2.8-gompi-2014a-LAPACK-3.5.0/lib/libopenblas.so;/apps/antwerpen/ivybridge/sl6/OpenBLAS/0.2.8-gompi-2014a-LAPACK-3.5.0/lib/libopenblas.so
-- -------- HDF5 detection -------------
--  HDF5_LIBRARIES = /apps/antwerpen/ivybridge/sl6/HDF5/1.8.12-foss-2014a-serial/lib/libhdf5.so;/usr/lib64/libpthread.so;/apps/antwerpen/ivybridge/sl6/Szip/2.1-foss-2014a/lib/libsz.so;/apps/antwerpen/ivybridge/sl6/zlib/1.2.8-foss-2014a/lib/libz.so;/usr/lib64/librt.so;/usr/lib64/libdl.so;/usr/lib64/libm.so;/usr/lib64/libm.so;/usr/lib64/libpthread.so;/apps/antwerpen/ivybridge/sl6/HDF5/1.8.12-foss-2014a-serial/lib/libhdf5_hl.so;/apps/antwerpen/ivybridge/sl6/HDF5/1.8.12-foss-2014a-serial/lib/libhdf5.so 
-- hdf5 version: 1.8.1
-- -------- GMP detection -------------
-- GMP libs: /apps/antwerpen/ivybridge/sl6/GMP/5.1.3-foss-2014a/lib/libgmp.so /apps/antwerpen/ivybridge/sl6/GMP/5.1.3-foss-2014a/lib/libgmpxx.so
-- -------- FFTW detection -------------
-- -------- NFFT detection (optional) -------------
-- Could NOT find NFFT (missing:  NFFT_LIBRARIES NFFT_INCLUDE_DIR) 
-- Build type: Release
-- -------- git and hash detection -------------
/usr/bin/git: /apps/antwerpen/ivybridge/sl6/zlib/1.2.8-foss-2014a/lib/libz.so.1: no version information available (required by /usr/bin/git)
-- Git hash c11bf5f799da859bbec83c1e51b56326633e50d8
-- Git branch :  master
-- -------- Preparing python extension modules  -------------
-- Preparing extension module gf
-- Preparing extension module lattice_tools
-- Preparing extension module operators
-- Preparing extension module random_generator
-- -------- Preparing tests  -------------
-- Preparing extension module my_module
-- Preparing extension module my_moduleB
-- Preparing extension module test_g
-- -------- Making TRIQSConfig.cmake -------------
-- Configuring done
-- Generating done
-- Build files have been written to: /user/antwerpen/201/vsc20170/scratch/triqs-1.2/triqs/build

**Comment by krivenko** [comment]
This is a duplicate of #138.

**Comment by aichhorn** [comment]
Had the same yesterday on a cluster, also with gcc 4.8.2. The problem disappears with clang, for instance. The simple workaround for you (I did the same yesterday): You go to the source directory, locate gfv2.cpp, and just delete it. Then do a fresh build from scratch (which is done now without the gfv2 test). If you are as lucky as me, then all other things (including the ctqmc solver) work and all other tests pass.

**Comment by Bert-Tijskens** [comment]
many thanks
as a workaround this is a bit rough on the edges imho. the file is there for some purpose i presume
will try gcc 4.9.2 soon
On 21 Jan 2015, at 12:35, Markus Aichhorn <notifications@github.com<mailto:notifications@github.com>> wrote:


Had the same yesterday on a cluster, also with gcc 4.8.2. The problem disappears with clang, for instance. The simple workaround for you (I did the same yesterday): You go to the source directory, locate gfv2.cpp, and just delete it. Then do a fresh build from scratch (which is done now without the gfv2 test). If you are as lucky as me, then all other things (including the ctqmc solver) work and all other tests pass.

—
Reply to this email directly or view it on GitHub<https://github.com/TRIQS/triqs/issues/180#issuecomment-70822959>.

Dr Engelbert Tijskens
HPC Analyst
Flemish Supercomputer Center vscentrum.be<http://vscentrum.be>
CalcUA Core Facility uantwerp.be/calcua<http://uantwerp.be/calcua>
University of Antwerp www.uantwerp.be<http://www.uantwerp.be>
Middelheimlaan1 G.309, B-2020 Antwerp, Belgium
engelbert.tijskens@uantwerpen.be<mailto:engelbert.tijskens@uantwerpen.be>
++32 3 265 3879

**Comment by aichhorn** [comment]
It is a bit rough, yes. For me, the feature that I need is the solver, that is why I could live with the solution. Of course, if you want to use the library itself more extensively, than this workaround is really hazardous.

**Comment by parcollet** [comment]
Yes indeed it seems to be the same as #138.
It looks like the pb is a bug in gcc 4.8.2.
If I remember correctly : it is solved in 4.9.x, even in 4.8.3 (to be checked)
and it was not present in 4.8.2 Ubuntu 14.04 (default compiler, which is apparently patched from the 
original 4.8.2).
Our conclusion that it was not worth spending time for a workaround, 
we would simply upgrade the compiler to have the bug fixed.
