### ISSUE TITLE
two small install issues

### ISSUE THREAD

**Issue by Bert-Tijskens** [TRIQS/triqs#181]
To build TRIQS successfully the following changes were necessary to the code as
it was checked out on 2015 jan 21 from https://github.com/TRIQS/triqs.git

1) HDF5 issue
=============
see https://github.com/TRIQS/triqs/issues/174 for using HDF5/1.8.14
solve the problem by adding the following line 
#include<H5Ppublic.h>
to file triqs/triqs/h5/base_public.hpp, right after line
#include<H5Gpublic.h>
**with a little bit of preprocessor magic this can be probably be solved in a generic way**

2) CMake issue with mixing strings and list in handling CMake variable PYTHON_EXTRA_LIBS
=========================================================================
in file triqs/CMakeLists.txt
in section "# Python support" add this line 
 separate_arguments( PYTHON_EXTRA_LIBS )
just before  )
 set (TRIQS_LIBRARY_PYTHON ${PYTHON_LIBRARY} ${PYTHON_EXTRA_LIBS})
 set (TRIQS_INCLUDE_PYTHON ${PYTHON_NUMPY_INCLUDE_DIR} ${PYTHON_INCLUDE_DIRS})

the presence of some static libs in our python version caused PYTHON_EXTRA_LIBS to be treated as a string yielding some suspicious double qoutes in link.txt fields which caused weird link errors

Furthermore, regarding testing:
98% tests passed, 2 tests failed out of 130

Total Test time (real) =  38.62 sec

The following tests FAILED:
	104 - autocorrelation_time (Failed)
	105 - basic_statistics (Failed)
Errors while running CTest
make: *** [test] Error 8

kindest regards and thanks for the support
bert

**Comment by Bert-Tijskens** [comment]
it would also be useful to specify that gcc 4.9.1 is necessary to compile triqs rather than 4.8.1 on the web page http://ipht.cea.fr/triqs/1.1/install.html 
kindest regards
bert

**Comment by pseth** [comment]
Hi Bert,

I think gcc 4.9.1 is recommended for the v1.2 of the doc:
http://ipht.cea.fr/triqs/1.2/installation/install_options.html

@parcollet Perhaps we should make the v1.2 doc open by default!

Pri

**Comment by Bert-Tijskens** [comment]
i didnt find the 1.2 documentation, just a link in 1.1 could do …

On 22 Jan 2015, at 12:07, Priyanka Seth <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Bert,

I think gcc 4.9.1 is recommended for the v1.2 of the doc:
http://ipht.cea.fr/triqs/1.2/installation/install_options.html

@parcollet<https://github.com/parcollet> Perhaps we should make the v1.2 doc open by default!

Pri

—
Reply to this email directly or view it on GitHub<https://github.com/TRIQS/triqs/issues/181#issuecomment-71004892>.

Dr Engelbert Tijskens
HPC Analyst
Flemish Supercomputer Center vscentrum.be<http://vscentrum.be>
CalcUA Core Facility uantwerp.be/calcua<http://uantwerp.be/calcua>
University of Antwerp www.uantwerp.be<http://www.uantwerp.be>
Middelheimlaan1 G.309, B-2020 Antwerp, Belgium
engelbert.tijskens@uantwerpen.be<mailto:engelbert.tijskens@uantwerpen.be>
++32 3 265 3879

**Comment by parcollet** [comment]
Yes, the default master branch is now 1.2, but the default link to the doc is 1.1 ...
@pseth, @mferrero:  I have changed the default link to 1.2

**Comment by parcollet** [comment]
Ps : but we need to keep a link to 1.1 somewhere ...

**Comment by parcollet** [comment]
1) is solved in f3e9c97d5d396dd522d6e46aae807f46ff7275e5
2) thanks, done.
3) I would need the test log of cmake to understnad the issue for the failed tests.
cd test/triqs/statistics/
make test
more Testing/Temporary/LastTest.log 
Can you make a gist out of them ?

**Comment by parcollet** [comment]
The failed tests are likely due to a change in boost version.
Being fixed in another issue.
