### ISSUE TITLE
tails and green functions c++

### ISSUE THREAD

**Issue by facioj** [TRIQS/triqs#182]
Hi,

Only a few questions/comments regarding the use of TRIQS in C++. I'm using 1.0 so perhaps some are old problems. Any way, I put it here in case is useful for somebody else.

a) The following piece of code:

```
auto g = gf<imfreq,scalar_valued>{{10, Fermion, 1000}};
auto g2 = gf<imfreq,scalar_valued>{{10, Fermion, 1000}};
triqs::clef::placeholder<0> wn_;
g(wn_) << wn_+1;
g2 = g * g;
std::cout << "Tail: " << g2.singularity();
```

produces the following output:

```
Tail: tail/tail_view: min/smallest/max = -1 -1 7
 ...  Order -1 =
[[(2,0)]]
 ...  Order 0 =
[[(1,0)]]
 ...  Order 1 =
[[(0,0)]]
 ...  Order 2 =
```

I'm not sure I'm understand correctly, but, the leading order shouldn't be -2?

b) The following two Green functions should be equal, but they have different Matsubara sum. It appears to be due to a difference in their tail.

```
    auto g = gf<imfreq,scalar_valued>{{10, Fermion, 1000}};
    auto g2 = gf<imfreq,scalar_valued>{{10, Fermion, 1000}};
    triqs::clef::placeholder<0> wn_;
    g(wn_) << 1/ ((wn_+1) * (wn_+1)); //this one has some problem I think
    g2(wn_) << (1/ (wn_+1)) * (1/(wn_+1));

    std::cout << g.singularity() << std::endl;
    std::cout << g2.singularity() << std::endl;
```

c)  When I have a have matrix Green function:

```
    auto G = gf<imfreq>{{10, Fermion, 1000}, {2, 2}};
```

How can I access each element? I tried different things but didn't suceed. For example:

```
    G(wn_)[0,1] << wn_ + 1;
```

or

```
    G(wn_)(0,1) << wn_ + 1;
```

Thanks,
Jorge.

**Comment by tayral** [comment]
Hi Jorge,
Regarding a): the result is correct, the coefficients of the tail being defined as the coefficients in front of (i \omega_n)^{-n} (see http://ipht.cea.fr/triqs/1.x/reference/gfs/tail.html)
Regarding b): what is the output of your cout's?
Regarding c): *filling* each matrix component of a gf individually does not really make sense, does it? To *access* it, G[w](0,1) (with w defined in http://ipht.cea.fr/triqs/1.x/reference/gfs/c++/gf_subscript.html#gf-subscript)

**Comment by facioj** [comment]
Hi Tayral, 
Thanks for the answer.

a): Ok, then I don't understand.  
     I have g2 = (wn+1)*(wn+1) = wn^2+2wn +1.
     So, after multiplication there is a cuadratic term. ¿Shouldn't this be reflected in the large frequency expansion?
     Otherwise, if for example, I then calculate the inverse of g2, I would get wrong the coefficients of the large frequency expansion.
I mean the following:

```
auto invg2 = gf<imfreq,scalar_valued>{{10, Fermion, 1000}};
invg2 = 1/g2;
std::cout << "Tail: " << invg2.singularity();
```

Output:
```
Tail: tail/tail_view: min/smallest/max = -1 1 8
 ...  Order -1 = 
[[(0,0)]]
 ...  Order 0 = 
[[(0,0)]]
 ...  Order 1 = 
[[(0.5,0)]]
 ... 
```
But inv2g = 1 /(wn^2+2wn+1) goes as ~ 1/wn^2 -2 /wn^3 + ...
and the 'smallest' order should be 2. (?)

b): The output is:
```
tail/tail_view: min/smallest/max = -1 1 8
 ...  Order -1 = 
[[(0,0)]]
 ...  Order 0 = 
[[(0,0)]]
 ...  Order 1 = 
[[(0.5,0)]]
 ...  Order 2 = 
[[(-0.25,0)]]
 ...  Order 3 = 
[[(0.125,0)]]
 ...  Order 4 = 
[[(-0.0625,0)]]
 ...  Order 5 = 
[[(0.03125,0)]]
 ...  Order 6 = 
[[(-0.015625,0)]]
 ...  Order 7 = 
[[(0.0078125,0)]]
 ...  Order 8 = 
[[(-0.00390625,0)]]
tail/tail_view: min/smallest/max = -1 2 8
 ...  Order -1 = 
[[(0,0)]]
 ...  Order 0 = 
[[(0,0)]]
 ...  Order 1 = 
[[(0,0)]]
 ...  Order 2 = 
[[(1,0)]]
 ...  Order 3 = 
[[(-2,0)]]
 ...  Order 4 = 
[[(3,0)]]
 ...  Order 5 = 
[[(-4,0)]]
 ...  Order 6 = 
[[(5,0)]]
 ...  Order 7 = 
[[(-6,0)]]
 ...  Order 8 = 
[[(7,0)]]
```
and the Matsubara sums are:
```
std::cout << density(g) << std::endl;
std::cout << density(g2) << std::endl;
```
Output:
```
0.250179
-0.000453959
```
I checked that in the frequency domain the two Green functions are the same.

c) Ok thanks. I wanted to initially fill a 2x2 gf like this: 
      (wn_+e      V      )
      (     V     wn_+e  )
This can be done in the python interface but not in c++ code. ¿I understand correctly?

**Comment by tayral** [comment]
Hi,
Your point seems fair to me: the high-freq expansion of (iw+1)(iw+1) should indeed take the quadratic term into account in order to yield a correct tail for its inverse -- which it doesn't because so far only moments from the linear term onwards (and then constant, then 1/iw etc.) are taken into account.
You can solve your problem as you mentioned, namely by writing 1/(iw+1) * 1/(iw+1).
@parcollet and @mferrero : what do you think?
As for the c), I guess filling with w_n*Id + ((0,V),(V,0)) will work (where Id is a  2x2 identity matrix)

**Comment by parcollet** [comment]
a) is a bug. It should be correct or throw, and indeed it must be at -2.
Assigned to me.

**Comment by parcollet** [comment]
@tayral :pls retest

**Comment by tayral** [comment]
Now, the output is:
```
Tail: tail/tail_view: min/smallest/max = -1 -1 7
 ...  Order -1 = 
[[(2,0)]]
 ...  Order 0 = 
[[(1,0)]]
 ...  Order 1 = 
[[(0,0)]]
 ...  Order 2 = 
[[(0,0)]]
 ...  Order 3 = 
[[(0,0)]]
 ...  Order 4 = 
[[(0,0)]]
 ...  Order 5 = 
[[(0,0)]]
 ...  Order 6 = 
[[(0,0)]]
 ...  Order 7 = 
[[(0,0)]]
```

**Comment by parcollet** [comment]
@tayral : what is the status of this ?

**Comment by parcollet** [comment]
@tayral : is the pb fixed ?

**Comment by parcollet** [comment]
Obsolete in 2.0
