### ISSUE TITLE
-L$CMAKE_PREFIX_PATH/lib is not passed to $TRIQS_LIBRARY_ALL

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#183]
Good evening,

I've just noticed a subtle installation issue, which is, however, prevents me from installing the applications on a machine with completely outdated software. To overcome the old libraries and compilers shipped with the distro, I created a local installation prefix `~/LIBS`. There I put gcc-4.9, a new Python and a dozen of the libraries TRIQS is dependent on. Then I ran cmake as
```
cmake -DCMAKE_PREFIX_PATH=${HOME}/LIBS -DCMAKE_INSTALL_PREFIX=${HOME}/TRIQS ...
```
and successfully built the library. Everything had been fine until I tried to install cthyb under `${HOME}/TRIQS`. The linker refused to find many libraries, because `${HOME}/LIBS/lib` was missing from `$TRIQS_LIBRARY_ALL`. Would it make sense to include `-L${CMAKE_PREFIX_PATH}/lib` into `TRIQS_LIBRARY_ALL`, if former variable is explicitly set by the user?

**Comment by parcollet** [comment]
Why do not you configure the applications with 
cmake -DCMAKE_PREFIX_PATH=${HOME}/LIBS
as well ?

**Comment by krivenko** [comment]
I was sure I tried what you suggest... And for some reason it did not work.
Nonetheless, everything goes smoothly now, if I pass `-DCMAKE_PREFIX_PATH` to the application too.
So, thank you for the tip! The issue is closed.
