### ISSUE TITLE
failed triqs install on arch linux

### ISSUE THREAD

**Issue by Titan-C** [TRIQS/triqs#184]
I'm trying to compile triqs on arch linux.
on gcc 4.9.2 from the distribution
on boost 1.57.0 compiled from source
using an anaconda virtual environment to work on python 2.7 as the arch default is 3.4
gist link of cmake output and make fail is at
https://gist.github.com/Titan-C/b4a313718b76ed78ead9

**Comment by aichhorn** [comment]
Hm, seems to be a problem with your Boost MPI installation. Is this a system boost, or did you compile it yourself? I think to remember that I had a similar problem once, which I solved by compiling boost myself and linking to this build, and not the system boost.

**Comment by aichhorn** [comment]
Sorry, just saw that you compiled boost yourself. Did somebody try Boost 1.57 yet? I know that 1.49 and 1.55 is working.

**Comment by parcollet** [comment]
I agree it is a problem with boost.mpi. 
Can you cd to test/triqs/gfs/ 
and make VERBOSE=1 mpi_red 
it will give us the exact linking command.
Are you sure that you compile *and link* against the boost you compiled
(and e.g. not linking against a default system boost ?).

**Comment by parcollet** [comment]
Btw: why did you need to recompile boost ?

**Comment by Titan-C** [comment]
This is the gist with make VERBOSE=1 mpi_red 
https://gist.github.com/Titan-C/b4a313718b76ed78ead9#file-mpi_red-verbose

Yes the compilation is linked against my source compiled boost. The address is the usual system installed as arch linux lets you choose at install time to use system binaries or compile them from source.
I recompile boost from source as in arch openmpi support is not linked by default in the system binaries.

**Comment by Titan-C** [comment]
One extra information. On my personal laptop I have the same system as in my lab workstation
on gcc 4.9.2 from the distribution
on boost 1.57.0 compiled from source
using an anaconda virtual environment to work on python 2.7 as the arch default is 3.4
but the compilation fail even earlier with a different error
https://gist.github.com/Titan-C/b4a313718b76ed78ead9#file-on-personal-laptop

**Comment by tayral** [comment]
The issue with H5P_DEFAULT may have to do with issue #174... @parcollet is looking into this.

**Comment by parcollet** [comment]
Yes, the last issue is due to a change in boost, it is #184.

**Comment by parcollet** [comment]
H5P_DEFAULT has been fixed.

**Comment by Titan-C** [comment]
Installation more or less solved.
I realized that my boost libraries are compiled against the system openmpi, but I was installing triqs within a virtual environment which has its own version of openmpi to which mpi4py is linked, but not boost. So it looked like boost was giving the trouble, but is not an issue of boost. Installing from the system packages works fine where boost and mpi4py link to the same openmpi.

When doing the tests. It fails is 2
autocorrelation_time and basic_statistics
I'm using boost 1.57, so as specified in #24 its a boost problem
I also notice in issue #181 both test are also reported to fail.

**Comment by parcollet** [comment]
These 2 tests fail because of a change in boost.
taken care of in #241
