### ISSUE TITLE
creating gf views abnormally slow

### ISSUE THREAD

**Issue by pascaldelange** [TRIQS/triqs#185]
Hi,

I ran into a problem where putting values into a GF is extremely slow. 

```
#include <triqs/gfs.hpp>
#include <triqs/gfs/local/functions.hpp>
using namespace triqs::gfs;

int main() {
 double beta = 10;
 int Nfreq = 10000000;
 auto g = gf<imfreq>{{beta, Fermion, Nfreq}, {1, 1}};
 for(int n=0; n<Nfreq; ++n){
   g[n](0,0)+=1;
 }
}
```
and 
```
#include <triqs/gfs.hpp>
#include <triqs/gfs/local/functions.hpp>
using namespace triqs::gfs;

int main() {
 double beta = 10;
 int Nfreq = 10000000;
 auto g = gf<imfreq,scalar_valued>{{beta, Fermion, Nfreq}};
 for(int n=0; n<Nfreq; ++n){
   g[n]+=1;
 }
}
```

both take ~2 seconds to run, while 

```
#include <triqs/gfs.hpp>
#include <triqs/gfs/local/functions.hpp>
using namespace triqs::gfs;

int main() {
 double beta = 10;
 int Nfreq = 10000000;
 std::vector<float> V(Nfreq);
 for (int n=0; n<Nfreq; ++n) V[n]+=1;
}
```
takes around 0.3 second. This was problematic in a QMC program. Is this normal ?

Best wishes,
Pascal

**Comment by parcollet** [comment]
Is 
#define TRIQS_ARRAYS_ENFORCE_BOUNDCHECK
present or not (it was in the email, it is gone now ????).
this makes the lib very slow, it is a debug mode.

**Comment by tayral** [comment]
Pascal removed the macro (10s --> 2s)

**Comment by tayral** [comment]
Note: as a consequence, turning "measure_gw" in cthyb_segment solver slows down the code (by a factor of 100)... (@pseth also noticed a 10-20% slowdown a few months ago in her measure_gt)

**Comment by mferrero** [comment]
Do I have to understand that there was a point in the past when the codes above were running faster? If so, it would be extremely useful to figure which commit made the codes slow...

**Comment by parcollet** [comment]
Well, it would be better to first compare things which are comparable !
gf : the data is an array of complex<double>
the other one a vector<float> !
If I use a vector<complex>, I get the same time for the vector, the g[n], 
and also a direct array<complex,1>.

Added a speed test : issue185.cpp to investigate this issue.
Tested on OS X, and Linux (CDF).
PS : Cf the test. This is a better test, with a loop to get some stat on the running times...

It seems to me that there is no pb.  Retest and reopen if necessary
