### ISSUE TITLE
HDFArchive cannot save GF

### ISSUE THREAD

**Issue by alenhorvat** [TRIQS/triqs#186]
Hi,

we are facing following issue:
4 out of 147 tests fail:

The following tests FAILED:
	141 - gf_init (Failed)
	142 - gf_base_op (Failed)
	144 - pade (Failed)
	147 - wrap_a (Failed)
Errors while running CTest
make: *** [test] Error 8

All of the errors are of the same origin - the hdf5/h5py
After installing Triqs (with failed tests) we traced the error:
If we try to save a GF as:

h=HDFArchive('gf_init.output.h5','w')
h['g1'] = g

we get the following error:
Traceback (most recent call last):
  File "gf_init.py", line 33, in <module>
    h['g1'] = g
  File "/home/horvat/triqsinstall/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 186, in __setitem__
    val.__write_hdf5__(self._group,key)
TypeError: Internal error : invalid id from h5py !

If we replace the code above with:
h=HDFArchive('gf_init.output.h5','w')
h['g1'] = g.data

no error occurs.
Same problem causes errors in all of the failed tests. No other errors/warnings occur during cmake/make process.

Thank you in advance!

Alen

**Comment by parcollet** [comment]
Hello, 
The error means that the id of the hdf5 object as seen by h5py
does not make sense at the C++ level, for the C hdf5 library.
It is thrown by the triqs library, as a security check.
While I never encountered this pb myself, 
I think that maybe the version of the hdf5 library used by h5py and the version the C++ code has been linked against are different.
Do you have several hdf5 versions/ libraries ? Which system do you use ?

**Comment by alenhorvat** [comment]
Hi,
it is possible that h5py and c++ are linked against different hdf5 libraries. I will check this. Installation was done on a cluster with CentOS6.5 os. 

If we leave the instalation as is, can this incompatibility cause any errors in simulations?

**Comment by parcollet** [comment]
You must link h5py (the standard python module) and the c++ code to *exactly* the same hdf5 library.
HDFArchive, or h5py  (which is the standard python module), 
Otherwise, I do not know what can happen (random crash ?), 
that why I added this security in the code to stop it.

**Comment by alenhorvat** [comment]
Thank you for your quick response. This exactly was the problem. C++ was linked to other hdf5 libs. Problem is solved.
