### ISSUE TITLE
DMFT

### ISSUE THREAD

**Issue by pdelamora** [TRIQS/triqs#193]
Dear Professor Oliver Parcollet,
As I wrote to you last year;
    I am interested in calculating ruthenates and iridiates and I think that the strong intraatomic correlations are well taken into account with the DMFT which I was told that is in TRIQS.
    ​I have finally downloaded TRIQS.
    I work with the WIEN2k code and there is a WIEN2k => TRIQS link so I could start the calculations with the WIEN code.
Is there a package in TRIQS that could use the WIEN2k imput to do the DMFT calculation?
            Yours

                    Pablo de la Mora

**Comment by parcollet** [comment]
You need to install the solver (cthyb) and the dft_tools package, 
Cf the documentation.
