### ISSUE TITLE
ipython --pylab hides sum builtin python

### ISSUE THREAD

**Issue by wwrowe** [TRIQS/triqs#197]
from pytriqs.plot.mpl_interface import *
import numpy as np
sum is np.sum

-- True

This is surprising, one expects sum to be ordinary python sum

**Comment by parcollet** [comment]
Even worse
ipython --pylab
sum??
and sum is not any more the regular python sum !!

**Comment by parcollet** [comment]
@pseth, @mferrero : are you aware of this ?

**Comment by parcollet** [comment]
@wwrowe 
Put
 from __builtin__ import sum
at the beginning of your script, sum will be the builtin sum.
But that is a surprising behavior, unrelated to triqs however.
