### ISSUE TITLE
Problem with view_selected_blocks and copy_selected_blocks

### ISSUE THREAD

**Issue by rrichter90** [TRIQS/triqs#202]
Hi,
I discovered that there is a small bug in block_gf.py. Both methods view_selected_blocks and copy_selected_blocks have a loop over "G" which is not defined. It should be a loop over "self" as it was in the older versions.

    def view_selected_blocks(self, selected_blocks):
        """Returns a VIEW of the selected blocks of self, in the same order as self."""
        for b in selected_blocks: assert b in self.__indices,"Selected Blocks must be existing blocks"
        return self.__class__ ( name_block_generator = [(n,g) for n,g in G if n in selected_blocks ],make_copies=False)

It should be:

    def view_selected_blocks(self, selected_blocks):
        """Returns a VIEW of the selected blocks of self, in the same order as self."""
        for b in selected_blocks: assert b in self.__indices,"Selected Blocks must be existing blocks"
        return self.__class__ ( name_block_generator = [(n,g) for n,g in self if n in selected_blocks ],make_copies=False)

**Comment by parcollet** [comment]
Thanks.
