### ISSUE TITLE
writing to h5

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#205]
This following to issue #170 , because it is closed, but I and Pri still have this problem with the code crushing as explained in the last post in #170 

The crush is due  check of key being a string in _key_cipher in pytriqs/archive/hdf_archive.py : 
 
            if type(key) not in [ type('') , type(u'a')] :
                raise KeyError, "Key must be string only !"

if I check the type of key at the crush it gives:
key =  up_2 type 'numpy.string_'
so it is not str but numpy.string

**Comment by mferrero** [comment]
I think we really need a script that reproduces the bug. I tried to write a short test that reads a BlockGf from an archive and checks the type of the indices and they were standard strings. There must be something special in your script...

**Comment by leopo** [comment]
Try this script on montblanc 

from pytriqs.gf.local import *
from pytriqs.archive import *
import pytriqs.utility.mpi as mpi

blocks=['up0','down0']
n_points =1000
beta=40.0

glist = lambda : [ GfImFreq(indices = [0], beta = beta, n_points = n_points) for bl in blocks]
G=BlockGf(name_list = blocks, block_list = glist(),make_copies=False)

if mpi.is_master_node():
    for s,g in G:
        print s,type(s)

if mpi.is_master_node():
    print 'write'
    ar = HDFArchive('test.h5','a')
    ar['G']=G
    del ar

if mpi.is_master_node():
    print '\nread'
    ar = HDFArchive('test.h5','r')
    G = ar['G']
    del ar

G=mpi.bcast(G)
if mpi.is_master_node():
    for s,g in G:
        print s,type(s)

I get the following output:

>pytriqs test.py
Starting on 1 Nodes at : 2015-03-06 23:58:46.750100
up0 <type 'str'>
down0 <type 'str'>
write

read
up0 <type 'numpy.string_'>
down0 <type 'numpy.string_'>




So the problem appears due to mpi.bcast()

**Comment by leopo** [comment]
in the script above all spaces at the line starts disappeared, I don't know how to keep python formatting here.

**Comment by mferrero** [comment]
I have pushed a fix. @leopo : can you check that things are ok now and close the issue?

**Comment by leopo** [comment]
Seems to work, thanks!
