### ISSUE TITLE
missing mako.template during compilation

### ISSUE THREAD

**Issue by phanousk** [TRIQS/triqs#207]
I have just did 'git clone https://github.com/TRIQS/triqs.git src' and ccmaked the Makefile with no problem and complains. After running 'make' the process says:
Scanning dependencies of target py_copy
[  0%] Built target py_copy
[  1%] Generating operators_wrap.cpp, ../../include/pytriqs/converters/operators.hpp
Traceback (most recent call last):
  File "/scratch/hanousek/triqs/src/build/pytriqs/operators/operators_desc.py", line 1, in <module>
    from wrap_generator import *
  File "/scratch/hanousek/triqs/src/build/pytriqs/c++2py/wrap_generator.py", line 4, in <module>
    from mako.template import Template
ImportError: No module named mako.template
make[2]: *** [pytriqs/operators/operators_wrap.cpp] Error 1
make[1]: *** [pytriqs/operators/CMakeFiles/python_wrap_operators.dir/all] Error 2

However running python and importing required module works:
$python
Python 2.7.6 (default, Jul 10 2014, 17:01:27) 
[GCC 4.7.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from mako.template import Template
>>> 

What could be wrong?
Best regards, Petr

**Comment by aichhorn** [comment]
You installed mako yourself, or with root access? In the first case you might encounter something similar to issue #177 . The solution was to symbolically link the mako installation directory into the build directory. Or use virtualenv.

**Comment by parcollet** [comment]
python -v
and your "from ... test".
will tell you where the module is loaded from ...

**Comment by phanousk** [comment]
Aichhorn hit the nail ... I use the non standard locations, because of cluster environment and many libraries and software are maintained via modules system. OK, I linked mako, numpy and scipy installed python modules to build dir and the make procedure continued. Thank you for help.
However there is another error in 21%:
```
[ 21%] Building CXX object pytriqs/operators/CMakeFiles/operators.dir/operators_wrap.cpp.o
In file included from /scratch/hanousek/triqs/src/build/pytriqs/operators/operators_wrap.cpp:7:0:
/scratch/hanousek/triqs/src/triqs/python_tools/converters/vector.hpp: In instantiation of 'static PyObject* triqs::py_tools::py_converter<std::vector<_RealType> >::c2py(const std::vector<_RealType>&) [with T = boost::variant<int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > >; PyObject = _object]':
/scratch/hanousek/triqs/src/triqs/python_tools/converters/pair.hpp:12:52:   required from 'static PyObject* triqs::py_tools::py_converter<std::pair<_T1, _T2> >::c2py(const std::pair<_T1, _T2>&) [with T1 = bool; T2 = std::vector<boost::variant<int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >; PyObject = _object]'
/scratch/hanousek/triqs/src/triqs/python_tools/converters/vector.hpp:11:37:   required from 'static PyObject* triqs::py_tools::py_converter<std::vector<_RealType> >::c2py(const std::vector<_RealType>&) [with T = std::pair<bool, std::vector<boost::variant<int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >; PyObject = _object]'
/scratch/hanousek/triqs/src/triqs/python_tools/converters/pair.hpp:11:52:   required from 'static PyObject* triqs::py_tools::py_converter<std::pair<_T1, _T2> >::c2py(const std::pair<_T1, _T2>&) [with T1 = std::vector<std::pair<bool, std::vector<boost::variant<int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >; T2 = double; PyObject = _object]'
/scratch/hanousek/triqs/src/triqs/python_tools/converters/../wrapper_tools.hpp:51:76:   required from 'PyObject* triqs::py_tools::convert_to_python(T&&) [with T = std::pair<std::vector<std::pair<bool, std::vector<boost::variant<int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > >, double>; PyObject = _object]'
/scratch/hanousek/triqs/src/build/pytriqs/operators/operators_wrap.cpp:1244:142:   required from here
/scratch/hanousek/triqs/src/triqs/python_tools/converters/vector.hpp:11:37: error: incomplete type 'triqs::py_tools::py_converter<boost::variant<int, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >' used in nested name specifier
    pyref y = py_converter<T>::c2py(x);
                                     ^
make[2]: *** [pytriqs/operators/CMakeFiles/operators.dir/operators_wrap.cpp.o] Error 1
make[1]: *** [pytriqs/operators/CMakeFiles/operators.dir/all] Error 2
```
Is this because of gcc-4.8.1? I have noticed an issue with this compiler in list. Or is it because boost (version 1.56) or other libraries are also maintained via modules and thus in non standard location? The loaded modules (software somewhere in /software/... directory tree) are:
```
Currently Loaded Modulefiles:
  1) /software/modules/current/metabase   6) openmpi-1.8.2-gcc
  2) python-2.7.6-gcc                     7) hdf5-1.8.12-gcc-serial
  3) python27-modules-gcc                 8) boost-1.56-gcc
  4) ofed-1.5.4                           9) fftw-3.3
  5) gcc-4.8.1                           10) cmake-2.8.12
```

**Comment by parcollet** [comment]
It is as if an include of the variant converter had been forgotten, but why does it compile elsewhere, and not here ?? @ mferrero ...

**Comment by phanousk** [comment]
I have tried today the compilation with the fresh source files and the issue is still there. Do you have any hint so far?

**Comment by parcollet** [comment]
Looks like the same error as #228. 
Probably the problem arise with boost 1.56....
Assigned to Igor and me.

**Comment by parcollet** [comment]
Same as #228. Fix in progress

**Comment by phanousk** [comment]
Greetings, I confirm that reported error is solved for me. 

However I can not pass through 79% with:
```
[ 79%] Building CXX object test/triqs/gfs/CMakeFiles/gfv2.dir/gfv2.cpp.o
... output ommited ...
  /afs/ics.muni.cz/software/gcc-4.8.1/include/c++/4.8.1/bits/move.h:89:7: error: static assertion failed: template argument substituting _Tp is an lvalue reference type
       static_assert(!std::is_lvalue_reference<_Tp>::value, "template argument"
       ^
make[2]: *** [test/triqs/gfs/CMakeFiles/gfv2.dir/gfv2.cpp.o] Error 1
```

Full error message is at http://pastebin.com/NT3MBgKB .
Petr

**Comment by parcollet** [comment]
@krivenko 
Hello, 
It looks to me like the famous bug in gcc 4.8.1 which we had several times before.
Igor, do you confirm ?

If you have the opportunity to use a more recent gcc (4.9.x or even 4.8.2), 
it should solve this.

@krivenko : should we request 4.8.2 at least ?

Olivier

**Comment by phanousk** [comment]
Thank you @parcollet , that's it. I have tried gcc-4.8.4 and everything now seems OK and compiled for 100%. This track can be closed for me.
Petr

**Comment by krivenko** [comment]
> It looks to me like the famous bug in gcc 4.8.1 which we had several times before.
> Igor, do you confirm ?

I confirm, this is issue #138 again.

 > should we request 4.8.2 at least ?

As it's seen from the discussion of #138, gcc 4.8.2 is not necessarily enough.
I'd rather think about disabling or removing that `gfv2` test.

**Comment by parcollet** [comment]
4.8.4 is clearly enough. Ubuntu 14.04LTS is 4.8.2 but the updates of the distribution 
push it to 4.8.4. Maybe we should request 4.8.4 ?
I do not like removing tests, the bug is still here, it may reappear in any app...

**Comment by krivenko** [comment]
> Maybe we should request 4.8.4 ?

4.8.4 was released less than 1 year ago. 
Did anyone successfully try 4.8.3? It would make the transition a bit more merciful.
