### ISSUE TITLE
Equality of HDFArchive quantities

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#208]
It seems that I cannot (correctly) check equality of an object directly taken from an archive:

```
print R['G0_iw'] == R['G0_iw']
```
and
```
for name,gf in G0:
    print R['G0_iw'][name] == R['G0_iw'][name]
```
both give False, while
```
for name,gf in G0:
    print gf == gf
```
gives True.

Is this expected behaviour?

Also two separate objects in the archive that should be identical don't seem to be when the objects are read in. Anyone seen this before?

**Comment by parcollet** [comment]
== is ill defined for real number, so the code is convervative here.
If g1, g2 are 2 gf : 
if there are the same reference, then g1 is g2 and g1 == g2 are true
else they are both false.
