### ISSUE TITLE
INABILTY to run examples

### ISSUE THREAD

**Issue by EBRUDU1** [TRIQS/triqs#209]
After six months of battlng I have finally installed TRIQS 1.2.0 on Ubuntu14.04.
During the installation gfv2 test failed.
I do not whether because of that failure  I was unable run any of the tutorials.
The commands I used are reproduced below:
Please look through and tell me my faults.

(.my_python)enukpere@ubuntu:~$ cd build/pytriqs
(.my_python)enukpere@ubuntu:~/build/pytriqs$ _init_.py
_init_.py: command not found
(.my_python)enukpere@ubuntu:~/build/pytriqs$ from pytriqs.gf.local import GfImFreq, iOmega_n, inverse
from: can't read /var/mail/pytriqs.gf.local
(.my_python)enukpere@ubuntu:~/build/pytriqs$ # Import the Green's functions
(.my_python)enukpere@ubuntu:~/build/pytriqs$ from pytriqs.gf.local import GfImFreq, iOmega_n, inverse
from: can't read /var/mail/pytriqs.gf.local
(.my_python)enukpere@ubuntu:~/build/pytriqs$ cd ..
(.my_python)enukpere@ubuntu:~/build$ cd bin
(.my_python)enukpere@ubuntu:~/build/bin$ pytriqs
pytriqs: command not found
(.my_python)enukpere@ubuntu:~/build/bin$ ./pytriqs
Python 2.7.6 (default, Mar 22 2014, 22:59:38) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> # Import the Green's functions
... from pytriqs.gf.local import GfImFreq, iOmega_n, inverse
>>> 
>>> # Create the Matsubara-frequency Green's function and initialize it
... g = GfImFreq(indices = [1], beta = 50, n_points = 1000, name = "$G_\mathrm{imp}$")
>>> g << inverse( iOmega_n + 0.5 )
gf_view
>>> from pytriqs.plot.mpl_interface import oplot
>>> oplot(g, '-o',  x_window  = (0,10))
>>>

**Comment by aichhorn** [comment]
The test gfv2 sometimes fails, this is not related to your problem. Your problem is that you try to run a PYTHON script in a linux SHELL as shell script. That means that you try to execute python commands as they were linux shell commands, and that of course does not work.
Normally, you should install the code properly using 'make install'. Then you use the installed executable to run the the tutorial scripts as:
pytriqs example.py 
The folder where the pytriqs exectuable has to be in your PATH variable for the command to work.

**Comment by EBRUDU1** [comment]
Markus Alchorn, thanks for your prompt response to my post.
Please help me as I am new to the PYTHON/IPYTHON language and the tutorials I have been reading do not for instance show how to call TRIQS which is installed in  "~/build/  "
from: (.my_python)enukpere@ubuntu:~$  As you can see I created a virtualenv following the instruction on the TRIQS webpage. I am sure the installation process went well. So if you do not mind be more explicit with the following lines  which appeared in your contribution.: That means that you try to execute python commands as they were linux shell commands, and that of course does not work.
Normally, you should install the code properly using 'make install'. Then you use the installed executable to run the the tutorial scripts as:
pytriqs example.py 
The folder where the pytriqs exectuable has to be in your PATH variable for the command to work.I have attached the cmakeoutput.log  in the hope that you may find it helpful.


  


     On Tuesday, April 7, 2015 8:28 AM, Markus Aichhorn <notifications@github.com> wrote:
   

 The test gfv2 sometimes fails, this is not related to your problem. Your problem is that you try to run a PYTHON script in a linux SHELL as shell script. That means that you try to execute python commands as they were linux shell commands, and that of course does not work.
Normally, you should install the code properly using 'make install'. Then you use the installed executable to run the the tutorial scripts as:
pytriqs example.py 
The folder where the pytriqs exectuable has to be in your PATH variable for the command to work.—

**Comment by aichhorn** [comment]
Okay, that means, before you get started with TRIQS you should get familiar with python. Fpr that purpose you can find plenty of tutorials on the web. The basic idea is that you put your code into a script file, e.g. my_script.py, and execute the code by
python my_script.py
Exactly the same is true with pytriqs. 
BTW, there is no cmakeoutput.log attached, and I don't think its content is useful to solve your problem.

**Comment by EBRUDU1** [comment]
Inability to run examples
As noted in my earlier post I was unable to run 

(.my_python)enukpere@ubuntu:~/build/bin$ ipython
Python 2.7.6 (default, Mar 22 2014, 22:59:38) 
Type "copyright", "credits" or "license" for more information.
IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
In [1]: ipytriqs
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-f6ea52ebb176> in <module>()
----> 1 ipytriqs
NameError: name 'ipytriqs' is not defined
In [2]: from pytriqs.gf.local import GfReFreq, Omega, Wilson, inverse
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-3b1f711c6c14> in <module>()
----> 1 from pytriqs.gf.local import GfReFreq, Omega, Wilson, inverse
ImportError: No module named pytriqs.gf.local
In [3]:

**Comment by EBRUDU1** [comment]
nability to run examples
As noted in my earlier post I was unable to run

(.my_python)enukpere@ubuntu:~/build/bin$ ipython
Python 2.7.6 (default, Mar 22 2014, 22:59:38)
Type "copyright", "credits" or "license" for more information.
IPython 3.1.0 -- An enhanced Interactive Python.
? -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help -> Python's own help system.
object? -> Details about 'object', use 'object??' for extra details.
In [1]: ipytriqs

NameError Traceback (most recent call last)
in ()
----> 1 ipytriqs
NameError: name 'ipytriqs' is not defined
In [2]: from pytriqs.gf.local import GfReFreq, Omega, Wilson, inverse

ImportError Traceback (most recent call last)
in ()
----> 1 from pytriqs.gf.local import GfReFreq, Omega, Wilson, inverse
ImportError: No module named pytriqs.gf.local
In [3]:
@EBRUDU1
Markdown supported
Edit in fullscreen
Write Preview

Attach images by dragging & dropping or selecting them.

**Comment by EBRUDU1** [comment]
I am having serious issues either with the proper installation of the TRIQS code or with the running of the code in a python environment.
As part of the problem I do not even know if the code is properly installed although the output seem to say something to that effect. What I would really like is for someone to really work me through the usage of the TRIQS  after its installation in "~/build".
Please write out the requisite commands explicitly.
May God Bless you for your time.

**Comment by aichhorn** [comment]
I suggest to start with the installation precedure again. One major point is that if you want a clean installation, then the installation directory should not be ~/build, since this is most probably the build directory. The structure is the following:
1) Source directory: here is the code
2) build directory: here you do cmake and make stuff
3) install directory: This is the location where the libraries and executables are installed
I am not sure, but it looks like you install directory is called 'build'. So let's look at your structure:
1) In what directory did you download the code?
2) In what directory did you build the package?
3) What installation directory did you specify in cmake through -DCMAKE_INSTALL_PREFIX?

**Comment by EBRUDU1** [comment]
Thanks for your kind help
Code was downloaded into ~/Downloadthen it was unzipped in home to produce  
~/triqs_masterthen a build directory was created in home ie 
~/build  and it was here installation was carried out.
-DCMAKE_INSTALL_PREFIX path to install directory
~/build


 


     On Monday, April 13, 2015 12:55 PM, Markus Aichhorn <notifications@github.com> wrote:
   

 I suggest to start with the installation precedure again. One major point is that if you want a clean installation, then the installation directory should not be ~/build, since this is most probably the build directory. The structure is the following:
1) Source directory: here is the code
2) build directory: here you do cmake and make stuff
3) install directory: This is the location where the libraries and executables are installed
I am not sure, but it looks like you install directory is called 'build'. So let's look at your structure:
1) In what directory did you download the code?
2) In what directory did you build the package?
3) What installation directory did you specify in cmake through -DCMAKE_INSTALL_PREFIX?—

**Comment by aichhorn** [comment]
You have a directory ~/build, which you use as build and install directory. Unless you know exactly what you are doing, I would not do it like that. I propose the following procedure. You go into your ~/build directory and delete everything. Now you build the code again, but when you invoke the cmake command (as you did before) you add -DCMAKE_INSTALL_PREFIX=$HOME/triqs. Then you do
make
make test
make install
Provided the compilation works, you get the executables and libraries installed into ~/triqs/bin and ~/triqs/lib. If you want to run pytriqs, you type just ~/triqs/bin/pytriqs.
