### ISSUE TITLE
Tight binding tools: Triangular Lattice

### ISSUE THREAD

**Issue by xiaoyukaka** [TRIQS/triqs#210]
Hi,
Triqs 1.2 installation on my Ubuntu machine (all tests passed). A tight-binding model on a square lattice shows a correct DOS. However, on a triangular lattice I can not get a correct DOS. My code and result are followed.
********************************************************************************
from pytriqs.lattice.tight_binding import *
import math
p1=math.sqrt(3.0)/2.0
#Define the Bravais Lattice : a triangle lattice in 2d
BL = BravaisLattice(units = [(1,0,0) , (0.5,p1,0)], orbital_positions= [ (0,0,0)] )
#Prepare a nearest neighbour hopping on BL
t   = 1.00                # First neighbour Hopping
tp  =  0.0*t               # Second neighbour Hopping
hop= {  (1,0)  :  [[ t]],
        (-1,0) :  [[ t]],
        (0.5,p1)  :  [[ t]],
        (-0.5,-p1) :  [[ t]],
        (-0.5,p1)  :  [[ t]],
        (0.5,-p1) :  [[ t]]}
TB = TightBinding ( BL, hop)
#Compute the density of states
d = dos (TB, n_kpts= 2000, n_eps = 101, name = 'dos')[0]
#Plot the dos it with matplotlib
from pytriqs.plot.mpl_interface import oplot
from matplotlib import pylab as plt
#plt.xlim ( -5,5 )
#plt.ylim ( 0, 2)
oplot(d,'-o')
raw_input('press enter!')
***************************************
DOS:
![2000k](https://cloud.githubusercontent.com/assets/10613848/7104024/cb091c42-e0f6-11e4-8997-a57d379a987b.png)

But the DOS for triangular lattice should be like this ({Ref. FARAUTE Ciens. y Tec., 3(1):31-39,2008. } http://servicio.bc.uc.edu.ve/facyt/v3n1/3-1-4.pdf)
![tri-dos](https://cloud.githubusercontent.com/assets/10613848/7104033/7017722e-e0f7-11e4-8f45-31706d52ef4b.jpg)

kaka

**Comment by tayral** [comment]
Dear xiaoyukaka,
Your hopping dictionary 'hop' is not correct. Its keys should be the 
coordinates of the hopping in the basis of the unit vectors. They have 
to be pairs of integers.

**Comment by xiaoyukaka** [comment]
Thank you, tayral~ I have got the correct DOS.
