### ISSUE TITLE
Value of Hubbard U and Hund exchange J

### ISSUE THREAD

**Issue by pdelamora** [TRIQS/triqs#211]
I saw the paper 
+    Vaugier, Jiang and Biermann PRB 86, 165105 (2012) 

in this paper they evaluate the Hubbard U and Hund exchange J
but it seems that this procedure is not yet for public usage.
Does anyone know if there are other possible solutions?

**Comment by tayral** [comment]
The calculation of U and J is not part of TRIQS.

**Comment by pdelamora** [comment]
One question and one comment
---
Is this a place for academic questions or is it only for issues directly related to TRIQS?
...
In the paper that I mentioned and in the folowing
arXiv:cond-mat/0603138 
the U is calculated with DMFT, so it would be natural to expect that a package like TRIQS could be related to this issue.
...
A final comment
In the WIEN2k mailing list I got this answer;
"To my knowledge there is no simple AND reliable way to calculate U and J"

**Comment by pseth** [comment]
As you correctly suspect, this is not meant to be a forum for discussions. Please restrict your questions to those related exclusively to TRIQS-related issues. In the TRIQS context, as Thomas said, TRIQS does not have any means to calculate U and J.

**Comment by aichhorn** [comment]
The U and J is never calculated with DMFT, it is calculated for DMFT. TRIQS is related in the sense that it needs these parameters as input, just as other parameters. For now we do not plan to include methods to calculate U and J. Some DFT packages have them included, though, in one way or the other.
And the answer you got in the Wien2k mailing list is perfectly correct.
