### ISSUE TITLE
Placeholder inside special functions

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#214]
In python, using the placeholder Omega inside sqrt( .. ) expression, as e.g. necessary when using superconducting baths, yeilds type error:

eta = 0.01
DEL = 1.0
g0m = GfReFreq( n_points = 200, window = (-2.0, 2.0), indices = [0,1], name = "g0m")
g0m[0,0] = Omega - EPS                                                               \#   **Works!**
g0m[0,1] = DEL / sqrt( DEL \* DEL  - Omega \* Omega + 1j \* eta  )  \#   **TypeError: a float is required**
g0m[1,0] = DEL / sqrt( DEL \* DEL  - Omega \* Omega + 1j \* eta  ) 
g0m[0,0] = Omega + EPS
g0m.invert()

The same holds for the usage of copysign(1, Omega), which might be useful in some cases.

Cheers

**Comment by krivenko** [comment]
Hello Wentzell,
I think you should have used `Function()` descriptor to achieve what you wanted.
```python
from pytriqs.gf.local import *
from pytriqs.gf.local.descriptors import Omega, Function
from cmath import sqrt

EPS = 1.0
eta = 0.01
DEL = 1.0
g0m = GfReFreq( n_points = 200, window = (-2.0, 2.0), indices = [0,1], name = "g0m")
g0m[0,0] = Omega - EPS
g0m[0,1] = Function(lambda w: DEL / sqrt(DEL * DEL - w*w + 1j * eta))
g0m[1,0] = Function(lambda w: DEL / sqrt(DEL * DEL - w*w + 1j * eta))
g0m[1,1] = Omega + EPS # Was g0m[0,0] in your example, probably erroneously
g0m.invert()
```
As far as I understand the way expressions work, we would have to explicitly enumerate in the source all the special functions we want to support. This list of functions would be long, difficult to maintain, yet not exhaustive (everyone has her own needs).

**Comment by Wentzell** [comment]
Ok, thank you!
