### ISSUE TITLE
Pade continuation of matrix-valued green functions

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#215]
There seems to be a problem when extending your pade example to matrix-valued green functions.
For a 2x2 matrix structure it seems that only the 1,1 component is continued, not the 0,0 one.

\#!/usr/bin/python
import numpy
import matplotlib.pyplot as pl
from math import pi
from cmath import sqrt, log
from pytriqs.gf.local import \*
from pytriqs.gf.local.descriptors import Function

beta = 100  \# Inverse temperature
L = 101     \# Number of Matsubara frequencies used in the Pade approximation
eta = 0.01 \# Imaginary frequency shift

\#\# Test Green's functions ##

\# Two Lorentzians
def GLorentz(z):
    return 0.7/(z-2.6+0.3\*1j) + 0.3/(z+3.4+0.1\*1j)

\# Semicircle
def GSC(z):
    return 2.0\*(z + sqrt(1-z\*\*2)\*(log(1-z) - log(-1+z))/pi)

\# A superposition of GLorentz(z) and GSC(z) with equal weights
def G(z):
    return numpy.array( [[GSC(z), GSC(z)], [GSC(z), GSC(z)]] )

\# Matsubara GF
gm = GfImFreq(indices = [0,1], beta = beta, name = "gm")
gm << Function(G)
gm.tail.zero()
gm.tail[1] = numpy.array([[1.0,1.0]])

\# Real frequency BlockGf(reference)
gr = GfReFreq(indices = [0,1], window = (-5.995, 5.995), n_points = 120, name = "gr")
gr << Function(G)
gr.tail.zero()
gr.tail[1] = numpy.array([[1.0,1.0]])

\# Analytic continuation of gm
g_pade = GfReFreq(indices = [0,1], window = (-5.995, 5.995), n_points = 120, name = "g_pade")
g_pade.set_from_pade(gm, n_points = L, freq_offset = eta)

\# Comparison plot
from pytriqs.plot.mpl_interface import oplot
oplot(gr[0,0], '-o', RI = 'S', name = "Original DOS")
oplot(g_pade[0,0], '-x', RI = 'S', name = "Pade-reconstructed DOS") \#  **This array is identically zero**
pl.show()

**Comment by tayral** [comment]
Hi Nils,
Igor fixed the bug--do you confirm it works?
Cheers,
Thomas

**Comment by Wentzell** [comment]
Yes, it works now! Thanks!

Cheers
