### ISSUE TITLE
Problem with matrix<complex<double>> eigenvalues

### ISSUE THREAD

**Issue by sophiechauvin** [TRIQS/triqs#219]
Dear all,

I tried to write the following two tests in test/triqs/arrays, which give different answers:
Test n°1:
```
#include <triqs/arrays.hpp>
#include <iostream>
#include <triqs/arrays/linalg/eigenelements.hpp>
#include <triqs/arrays/matrix.hpp>

using triqs::arrays::array;
using triqs::arrays::matrix;
using triqs::arrays::linalg::eigenvalues;
using triqs::clef::placeholder;
using triqs::arrays::matrix_view;

int main(int argc,char ** argv){

 //placeholder<0> i_;
 //placeholder<1> j_;
 matrix<std::complex<double>> A(2, 2);
 //A(i_, j_) << i_ + j_;
 A(0, 0) = 1.;
 A(0, 1) = std::complex<double>(0., 0.1);
 A(1, 0) = std::complex<double>(0., -0.1);
 A(1, 1) = 1.;
 std::cout << " A = " << A <<std::endl;

 auto v = eigenvalues(matrix_view<std::complex<double>>(A));
 std::cout << "v = " << v << std::endl;

 return 0;
}
```
for which the output is ok:
```
 A = 
[[(1,0),(0,0.1)]
 [(0,-0.1),(1,0)]]
v = [0.9,1.1]
```
(however I'm surprised that v does not contain complex values. I know the matrix A is hermitian, but the machine doesn't).

Test n°2:
```
#include <triqs/arrays.hpp>
#include <iostream>
#include <triqs/arrays/linalg/eigenelements.hpp>
#include <triqs/arrays/matrix.hpp>

using triqs::arrays::array;
using triqs::arrays::matrix;
using triqs::arrays::linalg::eigenvalues;
using triqs::clef::placeholder;
using triqs::arrays::matrix_view;

int main(int argc,char ** argv){

 //placeholder<0> i_;
 //placeholder<1> j_;
 matrix<std::complex<double>> A(2, 2);
 //A(i_, j_) << i_ + j_;
 A(0, 0) = 1.;
 A(0, 1) = std::complex<double>(0., 0.1);
 A(1, 0) = std::complex<double>(0., -0.1);
 A(1, 1) = 1.;
 //std::cout << " A = " << A <<std::endl;

 auto v = eigenvalues(matrix_view<std::complex<double>>(A));
 std::cout << " A = " << A <<std::endl;
 std::cout << "v = " << v << std::endl;

 return 0;
}
```

for which the output is:
```
 A = 
[[(1,0),(0,0.1)]
 [(-0.1,0),(1,0)]]
v = [0.9,1.1]
```

Note the off-diagonal elements in the matrix A!!

Thanks a lot for your answer!

**Comment by krivenko** [comment]
Hi Sophie,
By default, function `eigenvalues()` modifies its argument. If you don't like this side effect, you should use `eigenvalues(make_clone(A))` (slower, since makes a copy of `A`).

**Comment by parcollet** [comment]
Yes, but it is a poor API, it is surprising to the user (as shown here).
I do not like functions that are not pure in general.
Of course here, it is like this because it is simply a lapack call, and lapack works like this ...
@krivenko @mferrero : any idea to improve it ?

**Comment by krivenko** [comment]
> any idea to improve it ?

What if `eigenvalues(M)`/`eigenelements(M)` make a copy of `M` by default, but then we allow to write something like `eigenvalues(in_place(M))`.

**Comment by parcollet** [comment]
Todo: 
- make 2 versions of the function: 
  1- take const &  + make a copy
  2- take a pointer to allow modification of the argument.
