### ISSUE TITLE
Keys of dicts coming back in wrong type from HDF

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/triqs#220]
I want to store a dictionary in the archive, where the key is something more complicated, like a tuple.
d = {(1,2) : 1}
ar['d'] = d
When I retrieve it from the archive, the key is not a tuple but a string:
ar['d'] returns
d = {'(1,2)' : 1}
so it cannot be used as the original dictionary. Happens for instance for SK.sumk_to_solver.

**Comment by krivenko** [comment]
Hello Markus,
I think, this issue looks more like a feature request.
Names of HDF5 groups and datasets have to be strings, and the Python dictionaries are stored as HDF5 groups. However, I can see a way around it. The non-string names could be simply represented by strings, and accompanied by small type tags (HDF5 attributes). These type tags would allow to correctly reconstruct the corresponding Python objects from the string form on loading.

**Comment by parcollet** [comment]
Yes, it is possible. But that is one more thing to maintain.
Is it really necessary ?

**Comment by parcollet** [comment]
@mferrero : opinion ?

**Comment by parcollet** [comment]
H5 files are such that keys are strings. One should keep it this way, 
or interaction with other projects like ALPS will be even more complex.
