### ISSUE TITLE
[c++2py] Range objects converted from Python slices are forced to have length <= 4

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#221]
Dear all,

I have been asked by a fellow physicist (credits to Stefan Barthel) about weird behavior of GF slicing. After a brief inspection of his example I realized that pytriqs does not allow slices with length > 4:
```python
from pytriqs.gf.local import *

g = GfImFreq(indices = range(10), beta = 10, n_points = 1025)

print g.N1, g.N2
print g[:,:].N1, g[:,:].N2

for n in range(1,10): print g[0:n,0:n].N1, g[0:n,0:n].N2
```
Output:
```
10 10
4 4
1 1
2 2
3 3
4 4
4 4
4 4
4 4
4 4
4 4
```

This issue roots in the following (rather funny) fragment of ` triqs/python_tools/converters/arrays.hpp`:
```c++
 int len = 4; // no clue what this len is ??
Py_ssize_t start, stop, step, slicelength;
if (PySlice_GetIndicesEx((PySliceObject *)ob, len, &start, &stop, &step, &slicelength) < 0) return {};
return {start, stop, step};
```
API docs of Python [give an answer](https://docs.python.org/2/c-api/slice.html) to what `length` is for.

**int PySlice_GetIndicesEx(PySliceObject *slice, Py_ssize_t length, Py_ssize_t *start, Py_ssize_t *stop, Py_ssize_t *step, Py_ssize_t *slicelength)**

Usable replacement for PySlice_GetIndices(). Retrieve the `start`, `stop`, and `step` indices from the slice object `slice` **assuming a sequence of length** `length`, and store the length of the slice in `slicelength`. **Out of bounds indices are clipped in a manner consistent with the handling of normal slices**.

I'm not sure what would be a correct way to fix the bug; the length of the container (sequence) is not known at the point where `PySlice_GetIndicesEx` is called.

**Comment by parcollet** [comment]
Indeed, there is a bug, I forgot to clean this piece of code...
I pushed on gtest branch a fix. 
For code review by @krivenko and @mferrero.
I think now it is right, at least the test above is ok.
Opinions ?

**Comment by krivenko** [comment]
Your solution looks fine to me.
Indeed, conversion of slices has to be done as a part of container's indexing operator.
