### ISSUE TITLE
[doc] Two general issues of the online docs

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#227]
Hi,
There are two annoying problems with the [online documentation](http://ipht.cea.fr/triqs/1.2/documentation.html).

* Equations are not displayed, because `MathJax.js` cannot be loaded.
* Docs of the C++/Python wrapper generator are empty. Must be some Sphinx error.

**Comment by parcollet** [comment]
1- a pb that arised after a recent migration of our servers. Assigned to me.
2- Ok.

**Comment by tayral** [comment]
Where are we standing here? (the non-display of equations is pretty annoying indeed...)

**Comment by krivenko** [comment]
The issue number 1 is solved for me. Thank you!

Regarding the second one, it is the `pytriqs/cpp2py -> pytriqs/c++2py` symlink what causes a Sphinx failure. CMake creates two different binary dirs for `cpp2py` and `c++2py` with different contents. In particular, `__init__.py` is absent from `cpp2py`. That's why autodoc fails to import the modules and to produce any output.

All in all, do you really want those `+` signs? They are invalid characters in a Python module/package name after all.

**Comment by parcollet** [comment]
No I do not, it was a quick fix that has been left over...
