### ISSUE TITLE
[c++2py] Converter for std::tuple

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#231]
Hello,
Apparently, there is no C++/Python converter for `std::tuple` (or am I missing something?)
Would you mind, if I write one? I need it for a small change in cthyb's interface, where a function returning `std::vector<std:pair<...>>` should return 3 instead of 2 values per vector element.

**Comment by parcollet** [comment]
Indeed, it seems that there is not. Please go ahead, it will be very helpful.
However, I would insist on NOT using boost, boost::mpl etc .
I want to detach c++2py and minimize its dependencies.

**Comment by krivenko** [comment]
Pull request #233 is here.

**Comment by parcollet** [comment]
merged.
