### ISSUE TITLE
Not an issue, just a few questions

### ISSUE THREAD

**Issue by kananenka** [TRIQS/triqs#235]
Dear TRIQS team, I am going to use your CT-HYB code in my PhD project and I have several questions about setting up the calculations. My first question is
Does the CT-HYB work only in orthogonal basis where G0(iw) = [(iw + m)S - Delta(iw)]^{-1}
and S is a unit matrix or it can support non-orthogonal basis too?

**Comment by krivenko** [comment]
Hey,
Do you mean a theory with a generalized canonical commutation relation `{c^+_i, c_j} = S_{ij}`? I'm afraid that we do not support this.

**Comment by kananenka** [comment]
Ok. I see. Another question would be the following
If hybridization is not given as a well known expression but rather as some matrix that I precompute before. How do I input it using set from << operator? I can do it like this:
for w in xrange(n_iw):
       delta.data[w] = matrix[:,:,w]

where delta is the hybridization
but I assume that this is not the proper way of doing it. Is there are any other way to achieve this goal?

**Comment by krivenko** [comment]
> If hybridization is not given as a well known expression but rather as
some matrix that I precompute before. How do I input it using set from <<
operator? I can do it like this:
> for w in xrange(n_iw):
> delta.data[w] = matrix[:,:,w]

> where delta is the hybridization
> but I assume that this is not the proper way of doing it. Is there are
any other way to achieve this goal?

If you have a NumPy array `d` such that `delta.data.shape == d.shape`, you
can write `delta.data[:] = d`.

On 2 July 2015 at 00:33, kananenka <notifications@github.com> wrote:

> Ok. I see. Another question would be the following
> If hybridization is not given as a well known expression but rather as
> some matrix that I precompute before. How do I input it using set from <<
> operator? I can do it like this:
> for w in xrange(n_iw):
> delta.data[w] = matrix[:,:,w]
>
> where delta is the hybridization
> but I assume that this is not the proper way of doing it. Is there are any
> other way to achieve this goal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TRIQS/triqs/issues/235#issuecomment-117842039>.
>



-- 
Dr. Igor Krivenko
I. Institut für Theoretische Physik
Universität Hamburg
Jungiusstraße 9
20355 Hamburg, Germany
Tel: +49 40 42838 2842
Mob.-Tel.: +49 176 87610925

**Comment by kananenka** [comment]
Thank you, it works. I installed the latest version of CT-HYB solver and tried to run kanamori_offdiag example from:

.../src/benchmark/kanamori_offdiag

and I got the following error message:

Traceback (most recent call last):
  File "./kanamori_offdiag.py", line 6, in <module>
    from pytriqs.operators.util.op_struct import set_operator_structure, get_mkind
ImportError: No module named util.op_struct

Does the current version have pytriqs.operators.util.op_struct module?

**Comment by kananenka** [comment]
Dear TRIQS developers, I have another question. It happens pretty frequently and I would like to know what causes this problem:
-------------------------------------------------------------------------------------------------------------------------------------------
S.solve(**p)
  File "/export/zgid/akanane/TRIQS_test/build/lib/python2.7/site-packages/pytriqs/applications/impurity_solvers/cthyb/cthyb_solver.py", line 105, in solve
    SolverCore.solve(self, **params_kw)
RuntimeError: Error occurred at Tue Jul 14 20:05:12 2015

Error calling C++ overload
 solve() -> void
in implementation of method SolverCore.solve
C++ error was :
 Triqs runtime error at /export/zgid/akanane/TRIQS_test/build/include/triqs/mc_tools/./mc_move_set.hpp : 203

Monte Carlo Error : the rate (-nan) is not finite in move Shift one operator
 Error occurred on node 3
-------------------------------------------------------------------------------------------------------------------------------------------

**Comment by tayral** [comment]
Dear Kananenka,
There is a dedicated issue list for "cthyb" ( 
https://github.com/TRIQS/cthyb/issues)... can you repost your issue there?

Thanks!
