### ISSUE TITLE
Fourier transform of scalar_valued functions: does not work

### ISSUE THREAD

**Issue by lmessio** [TRIQS/triqs#239]
Hello, 

This small code does not compile :

    #include <triqs/gfs.hpp>
    using namespace triqs::gfs;
    int main() {
      double beta = 1.;
      double a = 1;
      int N = 10000;
      auto gw = gf<imfreq, scalar_valued>{{beta, Fermion, N/2}};
      auto gt = gf<imtime, scalar_valued>{{beta, Fermion, N+1}};
      triqs::clef::placeholder<0> om_;
      gw(om_) << 1 / (om_ - a);
      // fills a full *view* of gt with the contents of the FFT
      gt() = inverse_fourier(gw);
      // make a new fresh gf from the FFT of gt with a mesh of size N/2
      auto gw2 = make_gf_from_fourier(gt, N/2);
    }

The error obtained is :

In file included from sources/LIB/triqs/gfs.hpp:42:0,
                 from sources/LIB/test/triqs/gfs/test_fourier_real_time_scalar.cpp:2:
sources/LIB/triqs/gfs/local/fourier_matsubara.hpp: In instantiation of 'triqs::gfs::gf<triqs::gfs::imfreq, Target, Singularity, Evaluator> triqs::gfs::make_gf_from_fourier(
const triqs::gfs::gf_impl<triqs::gfs::imtime, Target, 
Singularity, Evaluator, V, C>&, int) 
[with Target = triqs::gfs::scalar_valued; Singularity = triqs::gfs::tail; Evaluator = void; bool V = false; bool C = false]':
sources/LIB/test/triqs/gfs/test_fourier_real_time_scalar.cpp:31:42:   required from here
sources/LIB/triqs/gfs/local/fourier_matsubara.hpp:50:79: error: no matching function for call to 'triqs::gfs::gf<triqs::gfs::imfreq, triqs::gfs::scalar_valued>::gf(<brace-enclosed initializer list>)'
   auto gw = gf<imfreq, Target, Singularity, Evaluator>{m, get_target_shape(gt)};
                                                                               ^
sources/LIB/triqs/gfs/local/fourier_matsubara.hpp:50:79: note: candidates are:
In file included from sources/LIB/triqs/gfs/block.hpp:23:0,
                 from sources/LIB/triqs/gfs.hpp:26,
                 from sources/LIB/test/triqs/gfs/test_fourier_real_time_scalar.cpp:2:
sources/LIB/triqs/gfs/./gf.hpp:501:3: note: triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::gf(typename triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::B::mesh_t, triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::target_shape_t, const typename triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::B::indices_t&, std::string) [with Variable = triqs::gfs::imfreq; Target = triqs::gfs::scalar_valued; Singularity = triqs::gfs::tail; Evaluator = void; typename triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::B::mesh_t = triqs::gfs::gf_mesh<triqs::gfs::imfreq>; triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::target_shape_t = triqs::utility::mini_vector<int, 0>; typename triqs::gfs::gf<Variable, Target, Singularity, Evaluator>::B::indices_t = triqs::gfs::nothing; std::string = std::basic_string<char>]
   gf(typename B::mesh_t m, target_shape_t shape = target_shape_t{}, typename B::indices_t const &ind = typename B::indices_t{},
   ^
...
...

Best
Laura.

**Comment by tayral** [comment]
I have the same pb! (#243)
