### ISSUE TITLE
No cast of elements of an array

### ISSUE THREAD

**Issue by lmessio** [TRIQS/triqs#240]
Hello, 

There is not automatic cast in the array class. It is not practical for example when using complex numbers : we have to add an imaginary part 0_j when the number is real. 
This code does not compile because of A3:

    #include <triqs/arrays/array.hpp>
    using namespace triqs::arrays;
    int main(int argc, char **argv) {
      array<double,1> A{1.,3.};
      std::cout << "A" << A << std::endl;
      array<double,1> A2{3.,2.};
      std::cout << "A2" << A2 << std::endl;
      array<double,1> A3{2, 3.};
      std::cout << "A3" << A3 << std::endl;
     return 0;
    }

Error is :

/users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/test/triqs/arrays/array_types.cpp: In function 'int main(int, char**)':
/users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/test/triqs/arrays/array_types.cpp:29:27: warning: narrowing conversion of '3.0e+0' from 'double' to 'size_t {aka long unsigned int}' inside { } [-Wnarrowing]
   array<double,1> A3{0, 3.};
                           ^
In file included from /users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/test/triqs/arrays/array_types.cpp:22:0:
/users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/triqs/arrays/array.hpp: In instantiation of 'triqs::arrays::array<ValueType, Rank, TraversalOrder>::array(size_t, size_t, triqs::arrays::memory_layout<Rank>) [with ValueType = double; int Rank = 1; TraversalOrder = void; size_t = long unsigned int]':
/users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/test/triqs/arrays/array_types.cpp:29:27:   required from here
/users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/triqs/arrays/array.hpp:147:802: error: no matching function for call to 'triqs::arrays::indexmaps::cuboid::map<1, void>::map(triqs::utility::mini_vector<long unsigned int, 2>, triqs::arrays::memory_layout<1>&)'
     BOOST_PP_REPEAT(ARRAY_NRANK_MAX , IMPL, nil)

Laura

**Comment by parcollet** [comment]
Hi Laura, 
This is a rule of C++11, the { } constructor do not support "narrowing", designed for safety.
It can not be changed.
O.
