### ISSUE TITLE
latest commits do not compile on weiss

### ISSUE THREAD

**Issue by pascaldelange** [TRIQS/triqs#244]
The latest commits do not compile on weiss, the error message is : 

[ 29%] Building CXX object test/triqs/det_manip/CMakeFiles/det_manip2.dir/det_manip2.cpp.o
In file included from /home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/test/triqs/statistics/../test_tools.hpp:28:0,
                 from /home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/test/triqs/statistics/autocorrelation_jackknife.cpp:1:
/home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/triqs/h5/serialization.hpp: In function ‘std::string triqs::h5::serialize(const T&)’:
/home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/triqs/h5/serialization.hpp:48:59: error: there are no arguments to ‘H5Fget_file_image’ that depend on a template parameter, so a declaration of ‘H5Fget_file_image’ must be available [-fpermissive]
   ssize_t image_len = H5Fget_file_image(f, NULL, (size_t)0);
                                                           ^
/home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/triqs/h5/serialization.hpp:48:59: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/triqs/h5/serialization.hpp:53:79: error: there are no arguments to ‘H5Fget_file_image’ that depend on a template parameter, so a declaration of ‘H5Fget_file_image’ must be available [-fpermissive]
   ssize_t bytes_read = H5Fget_file_image(f, (void *)&buf[0], (size_t)image_len);
                                                                               ^
/home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/triqs/h5/serialization.hpp: In function ‘T triqs::h5::deserialize(const string&)’:
/home/delange/sources/TRIQS_1.2_cthyb_debug/triqs/src/triqs/h5/serialization.hpp:70:60: error: there are no arguments to ‘H5Pset_file_image’ that depend on a template parameter, so a declaration of ‘H5Pset_file_image’ must be available [-fpermissive]
   err = H5Pset_file_image(fapl, (void *)&buf[0], buf.size());

I did not have problems when upgrading from a previous commit, the issue arose as I reinstalled another copy of triqs "from scratch".

Pascal

**Comment by tayral** [comment]
I am having the same issue...

**Comment by parcollet** [comment]
My mistake, sorry...

**Comment by pascaldelange** [comment]
Merci !

2015-07-31 17:37 GMT+02:00 Olivier Parcollet <notifications@github.com>:
