### ISSUE TITLE
Strange behavior of operator == in python?

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#245]
Hi,
In python, the operator == for gfs and meshes has a strange behavior (in my opinion): for instance,
````
m = MeshImFreq(beta=50.,S="Fermion", n_max=100)
m2 = MeshImFreq(beta=50.,S="Fermion", n_max=100)

print m==m2, m.beta==m2.beta, m.statistic==m2.statistic

g=GfImFreq(beta=50,n_points=200, indices=['up'], statistic="Fermion")
g2=GfImFreq(beta=50,n_points=200, indices=['up'], statistic="Fermion")
g3=g.copy()


print g==g2,g.mesh==g2.mesh, g.indices==g2.indices, g==g3
````
yields
````
False True True
False False True False
````
It seems to me that m and m2, and g, g2 and g3, should be equal. These equalities are fulfilled at the C++ level.
Any idea how to fix this?

**Comment by krivenko** [comment]
Hi Thomas,
Operator `==` is not defined for meshes and GFs on the Python level. For some reason `gf_desc.py` does not contain a description of the special methods `__eq__` and `__ne__`.
The result you get from `m==m2` is implementation-dependent (most likely it is equivalent o `id(m) == id(m2)`).

**Comment by tayral** [comment]
Hi Igor,
I understand.
Nevertheless, it would be nice to have these operators (they were 
working in TRIQS 1.1).

Cheers
Thomas

**Comment by parcollet** [comment]
Hello, 
Indeed, the == and != have not been implemented (forgotten simply ...).
The best way is to implement tp_richcompare in cpp2y, calling c++ ==.
I can do it when I am back, I guess it is not very urgent...
Olivier

**Comment by parcollet** [comment]
todo : 
- https://docs.python.org/2/c-api/typeobj.html?highlight=richcmpfunc#c.PyTypeObject.tp_richcompare
- add a flag in the wrap_generator to generate == and !=
- write tp_richcompare, only for == and !=, raising not implemented for the others
- add it to the table.

**Comment by parcollet** [comment]
g1 == g2 does not exists at the C++ level, does it ??
For gf_view in particular.
