### ISSUE TITLE
[tail] order_max should not recompute at each call. Operator() is slow for large size.

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#247]
Hi,
the function total_density approximately scales as **N^4** (with N = dimension of the Green's function)... reading the code, it should be **O(N^2)** (and if done optimally O(N)...)... 

```
from pytriqs.gf.local import *
%pylab inline
from time import time

times={}
for N in [2**i for i in range(4,10)]: 

 G=GfImFreq(indices=[i for i in range(N)], beta=1,n_points=250)
 G<<SemiCircular(1.)

 a=time()
 G.total_density()

 b=time()
 G.invert()

 c=time()

 times[N]=[b-a,c-b]

tot_dens_times=array([times[N][0] for N in sorted(times.keys())])
invert_times=[times[N][1] for N in sorted(times.keys())]
time_pts=array([N for N in sorted(times.keys())])

plot(time_pts,invert_times,'-ob', label ="invert")
plot(time_pts,tot_dens_times,'-->r', label ="tot dens")
plot(time_pts,time_pts**3/10000000.,'-b', label ="$x^3$")
plot(time_pts,time_pts**2/1000000.,'-.k', label ="$x^2$")

plot(time_pts,time_pts**4/100000000.,'-r', label ="$x^4$")

plot()
legend(loc="best")
xscale("log")
yscale("log")
```

Here is the graph (also plotted: time for inversion to check... it is indeed less than O(N^3))

![scaling](https://cloud.githubusercontent.com/assets/1186890/9087904/b7763c22-3b8d-11e5-8663-9443747d62a2.png)

Any idea?
Thanks
Pascal and Thomas

**Comment by parcollet** [comment]
Hi, 
Why it looks like N^4 is a mystery, I agree from the code it looks it should be N^2.
But do you also find N^2 for the inverse ?? Not N^3 ?
And even so, It is clear that it is suboptimal, it should be N.
(because we compute the whole matrix while we need the trace).
The general point is that when writing this code, the performance for large N was clearly not a design goal, we had small N.

**Comment by pascaldelange** [comment]
Hi,

we fixed this by making the following changes:
-make a function density_diag that only computes the diagonal elements of the density matrix
-change the line 
````
dcomplex d= t(1)(n,n) , A=t(2)(n,n),B = t(3)(n,n) ;
````
to 
````
dcomplex d= t.data()(1-t.order_min(),n,n) , A=t.data()(2-t.order_min(),n,n),B = t.data()(3-t.order_min(),n,n) ;
````
as the operation t() where t is a tail_view returns the whole array (hence N^2).

I don't know why inverse should be faster than N^3 though.

**Comment by parcollet** [comment]
- first change is clear, because we do not use expression template here...
- second is strange : does this really change the perf ?? tail_view should cost nothing...

**Comment by pascaldelange** [comment]
We tested it, apparently it does.

**Comment by parcollet** [comment]
A lot ? We should isolate this and fix it at the root, this is highly not normal...

**Comment by pascaldelange** [comment]
![scaling](https://cloud.githubusercontent.com/assets/8996050/9108914/d685d204-3c31-11e5-8e35-8059c8fcd4bf.png)

see image.
Before changing this line, it was going exactly as N^2.
Of course on this particular case, this is no such an issue as the rescaling from N^4 to N^2 should be enough here for all practical purposes, but it might cause problems in other places.

**Comment by parcollet** [comment]
I think I now the origin, and it must be fix, this is a library bug.
We need to isolate it in a small example.

**Comment by parcollet** [comment]
A quick look to this reveals the origin of the pb, it seems quite simple : 
order_max() is *recomputed* at each call, using max_element(mask), which is of order NxN.
For small N, it does not matter, for larger N, it is N^2.
@mferrero : one needs to store omax, like omin, and have the assessor just return omax.

**Comment by parcollet** [comment]
@mferrero 
Is this fixed by now ? Can we close this ?

**Comment by pascaldelange** [comment]
It is !
Pascal

2017-06-25 13:54 GMT+02:00 Olivier Parcollet <notifications@github.com>:
