### ISSUE TITLE
[gfs] conjugate of lazy expr not possible

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#250]
Hi,
I am encountering problems writing the following expressions:

```
gt=GfImTime(beta=1, indices=[0])
#gw=Fourier(gt).conjugate()  #Fourier (a lazy_expr) does not have a method conjugate()
gw=Fourier(gt)
#g2=inverse(gw).conjugate() #inverse() (when applied to a lazy_expr) does not have a method conjugate()
#g2=conjugate(gw) #does not work either
```

Of course, one can circumvent the problem by first filling the gf with the expression Fourier, and then conjugating it, but it should be possible to write a conjugate of an expression (if this expression has the concept of a gf).

**Comment by mferrero** [comment]
Decision: make a conjugate function just like the inverse function that check whether there is a conjugate() method. I'll do this.

**Comment by parcollet** [comment]
@mferrero : for milestone 1.5

**Comment by mferrero** [comment]
Should be fixed. Now the following code does what you expect:

```python
gw = GfImFreq(beta=1, indices=[0])
gw << inverse(conjugate(iOmega_n) + 0.2)
gw2 = gw.conjugate()
gw2 << conjugate(gw)
gt = GfImTime(beta=1, indices=[0])
gt << conjugate(InverseFourier(gw))
gt << InverseFourier(conjugate(gw))
```
