### ISSUE TITLE
[h5] cannot open HDFArchive in 'a' mode after 'r' mode

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#252]
Hi
Suppose I create an HDFArchive:
````
from pytriqs.archive import *
A=HDFArchive("test.h5")
A["a"]=1.0
del A
````
and then want to (a) read something in (then close the archive with "del"), and later only (b) append to the file:
````
from pytriqs.archive import *
A=HDFArchive("test.h5",'r')
del A
A=HDFArchive("test.h5",'a')
````
This code snippet returns the error:
````
IOError: unable to create file (File accessability: Unable to open file)
````
Everything works if I comment out lines 2 and 3. It seems that instantiating a HDFArchive and then deleting it does not leave the archive in the initial state... why is this? This is pretty annoying...

**Comment by pseth** [comment]
See this dft_tools issue: https://github.com/TRIQS/dft_tools/issues/41
I think Igor has fixed this, are you on the lastest library version?

**Comment by tayral** [comment]
OK, thanks! (I had not seen the fix because I am not on the dft_tools list)
