### ISSUE TITLE
[gfs] curry of imtime does not compile

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#253]
Hi, 
the following code does not compile:
````
#include <triqs/gfs.hpp>
using namespace triqs::gfs;
using namespace triqs::lattice;

int main(){
 int nw=50;
 int nk=4;
 double beta=1.0;
 auto G_r_tau = gf<cartesian_product<cyclic_lattice, imtime>, matrix_valued, no_tail>{{ {nk, nk},{beta, Fermion, 2*nw+1}},{1,1}};
 auto expr1 = curry<0>(G_r_tau); //OK
 auto expr2 = curry<1>(G_r_tau); //does not compile
}
````
The error message is quite long. The interesting part is:
````
 error: no matching function for call to ‘triqs::arrays::indexmap_storage_pair<triqs::arrays::indexmaps::cuboid::map<3, void>, triqs::arrays::storages::shared_block<std::complex<double>, false>, void, false, true, triqs::arrays::Tag::array_view>::indexmap_storage_pair(const indexmap_type&, const storage_type&)’
````
Note that the same code with "retime" or "imfreq" instead of "imtime" compiles.
Any idea?

**Comment by parcollet** [comment]
Most likely because a single variable imtime function is *real* valued, 
while a function with 2 variables is *complex* valued.
The best fix will probablyl be to change the default for imtime (to complex), 
while we implement G(tau) complex functions.

**Comment by tayral** [comment]
https://github.com/tayral/triqs/blob/thomas_test/test/triqs/gfs/thomas/issue_253.cpp

**Comment by parcollet** [comment]
Solved in g_tau_complex branch.
