### ISSUE TITLE
[archive] create_group error after recent changes

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#254]
I have been having some trouble with one of my scripts since the recent archive changes. This is the message that I see.

```
    ar.create_group('non-int')
  File "/home/pseth/SOURCES/TRIQS/install/lib/python2.7/site-packages/pytriqs/archive/hdf_archive_basic_layer_h5py.py", line 120, in create_group
    self._group.create_group(key)
  File "build/bdist.linux-x86_64/egg/h5py/_hl/group.py", line 30, in create_group
  File "h5g.pyx", line 135, in h5py.h5g.create (h5py/h5g.c:2088)
ValueError: not a location (Invalid arguments to routine: Inappropriate type)
mpirun: killing job...
```

This problem does not occur with my HEAD at d9791c5, so I suspect the bug is hiding in 3da2875.

**Comment by krivenko** [comment]
Hi Pri,
Would be nice to see the part of the script where `ar` is created and used.

**Comment by pseth** [comment]
```
    ...set params, etc...

    # Is this a continuation?
    previous_runs = 0
    previous_present = False
    if mpi.is_master_node():
        ar = HDFArchive(out_filename,'a')
        if 'dmft_output' in ar:
            ar2 = ar['dmft_output']
            if 'iterations' in ar2:
                previous_present = True
                previous_runs = ar2['iterations']
        else:
            ar.create_group('dmft_output')
        del ar
    previous_runs    = mpi.bcast(previous_runs)
    previous_present = mpi.bcast(previous_present)
    if previous_present: h_field = 0.0
    if (not previous_present) and measures: raise ValueError('Stopping: measuring but no previous runs saved.')

    ...more intermediate steps...

    # If previous run present, use the Sigma
    if previous_present:
        ...do stuff...
    else:
        # Set full_Sigma to dc_imp so that dc correction in first DMFT iteration cancels out
        full_Sigma << SK.dc_imp[0]['up']
        # Write out initial data to outfile
        if mpi.is_master_node():
            ar = HDFArchive(out_filename,'a')['dmft_output']
            ar.create_group('non-int')
            ar['non-int']['SK_Sigma_iw'] = full_Sigma
            ar['non-int']['SK_G_iw'] = full_G
            ar.create_group('convergence')
            ar.create_group('measures')
            del ar

    ...do more stuff...
```

Just a note -- my `out_filename` h5 file does not exist when the script starts. Is that a problem wrt the recent changes, given that I open it in the 'a' mode?

**Comment by krivenko** [comment]
Ok, I see...
Could this issue wait until I'm back from vacation (Monday)?

**Comment by pseth** [comment]
Sure, of course. In the meantime, I have gone back to the library version for which this script works. Enjoy your holiday!

**Comment by krivenko** [comment]
So, I have been thinking about your case...
First of all, is your code actually doing what you expect it to do?
```python
ar = HDFArchive(out_filename,'a')['dmft_output']
ar.create_group('non-int')
ar['non-int']['SK_Sigma_iw'] = full_Sigma
ar['non-int']['SK_G_iw'] = full_G
ar.create_group('convergence')
ar.create_group('measures')
del ar
```
Why do you delete `ar` here? This object corresponds to `/dmft_output` group in the archive, but not to the archive itself. If you mean to delete the archive object (and close `out_filename`), please rewrite this part as
```python
ar = HDFArchive(out_filename,'a')
gr = ar['dmft_output']
gr.create_group('non-int')
gr['non-int']['SK_Sigma_iw'] = full_Sigma
gr['non-int']['SK_G_iw'] = full_G
gr.create_group('convergence')
gr.create_group('measures')
del ar
```
and let me know, if this fixes the bug.

My point is that this expression
```python
HDFArchive(out_filename,'a')['dmft_output']
```
creates a temporary object of type `HDFArchive`, and deletes the object as soon as the expression is evaluated. In other words, it opens and closes the HDF5 file almost immediately. The file had not been closed on destruction, before I commited 3da2875, and your script was working thanks to this bug.

**Comment by pseth** [comment]
Hi Igor,

Thanks for the explanation. I changed the code as you suggested, and it works with the new changes.
I am closing this.

Cheers,
Pri

**Comment by krivenko** [comment]
I believe this issue deserves some more discussion.

We could consider storing a reference to the parent `HDFArchiveGroup` in every `HDFArchiveGroup` object. In this way we would ensure that a file remains open as long as there is at least one group object descendant from that file.
@mferrero @parcollet What do you think?

**Comment by parcollet** [comment]
Igor, I completely agree.
The problem should not occur, the group should keep a handle to the file...

**Comment by krivenko** [comment]
I've pushed a fix.
You should be able to use your original code now, and the archive file will be closed only by `del ar`.

**Comment by pseth** [comment]
Thanks Igor. It does work.

However, can I push a bit further? At the moment I can't write something like
```
with HDF(file.h5,'r')['dmft_output'] as ar:
    gf = ar['gf']
```
as I get `AttributeError: HDFArchiveGroup instance has no attribute '__exit__'`. Can this be added as well for the groups/subgroups?

This is not a bug, just a feature request.

**Comment by krivenko** [comment]
Please, give it a try now.

**Comment by pseth** [comment]
Brilliant, works like a charm. I am happy to close this issue now, unless there is more to be done?
