### ISSUE TITLE
[archive] Cannot store empty Python dictionary

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#255]
Hello,
I wonder why it is forbidden to store an empty Python dictionary in the archive:
```Python
from pytriqs.archive import *
ar = HDFArchive('test.h5','w')
ar['d'] = {}
```
```
Traceback (most recent call last):
  File "h5_empty_dict.py", line 3, in <module>
    ar['d'] = {}                                                                                                                                                                         
  File "/afs/physnet.uni-hamburg.de/users/th1_li/ikrivenk/TRIQS/installed/lib/python2.7/site-packages/pytriqs/archive/hdf_archive.py", line 194, in __setitem__
    if (d=={}) : raise ValueError, "__reduce_to_dict__ returns an empty dict"
ValueError: __reduce_to_dict__ returns an empty dict
```
Any good reason to keep this restriction?

**Comment by opeil** [comment]
I second that. What kind of crime is it to store empty lists, dicts etc? If this condition is here only to catch errors in __reduce_to_dict__() then it might make sense to do all the checks at the stage of reduction itself (and throw relevant excpetions if needed).

**Comment by krivenko** [comment]
I remove that check, since neither me nor anyone else seems to have arguments for keeping it.
Feel free to reopen if you disagree.
