### ISSUE TITLE
[gfs] 'target_shape' of a gf/gf_view

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#260]
Hi,
For a given gf_view gv, e.g. 

```
g=gf<imfreq,matrix_valued>{{1.0,Fermion},{2,2}};
auto gv = gf_view<imfreq, matrix_valued>(g);
```

... I would like to know the shape of the 'target_space' elements (namely {2,2}). One way is to call

```
gv.data().shape()
```

(namely {1025, 2, 2}) from which I can extract what I want. Is there a more direct way?
I have tried an easier (yet a bit awkward) way:

```
gv[0].shape()
```

but it does not compile:

```
error: ‘using r_type = std::c14::result_of_t<triqs::gfs::gfs_implementation::data_proxy<triqs::gfs::imfreq, triqs::gfs::matrix_valued>(triqs::arrays::array_view<std::complex<double>, 3, void, false, false>&, long int)>’ has no member named ‘shape’
```

(note: this line would compile if using g instead of gv)
a) Is it an unwanted behavior or is it intended? 
b) Would it make sense to have a member 'target_shape()' for all gf's/gf_view's?

Thanks

**Comment by tayral** [comment]
Note:
```
auto s = get_target_shape(gv)
```
works.

**Comment by parcollet** [comment]
Add shape method to matrix_tensor_proxy

**Comment by tayral** [comment]
The full example:
```
#include <triqs/gfs.hpp>
using namespace triqs::gfs;
int main(){
auto g=gf<imfreq,matrix_valued>{{1.0,Fermion},{2,2}};
auto gv = gf_view<imfreq, matrix_valued>(g);

auto s = gv.data().shape();

//auto s2 = gv[0].shape();
auto s2 = g(0).shape();
//auto s2 = get_shape(gv[0]);
std::cout << s2 << std::endl;

auto s3 = get_target_shape(gv);

}
```

**Comment by tayral** [comment]
https://github.com/tayral/triqs/blob/thomas_test/test/triqs/gfs/thomas/issue_260.cpp

**Comment by parcollet** [comment]
get_target_shape is the proper solution.
Nothing to do.
