### ISSUE TITLE
Moving to python3

### ISSUE THREAD

**Issue by Titan-C** [TRIQS/triqs#263]
I would like to know the development towards the migration to python3.

**Comment by parcollet** [comment]
Is it useful ??
Most of the scientific community is still in 2.7, as far as I know...

**Comment by Titan-C** [comment]
> it useful ??

Yes, or at least move towards a more compatible one.
I have crashes with absolute and relative imports.

I prefer python3 use of iterators, advanced unpacking features, and chained exceptions.

> Most of the scientific community is still in 2.7, as far as I know...

Most of the scientific software in python is already in python3. Numpy, Scipy, Matplotlib, Pandas, Cython

**Comment by parcollet** [comment]
If you have a pb with import with 2.x, one can probably fix that

The basic scientific libs have finally been ported to 3.x, 
but many scientific projects are still in 2.x, and will stay for some time, probably years.
Issues for us are : 
- adapt the c++2py tool, some of the API has changed. Doable but a bit boring.
- The change of print syntax, a/b meaning for int, ... a lot of source of problems.
We can not maintain 2 versions of TRIQS for 2 and 3. If we switch, everyone must switch to 3.
I do not think most users will be happy.
It is not my priority at the moment, I prefer that people upgrade their C++ compiler...
 
cc @krivenko, @mferrero : your opinion ?

**Comment by krivenko** [comment]
Hello,
We will have to move to Python 3 sooner or later... but not now.
There are many other, more important and anticipated things to do, including
* API stabilization;
* Better documentation;
* Bug fixes.

Let alone feature requests and new functionality we need for our own TRIQS-based projects.

And also this,
> We can not maintain 2 versions of TRIQS for 2 and 3. If we switch, everyone must switch to 3.  I do not think most users will be happy.

From my experience, Python 3 is still rarely found on HPC machines. Even 2.7 is not always available.

**Comment by Titan-C** [comment]
> We will have to move to Python 3 sooner or later... but not now.
> There are many other, more important and anticipated things to do, including
> 
>     API stabilization;
>     Better documentation;
>     Bug fixes.

I do agree on your priority list.

>  We can not maintain 2 versions of TRIQS for 2 and 3. If we switch, everyone must switch to 3. I do not think most users will be happy.

The python2 and python3 is indeed a bit of a pain, although the transition can be smoothed. Some changes are back ported back even to python 2.6. And the six module does help a lot when keeping both versions.
A huge step forward would be to start with this heading in the python files
```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
```

> From my experience, Python 3 is still rarely found on HPC machines. Even 2.7 is not always available.

I have also this experience. Most of my problems were solved using the virtual environments of Continuum Analytics( the Anaconda distribution), as it contains a python environment but can hold many other libraries and binaries.

**Comment by mferrero** [comment]
After discussing with @parcollet, @tayral and @pseth we decided that:

- From now on in future python codes we will be careful to write divisions correctly to prepare for the migration
- Later on we will go through the old python scripts and fix the syntax where needed and add the __future__ imports

**Comment by tayral** [comment]
Dear all,
A few years have passed since this issue was raised, and my impression is that Python 3 is now becoming the standard version of Python, even in the scientific community.
What do you think? Is there any plan to move to Python 3 at some point, or do we have good reasons to stick to 2.7?

Thanks
Thomas

**Comment by parcollet** [comment]
You are correct. And support for Python 2.7 will start to go in 2019-2020.
Moving to Python 3 is high on the priority list, this will be discussed
at the next TRIQS meeting in June.

**Comment by krivenko** [comment]
I want to mention one important point regarding transition to Python 3 (I'll forget it otherwise...)

Python 3.3 features [PEP 420](https://www.python.org/dev/peps/pep-0420). This PEP defines so called "namespace package", that is a package whose files are located in multiple disjoint directories. It completely solves the problem, which once was addressed with the `sitecustomize.py` hack.

**Comment by parcollet** [comment]
Ok, thank you Igor for this point.
Indeed, it would simplify our lives in many cases.

**Comment by tayral** [comment]
Hi all,
If you don't already know, there is a tool that seems to make it easy to go from python2 to python3: 2to3 (https://docs.python.org/2/library/2to3.html). I don't know if it will do 100% of the job, but it could help.
Thomas

**Comment by DerWeh** [comment]
I would also appreciate Python3 support. The main scientific libraries will [drop support by 2020 ](http://python3statement.org/).

Especially the IPython packages, which is to my mind central for the Python work flow already [dropped support from version 6.0](http://ipython.readthedocs.io/en/stable/whatsnew/version6.html#ipython-6-0), which adds a lot of comfort (supports `jedi`).  
Of course the new formatted strings and asynchronous support add a lot of niceties. 

Beside the already mentioned `from __future__` imports, also the [reorganization of the standard library](http://python-future.org/quickstart.html#standard-library-reorganization) should be taken into account.

**Comment by Titan-C** [comment]
Nice to see this getting some attention, so bad I don't work on this anymore. Moving the python codebase is simple. You can use the futurize project is much better than 2to3 from the standard library. It also helps to keep track of backwards compatibility during the transition, certainly you still want python2 support for a while. I did do all this, is just a few hours of work. 

The true wall I got stuck is in the way triqs is designed to talk to python. You have to work again how you treat strings and how objects are encapsulated. That you need to move from int to long int. The PyCObject, which was already deprecated years ago in favor of PyCapsule. It is really complex to support python2 and 3 at the level of C extensions, especially if one tries to directly use calls to Python.h

I know triqs has its in house way of creating the C++ bindings for python. I might be a good time to rethink about that too. Currently there a newer projects like Pybind which work really well.

**Comment by HugoStrand** [comment]
Another piece of info on this:
Numpy will stop feature development in Python2 by the end of this year (2018).
https://www.numpy.org/neps/nep-0014-dropping-python2.7-proposal.html

**Comment by DerWeh** [comment]
Most libraries of the scientific stack will drop support soon.
[https://python3statement.org/](https://python3statement.org/)
Matplotlib new release is also Python3 only, the old 2.2.x version will however receive bug-fixes.
[https://matplotlib.org/ ](https://matplotlib.org/ )

**Comment by shinaoka** [comment]
Is there any update on this issue?

**Comment by brambmax** [comment]
I am a PhD Student at Professor Schollwoecks chair in Munich. We are currently rewriting our DMFT code. The new version is in python3, so for us it would also be great if TRIQS had python3 support.

**Comment by Wentzell** [comment]
The next release of TRIQS (3.0.0) will be based on Python 3.
We plan to have a first release candidate in the beginning of next year.
The largest complication is the Python 3 compatibility of the cpp2py tool wrapping tool.

**Comment by shinaoka** [comment]
Thank you for the information.
Will TRIQS 3.0.0 be compatible with C++17?

**Comment by Wentzell** [comment]
Yes the next version will still be reliant on C++17.

**Comment by ghost** [comment]
great!! i am still waiting the update for python3!

**Comment by Wentzell** [comment]
Dear @muhammadgaffar @shinaoka @DerWeh @Titan-C,

The Python3-based release candidate [3.0-rc1](https://github.com/TRIQS/triqs/releases/tag/3.0-rc1) was tagged both for TRIQS and various applications. Please let me know if things work for you!

If I don't hear back from you I assume things are working and will close this issue.
The final 3.0.0 will be tagged shortly.

**Comment by shinaoka** [comment]
Hi, thank you for your work!
I've not had time to test TRIQS 3.0-rc1 yet but we can close this issue.

**Comment by Wentzell** [comment]
I will close this issue. If you run into problems with the 3.0-rc1 or 3.0.0 once it is tagged, please open a separate issue.
