### ISSUE TITLE
[c++2py] std::pair and std::tuple should be converted to tuple()

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#264]
Hello,

Presently c2py converters for `std::pair` and `std::tuple` return Python list objects. This may have undesirable side effects in the contexts where Python makes difference between mutable and immutable types. I have found that it is impossible to convert an `std::map` to Python dictionary using `std::pair` or `std::tuple` as map keys.
```python
from wrap_generator import *

module = module_(full_name = "pytriqs.issue264", doc = "Issue #264")

module.add_preamble("""
#include <utility>
#include <tuple>
#include <map>

using pair_to_double_t = std::map<std::pair<int,int>,double>;
using tuple_to_double_t = std::map<std::tuple<int,int>,double>;

pair_to_double_t make_ptd() {
 return {{std::make_pair(1,2),0.5}};
}

tuple_to_double_t make_ttd() {
 return {{std::make_tuple(1,2),0.5}};
}
""")
module.add_include("<triqs/python_tools/converters/pair.hpp>")
module.add_include("<triqs/python_tools/converters/tuple.hpp>")
module.add_include("<triqs/python_tools/converters/map.hpp>")

module.add_function("pair_to_double_t make_ptd()")
module.add_function("tuple_to_double_t make_ttd()")

module.generate_code()
```
This module compiles well, but when I try to use `make_ptd()` or `make_ttd()` I get an error:
```
>>> from issue264 import *
>>> make_ptd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> make_ttd()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```
It seems easy to fix this issue, just return `tuple()` instead of `list()` from the converters. But this would be a potential API break, so I want to know your opinion.

**Comment by parcollet** [comment]
I have met exactly the same point a few days ago.
@tayral : can you remind me your example, where we concluded we needed to convert into a tuple instead of a list ?
API break: a priori yes, but how often do we use this ? What is the impact of such break ?

**Comment by krivenko** [comment]
>  API break: a priori yes, but how often do we use this ? What is the impact of such break ?

I used `std::tuple` only in one place in cthyb's interface. `std::pair` has to be more pervasive.

**Comment by parcollet** [comment]
Ok, but returning a tuple instead of a list will *not* break python code in vast majority of cases, 
(they are both iterables, etc...).

**Comment by krivenko** [comment]
> Ok, but returning a tuple instead of a list will not break python code in vast majority of cases
True.
Ok, if you don't mind I can prepare a fix even today.

**Comment by parcollet** [comment]
At present, I think it is ok, I see no counter example.
Anyway, I did *not* decide to use list instead of tuple when I wrote it, 
I simply did not consider this point, that is clear to me.
So yes, go ahead. I guess it is just replace the PyList functions of the API by xxxTuple ones.

**Comment by krivenko** [comment]
Done.
I hope no reference leaks have been introduced...

**Comment by parcollet** [comment]
Where ? I can review for leaks...

**Comment by parcollet** [comment]
Got it: reviewing...

**Comment by parcollet** [comment]
Looks very good to me. No leak.
 Closing.

**Comment by parcollet** [comment]
@tayral: please confirm that this also fix your pb with tuple transcription, 
I think it should.
