### ISSUE TITLE
autocorrelation_jackknife test fail

### ISSUE THREAD

**Issue by pbakalov** [TRIQS/triqs#266]
make proceeds fine until this point:

```
Scanning dependencies of target gf3
[ 76%] Building CXX object test/triqs/gfs/CMakeFiles/gf3.dir/gf3.cpp.o
/Users/fun/triqs/src/test/triqs/gfs/gf3.cpp:54:16: error: use of undeclared identifier 'cartesian_product'
  auto g2 = gf<cartesian_product<imfreq,imfreq>, matrix_valued>{{{1.0,Fermion},{1.0,Fermion}},{1,1}};
               ^
/Users/fun/triqs/src/test/triqs/gfs/gf3.cpp:54:34: error: 'imfreq' does not refer to a value
  auto g2 = gf<cartesian_product<imfreq,imfreq>, matrix_valued>{{{1.0,Fermion},{1.0,Fermion}},{1,1}};
                                 ^
/Users/fun/triqs/src/triqs/gfs/./meshes/matsubara_freq.hpp:28:9: note: declared here
 struct imfreq {};
        ^
/Users/fun/triqs/src/test/triqs/gfs/gf3.cpp:54:50: error: declaration of variable 'matrix_valued' with type 'auto' requires an initializer
  auto g2 = gf<cartesian_product<imfreq,imfreq>, matrix_valued>{{{1.0,Fermion},{1.0,Fermion}},{1,1}};
                                                 ^
/Users/fun/triqs/src/test/triqs/gfs/gf3.cpp:54:63: error: expected ';' at end of declaration
  auto g2 = gf<cartesian_product<imfreq,imfreq>, matrix_valued>{{{1.0,Fermion},{1.0,Fermion}},{1,1}};
                                                              ^
                                                              ;
4 errors generated.
make[2]: *** [test/triqs/gfs/CMakeFiles/gf3.dir/gf3.cpp.o] Error 1
make[1]: *** [test/triqs/gfs/CMakeFiles/gf3.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Any ideas where the problem might be?

**Comment by parcollet** [comment]
I have Yosemite, it works fine here.
What is the value of USE_CPP14 make flags ?
which clang++ ?

**Comment by pbakalov** [comment]
`clang++ --version` gives me:
```
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```

I'm now repeating with `-USE_CPP14=ON`

**Comment by parcollet** [comment]
1- CPP14 should be on by default on OS.X.

2- commit 1770cd4a2a4cffe4b9c15fa0bc5065d99e88794d
@tayral 
Author: tayral <thomas.ayral@polytechnique.edu>
Date:   Fri Oct 9 17:52:20 2015 +0200
    [operators] extract U matrix from H (c++)

Added some test with multivariable gf, which are only in C++11 mode.

@mferrero, @krivenko : see ? C++11 mode is a source of errors.

Fixing.

**Comment by pbakalov** [comment]
Many thanks! 

Now `make` completes fine, but `make test` yields `110 - autocorrelation_jackknife (Failed)` (that's the only one that fails)

**Comment by parcollet** [comment]
I have seen it, another commit of @tayral ?
Don't worry, it is not important.
@tayral : to fix for 1.3 release.

**Comment by tayral** [comment]
I need more info, all tests pass on Ubuntu 14.04 and I do not have 
access to Yosemite.

**Comment by parcollet** [comment]
Cf 
https://gist.github.com/parcollet/d2ffbdb3accc5e098401
Looks like a rounding error.
We can kill it on the Triqs meeting on Friday.
