### ISSUE TITLE
installation 1.2 import scipy

### ISSUE THREAD

**Issue by facioj** [TRIQS/triqs#269]
Hi. Installing version 1.2 (on a CentOS 6.x based system, without root privilegies, using virtualenv), I had the following issue:

Cmake seems to end up well ( output: http://pastebin.com/S5LdXzaD ), but then it crashes:
```javascript
Scanning dependencies of target python_wrap_gf
[  1%] Generating gf_wrap.cpp, ../../../include/pytriqs/converters/gf.hpp
Traceback (most recent call last):
  File "/home/facioj/repos/triqs1.2_sources/prueba/build/pytriqs/gf/local/gf_desc.py", line 370, in <module>
    g = make_gf(py_type = "GfImFreq", c_tag = "imfreq", is_im = True)
  File "/home/facioj/repos/triqs1.2_sources/prueba/build/pytriqs/gf/local/gf_desc.py", line 361, in make_gf
    g.add_pure_python_method("pytriqs.gf.local._gf_%s.plot"%c_tag, rename = "_plot_")
  File "/home/facioj/repos/triqs1.2_sources/prueba/build/pytriqs/cpp2py/wrap_generator.py", line 544, in add_pure_python_method
    m = __import__(module.rsplit('.')[-1])
  File "/home/facioj/repos/triqs1.2_sources/prueba/build/pytriqs/gf/local/_gf_imfreq.py", line 1, in <module>
    from scipy.optimize import leastsq
ImportError: No module named scipy.optimize
make[2]: *** [pytriqs/gf/local/gf_wrap.cpp] Error 1
make[1]: *** [pytriqs/gf/local/CMakeFiles/python_wrap_gf.dir/all] Error 2
make: *** [all] Error 2
```

Nevertheless, in a python environment I can import scipy.optimize without any problem.

Just trying to understand better the problem I remove (in src/pytriqs/gf/local/_gf_imfreq.py) the line:
```javascript
from scipy.optimize import leastsq
```
and the installation goes on fine, and all the tests (except the 128-autocorrelation_jackknife ) are passed.
So I presume it's working. But I don't know how safe it's what I did. Should I expect some problems? Or that line for some reason is useless ?

Best,
Jorge

**Comment by parcollet** [comment]
The leastsq is used only in a deprecated function.
The pb probably means that your python environment is broken in some way.
Anyway, I can move in the import in the unused function, it is better anyway not to import scipy if not needed.
