### ISSUE TITLE
[gfs] cannot fourier transform tensor_valued gf

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#273]
Tensor-valued gfs cannot be Fourier transformed.
e.g.

```
 auto Gf = gf<imfreq, tensor_valued<3>>{{beta, Boson, n_im_freq},{1,1,1}};
 auto Gt = gf<imtime, tensor_valued<3>>{{beta, Boson, n_tau},{1,1,1}};

 Gt() = inverse_fourier(Gf);
```

does not compile.
Missing: _fourier_impl for tensor_valued.
Note: _fourier_impl for tensor_valued requires the specialization of slice_target_to_scalar to tensor_valued functions ; this OK except that leads to problems with imtime which is supposed to be double-valued instead of complex...

**Comment by parcollet** [comment]
Will be solved by i) g(tau) complex change ii) vectorisation of fourier fttw call.

**Comment by parcollet** [comment]
@tayral : still open ?

**Comment by parcollet** [comment]
Fixed in 0ac38c8c0f17f1dcc346389fa7b7c3b67e655cb6

**Comment by tayral** [comment]
Well, should we really close this? There are still issues with the tail of a tensor-valued, and further testing is needed...

**Comment by parcollet** [comment]
Then
- change title
- list the things to be done.

**Comment by parcollet** [comment]
Was it solved by the recent merge of your branch ?
If not, please list what is still missing...

**Comment by parcollet** [comment]
@tayral : status of this ?

**Comment by parcollet** [comment]
We will reimplement the fourier, unifying the call to FFTW , tensor like.

**Comment by Wentzell** [comment]
This should be fixed in the latest development version. To be rechecked.

**Comment by Wentzell** [comment]
This is fixed. c.f. https://github.com/TRIQS/triqs/blob/22f9f60a6072a667235114408443d5ecd9618975/test/c%2B%2B/gfs/fourier_matsubara.cpp#L33-L48
