### ISSUE TITLE
[gfs] No std::swap() for views?

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#276]
Hi,
I'm working on a new move for cthyb, and I want to swap two `det_manip` objects. Copying them would be a serious performance penalty, and is not an options. The determinants are constructed out of a function-object with one data member, `gf_const_view<imtime> delta_block`. `swap()` is explicitly deleted for `gf_const_view`. Does this really mean that I cannot swap my determinants? What options do I have?
Thanks in advance!

**Comment by parcollet** [comment]
Why can't we swap const_view ? Any reason ?

**Comment by parcollet** [comment]
I mean: I see we can not. The question is : is it correct ?

**Comment by krivenko** [comment]
Thanks a lot for the fix!
