### ISSUE TITLE
Compilation error gcc 4.8.1

### ISSUE THREAD

**Issue by phansmann** [TRIQS/triqs#277]
compilation of triqs gives error due to line 76 in triqs.src/test/triqs/gfs/gfv2.cpp 
which reads 
``
G3 = G +2* Gc;
``
commenting out that line resolves the error which reads:

``
/home/hansmann/SOURCES/TRIQSn/triqs.src/test/triqs/gfs/gfv2.cpp:76:6:   required from here
/usr/include/c++/4.8/bits/move.h:89:7: error: static assertion failed: template argument substituting _Tp is an lvalue reference type
       static_assert(!std::is_lvalue_reference<_Tp>::value, "template argument"
       ^
``

**Comment by mferrero** [comment]
Hi Philipp. This is most likely the same problem as in  #138 and #180. It seems that there is a bug in gcc 4.8.1 and gcc 4.8.2 (or at least some versions of these...). Should be fixed for gcc >= 4.8.3.

**Comment by phansmann** [comment]
OK - Thanks! Just about to update gcc.
