### ISSUE TITLE
[c++2py] Convert std::map<std::vector<K>,V> to Python

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#278]
Hello,

The type mentioned in the subject is asymmetric w.r.t. C++/Python conversions.  It can be converted from `dict{(...) : ...}`, but the way back is forbidden. Lists are not hashable in Python and are not allowed as keys of a dictionary.

What is the cleanest way to avoid this difficulty?

My practical example involves `std::vector<variant_int_string>`, i.e. index type of the `many_body_operator`.

**Comment by parcollet** [comment]
vector is converted back to list ? why not tuple ?
I thought you changed that to tuple at some point ?

**Comment by krivenko** [comment]
Before it was even worse: `std::tuple` was converted to list. This is what I fixed.
Vector is still converted to list, which seems logical, in principle.

**Comment by parcollet** [comment]
What would forbid to convert vector to a tuple ?
Even though it is not very logical...
One can also fix the converter of std::map to make the key tuple if they are list.
That is ad-hoc however.

**Comment by krivenko** [comment]
> What would forbid to convert vector to a tuple ?

Another API break. And more severe than it was last time.
Apart from that... I don't know.

> One can also fix the converter of std::map to make the key tuple if they are list.
> That is ad-hoc however.

The problem itself is quite singular...

**Comment by parcollet** [comment]
Cf my commit on dev.
Solve the pb, and there is API break.

**Comment by krivenko** [comment]
Thank you!
