### ISSUE TITLE
Intel compilers version 16.0.1 : speed test needed

### ISSUE THREAD

**Issue by johanjoensson** [TRIQS/triqs#279]
Hello!

I am trying to compile TRIQS with the intel compiler version 16.0.1, but the compilation fails. The error messages seem to indicate some sort of error/bug in the intel compilers. I have built TRIQS using GCC, on another system and I did not get these errors.

I have attached a file with all the output from the installation.

[triqs_compile.txt](https://github.com/TRIQS/triqs/files/62622/triqs_compile.txt)

Regards,
Johan Jönsson

**Comment by parcollet** [comment]
Hi, 
- did you use C++14 mode ?

**Comment by johanjoensson** [comment]
Yes, I tried using both C++14 and C++11 mode, but got the exact same error in both cases.

**Comment by parcollet** [comment]
Ok, it was working with the icc 16beta.
I do not have access to icc 16 at the moment, so I have to postpone this issue for the time being.

**Comment by parcollet** [comment]
Fixed triqs for icc (ICC) 16.0.1 20151021
triqs and cthyb compiles and pass tests.
TODO : 
- check link to mkl.
- run various code with gcc and icc to compare speed. Is it worth using icc ?

**Comment by parcollet** [comment]
Added automatic detection of MKL in cmake
