### ISSUE TITLE
Make test fails almost completely due to non-standard location of installed packages

### ISSUE THREAD

**Issue by rakeshgautam** [TRIQS/triqs#281]
Hi there,

I am trying to install TRIQS 1.3 in Mac OS 10.11.2 and Xcode 7.2. I have installed required python packages and c++ libraries in /opt/... directories. I load those packages and libraries via module files:

Currently Loaded Modulefiles:
  1) cmake/3.4.1                             5) gmp/6.1.0
  2) openmpi/openmpi-gcc/1.10.0   6) fftw/3.3.4
  3) boost/1.58.0                             7) anaconda/python-2.7
  4) hdf5/1.8.15

And in anaconda I have required python packages: python, scipy, numpy, h5py, matplotlib, pyparsing, sphinx, mpi4py, mako.

I configure TRIQS by

cmake -DCMAKE_INSTALL_PREFIX=/opt/triqs/triqs-1.3 \
  -DCMAKE_C_COMPILER:FILEPATH=/usr/bin/clang \
  -DCMAKE_CXX_COMPILER:FILEPATH=/usr/bin/clang++ \
  -DBoost_LIBRARY_DIR:PATH=/opt/boost/boost-1.58.0/lib \
  -DBoost_INCLUDE_DIR:PATH=/opt/boost/boost-1.58.0/include \
  -DHDF5_LIBRARIES:FILEPATH=/opt/hdf5/hdf5-1.8.15/lib/libhdf5.dylib \
  -DHDF5_INCLUDE_DIR:PATH=/opt/hdf5/hdf5-1.8.15/include  \
  -DPYTHON_INTERPRETER:FILEPATH=/opt/anaconda/python-2.7/bin/python \
  -DFFTW_LIBRARIES:FILEPATH=/opt/fftw/fftw-3.3.4/lib/libfftw3.a \
  -DFFTW_INCLUDE_DIR:PATH=/opt/fftw/fftw-3.3.4/include \
  -DGMPXX_LIBRARIES:FILEPATH=/opt/gmp/gmp-6.1.0/lib/libgmpxx.dylib \
  -DGMP_LIBRARIES:FILEPATH=/opt/gmp/gmp-6.1.0/lib/libgmp.dylib \
  -DGMP_INCLUDE_DIR:PATH=/opt/gmp/gmp-6.1.0/include \
  $PWD/../triqs-1.3

and it successfully configured and output of cmake . gives:

-- Installation directory is /opt/triqs/triqs-1.3
-- Compiler version = Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
-- Compiler is clang with version Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
-- Adding compilation flags -stdlib=libc++ 
-- Compiling in C++11 mode
-- DYNAMIC Built 
-- -------- Python detection -------------
-- Python interpreter /opt/anaconda/python-2.7/bin/python
-- Python interpreter and modules are ok : version 2.7.11
-- PYTHON_INCLUDE_DIRS =  /opt/anaconda/python-2.7/include/python2.7
-- PYTHON_H5PY_HDF5VERSION = 1.8.15
-- PYTHON_NUMPY_INCLUDE_DIR = /opt/anaconda/python-2.7/lib/python2.7/site-packages/numpy/core/include
-- PYTHON_NUMPY_VERSION = 1.10.2
-- PYTHON_SITE_PKG = /opt/anaconda/python-2.7/lib/python2.7/site-packages
-- PYTHON_LIBRARY = /opt/anaconda/python-2.7/lib/python2.7/config/libpython2.7.a
-- PYTHON_EXTRA_LIBS =-ldl  -framework CoreFoundation
-- IPython found
-- --------------------------------------------
-- Numpy include in /opt/anaconda/python-2.7/lib/python2.7/site-packages/numpy/core/include
-- Python modules will be installed in /opt/triqs/triqs-1.3/lib/python2.7/site-packages/pytriqs
-- Preparing the various scripts 
-- -------- MPI detection -------------
-- MPI CXX compiler : /opt/openmpi/openmpi-gcc/openmpi-gcc-1.10.0/bin/mpicxx
-- MPI_COMPILE_FLAGS :  
-- MPI_CXX_INCLUDE_PATH : /opt/openmpi/openmpi-gcc/openmpi-gcc-1.10.0/include
-- -------- Boost detection -------------
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   mpi
--   serialization
--   system
-- Boost include dir: /opt/boost/boost-1.58.0/include
-- Boost libraries: /opt/boost/boost-1.58.0/lib/libboost_mpi.dylib;/opt/boost/boost-1.58.0/lib/libboost_serialization.dylib;/opt/boost/boost-1.58.0/lib/libboost_system.dylib
-- Checked max_align_t. No workaround needed
-- 64 bit machine : Adding -fpic 
-- -------- Lapack detection -------------
-- Using Framework on Darwin.
-- Lapack libraries : -framework Accelerate /usr/lib/libpthread.dylib
-- -------- HDF5 detection -------------
--  HDF5_LIBRARIES = /opt/hdf5/hdf5-1.8.15/lib/libhdf5.dylib;/opt/hdf5/hdf5-1.8.15/lib/libhdf5.dylib;/opt/szip/szip-2.1/lib/libsz.dylib;/opt/zlib/zlib-1.2.8/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib;/opt/hdf5/hdf5-1.8.15/lib/libhdf5_hl.dylib;/opt/hdf5/hdf5-1.8.15/lib/libhdf5.dylib;/opt/szip/szip-2.1/lib/libsz.dylib;/opt/zlib/zlib-1.2.8/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib 
-- hdf5 version: 1.8.15
-- -------- GMP detection -------------
-- GMP libs: /opt/gmp/gmp-6.1.0/lib/libgmp.dylib /opt/gmp/gmp-6.1.0/lib/libgmpxx.dylib
-- -------- FFTW detection -------------
-- -------- NFFT detection (optional) -------------
-- Could NOT find NFFT (missing:  NFFT_LIBRARIES NFFT_INCLUDE_DIR) 
-- Build type: Release
-- -------- git and hash detection -------------
-- This is not a git clone
-- Git hash 
-- Git branch :  
-- -------- LibClang detection -------------
-- LibClang location: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib
-- LibClang additional flags:  -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1 -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/7.0.2/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/usr/include -I/System/Library/Frameworks -I/Library/Frameworks
-- -------- Preparing python extension modules  -------------
-- Preparing extension module gf
-- Preparing extension module lattice_tools
-- Preparing extension module operators
-- Preparing extension module random_generator
-- -------- Preparing tests  -------------
-- Preparing extension module my_module
-- Preparing extension module my_moduleB
-- Preparing extension module test_g
-- -------- Making TRIQSConfig.cmake -------------
-- -------- Python detection -------------
-- Python interpreter /opt/anaconda/python-2.7/bin/python
-- Python interpreter and modules are ok : version 2.7.11
-- PYTHON_INCLUDE_DIRS =  /opt/anaconda/python-2.7/include/python2.7
-- PYTHON_H5PY_HDF5VERSION = 1.8.15
-- PYTHON_NUMPY_INCLUDE_DIR = /opt/anaconda/python-2.7/lib/python2.7/site-packages/numpy/core/include
-- PYTHON_NUMPY_VERSION = 1.10.2
-- PYTHON_SITE_PKG = /opt/anaconda/python-2.7/lib/python2.7/site-packages
-- PYTHON_LIBRARY = /opt/anaconda/python-2.7/lib/python2.7/config/libpython2.7.a
-- PYTHON_EXTRA_LIBS =-ldl  -framework CoreFoundation
-- IPython found
-- --------------------------------------------
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/rakesh/tmpbuild/triqs.build

The make command compile TRIQS successfully:
........
 [100%] Built target test_g 

The make test fails almost completely only test_example passes: 1% tests passed, 139 tests failed out of 140. The problem is related to linking problem of dynamic libraries as triqs.build/Testing/Temporary/LastTest.log suggests. 

Start testing: Dec 22 16:11 SGT
----------------------------------------------------------
1/140 Testing: algorithms
1/140 Test: algorithms
Command: "/Users/rakesh/tmpbuild/triqs.build/test/triqs/arrays/algorithms"
Directory: /Users/rakesh/tmpbuild/triqs.build/test/triqs/arrays
"algorithms" start time: Dec 22 16:11 SGT
Output:
----------------------------------------------------------
dyld: Library not loaded: libboost_mpi.dylib
  Referenced from: /Users/rakesh/tmpbuild/triqs.build/test/triqs/arrays/algorithms
  Reason: image not found
<end of output>
Test time =   0.13 sec
----------------------------------------------------------
Test Failed.
"algorithms" end time: Dec 22 16:11 SGT
"algorithms" time elapsed: 00:00:00
----------------------------------------------------------

I have already set LD_LIBRARY_PATH and DYLD_LIBRARY_PATH in module file.

-------------------------------------------------------------------
/opt/Modules/mymodules/boost/1.58.0:

module-whatis	 BOOST 1.58.0 
prepend-path	 PATH /opt/boost/boost-1.58.0/include 
prepend-path	 LD_LIBRARY_PATH /opt/boost/boost-1.58.0/lib 
prepend-path	 DYLD_LIBRARY_PATH /opt/boost/boost-1.58.0/lib 
-------------------------------------------------------------------

I figured out that make test gives great success with only 12 failures if I place all boost dynamic libraries in /usr/local/lib location. This is something I don't want to do due to software management issue. I tried hard to circumvent this problem but did not get success. Could you please suggest me any working solution.

Best regards,
Rakesh

**Comment by parcollet** [comment]
Hi, 

1- The simplest solution is probably to work with master branch. Since 1.3, I have remove all need to link to a boost library (we still use some pure header boost), so it should solve your issue at once.
Unless you really want the 1.3 version, not the development branch (i.e. master) ?

2- I do not know why it does not work. DYLD_LIBRARY_PATH should do its job. did you try it directly ? 
I am not familiar with configuring module on a mac.

PS : please use a gist for long output on github, it makes issues a lot more readable later.

Olivier

**Comment by rakeshgautam** [comment]
Thank you very much for your quick reply.
Now I am trying to install the master branch of TRIQS. It configures successfully. 

Configuration result is attached in this file.
https://gist.github.com/rakeshgautam/5aa5828e64e235c7ad5d

Now another problem is coming in make:

[  0%] Built target py_copy
[  0%] Generating comparison_tests_wrap.cpp, ../../include/pytriqs/converters/comparison_tests.hpp
Traceback (most recent call last):
  File "/Users/rakesh/tmpbuild/triqs-build/pytriqs/utility/comparison_tests_desc.py", line 1, in <module>
    from wrap_generator import *
ImportError: No module named wrap_generator
make[2]: *** [pytriqs/utility/comparison_tests_wrap.cpp] Error 1
make[1]: *** [pytriqs/utility/CMakeFiles/python_wrap_comparison_tests.dir/all] Error 2
make: *** [all] Error 2

Please help me out!!

**Comment by parcollet** [comment]
Have you made a clean build ? i.e. rm the build dir and reconfigure it from scratch.

**Comment by rakeshgautam** [comment]
I removed all old files and directories, and did this installation from scratch.

**Comment by krivenko** [comment]
Together with @MHarland, we have just seen a similar build failure on a Linux machine.

**Comment by krivenko** [comment]
Building TRIQS with CMake 2.8.12.2 on Ubuntu 14.04...
```
FILE(GLOB_RECURSE all_py_files RELATIVE ${CMAKE_SOURCE_DIR}/tools *.py )
SET(py_copy_tar  ${CMAKE_BINARY_DIR}/py_copy2.tar)
add_custom_command (OUTPUT ${py_copy_tar} DEPENDS ${all_py_files}
 COMMAND cd ${CMAKE_SOURCE_DIR}/tools && tar cf ${py_copy_tar} ${all_py_files} && cd ${CMAKE_BINARY_DIR}/tools && tar xf ${py_copy_tar} )
add_custom_target(py_copy2 ALL DEPENDS ${py_copy_tar})
```
This part of `tools/CMakeLists.txt` does not copy Python scripts into the respective binary dir.

**Comment by parcollet** [comment]
why ?
@mferrero : any idea ?

**Comment by krivenko** [comment]
There was a missing dependency...

**Comment by parcollet** [comment]
Ok for me. Closed ?

**Comment by MHarland** [comment]
Installation works now for the Ubuntu machine Igor mentioned above.
