### ISSUE TITLE
Round-off error in time_pt

### ISSUE THREAD

**Issue by JaksaVucicevic** [TRIQS/triqs#284]
There is a problem with the constructor of time point from double

triqs::utility::time_pt::time_pt(double v, double beta_) 
{ beta = beta_; val = v;  n = std::floor(Nmax*(v/beta)); }

Even when v==beta precisely, (v/beta) as a double is 1+epsilon such that n of the returned point is not Nmax but slightly larger, because Nmax is huge

static constexpr uint64_t Nmax = std::numeric_limits<uint64_t>::max();

Then when I acces a point of the imtime gf mesh by using 

gf[closest_mesh_pt(double(time_pt(beta,beta)))]

I get gf[0] instead gf[-1], due to cyclicity

A quick fix works:

time_pt(double v, double beta_)
 { beta = beta_; val = v; if (v==beta) n = Nmax; else n = std::floor(Nmax*(v/beta));}

but this needs to be dealt with systematically so as to avoid equating doubles.

The time_pt should be redesigned and there seems to be no real need for time_segment struct.

Also, since time_pt is used in both ctint and cthyb_spin, we should have support for this type in gf so as to avoid converting back and forth between double and time_pt. Ideally, an overload of [] operator would allow

gf[time_pt(v,beta)]

or at least

gf[closest_mesh_pt(time_pt(v,beta))]

The idea is to have two meshes in gf, one of doubles (taus), and one of integers corresponding to n of the time point, or a mesh of actual time points. In this second mesh, the last point could be set manually to Nmax (or time_pt(Nmax, beta, true)) . Then, for example, in ctint code, configuration.hpp, g0tau_adaptor::operator() we would have instead of

double res = gt[closest_mesh_pt(double(x.tau - y.tau))](x.a,y.a);

just

double res = gt[x.tau - y.tau](x.a,y.a);

or

double res = gt[closest_mesh_pt(x.tau - y.tau)](x.a,y.a);

where x.tau and y.tau are time_pt, and there is no need for conversion.

Also, one should be able to iterate over the mesh as time_pt instead of doubles. There is a need for this when we do measurements by operator insertion. For example

for(const time_pt& t: gf.mesh())

or 

for(int n: gf.mesh())
   //use time_pt(n,beta,true)

**Comment by pseth** [comment]
I see a similar problem when adding beta (a double) to a time_pt casted as a double. My solution was to add two time_pts and then cast the resulting value as a double. 
To do this, I added a function make_time_pt_beta (and likewise make_time_pt_zero) to the time_pt class. 

@mferrero can we add these functions to the class? I agree with Jaksa that we do not really need a time_segment class, why not just move the functions up to time_pt? It would make the API more natural.

**Comment by parcollet** [comment]
@mferrero 
this class should go back to CT-HYB, it is quite specific, no ?
I would simply remove that from the lib, it is not documented anyway.

**Comment by Wentzell** [comment]
@parcollet Agreed.

**Comment by Wentzell** [comment]
This class is in fact used in both CTHyb and CTSeg, so it should remain where it is.
Neither of the two codes use the constructor mentioned above.
I have
- Removed the `time_pt(double v, double beta_)` constructor from the `time_pt` class
  It is up to the user to provide the proper `uint64_t` value instead.
- Protected the rounding in the time_segment::make_time_point(double) function

C.f. 8cfbdaed
