### ISSUE TITLE
Speed pb with multiple var gf

### ISSUE THREAD

**Issue by parcollet** [TRIQS/triqs#287]
Cf bench : 
https://github.com/parcollet/benchmarks/blob/master/benchs/gf_m.cpp

The same technique used for one var should be generalised ...

**Comment by tayral** [comment]
Is there any progress here? (we can still use data() but it is awkward...)
Thanks

**Comment by parcollet** [comment]
I know, I have a patch, I need to clean it and merge it ...

**Comment by parcollet** [comment]
Part of gf bench now.
