### ISSUE TITLE
missing redirection for documentation

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#290]
hi,
At the moment, the github link (http://ipht.cea.fr/triqs/1.x/index.html) is not redirected to the new version of the documentation (https://triqs.ipht.cnrs.fr/1.x/index.html)
Cheers
Thomas

**Comment by parcollet** [comment]
@mferrero : can you do the redirection of the whole tries website to the new one ?

**Comment by tayral** [comment]
Anything new here?
Thx

**Comment by parcollet** [comment]
Yes it is becoming urgent ... The official doc is not sync'd with the master...

**Comment by mferrero** [comment]
Done!
