### ISSUE TITLE
requirements for compiling documentation

### ISSUE THREAD

**Issue by gsclauzero** [TRIQS/triqs#294]
Hi,
   I am trying to compile the documentation, but I encounter a problem:
[ 66%] Generating cpp2py.log
make[2]: **\* [doc/cpp2py.log] Error 1
...

The error is related to a missing python binding clang.cindex,
 File "/Users/gabriele/Software/Triqs/Builds/triqs-1.4dev/tools/clang_parser.py", line 7, in <module>
    import clang.cindex
ImportError: No module named clang.index

Strangely, two days ago I managed to compile all the documentation and this error did not show up.
Do I need to add those bindings to the python library?
Thanks

**Comment by gsclauzero** [comment]
I fixed the problem by installing the bindings with
pip install clang
I could have find out earlier by searching better on the first place, sorry...

**Comment by parcollet** [comment]
Indeed, 
I pushed on master another commit (we are about to finish 1.4, so we merge a lot of things...)
so that the doc is automatically generated from C++ code, using libclang,
but the install. doc has not been updated yet for OS X.

yes, you need the clang python bindings...

**Comment by parcollet** [comment]
Leave it open to remember to fix the install doc.

**Comment by Wentzell** [comment]
Fixed by commit cd5afff
