### ISSUE TITLE
Installation on Archlinux

### ISSUE THREAD

**Issue by AnMaillard** [TRIQS/triqs#295]
Install the following packages (TRIQS uses Python 2 but the default Python version on Archlinux is 3): 
 `yaourt -S boost boost-libs cmake git gcc gcc-fortran openmpi blas lapack fftw gmp hdf5 python2 python2-h5py python2-numpy python2-scipy python2-jinja python2-matplotlib python2-tornado python2-pyzmq python2-mako python2-mpi4py`

Then follow the usual installation, but add as argument to cmake : 

`cmake -DCMAKE_INSTALL_PREFIX=path_to_install_directory ../triqs.src -DPYTHON_INTERPRETER=python2`

And after make and make install, do not use the deprecated ipytriqs_notebook, but first add the path of the TRIQS libraries : 
`export PYTHONPATH=/your_path/INSTALL_DIR/lib/python2.7/site-packages:$PYTHONPATH
` 

And then load  notebook using 
`jupyter notebook` and start a Python2 kernel

**Comment by parcollet** [comment]
@mferrero : you see, distributions start to have python 3 by default ....

**Comment by Titan-C** [comment]
On Archlinux, Python 3 is the default since October 2010.

**Comment by parcollet** [comment]
Ok, but still our decision is still not to support Python3 at this stage.
Too much costs, no real benefits.
