### ISSUE TITLE
Installation on curie

### ISSUE THREAD

**Issue by JaksaVucicevic** [TRIQS/triqs#296]
I just pulled triqs to curie and installed from scratch. Boost is automatically detected, version 1.53.0, hdf5 version: 1.8.9, other libraries found as well, except for NFFT and libclang.

It compiles and passes all tests except for 

pytriqs/base/gf_base_op.py 

with the following error message

Traceback (most recent call last):
  File "<stdin>", line 125, in <module>
  File "/ccc/cont003/home/dsm/vucicevj/TRIQS/build/triqs/pytriqs/archive/hdf_archive.py", line 222, in __getitem__
    return self.__getitem1__(key,self._reconstruct_python_objects)
  File "/ccc/cont003/home/dsm/vucicevj/TRIQS/build/triqs/pytriqs/archive/hdf_archive.py", line 231, in __getitem1__
    if self.is_group(key) :
  File "/ccc/cont003/home/dsm/vucicevj/TRIQS/build/triqs/pytriqs/archive/hdf_archive_basic_layer_h5py.py", line 57, in is_group
    return p in self.cached_keys and type(self._group[p]) == h5py.highlevel.Group
  File "/ccc/products/ccc_python/2.7.8_201409/lib/python2.7/site-packages/h5py/_hl/group.py", line 127, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._shared.lapl)
  File "/ccc/products/ccc_python/2.7.8_201409/lib/python2.7/site-packages/h5py/_hl/base.py", line 52, in _shared
    return filedata[self.id.fileno]
  File "_objects.pyx", line 201, in h5py._objects.ObjectID.fileno.__get__ (h5py/_objects.c:2604)
ValueError: not a location (Invalid arguments to routine: Inappropriate type)

What do I do?

**Comment by krivenko** [comment]
Hey Jaksa,
Please, show us the output of
```
$ pytriqs
>>> import h5py
>>> print h5py.version.version, h5py.version.hdf5_version
```

**Comment by JaksaVucicevic** [comment]
CURIE:~/TRIQS/build/triqs $ pytriqs
Python 2.7.8 (default, Aug 27 2014, 17:50:16) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
>>> print h5py.version.version, h5py.version.hdf5_version
2.0.1 1.8.9

**Comment by parcollet** [comment]
Indeed, this looks like, once more, the h5py and the hdf5 lib
are not compatible (i.e. h5py is not compiled with this version of hdf5).
(At some point, I should really get rid of h5py finally. It is a recurrent pb).
But the number indicates otherwise ...

Can you give us exactly the 
module list

**Comment by JaksaVucicevic** [comment]
$ module list
Currently Loaded Modulefiles:
 1) ccc                       4) licsrv/intel              7) fortran/intel/14.0.3.174 10) intel/14.0.3.174         13) fftw3/gnu/3.3.4          16) python/2.7.8             
 2) datadir/own               5) c/intel/14.0.3.174        8) mkl/14.0.3.174           11) mpi/bullxmpi/1.2.8.4     14) c++/gnu/4.9.1            
 3) dfldatadir/own            6) c++/intel/14.0.3.174      9) idb/14.0.3.174           12) cmake/2.8.9              15) atlas/3.9.72

**Comment by parcollet** [comment]
where is hdf5 module ?

**Comment by JaksaVucicevic** [comment]
I didn't put it in bashrc. Now I loaded it manually but the test is still broken, even when I recompiled triqs. The default version (and the once which I loaded) is hdf5/1.8.8

**Comment by pseth** [comment]
That is odd. As Olivier said, you have two diff versions that should raise an error during the cmake. Did you do a clean install (ie. with a fresh cmake) after importing the module? The compilation shouldn't work at all, unless something has been changed in the configuration..

**Comment by JaksaVucicevic** [comment]
yes, now it does complain when I do I fresh cmake
```bash
-- hdf5 version: 1.8.8
CMake Error at CMakeLists.txt:310 (message):
  The HDF5 version of the h5py (1.8.9) is different from the hdf5 library
  found for C++ (1.8.8).  You MUST have the same version.
```
so do I install h5py 1.8.8 or hdf5 1.8.9?

**Comment by parcollet** [comment]
You need that same version for h5py and hdf5. Hence I guess load the 1.8.9 module

**Comment by JaksaVucicevic** [comment]
The guys at TGCC installed hdf5/1.8.9.
I load the module in bashrc now (didn't forget to source it) I do a fresh cmake and it no longer complains, but the test still fails...

**Comment by parcollet** [comment]
Strange.
Check that lib is really linked with hdf5/1.8.9.

**Comment by tayral** [comment]
Hi Jaska,
the hotline just installed a newer version of h5py at my request, the codes compile and run.
Please check that it also works on your account, and close the issue...

**Comment by JaksaVucicevic** [comment]
Excellent, the triqs now compiles and passes tests, but I'm still getting a bunch of warnings such as
```
Cannot generate a safe runtime search path for target
  test_tuple_and_variadic_2 because there is a cycle in the constraint graph:
```
Are you seeing these?

**Comment by tayral** [comment]
No, I have not seen this issue so far.

**Comment by parcollet** [comment]
Still open ?
