### ISSUE TITLE
.conjugate() for GfImTime

### ISSUE THREAD

**Issue by MHarland** [TRIQS/triqs#298]
Since CTHYB works now with a complex hybridization I would like to be able to force the imaginary part of it to be exact zero in some situations. Therefore it would be nice to have the `.conjugate()` function of `GfImFreq` available also for `GfImTime` and `GfLegendre`.

**Comment by parcollet** [comment]
Yes.

**Comment by parcollet** [comment]
Fixed in unstable.
conj(g) can be all the cases.
