### ISSUE TITLE
[69bd67a9] Compiler error while building test/triqs/utility/CMakeFiles/ser.dir/ser.cpp.o

### ISSUE THREAD

**Issue by opeil** [TRIQS/triqs#302]
Lots of boost-related compilation errors produced by clang3.6.

Output of clang-3.6 -v:
```
Debian clang version 3.6.1-debian1precise1 (tags/RELEASE_361/final) (based on LLVM 3.6.1)
Target: x86_64-pc-linux-gnu
Thread model: posix
....
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/5.2.1
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

Boost version 1.54.

CMake script is executed with the following options:
```
CC=clang-3.6 OMPI_CXX=clang-3.6 OMPI_CC=clang-3.6 CXX=mpic++ FC=mpif90 cmake ../src \
   -DCMAKE_CXX_FLAGS="-DH5Tarray_create_vers=2" \
   -DCMAKE_INSTALL_PREFIX=$HOME/Codes/triqs/triqs1.4/install \
   -DBOOST_ROOT=$HOME/Codes/libs/boost_install \
   -DFFTW_INCLUDE_DIR=/usr/include \
   -DFFTW_LIBRARIES=/usr/lib/libfftw3.so \
   -DBLAS_LIBRARY=$MKL_ROOT/lib/intel64/libmkl_rt.so \
   -DLAPACK_LIBRARY=$MKL_ROOT/lib/intel64/libmkl_rt.so
```

One of the error messages:
```
CMakeFiles/ser.dir/ser.cpp.o: In function `boost::serialization::singleton<boost::serialization::extended_type_info_typeid<std::vector<std::string, std::allocator<std::string> > > >::get_instance()':
ser.cpp:(.text._ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv[_ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv]+0x39): undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::extended_type_info_typeid_0(char const*)'
ser.cpp:(.text._ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv[_ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv]+0x56): undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::type_register(std::type_info const&)'
ser.cpp:(.text._ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv[_ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv]+0x5e): undefined reference to `boost::serialization::extended_type_info::key_register() const'
ser.cpp:(.text._ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv[_ZN5boost13serialization9singletonINS0_25extended_type_info_typeidISt6vectorISsSaISsEEEEE12get_instanceEv]+0xa5): undefined reference to `boost::serialization::typeid_system::extended_type_info_typeid_0::~extended_type_info_typeid_0()'
`

**Comment by gkraberger** [comment]
I see the same issue here with gcc 4.9.3 and boost 1.60.0

**Comment by parcollet** [comment]
version of hdf5 ??

**Comment by opeil** [comment]
hdf5 version: 1.8.4


On Fri, Feb 12, 2016 at 6:06 PM, Olivier Parcollet <notifications@github.com
> wrote:

> version of hdf5 ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/TRIQS/triqs/issues/302#issuecomment-183414855>.
>



-- 

 Dr. Oleg E. Peil
 Department of Quantum Matter Physics
 Universite de Geneve
 CH-1211 Geneve 4
 Switzerland                Tel :+41 (0)22 379 3571

**Comment by parcollet** [comment]
That is it.
The ser.cpp example tests a serialize function that uses hdf5 and 
falls back to boost.serialization if hdf5 is too old.
But then we need to link against boost, which we removed, and our tests machines have a recent hdf5.
Which distribution do you have ? do you have other hdf5 ?
If not I will just comment this test in this case...

**Comment by opeil** [comment]
What is considered to be old? I can check what I can install on Ubuntu from
upstream.

**Comment by opeil** [comment]
I managed to compile it using HDF 1.8.11.

 Gernot, if you can confirm that the error disappears if you switch to a
version >= 1.8.9 (as it is required by triqs/serialization.hpp) then I can
close the issue.

On Sat, Feb 13, 2016 at 3:44 PM, Oleg Peil <oleg.peil@gmail.com> wrote:

> What is considered to be old? I can check what I can install on Ubuntu
> from upstream.
> On 12 Feb 2016 19:05, "Olivier Parcollet" <notifications@github.com>
> wrote:
>
>> That is it.
>> The ser.cpp example tests a serialize function that uses hdf5 and
>> falls back to boost.serialization if hdf5 is too old.
>> But then we need to link against boost, which we removed, and our tests
>> machines have a recent hdf5.
>> Which distribution do you have ? do you have other hdf5 ?
>> If not I will just comment this test in this case...
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/TRIQS/triqs/issues/302#issuecomment-183432938>.
>>
>


-- 

 Dr. Oleg E. Peil
 Department of Quantum Matter Physics
 Universite de Geneve
 CH-1211 Geneve 4
 Switzerland                Tel :+41 (0)22 379 3571

**Comment by gkraberger** [comment]
Yes, it works for me with HDF 1.8.16.

**Comment by parcollet** [comment]
old = 1.8.9
Reopen : we should simply remove this test is hdf5 is < 1.8.9
