### ISSUE TITLE
interpolation of gf<imtime> at tau=beta

### ISSUE THREAD

**Issue by JaksaVucicevic** [TRIQS/triqs#303]
If we want to evaluate the disconnected part of a three point correlator in imaginary time by using placeholders, analogous to the case of Eq.5 in http://arxiv.org/pdf/1504.01952.pdf, there is a problem because when G(tau) is interpolated at tau=beta, it returns beta+ instead of beta-.

Also there is still a problem with the place holders, the initialization of `gf<imtime>` still doesn't compile.

``` c++

#include <triqs/test_tools/gfs.hpp>

using namespace triqs::gfs;

TEST(Gf, SimpleAssign) {
 int n_tau = 50; 
 double beta = 10.0;
 auto g = gf<imtime>{{beta, Fermion, n_tau},{1,1}};
 //triqs::clef::placeholder<4> l_;
 //triqs::clef::placeholder<5> m_;
 //triqs::clef::placeholder<6> t_; 
 // g(t_)(l_,m_) << -0.5; // still doesn't compile!
 for(const auto & tau: g.mesh())
   g[tau](0,0) = -0.5;

 auto tau_beta = g.mesh()[n_tau - 1];
 std::cout << "G(beta-) = " <<  g(tau_beta)(0,0) << " but should be -0.5" << std::endl;


 //  compute the disconnected part of < T c_up(t1) c^+_up(0) n_up(t2) > 
 auto g2 = gf<cartesian_product<imtime,imtime>>{{{beta, Fermion, n_tau},{beta, Boson, n_tau}},{1,1}};
 triqs::clef::placeholder<0> i_;
 triqs::clef::placeholder<1> j_;
 triqs::clef::placeholder<2> t1_;
 triqs::clef::placeholder<3> t2_;
 g2(t1_,t2_)(i_,j_) << g(t1_)(0,0)*(g(0)(0,0)+1.0) 
                     - g(t2_)(0,0)*g(t1_-t2_)(0,0);
 std::cout << "chi^3(beta-,0) = " << g2.data()(n_tau-1,0, 0,0) 
                << " but should be -0.5" << std::endl; 
//the actual data is wrong, not the interpolation!!!
 std::cout << "chi^3(tau<beta,0) = " << g2.data()(n_tau-2,0, 0,0) 
               << " as it should be. " << std::endl;
}
MAKE_MAIN;
```

The output is

```
G(beta-) = (0.5,-0) but should be -0.5
chi^3(beta-,0) = (0.5,0) but should be -0.5
chi^3(tau<beta,0) = (-0.5,0) as it should be. 
```

**Comment by parcollet** [comment]
@mferrero : can you fix this ? or close ?

**Comment by Wentzell** [comment]
The evaluation of imaginary time Green functions has been restricted to `[0, beta]`, as there is no consistent way to account for the position of the discontinuities from e.g. `beta-` to `beta+` in Green-function expressions involving time differences.

The user should make sure that for their explicit use-case the boundaries are treated correctly and that anti-periodicity is accounted for, if applicable.
