### ISSUE TITLE
[c++2py] error: conversion from ‘int’ to non-scalar type ‘triqs::arrays::array<double, 1>’ requested

### ISSUE THREAD

**Issue by opeil** [TRIQS/triqs#304]
It is actually not a c++2py error but of the wrap_generator.

[69bd67a9] The wrapped c++ code generates the conversion error.

Original function definition:
`array<double, 2> tetra_DOS3D(array<double, 1> eigk, double e, array<int, 2> itt)`

Fragment of the wrapped function (the error is invoked for assignments like array<double,1> xxx = X):

```
 static PyObject* atm_tetra_DOS3D(PyObject *self, PyObject *args, PyObject *keywds) {
  PyObject * py_result; //final result
  // If no overload, we avoid the err_list and let the error go through (to save some code).
    {// overload tetra_DOS3D(array<double,1> eigk, double e, array<int,2> itt) -> array<double,2>
     // define the variable to be filled by the parsing method
     // wrapped types are converted to a pointer, other converted types to a value or a view
       array<double,1> eigk = 1; //  array<double,1> is a regular type
       double e ; //  double is a regular type
       array<int,2> itt = 2; //  array<int,2> is a regular type
```

If the assignments are removed, this particular error goes away (although there are more errors).

**Comment by parcollet** [comment]
I have not enough informations here.
Can you
- put in a gist a complete test that I can compile myself to solve the issue.
- also with error messages if possible.
cc @mferrero  ...
array<double,1> eigk = 1 is indeed meaningless.
Does the function have default arguments ?

**Comment by opeil** [comment]
Byt the way, if this is a useful information, the problem with crazy default values comes from lines 120 -- 126 in clang_parser.py. If an argument to a function is a template type (such `array<double,2>`) the parser produces a strange sequence of literals, including INTEGER_LITERAL (2), which is then treated as a parameter deafult value by virtue of the conditional within the above lines. To me, this looks wrong.

**Comment by parcollet** [comment]
same as #305
