### ISSUE TITLE
[Wrapper] 2D array as a function argument produces a runtime error

### ISSUE THREAD

**Issue by opeil** [TRIQS/triqs#306]
I am not sure whether it's a bug or a feature.

The following simple test (https://gist.github.com/opeil/3380acb11e112777ad8a) produces a runtime error.

```
>>> testlib.lib_fun(2.0, numpy.eye(3, dtype=int))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot convert to array/matrix/vector : the error was : 
.. Triqs runtime error at /home/opeil/Codes/triqs/triqs1.4/src/triqs/arrays/python/numpy_extractor.cpp : 93

numpy interface : the python object  is not convertible to a numpy. 
.. Error occurred on node 
```

Is it a normal behavior? How should one pass multidimensional arrays to a C-function?

**Comment by krivenko** [comment]
I suspect nobody has performed thorough tests with arrays of integers.
Will this error go if you change the type of `itt` to `array<double,2>`?

**Comment by opeil** [comment]
Just checked: works with `double`. 
Looks like a bug in case of `int`, then.

**Comment by krivenko** [comment]
One more question, could your call your original function as `testlib.lib_fun(2.0, numpy.eye(3, dtype=numpy.int32))`?

**Comment by parcollet** [comment]
try long instead of int , Python uses long, not int.
(sorry I am away until next monday, I will have a look at this next week).

**Comment by opeil** [comment]
In the end, both suggested modifications worked:
1). Using `array<int,2>` with `numpy.int32` (or `numpy.int16`) arrays.
2). Using `array<long,2>` with any kind of numpy integer arrays (I'll stick to this option).

It could be perhaps useful to define type names to be used in wrapped functions/classes, in analogy to NumPy API, where the types are defined as `npy_XXX` and there is a guarantee that they will be converted correctly to respective Python types. This could remove a potential incompatibility at runtime.
