### ISSUE TITLE
TRIQS in Window 10?

### ISSUE THREAD

**Issue by niazalikhan87** [TRIQS/triqs#307]
Can We use TRIQS in windows?

**Comment by parcollet** [comment]
Hello, 
Currently no developer uses windows, so we do not support it.
A priori, it should be possible to port to windows, but there would be a lot of technical details (starting with having a C++14 compiler, generalizing some install scripts, ...) 
and we do not have the resources to work on that.

If you are using windows, the simplest solution is to use a virtual Ubuntu machine, e.g. using virtualbox.
