### ISSUE TITLE
make_unit_matrix's signature can be misleading

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#311]
make_unit_matrix either takes a single int dim as an input (in this case it returns the dimxdim identity matrix), or it takes two values 
```c++
template <typename V> matrix<V> make_unit_matrix(int dim,V const &v) ;
```
in which case it returns v times the dim x dim identity matrix. This is quite misleading, as one may erroneously write
```c++
auto A = make_unit_matrix<double>(2,2);
```
and think this returns a 2x2 identity matrix -- while it in fact returns 2 times the 2x2 identity matrix.
I would remove this overload of make_unit_matrix: the user can instead write
```c++
auto A = 2 * make_unit_matrix<double>(2);
```
What do you think?

**Comment by parcollet** [comment]
I agree, and it seems the second form is only used in legacy C-Python code anyway, so speed is not very important there anyway.

**Comment by tayral** [comment]
Should I then just remove this overload? or at least deprecate it?
