### ISSUE TITLE
Sign in det_manip

### ISSUE THREAD

**Issue by lmessio** [TRIQS/triqs#312]
Hello, 
I have remarked that the sign in det_manip is false after a remove (or insert) operation (depending on the number of he row/col). The det has the same error, thus, they compensate !
But in check_mat_inv, the calculated sign can be different from the old, and it should not. 
Is the separation of the determinant into a "sign" and a "det" useful ?

**Comment by parcollet** [comment]
Please be more specific ... Example, patch ??

**Comment by parcollet** [comment]
@lmessio 
Laura : does this apply ?
Can you provide a test ?
I can not fix without an example.

**Comment by parcollet** [comment]
Not reproducible
