### ISSUE TITLE
make_real_in_tau Crash

### ISSUE THREAD

**Issue by max91219** [TRIQS/triqs#313]
Hi,

I am having problems with the make_real_in_tau function in C++. When I call it with a gf<imfreq> it appears to recursively call itself until it crashes out. However after looking at the code I saw that if you pass it a gf_const_view<imfreq> then it should work, and it does.

I was wondering if there was a problem with the code in triqs/gfs/imfreq.hpp. It appears as if the templates called with the greens function passed by value and by const reference should actually return make_tau_real(make_const_view(g)) not just make_tau_real(g) leading to recursion? or I may be misunderstanding how this piece of code works.

Here is a minimal example of code that reproduces the problem:

`#include <triqs/gfs.hpp>

using namespace triqs::gfs;
using triqs::clef::placeholder;

int main() {
    double beta = 100.0;
    int n_iw = 1025;
    double e = -1.25;

    auto G_iw = gf<imfreq>{{beta, Fermion, n_iw},{1,1}};

    triqs::clef::placeholder<0> om_;
    G_iw(om_) << om_ - e;
    G_iw = inverse(G_iw);

    G_iw = make_real_in_tau(G_iw);

    std::cout << "Done." << std::endl;

    return  0;
}`

However upon wrapping G_iw in make_const_view the code runs fine.

thanks,

Max

**Comment by parcollet** [comment]
Thank you for reporting this.
Fixed.
