### ISSUE TITLE
 could not match 'gf_const_view' against 'gf'

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#314]
Hi,
Is it normal for the following code:
```c++
template<typename D, typename T, typename S>
void myfunction(gf_const_view<D,T,S> g){}

int main(){

   gf<imfreq,matrix_valued,tail> g;
   myfunction(g);

}
```
not to compile?
The error message:
```
error: no matching function for call to 'myfunction'
   myfunction(g);
   ^~~~~~~~~~
 note: candidate template ignored: could not match 'gf_const_view' against 'gf'
void myfunction(gf_const_view<D,T,S> g){}
     ^
1 error generated.
```
I would have expected that the gf_const_view would be constructed automatically from the gf when necessary. Of course the code works if I write 
```c++
myfunction(make_const_view(g))
```
or if I turn myfunction into a template on a general Gf:
```c++
template<typename G> void myfunction(G const & g){}
```
but this is more restrictive than what I want to do.
Thanks

**Comment by parcollet** [comment]
yes, it is .
It is a (bad ?) feature of C++ template.
the call does not match
You have to overload my function.
Unfortunate, but if you find a workaround (except with conceptTS) 
I will be happy to use it.

**Comment by parcollet** [comment]
You mean less restrictive ?

No solution for now. You have to make 3 overloads, for gf, gf_view, gf_const_view.

With conceptsTS, however, we will say simply : 

template<typename G> 
requires(ConvertibleToGfConstView<G>) // something like that ...
void myfunction(G const & g){}

Anyway, this is not an issue. Closing.
