### ISSUE TITLE
Modular arithmetic of time_pt

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#315]
Hey,
Could anyone explain me how addition and subtraction of `time_pt` objects work?
My first guess is that results of all +/- operations are taken modulo \beta. A direct test, however, shows that \tau=\beta can appear as the result in some corner cases.

``` c++
 time_segment seg(10);

 time_pt zero_pt = seg.get_lower_pt();
 time_pt beta_pt = seg.get_upper_pt();
 time_pt pt = seg.make_time_pt(3);

 std::cout << pt + zero_pt << std::endl;
 std::cout << pt + beta_pt << std::endl;
 std::cout << pt - zero_pt << std::endl;
 std::cout << pt - beta_pt << std::endl;

 std::cout << zero_pt + zero_pt << std::endl;
 std::cout << zero_pt + beta_pt << std::endl;
 std::cout << beta_pt + zero_pt << std::endl;
 std::cout << beta_pt + beta_pt << std::endl;

 std::cout << zero_pt - zero_pt << std::endl;
 std::cout << zero_pt - beta_pt << std::endl;
 std::cout << beta_pt - zero_pt << std::endl;
 std::cout << beta_pt - beta_pt << std::endl;
```

I see the following

```
3 [time_pt : beta = 10 n = 5534023222112865280]
3 [time_pt : beta = 10 n = 5534023222112865280]
3 [time_pt : beta = 10 n = 5534023222112865280]
3 [time_pt : beta = 10 n = 5534023222112865280]
0 [time_pt : beta = 10 n = 0]
0 [time_pt : beta = 10 n = 0]
0 [time_pt : beta = 10 n = 0]
10 [time_pt : beta = 10 n = 18446744073709551615]
0 [time_pt : beta = 10 n = 0]
0 [time_pt : beta = 10 n = 0]
10 [time_pt : beta = 10 n = 18446744073709551615]
0 [time_pt : beta = 10 n = 0]
```

Shouldn't 8 last lines be the same (either 0 or \beta)? What's the logic behind the present behavior?

**Comment by parcollet** [comment]
That is for @mferrero 
Anyway, I think this class is too specific to stay in the library 
different projects require different behaviour in these details.

**Comment by krivenko** [comment]
Looking at Michel's commit b37008ef40ea3ddc3eb845635a1b8690b83b56ea...

His intention was to exclude \tau=\beta from the arithmetic; this point must be treated as 0 in all expressions. I would call this a bug ...

**Comment by parcollet** [comment]
No it was intentional, I forgot the reason

**Comment by krivenko** [comment]
No, I mean Michel's idea is correct and mathematically consistent, but the implementation looks buggy to me.

Well, if time_pt is about to be removed, I'd better copy it to my project and fix the issue there.

**Comment by parcollet** [comment]
Let's wait for Michel to answer first,

**Comment by parcollet** [comment]
@mferrero ?

**Comment by parcollet** [comment]
@mferrero : can you fix or close this ?

**Comment by mferrero** [comment]
Should be fixed now!
