### ISSUE TITLE
simple cubic band structure

### ISSUE THREAD

**Issue by kashikarravi** [TRIQS/triqs#317]
I am beginner to TRIQS I was going through examples in  that,   I got band structure and dos of simple cubic containing one atom per unit cell. But I am not able write hopping dictionaries for 2 atoms per unit cell. The Bravais lattice and atomic positions are given below:
BL-3 = BravaisLattice(units = [(1,0,0) , (0,1,0), (0,0,1) ], atomic positions= [ (0,0,0),(1, 0, 0) ] )

Please give information about how to write hopping dictionaries of different Bravais lattices

**Comment by tayral** [comment]
Hi,
Have you checked this page of the documentation:
https://triqs.ipht.cnrs.fr/1.x/reference/lattice_tools/tightbinding_and_example.html
?

Best
Thomas

**Comment by kashikarravi** [comment]
Hi Thomas
Ya I gone through that, and based on that I tried to get cubic band structure of 2atoms per unit cell for first neighbor hopping. Please go through this code. and suggest modifications. 

BL_2 = BravaisLattice(units = [(1,1,0) , (1,-1,0) ], orbital_positions= [ (0,0,0),(1,0,0)] )

# Hopping dictionaries
t = 1.0; tp = 0.0;



hop_2= {  (0,0,0) :[[0,t],
                  [t,0.]],
        (1,0,0)  :  [[ tp, 0],
                   [ t ,tp]],
        (-1,0,0) :  [[ tp, t],
                   [ 0 ,tp]],
        (0,1,0)  :[[ tp, 0],
                 [ t, tp]],
        (0,-1,0) :[[ tp, t],
                 [ 0 ,tp]],
        (0,0,1)  :  [[ 0, 0],
                   [ t,0]],
        (0,0,-1) :[[ 0, t],
                  [ 0,0]],
       }


TB_2 = TightBinding(BL_2, hop_2)


# High-symmetry points
G     =      array([0.        ,0. ,0      ]);
X       =  array([0,math.pi,0]);
M    =       array([math.pi   ,math.pi,0  ]);
G     =      array([0.        ,0. ,0 ]);
R  =         array([math.pi,math.pi, math.pi,]);
X         =  array([0,math.pi,0]);


n_pts=50


path_2=[G,X,M,G,R,X] #equivalent to path_1 in coordinates of 2at/ucell basis


def energies_on_path(path, TB, n_pts, n_orb=1):
    E=zeros((n_orb,n_pts*(len(path)-1)))
    for i in range(len(path)-1,0,-1):
        energies = energies_on_bz_path (TB, path[i-1], path[i], n_pts)
        for orb in range(n_orb):     E[orb,(i-1)*n_pts:(i)*n_pts]=energies[orb,:]
        print "index of point #"+str(i-1)+" = "+str((i-1)*n_pts)

    return E

E_2= energies_on_path(path_2,TB_2,n_pts,2)


from matplotlib import pylab as plt

plt.plot(E_2[0],'-.g', linewidth=4, label = "2 ats/unit cell")
plt.plot(E_2[1],'-.g', linewidth=4)

plt.grid()
plt.legend()
plt.axes().set_xticks([0,50,100,150,200,250])
plt.axes().set_xticklabels([r'$\Gamma_1$',r'$M_1$',r'$X_1$',r'$\Gamma_1$'])
plt.ylabel(r"$\epsilon$")
plt.show ()

**Comment by tayral** [comment]
Hi,
What is your specific question? With no further information, we cannot help you.
Best,
Thomas

**Comment by kashikarravi** [comment]
I wanted hopping dictionaries for simple cubic, bcc and fcc

**Comment by tayral** [comment]
Hi,
You can easily set up these dictionaries yourself, using the definitions given in https://triqs.ipht.cnrs.fr/1.x/tour/tight_binding.html. In
particular:
```
# Define the Bravais Lattice : a square lattice in 2d
BL = BravaisLattice(units = [(1,0,0) , (0,1,0) ]) 
```
Here, adapt this line by giving the cartesian coordinates of the unit vectors of the Bravais lattice you are considering

```
# Hopping[ Displacement on the lattice] = [[t11,t12,t13....],[t21,t22,t23....],...,[....,tnn]]
# where n=Number_Orbitals 
```
In your case the number of "orbitals" in the number of atoms per unit cell.
