### ISSUE TITLE
 -DPythonSupport=OFF in triqs-1.3 still looking for Python.h

### ISSUE THREAD

**Issue by Soumeniisc** [TRIQS/triqs#318]
Dear Triqs Experts,
I am using AMD cluster,Cent OS, gcc-4.8.2. I want to install  triqs-1.3
 I am getting following error during make.

[  9%] Building CXX object triqs/CMakeFiles/triqs.dir/gfs/local/pade.cpp.o
In file included from /home/soumen/Software/triqs-1.3/triqs/arrays/python/numpy_extractor.cpp:25:0:
/home/soumen/Software/triqs-1.3/triqs/arrays/python/../../python_tools/pyref.hpp:2:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/python/numpy_extractor.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
make: *** [all] Error 2
 output of cmake::
https://gist.github.com/Soumeniisc/199edf4080d534270f586d2195cecb0f
<script src="https://gist.github.com/Soumeniisc/199edf4080d534270f586d2195cecb0f.js"></script>
[CMakeCache.txt](https://github.com/TRIQS/triqs/files/226377/CMakeCache.txt)

------------------
is it possible to install triqs with out Python.?

**Comment by parcollet** [comment]
Hi,

Yes, the library part was designed to work in C++ only.
I have to admit that we do not use it that way often. We should add this to the Jenkins tests.
It is most likely a simple error in the pade which was incorporated recently.

Assigned to me.

**Comment by Soumeniisc** [comment]
Dear Sir,

Thanks.. Is there any solution to this?? does other older version could solve my problem. I was looking for such specific mode because in my cluster i am getting g lot of make error while installing the Python.

**Comment by parcollet** [comment]
Ok, the PythonSupport was broken.
Be aware that even though many people and collaborators uses TRIQS, 
this C++ only mode is, to my knowledge, used by nobody, so
other details might pop up compiling applications.
Having a machine without python is rare, even though the c++ part of TRIQS can 
live with it.
People usually make a pure C++ app., but still compiles with python, along with C++/Python apps...

**Comment by parcollet** [comment]
fixed in master
