### ISSUE TITLE
[c++gfs] initialize lattice GF using tight-binding

### ISSUE THREAD

**Issue by dombrno** [TRIQS/triqs#320]
Dear TRIQS team,

I am in the process of trying to upgrade the self-consistency condition implementation of our production DMFT code with the TRIQS library. For this purpose, I need to manipulate the lattice Green's function, and would like, to initialize it with some tight-binding dispersion. I have installed TRIQS, and have compiled a minimal working example which links to TRIQS, but I am not yet familiar enough with the TRIQS-defined containers and lazy expressions, and cannot figure out how to do what I need. Attached is the example, adapted from the tutorials, together with the CMakeLists.txt. The question should be clear from the code comments, but in a nutshell, I would like to use the output  of the Fourier transform of the tight_binding instance, instead of the  lazy expression provided in the tutorial.

Thanks a lot for your help.

[CMakeLists.txt](https://github.com/TRIQS/triqs/files/244877/CMakeLists.txt)

[gf_tb.txt](https://github.com/TRIQS/triqs/files/244881/gf_tb.txt)

**Comment by tayral** [comment]
Hi,
Doesn't
```c++
test_gk(k_, iw_) << 1 / (iw_ - TK(k_))) - 1 / (iw_ + 2));
```
work?

**Comment by dombrno** [comment]
Indeed - Compilation is successful. I will check that I obtain the expected result. Thank you for such a quick answer.

Dominique
