### ISSUE TITLE
new run function in mc_generic

### ISSUE THREAD

**Issue by JaksaVucicevic** [TRIQS/triqs#325]
The new "run" function in mc_generic.hpp does one cycle even if n_cycles is 0.

proposed solution:

```c++
  int run(uint64_t n_cycles, uint64_t length_cycle, std::function<bool()> stop_callback, bool do_measure = true) {
   if (n_cycles==0) return 0;
   Timer.start();
   triqs::signal_handler::start();
   ....
```

**Comment by tayral** [comment]
@parcollet : anything against this solution? Otherwise, I will fix this in the coming hours.

**Comment by parcollet** [comment]
I have not have time to review it, maybe @mferrero ?

**Comment by tayral** [comment]
I checked that it makes the tests in cthyb_spin pass as they did before this change. The tests of cthyb also pass. Anyway, this is pretty simple: if n_cycles is 0, the run() function should not do anything and return 0 (i.e. it has ran till then end). So to me this seems to be the right fix. Or is there sthg I overlooked?

**Comment by mferrero** [comment]
Looks fine to me
