### ISSUE TITLE
bcast

### ISSUE THREAD

**Issue by MHarland** [TRIQS/triqs#329]
bcast() seems to work only for Greensfunctionobjects. Running e.g.

```
from pytriqs.operators import c
from pytriqs.utility import mpi

op = c('a',0)
op = mpi.bcast(op)
print op
```

gives

```
Severe internal error : _c is null in py2c for type many_body_operator !
.. Error occurred on node 0
```

This is also the case for AtomDiag. For now, it is not too important for me personally and I can work-around it, but it seems to be unintended.

**Comment by parcollet** [comment]
Thanks. It is a bug indeed.

**Comment by krivenko** [comment]
This is not a proper resolution of the issue, I am afraid.

The operators were just an example, there are other wrapped types causing a similar crash. I can name at least three more, `pytriqs.lattice.lattice_tools.TightBinding`, `pytriqs.statistics.histograms.Histogram` and `AtomDiag` from cthyb.

The actual problem is not about some objects being unserializable (I personally see no point in serializing `AtomDiag`, really). It is about the Python interpreter getting killed with a cryptic error message.

Could we throw a meaningful exception from MPI routines if transferred type does not support serialization?

**Comment by parcollet** [comment]
1-
Anyway, it works for Operators, and its "repr " now acts properly, i.e. 
you can reconstruct the operator from the string, which is the most part of the referenced commit.

2-
In the previous commit 3e4de2dc9dc4c872b7f000c9e71efaa3c99c1d83, I have 
also added a default case, which is exactly your question : if no serialization is available, __reduce__ will now raise NotImplemented. I tested it on Operator when removing the serialization, it worked with mpi.bcast.
 
In addition, I added the "Repr" case, which is more generally any case where we
have a serialisation to string (the old "via_string" was broken).

3- 
We should be able to serialize Histograms, I agree there is no point for AtomDiag...

**Comment by parcollet** [comment]
Leave it open : todo : fix via_string, which uses h5 but did not seem to work properly 
for Operators.

**Comment by parcollet** [comment]
e.g.
>>> TB = TightBinding ( BL, hop)
>>> 
>>> mpi.bcast(TB)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/parcolle/triqs/BUILD/triqs/pytriqs/utility/mpi_mpi4py.py", line 41, in bcast
    return world.bcast(x, root=0)
  File "MPI/Comm.pyx", line 1276, in mpi4py.MPI.Comm.bcast (src/mpi4py.MPI.c:108819)
  File "MPI/msgpickle.pxi", line 612, in mpi4py.MPI.PyMPI_bcast (src/mpi4py.MPI.c:47005)
  File "MPI/msgpickle.pxi", line 112, in mpi4py.MPI.Pickle.dump (src/mpi4py.MPI.c:40704)
NotImplementedError: __reduce__ not implemented

**Comment by parcollet** [comment]
Done in 60d03ccb44eb2a13b6cb71fbf6f15494f1b1896e and 59716640a683b0e9262afb978af91202789cfe5e

**Comment by parcollet** [comment]
Fixed for me. Reopen if needed.

**Comment by krivenko** [comment]
>  In the previous commit 3e4de2d, I have
also added a default case, which is exactly your question : if no serialization is available, 'reduce' will now raise NotImplemented. I tested it on Operator when removing the serialization, it worked with mpi.bcast.

Perfect! Now I have nothing to object to.

**Comment by parcollet** [comment]
PS : I also fixed the "h5" (ex via_string).
It now works properly, as soon as the object is h5 read/writable, it can be serialised
(with hdf5 >1.8.9).
