### ISSUE TITLE
silent modification of data in h5_write of gf<imfreq>: should we keep it?

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#331]
Hi,
When we implemented the complex g(tau), we added a line

``` c++
if (is_gf_real_in_tau(g, 1.e-13)) return positive_freq_view(g);
```

before dumping a gf<imfreq> into an HDFArchive. Thus, any deviation to 'reality' smaller than 1e-13 is discarded without the user knowing it. 
While this is fine for most cases, this may cause trouble because it is a **silent violation of the (natural) expectation that dumping to H5 does not modify the data AT ALL**. 
E.g: I have recently encountered a case where I did not understand why, when I was computing DMFT observables at step n+1 starting from data of step n taken from an archive, it was not the same as going from step n to n+1 without dumping to H5. It took me a while to understand why this happened... 
IMO, it would be better if no implicit modification of data happens upon dumping to H5 (and the user can use positive_freq_view() if needed; at least the user knows what he/she does).
What do you think?

**Comment by tayral** [comment]
PS: all TRIQS tests pass after commenting out this line.

**Comment by tayral** [comment]
Note: still a problem in 'unstable'.

**Comment by parcollet** [comment]
That line is commented in unstable.

**Comment by parcollet** [comment]
How can it still be an issue, it was commented a while ago ?

**Comment by parcollet** [comment]
Should be fixed. Reopen if necessary.
