### ISSUE TITLE
Managing multiple installations

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#333]
A suggestion from Marc Hoeppner:

Change the executable files (pytriqs, ipytriqs and ipytriqs_notebook) to set LD_LIBRARY_PATH according to the given TRIQS_PATH. In this way, you can install many different versions in parallel without keeping track of your environment variable (you choose the version by the executable). Then one can easily define, for example:

alias pytriqs_1.4 /home/software/triqs/1.4/bin/pytriqs

**Comment by krivenko** [comment]
Now that I have to use two TRIQS installations (master/unstable) I'd like to raise this issue again.
Any solid objections against setting `LD_LIBRARY_PATH` in the bash scripts?

**Comment by Titan-C** [comment]
How will this be done?

I'm working on a cluster which has very old software and I had to
bootstrap an entire system in userspace. I thus keep virtual
environments(controlled by conda or python virtual env) which hold
updated software of binaries an libraries.

I much rather keep my `LD_LIBRARY_PATH` inside my `activate` script of
the virtual environment than having TRIQS override it from install time
configuration. Loading a virtual environment for different versions
feels more appropriate than to set an alias for an executable that will
set its specific library paths.

**Comment by krivenko** [comment]
> How will this be done?

Now in `$TRIQS_PATH/bin/pytriqs` and similar scripts we have
```bash
#!/bin/sh
export PYTHONPATH=/path/to/triqs/installation/dir/lib64/python2.7/site-packages:$PYTHONPATH

/usr/bin/python $@
```
The idea is to change this to
```bash
#!/bin/sh
export LD_LIBRARY_PATH=/path/to/triqs/installation/dir/lib64:$LD_LIBRARY_PATH
export PYTHONPATH=/path/to/triqs/installation/dir/lib64/python2.7/site-packages:$PYTHONPATH

/usr/bin/python $@
```
As you can see `LD_LIBRARY_PATH` will be affected only inside those scripts. Would this solution interfere with your setup?

**Comment by Titan-C** [comment]
It's fine with me.

**Comment by parcollet** [comment]
@Wentzell, @mferrero  : your opinion on this ?

**Comment by parcollet** [comment]
path was not supposed to remove the need of changing LD_LIBRARY_PATH ??

**Comment by Wentzell** [comment]
Why is it even necessary to set the LD_LIBRARY_PATH when using the python modules?

The corresponding *.so for the modules are anyways linked against a specific triqs installation, 
so the proper libtriqs.so should be automatically loaded, right?

**Comment by krivenko** [comment]
> rpath was not supposed to remove the need of changing LD_LIBRARY_PATH ??

It was. And as I can see now `LD_LIBRARY_PATH` is not necessary.
The results must have been affected by my own environment when I did testing a couple of months ago.
