### ISSUE TITLE
CPU and wall time in MC

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#334]
Request from Marc Hoeppner:

Output CPU time as well as the WALL time for the measurements and the warm ups separetely in the MC. This would help to find over-subscription and analyze the scaling easier without relying on the time command (and having overhead by e.g. chemical potential search, WarmUp Time, ...)

**Comment by parcollet** [comment]
Agreed. On the todo list.
Impl: put 2 timers in mc_generic.

**Comment by parcollet** [comment]
Fixed by recent pull request by Hugo.
