### ISSUE TITLE
MPI: Errors on master node does not lead to termination of slave processes

### ISSUE THREAD

**Issue by pseth** [TRIQS/triqs#335]
When performing a task (read / save data) just on the master process (i.e. rank 0), and the process experiences an error, the master process is killed without killing the slave processes.

```
import pytriqs.utility.mpi as mpi
import sys

if mpi.is_master_node(): sys.exit("(EE) master node exited")
mpi.barrier()
```

Can the TRIQS MPI interface be modified such that errors on the master node are propagated to the slave nodes as well?

**Comment by parcollet** [comment]
This is an  mpi4py issue, we can not change it
@Wentzell : do you confirm ?
