### ISSUE TITLE
[det_manip] Construction of det_manip on a singular matrix fails

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#336]
The following function unexpectedly fails:
```c++
#include <triqs/arrays/array.hpp>
#include <triqs/det_manip/det_manip.hpp>

int test_det_manip() {

 auto f = [](double x, double y) { return 1.0; };
 triqs::arrays::vector<double> x = {1,2};
 triqs::arrays::vector<double> y = {3,4};
    
 triqs::det_manip::det_manip<decltype(f)> dm(f, x, y);    
}
```
```
RuntimeError: .. Error occurred at Thu Jun  9 11:39:54 2016

.. Error .. calling C++ overload 
.. test_det_manip() -> int 
.. in implementation of function ext.test_det_manip
.. C++ error was : 
Inverse/Det error : matrix is not invertible
.. Error occurred on node
```
The point is that I am not asking to invert that singular matrix. I only want to know its determinant, and then decide whether it's safe to ask for the inverse. But `det_manip`'s constructor gives me no chance.

**Comment by parcollet** [comment]
The point of the class was to maintain the inverse M at all times.
So this behaviour is normal in this view.

**Comment by krivenko** [comment]
Fair enough.
Ok, I'll have to rethink my algorithm to detect the singular matrices beforehand.
