### ISSUE TITLE
[Installation] Error linking statically with 'readline' and 'ncurses'

### ISSUE THREAD

**Issue by opeil** [TRIQS/triqs#340]
On some systems the default static versions (from /usr/lib64) of readline and ncurses libraries are not correctly installed but there are "good" versions elsewhere. This causes linking errors.

In details, CMake finds the correct versions of the libraries but then falls back to "search library by name" (resulting in the linking errors) because of some stupid compatibility policy. The problem can be cured by adding the following line in CMakeLists.txt:
`cmake_policy(SET CMP0060 NEW)`

This is a very annoying issue and it took quite some time to figure out what was the problem. If this does not cause side-effects I would suggest to add it to all root CMakeLists.txt by default.

Another solution would be to force dynamic linking of readline and ncurses.

**Comment by parcollet** [comment]
These libraries are quite basic in unix systems, 
so the machine is quite seriously broken, I would say.

Short answer is : I do not know how this will affect the rest of the linking, or other platforms (OS X ?)
we have to look at it carefully.
Besides, I see that CMP0060 has been introduced in cmake 3.3, i.e. is recent.
Which version of cmake do you use ?

@mferrero : ?

**Comment by opeil** [comment]
Nevertheless, this is how one of the largest Swiss supercomputer works...

I used cmake3.3.2. I cannot check earlier versions because they are not
installed.

The dynamical counterparts of the libraries are fine. The stance of the
admins is that one should use them instead of static ones (which are
compiled without -fPIC). The only problem is that it is very difficult to
convince CMake to link implicit targets dynamically if it decided to do
this statically.



On Tue, Jun 28, 2016 at 8:47 PM, Olivier Parcollet <notifications@github.com
> wrote:

> These libraries are quite basic in unix systems,
> so the machine is quite seriously broken, I would say.
>
> Short answer is : I do not know how this will affect the rest of the
> linking, or other platforms (OS X ?)
> we have to look at it carefully.
> Besides, I see that CMP0060 has been introduced in cmake 3.3, i.e. is
> recent.
> Which version of cmake do you use ?
>
> @mferrero <https://github.com/mferrero> : ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TRIQS/triqs/issues/340#issuecomment-229144968>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ADT6fnuUpitp9gTEATx4QzdmAKFFi7WZks5qQWxAgaJpZM4I_8GH>
> .
>



-- 

 Dr. Oleg E. Peil
 Department of Quantum Matter Physics
 Universite de Geneve
 CH-1211 Geneve 4
 Switzerland                Tel :+41 (0)22 379 3571

**Comment by parcollet** [comment]
Is this still open ?

**Comment by opeil** [comment]
This could have beeen a configuration problem of this particular system. Let's close it.
