### ISSUE TITLE
block_gf: design problem?

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#342]
Hi,
Consider the following code snippet:

``` c++
  auto Ga = gf<imfreq>({1, Fermion}, {1, 1});
  auto Gb = gf<imfreq>({1, Fermion}, {1, 1});
  triqs::clef::placeholder<0> w_; 
  Ga(w_) << 1 / (w_ + 2); 
  Gb(w_) << 1 / (w_ - 2); 

  auto B_ab = make_block_gf<imfreq>({"a", "b"}, {Ga, Gb});
  auto B_ba = make_block_gf<imfreq>({"b", "a"}, {Gb, Ga});

  auto B_res = B_ab;
  for(auto const & ind : B_res.mesh())    B_res[ind] = B_ba(ind);
```

What should one expect this code to do?
It seems to me that the last line should mean that there is a block-by-block equality between B_res and B_ba, namely (in a python syntax) B_res["a"] = B_ba["a"] = Ga and similarly for "b".
Yet, this is not what happens, because what the last line really does is interpret "ind" as an integer indexing the blocks, so that one ends up with B_res["a"] = B_ba["b"] = Gb... which I find quite surprising... and error-prone.
What do you think?

**Comment by parcollet** [comment]
@mferrero : requires a discussion

**Comment by krivenko** [comment]
Each of these two lines
```c++
auto B_ab = make_block_gf<imfreq>({"a", "b"}, {Ga, Gb});
auto B_ba = make_block_gf<imfreq>({"b", "a"}, {Gb, Ga});
```
assigns different integer indices to `"a"` and `"b"`. What if we make the constructor assign those indices according to the lexicographical order of strings in `{"b", "a"}`?
`B_ab` and `B_ba` will be completely equivalent objects, just as they should.

**Comment by tayral** [comment]
Note: also raised in #349. A quite important issue!

**Comment by krivenko** [comment]
This annoying issue still exists in `unstable`...

**Comment by krivenko** [comment]
Let me ask again: why not sort block names in the constructor?
It is frustrating that `assert_block_gfs_are_close()` remains unusable due to this issue...

**Comment by parcollet** [comment]
Indeed, we were precisely discussing this with @Wentzell 
@mferrero : opinion ?

**Comment by Wentzell** [comment]
Indeed!
When creating the block gf we should sort lexicographically w.r.t the block_name
(and then the block2_name for block2_gf).

**Comment by mferrero** [comment]
I think it is not a good idea to order the blocks with block_name. One will define block_names=['up','down'] and then iterating over them you get 'down' first... It is not very natural. Sometimes you choose the order of the blocks with some physical reason in mind and a lexicographical might destroy the logic.

**Comment by krivenko** [comment]
> One will define block_names=['up','down'] and then iterating over them you get 'down' first... It is not very natural. Sometimes you choose the order of the blocks with some physical reason in mind and a lexicographical might destroy the logic.

So basically you are saying that `block_gf` must be understood as a list of `(name,block)` pairs, rather than an associative array `name -> block`. In this case `make_block_gf<imfreq>({"a", "b"}, {Ga, Gb})` and `make_block_gf<imfreq>({"b", "a"}, {Gb, Ga})` are indeed two different objects by definition, and what we are discussing here is a non-issue.

**Comment by parcollet** [comment]
That was the point in Python until now, exactly.
Gf is a block matrix, hence the order of the block matters.
Changing it would probably break codes.

Thomas' code was surprising, but in unstable .mesh has disappeared for block_gf
either you iterate on block name or on indices.

Now it may not be a good idea in an app to have both G.

What is the pb with assert_block_gfs_are_close ?

**Comment by krivenko** [comment]
> What is the pb with assert_block_gfs_are_close ?

https://github.com/TRIQS/triqs/issues/349

`assert_block_gfs_are_close` fails if its two arguments are equal up to the order of block names.
Now we come to a conclusion this behavior is actually expected.

**Comment by parcollet** [comment]
Yes, we should insist on this in the doc.

**Comment by krivenko** [comment]
Now I am a bit worried about the way we define `gf_struct` in `cthyb` (and other solvers?).
It is an `std::map` in C++, so there is no real control over how block names are ordered. They always come in the lexicographical order.

**Comment by Wentzell** [comment]
> Now I am a bit worried about the way we define gf_struct in cthyb (and other solvers?).
> It is an std::map in C++, so there is no real control over how block names are ordered. They always come in the lexicographical order.

Yeah that was exactly my train of thought. 
To be consistent one would have to change ```gf_struct``` to 

```c++
std::vector<std::pair<std::string, std::vector<std::variant_int_string>>
```

I can see the arguments for both solutions. Iterating and figuring out the position of a given block (in particular in the multi-band case) will be clearer with the latter solution.

Physically the first one makes more sense.

**Comment by parcollet** [comment]
Ok, now it seems to be a question for the solvers, not the triqs lib.
Closing.
