### ISSUE TITLE
Make test fails : Mac OS

### ISSUE THREAD

**Issue by VarshaRath** [TRIQS/triqs#343]
I am facing the following error,

The following tests FAILED:
	 76 - det_manip_all_operations (Failed)
	127 - hilbert_test (Failed)
Errors while running CTest
make: *** [test] Error 8

I am not sure what is to be fixed.

**Comment by parcollet** [comment]
pull the master. The first one was a mistake in a commit I think.
The second is a known trivial issue on OS X, you can safely ignore it.
I leave this as open to fix the hilbert_test
(the issue is the printing of an operator, the test is too strict).

**Comment by VarshaRath** [comment]
I am not sure what you mean by master file and what are the errors in the commenting?
It would be of help if you can elaborate a bit about how it can be fixed.
Thanks,

**Comment by parcollet** [comment]
git pull

pull the master branch.
and ignore the failure of hilbert_test.

**Comment by VarshaRath** [comment]
Thanks. It worked 👍
