### ISSUE TITLE
Discussion about RNGs

### ISSUE THREAD

**Issue by supermarche** [TRIQS/triqs#344]
Hi,

Daniil and me just ran into an error choosing the seed value for the standard RNG (Mersenne Twister, the one shipped with mc_tools). It would be nice to get some information on how to choose the seed value (apparently 32bit integer) in case of a large number of MC runs (same initial condition, just a different sequence of random numbers).

We noted that the seed values have to be odd (or differ by at least 2), see the comment in _triqs/mc_tools/MersenneRNG.hpp_. But still we are left with the question how to choose an optimal seed with a random 32bit pattern for a larger number of mpi ranks  (obviously a construction principle like A + B*mpi.rank does not necessarily produce a random bit pattern). At the moment, the only solution we can think of is using /dev/random and draw the seed values from there checking that we do not have duplicates (and draw more samples in that case). Is there a better solution? Do we have to check that the period of the sequence of random numbers is long enough for the given seed values (and if yes, how should we do it)?

All the best,
Marc

**Comment by Wentzell** [comment]
There is no need to draw the seeds randomly, you can use a deterministic way to calculate the seed from the rank, as we do e.g. in our TRIQS/cthyb CTQMC Impurity Solver, c.f. [triqs_cthyb/parameters.hpp:99](https://github.com/TRIQS/cthyb/blob/b43c2f1b99c78d53cc614ac848a38a00f0f45254/c%2B%2B/triqs_cthyb/parameters.hpp#L99)
```c++
    /// Seed for random number generator
    /// default: 34788 + 928374 * MPI.rank
    long random_seed = 34788 + 928374 * mpi::communicator().rank();
```

As you point out correctly seeds should differ by at least 2 when using the [triqs/mc_tools/MersenneRNG.hpp](https://github.com/TRIQS/triqs/blob/3.1.x/c%2B%2B/triqs/mc_tools/MersenneRNG.hpp) implementation.
