### ISSUE TITLE
triqs oplot

### ISSUE THREAD

**Issue by Sudiptakoley** [TRIQS/triqs#347]
I have installed triqs. Everything is running nice with the pytriqs command (did not find out ipytriqs).
but the plotting with oplot which is also running without any error
but not showing any thing in the screen.
then I got one help from this site
https://github.com/TRIQS/triqs/issues/38

but also the plot is not shown. Please help.

**Comment by tayral** [comment]
Hi,
Have you tried using the ipython notebook (now jupyter)? For that you should install ipython (you probably do not have it since you do not find ipytriqs).
In any case, please supply an example script.
Thanks.

**Comment by Sudiptakoley** [comment]
Thank You for your reply. But I have Ipython and ipython notebook both installed. 
Still I am not getting the plot.

Please see the script following:

from pytriqs.gf.local import *
from pytriqs.archive import *
from pytriqs.plot.mpl_interface import oplot
with HDFArchive('aim_solution.h5','r') as ar:
    oplot(ar['G_iw']['up'], '-o', x_window = (0,10))

**Comment by tayral** [comment]
In the jupyter/ipython notebook, you should add either of the following magics:
```python
%matplotlib notebook
%matplotlib inline
```
Does it solve your problem?

**Comment by Sudiptakoley** [comment]
it is solved with matplotlib.pyplot.
thank you.
