### ISSUE TITLE
Green's functions from pytriqs.gf.local are not local anymore

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#348]
Hello,

Many new GF Python wrappers have been added to the library recently. Among them, wrappers for the correlator functions defined on a `BrillouinZone` mesh.
Does it still make sense to call the module `local`? How about moving everything into `pytriqs.gf` with a deprecation warning on import attempts from `pytriqs.gf.local`?

**Comment by tayral** [comment]
Hi Igor,
Indeed, some renaming should be done... we are working on this.

Best
Thomas

**Comment by parcollet** [comment]
Fixed in unstable (1.5)
