### ISSUE TITLE
[doc] scalar_valued functions in python... add reinterpret_scalar_valued_gf_as_matrix_valued

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#35]
When h5-saving from c++ a gf<...,scalar_valued>, one should convert it to a matrix_valued gf... otherwise pytriqs cannot read it.
```
h5_write(file,"Pw_from_convol",reinterpret_scalar_valued_gf_as_matrix_valued(Pw_from_convol));
```

Thomas

**Comment by parcollet** [comment]
@mferrero, @tayral : what do we decide here ?

**Comment by tayral** [comment]
why not have a h5_write/read for scalar_valued? (or has it been implemented meanwhile?)

**Comment by parcollet** [comment]
I thought it was there (simply reinterpreting as 1x1 matrix).
We said that we do not want yet another h5 format...
Right ?

**Comment by tayral** [comment]
ok, it has indeed been solved meanwhile (cf test gf_scalar.cpp)
