### ISSUE TITLE
[shells] Interpreter for shell scripts

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#352]
Hey,
Are we actually using any bash-specific extensions in our shell scripts?
`zsh` is gaining popularity, so I think we should consider changing `#!/bin/bash` shebangs to `#!/bin/sh` to make users of alternative shells happier.

**Comment by parcollet** [comment]
Hi Igor, 
I don't know. I do not use zsh ...
We have very few shells (pytriqs, ipytriqs, ...), which are anyway almost trivial.
In the cmake, we use some "export" from time to time ...

**Comment by krivenko** [comment]
`export` is a keyword of the Shell Command Language described by the POSIX standard (http://pubs.opengroup.org/onlinepubs/009695399/utilities/export.html). Hence, it must be supported by `sh` interpreter, which is installed on pretty much any UNIX system.
In my first message I referred to a situation when `/bin/bash` is not available.
