### ISSUE TITLE
Method to switch temperature

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/triqs#354]
Dear All,

Suppose you have performed a calculation in certain "beta" and you want to use these converged results (GF, self-energies e.t.c.) as a starting point for a calculation at higher or lower temperature. 
 
Manually, this is possible by interpolating in order to adjust the two different matsubara axes and then by fixing the tail of the GF object, but frequently it produces huge problems especially when the resulting GF is the input on the CT-HYB solver.

Is there a routine for such a purpose?

All the best, 
Danny

**Comment by tayral** [comment]
Hi Danny,
What kind of problems does it produce? The procedure you describe looks reasonable (provided the adjustment of the tails is done properly).
Best
Thomas

**Comment by dmantadakis** [comment]
Dear Thomas,

After the interpolation and the adjustment of the tail (here is the problem) if you perform a FT and go to the tau space, you may see "kinks". In general this is true: In all tails that I have tried, I had a not so nice curve in the Gtau. Now, if this "anomaly" is not so severe the solver will not produce any problem, since iteration after iteration the form will be fixed. Otherwise, it will throw a huge sign-problem. I am pretty sure that it is the tail that creates the problem, but I cannot find a way to get this out.

Best,
Danny

**Comment by aichhorn** [comment]
Hi Danny and Thomas,
There should be no tail fitting involved at all. The only thing one should do is to adjust the number of Matsubara frequencies such that the tail starts at the same iomega. Then, the curves and in particular the tail for the two different beta should lie on top of each other. Remember that the tail is an analytic property of the green function. If the data is the same (and it is the same), then the tail does not change.

**Comment by tayral** [comment]
I agree. Danny, have you solved your problem?

**Comment by dmantadakis** [comment]
Dear Thomas and Markus,

The status is the same as before... Only one more detail: The interpolation should be performed only if you have an insulating GF. In case of, a metallic one I think that we have to extrapolate independently the positive and the negative Matsubara axis. That's because most probably we want to keep the overall behaviour of the GF (insulating or not). 

As for the comment of Markus: I cannot understand when you say that we shouldn't "touch" the tail. By changing the Matsubara mesh what we actually do is to "stretch" the function. Shouldn't the tail also be "stretched"? And when you say  "_The only thing one should do is to adjust the number of Matsubara frequencies such that the tail starts at the same iomega_" you mean that they should start from the same index or value in the axis??

I will try as soon as possible your suggestions and I will keep you informed. Thanks for your comments and help! 

Best,
Danny

**Comment by aichhorn** [comment]
Hi Daniil,

You don't stretch the function, you add just more omega points to it! The easiest way to see it is to do two calculations independently at, say, beta=40 and =80. The results are lying on top of each other, just that for beta=80 you have twice as many omega points available. So again, no stretching! That is why you want to 'interpolate' the functions from one temperature to the next. 
Since the tail has nothing to do with the number of Matsubaras, but is an analytic function of them, the interpolation must not change the tail.
And when I say the tail should start at the same frequency, I mean really the frequency, and not the index. What changes the tail is the point where you start fitting it, so if you keep this point the same, then the tail is unchanged.

**Comment by dmantadakis** [comment]
Dear Markus.

Thank you very much for your comment!! I see know what you mean... 

Best,
Danny

**Comment by tayral** [comment]
Hi Danny,
Can we close the issue?
Thomas

**Comment by dmantadakis** [comment]
Yes sure! Sorry for the late response and thanks for the advices!

Best,
Danny

2016-10-09 3:49 GMT+02:00 Thomas Ayral <notifications@github.com>:
