### ISSUE TITLE
Installation error - Could not find HDF5 

### ISSUE THREAD

**Issue by georgeyumnam** [TRIQS/triqs#357]
I am getting this error with TRIQS installation.

> -- Lapack libraries : /usr/lib/liblapack.so;/usr/lib/libblas.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/libblas.so
> -- -------- HDF5 detection -------------
> CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
> Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS)
> Call Stack (most recent call first):
> /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
>  /usr/share/cmake-3.5/Modules/FindHDF5.cmake:398 (find_package_handle_standard_args)
  CMakeLists.txt:289 (find_package)
>
>
> -- Configuring incomplete, errors occurred!
> See also "/home/thsim3/code/TRIQS/triqs.build/CMakeFiles/CMakeOutput.log".
> See also "/home/thsim3/code/TRIQS/triqs.build/CMakeFiles/CMakeError.log".

I have installed HDF5 (version 1.8.17), and defined the following in my .bashrc file:

 > HDF5_LIBRARIES=/home/thsim3/code/HDF5/CMake-hdf5-1.8.17/build/tools/lib
 > HDF5_INCLUDE_DIRS=/home/thsim3/code/HDF5/CMake-hdf5-1.8.17/build

However, this error persist. Have I done something wrong?

**Comment by krivenko** [comment]
Hi George,

`HDF5_LIBRARIES` and `HDF5_INCLUDE_DIRS` are not environment variables, they are CMake variables to be passed as command line arguments, i.e. `cmake -DHDF5_LIBRARIES=... -DHDF5_INCLUDE_DIRS=...`.

However, you should first try to define *environment variable* `HDF5_ROOT=/path/to/hdf5/installation/dir` and run cmake.

**Comment by georgeyumnam** [comment]
Hi @krivenko 

Thanks for this reply. It seems to have solved the problem.

**Comment by hungtranvn** [comment]
Hi all,

I got the same problem, and I had set the HDF5_ROOT but it still gets this error:
Can you help me?
`
-- -------- HDF5 detection -------------
-- Unable to determine HDF5 C flags from HDF5 wrapper.
-- Unable to determine HDF5 C version from HDF5 wrapper.
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS
  HDF5_HL_LIBRARIES C HL) (found version "")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindHDF5.cmake:928 (find_package_handle_standard_args)
  triqs/CMakeLists.txt:161 (find_package)
`

**Comment by Wentzell** [comment]
Dear @hungtranvn,

Please provide information on your operating system and the triqs version that you are trying to install.
Also, how was hdf5 installed on your computer and which version of cmake are you using?

**Comment by hungtranvn** [comment]
Hi @Wentzell 
Thanks for your reply. 
I am trying to install TRIQS 2.2 on my personal computer with fedora 30. 
Actually, I was trying to install hdf5 package by command: dnf install hdf5, however, the version is 1.8.20. I recieved an error: 
`CMake Error at triqs/CMakeLists.txt:165 (message):
  The HDF5 version of the h5py (1.8.18) is different from the hdf5 library
  found for C++ (1.8.20).  You MUST have the same version.`
and then, I was trying to find h5py version that matches hdf5 1.8.20 version, however, I did not find any suitable h5py version with hdf5.
After that, I decided removing hdf51.8.20 package by `dnf command ` and installed hdf5 1.8.18 version from source code in flowing directory: `/share/apps/hdf5.`
Finally, I got problem that I mentioned before.
Other information: cmake version 3.14.5

**Comment by the-hampel** [comment]
Hi @hungtranvn,

I had similar problems, and I ended up using HDF5 version 1.10.2 together with h5py 2.8.0, which works quite well for triqs 2.2.x . You can check here: https://github.com/the-hampel/Dockerfiles/blob/master/Dockerfile (line 73 ff.) how I installed both together. First hdf5 and then h5py.

However, cmake may not find your hdf5 version, even if you installed everything correctly. For me specifying in the cmake call the hdf5 dir explicitly did the trick. Can you try to add these cmake option (maybe adopt the dirs):
```
-DHDF5_INCLUDE_DIR=/share/apps/hdf5/include -DHDF5_DIR=/share/apps/hdf5
```
Hope that helps. 
-Alex

**Comment by hungtranvn** [comment]
Thanks @the-hampel !
I did put the options: `-DHDF5_INCLUDE_DIR=/share/apps/hdf5/include -DHDF5_DIR=/share/apps/hdf5`, but I still get error.
I am now trying to solve the problem by your way.

**Comment by Wentzell** [comment]
Dear @hungtranvn,

I would recommend you to remove both your custom hdf5 installation as well as h5py and proceed as follows

1. Install hdf5 through the package manager as you did before
2. Be sure to have `pip` installed: `dnf install python-pip`
2. Build h5py against the system hdf5 and install it into `~/.local` with 
`pip2 install --user --no-binary=h5py h5py`

**Comment by hungtranvn** [comment]
Dear @Wentzell ,
The problems was solved by your recommendation. And TRIQs was built successfully.
Thank for your help!
Hung Tran
