### ISSUE TITLE
[triqs/hilbert_space] Minor issue in the example program

### ISSUE THREAD

**Issue by francescopt** [TRIQS/triqs#361]
Hi,
I think I found a minor issue in the example program for the [hilbert_space] toolbox provided in 
_triqs.src/doc/reference/hilbert_space/hilbert_example.cpp_ and also found in:
https://triqs.ipht.cnrs.fr/1.x/reference/hilbert_space/contents.html

Git hash of my installation is c17bb1da99aec582aed237b27dbdd3715fdb50eb

The source _hilbert_example.cpp_ contains
`
foreach(partition, [&](fock_state_t s, int spn) {
  inv_subspaces[spn].add_fock_state(s);
 });
`

According to the [documentation of foreach](https://triqs.ipht.cnrs.fr/1.x/cpp2doc_generated/triqs/hilbert_space/space_partition/foreach.html#space-partition-foreach) the first parameter of the Lambda function passed to foreach should be the index of the fock state, rather than the fock_state_t itself.
Nevertheless, the above code works correctly because the fock state and its index are actually equal, as shown in the implementation of _hilbert_space::get_fock_state_ in _triqs/hilbert_space/hilbert_space.hpp:98_

`
 fock_state_t get_fock_state(int i) const {
  if (i >= dim) TRIQS_RUNTIME_ERROR << "This Fock state does not exist (index too big), i = " << i;
  return i;
 }
`

I think one could modify the example  _hilbert_example.cpp_ as follows

`
foreach(partition, [&](int s, int spn) {
  inv_subspaces[spn].add_fock_state(hs.get_fock_state(s));
 });
`

so that the code is independent of the actual implementation of fock states inside hilbert_space.

Best,

        Francesco

**Comment by krivenko** [comment]
Hi Francesco,
Your remark looks valid to me. This inconsistency could cause a problem if I tried to take a `sub_hilbert_space` and partition it again.
