### ISSUE TITLE
problem with cpp2py.log compilation on Mac 

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/triqs#362]
When building triqs incuding documentation I get the following problem:

[ 66%] Generating cpp2py.log
cd /Users/aichhorn/work/Codes/build/TRIQSdev/doc && export PYTHONPATH=$PYTHONPATH:/Users/aichhorn/work/Codes/build/TRIQSdev/tools/cpp2doc/mako && /usr/local/bin/python /Users/aichhorn/work/Codes/build/TRIQSdev/tools/c++2doc.py -N triqs /Users/aichhorn/work/Codes/TRIQS1.x/TRIQS/doc/reference/doc_root.hpp --output_directory=/Users/aichhorn/work/Codes/build/TRIQSdev/doc/cpp2doc_generated --includes=/Users/aichhorn/work/Codes/TRIQS1.x/TRIQS/ --includes=/Users/aichhorn/work/Codes/build/TRIQSdev/Config --compiler_options="-DTRIQS_BUILDING_LIBRARY" --mako_location=/Users/aichhorn/work/Codes/TRIQS1.x/TRIQS/tools/ 2>1 > cpp2py.log
make[2]: **\* [doc/cpp2py.log] Error 1
make[2]: **\* Deleting file `doc/cpp2py.log'
make[1]: **\* [doc/CMakeFiles/docs_cpp2doc.dir/all] Error 2
make: **\* [all] Error 2

When I do everything listed above manually, and rerun make, I get the message that cpp2py.log is correctly built, and the make moves on. This is strange.
OSX 10.11.6, XCode 8.0

**Comment by krivenko** [comment]
Hi Markus,
Could you locally revert 81159817c54b1051d9d59a24a8276bd7f9376b25 and try again?

**Comment by aichhorn** [comment]
I reverted to commit 7c39ae9, but have the same issue. Compilation still breaks at cpp2py.log.

**Comment by krivenko** [comment]
This is weird. We need to see what is actually going wrong.
To this end, I'd ask you to change `doc/CMakeLists.txt` a bit and try again.
```
diff --git a/doc/CMakeLists.txt b/doc/CMakeLists.txt
index b671e85..b5dd4c9 100644
--- a/doc/CMakeLists.txt
+++ b/doc/CMakeLists.txt
@@ -82,7 +82,7 @@ add_custom_command (OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/cpp2py.log DEPENDS ${all_
 		    ${CMAKE_BINARY_DIR}/tools/c++2doc.py -N triqs ${CMAKE_CURRENT_SOURCE_DIR}/reference/doc_root.hpp
 		    --output_directory=${CMAKE_CURRENT_BINARY_DIR}/cpp2doc_generated
 		    --includes=${CMAKE_SOURCE_DIR}/ --includes=${CMAKE_BINARY_DIR}/Config --compiler_options="-DTRIQS_BUILDING_LIBRARY"
-		    --mako_location=${CMAKE_SOURCE_DIR}/tools/ 2>1 > cpp2py.log)
+		    --mako_location=${CMAKE_SOURCE_DIR}/tools/)
 add_custom_target(docs_cpp2doc DEPENDS ${CMAKE_CURRENT_BINARY_DIR}/cpp2py.log)
 add_dependencies(docs_sphinx docs_cpp2doc triqs) # we must have installed the sources before building
 endif()
``

**Comment by aichhorn** [comment]
Now I am getting the error message:

Traceback (most recent call last):
  File "/Users/aichhorn/work/Codes/build/TRIQSdev/tools/c++2doc.py", line 3, in <module>
    from clang_parser import parse
  File "/Users/aichhorn/work/Codes/build/TRIQSdev/tools/clang_parser.py", line 7, in <module>
    import clang.cindex
ImportError: No module named clang.cindex

Am I missing a module? But why did it work when I did it manually? Strange.

**Comment by parcollet** [comment]
pip install clang

**Comment by aichhorn** [comment]
Thanks Olivier, works now. We should include the clang module in the list of prerequisites on the install page.

**Comment by krivenko** [comment]
Documentation has been updated.
CMake now tries to import `clang.cindex` if `Build_Documentation=ON`.
