### ISSUE TITLE
Extract int/string from variant_int_string

### ISSUE THREAD

**Issue by francescopt** [TRIQS/triqs#366]
Hi,

when parsing monomials in a `many_body_operator`, to each `c`/`c_dag` term one can extract an  object `indices_t indices` which is a `std::vector<triqs::utility::variant_int_string>`.
As far as I can understand, in the header file _triqs/utility/variant_int_string.hpp_ the union {int, string} is private and there is no method to extract from a `variant_int_string` an int or a string, depending on the actual type. I found a workaround by printing it to a string, and the converting it, such as follows

```
many_body_operator_complex HE;
many_body_operator_complex::const_iterator iter = HE.begin();
auto monomial = iter->monomial;
int index = atoi(triqs::utility::to_string(monomial[0].indices[0]).c_str());
```
(In the code above I am assuming I know that `monomial[0].indices[0]` is an integer.)

I think it would be nicer to have some additional methods in `class variant_int_string` to
- tell if a `variant_in_string` is actually an int or a string
- convert it to a int/string

Or can you suggest a better way to do the conversion above?

Best,

       Francesco

**Comment by krivenko** [comment]
Hi Francesco,

Variant types, such as our `variant_int_string`, are usually accessed using visitation technique.
Please, have a look at this example:
```c++
struct index_visitor  {
  void operator()(int i) { std::cout << "Found an integer" << std::endl; }
  void operator()(std::string s) { std::cout << "Found a string" << std::endl; }
};

index_visitor iv;
apply_visitor(iv, monomial[0].indices[0]);
```

**Comment by francescopt** [comment]
Hi Igor,

thanks a lot for the clarification! I modified my code to use apply_visitor.

         Francesco

**Comment by parcollet** [comment]
Yes, Igor is right.
variant_int_string is a temporary fix, to be replaced by 
std::variant (C++17) as soon as it is widely implemented.
So we will limit ourselves to std::variant API and not add other features.
