### ISSUE TITLE
Build by intel C++ compiler 2016

### ISSUE THREAD

**Issue by shinaoka** [TRIQS/triqs#368]
Hello,
I am now trying build the latest version in the repository using Intel C++ compiler Version 16.0.4.258.
But, I got the following error.
There seems to be some name look error.
Do you have any idea?

/home/k0156/k015600/build/triqs-build-c++14-24432f6adbd9113687000aa6e9598e1f807a06d7/pytriqs/gf/local/gf_wrap.cpp(18683): error: more than one operator "<<" matches these operands:
            function "triqs::gfs::operator<<(std::ostream &, triqs::gfs::tail_const_view)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::refreq, triqs::gfs::tensor_valued<3>, triqs::gfs::tail_zero<triqs::arrays::array<triqs::lattice::dcomplex, 3, void>>, void> &> &)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::retime, triqs::gfs::matrix_valued, triqs::gfs::tail, void> &> &)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::legendre, triqs::gfs::gf_default_target_t<triqs::gfs::legendre>, triqs::gfs::gf_default_singularity_t<triqs::gfs::legendre, triqs::gfs::matrix_valued>, void> &> &)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::imfreq, triqs::gfs::tensor_valued<4>, triqs::gfs::tail_zero<triqs::arrays::array<triqs::gfs::dcomplex, 4, void>>, void> &> &)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::imfreq, triqs::gfs::tensor_valued<3>, triqs::gfs::tail_zero<triqs::arrays::array<triqs::lattice::dcomplex, 3, void>>, void> &> &)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::refreq, triqs::gfs::tensor_valued<4>, triqs::gfs::tail_zero<triqs::arrays::array<triqs::gfs::dcomplex, 4, void>>, void> &> &)"
            function "triqs::gfs::operator<<(std::ostream &, const triqs::gfs::gf_unary_m_expr<const triqs::gfs::gf_view<triqs::gfs::imfreq, triqs::gfs::matrix_valued, triqs::gfs::no_tail, void> &> &)"
            operand types are: std::stringstream << triqs::gfs::tail_view
    std::stringstream fs; fs << self_c;

**Comment by parcollet** [comment]
@wentzell : we need to have a version of Intel somewhere to test or not support it at all.

**Comment by Wentzell** [comment]
Yes we should look into testing this just to know what problems exist and which version is necessary to compile master/unstable. Working on it.

**Comment by shinaoka** [comment]
Thanks. That will help us.

**Comment by parcollet** [comment]
Hi, 
can I ask why ?
We tested Intel C++ last year, and for triqs applications, the performance was not better than gcc.
Why use icc then ?

**Comment by shinaoka** [comment]
The performance is not an issue for us.
We're currently developing a software which depends TRIQS libraries.
It may not be a good idea to ask users to install latest gcc in a supercomputing system whose default C++ compiler is Intel.
What do you think?

**Comment by Wentzell** [comment]
We compiled TRIQS (both master and unstable) with the Intel Compiler 17.0.1 20161005
and we could not reproduce your problem. 
We ran however into some other problems with
ICC that required workarounds. See that fd7fbdfb19fd694db0441fbc0f47853db39476f0 and 0bde82faa4886708f5485ffb1bf1ad5fdf457c6a 

We can reopen this issue if further problems are encountered when compiling with an ICC version
newer than 17.0.1 20161005
