### ISSUE TITLE
[cpp2py] Unsafe implementation of release_GIL_and_enable_signal

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#369]
When `release_GIL_and_enable_signal` is switched on, the interpreter lock is released before all function arguments are converted from Python. If some of the arguments have wrapped types, `PyImport_ImportModule()` may be called, which is likely to result in a crash.

To reproduce:
Add `release_GIL_and_enable_signal = True` to the description of `cthyb::solve()` and run any Python test.

**Comment by parcollet** [comment]
Should be fixed now.
Except if you manually pass a code containing some Python API, but that is an advanced option.

**Comment by krivenko** [comment]
I can confirm `cthyb` does not crash anymore.
