### ISSUE TITLE
[unstable] GCC 5.4 cannot compile optional_compat.hpp

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#401]
As far as I understand `optional_compat.hpp` is a workaround for the older compilers supporting `<experimental/optional>` but not `<optional>`.
```c++
#if __cplusplus > 201402L 
#include <optional>
#else
#include <experimental/optional>
namespace std { // to be found by ADL

 using std::experimental::optional;
 using std::experimental::in_place;
}
#endif
```

Now the problem is that `__cplusplus` is defined to be 201500 on GCC 5.4, while `<optional>` is not yet supported by it.

My compiler is `gcc (Gentoo 5.4.0-r3 p1.3, pie-0.6.5) 5.4.0`.

**Comment by Wentzell** [comment]
Fixed by ``109cb9b``
