### ISSUE TITLE
[applications] wrong libmpi.so

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#407]
Hi,
I have successfully installed TRIQS on a cluster which has a couple of different MPI options (gnu, intel...):
```bash
$ find /opt -name "libmpi.so*"
/opt/ompi/intel/14.0/lib64/libmpi.so
/opt/ompi/intel/14.0/lib64/libmpi.so.1
/opt/ompi/intel/14.0/lib64/libmpi.so.1.5.0
/opt/ompi/gnu/lib64/libmpi.so
/opt/ompi/gnu/lib64/libmpi.so.1
/opt/ompi/gnu/lib64/libmpi.so.1.5.0
/opt/mpich3/intel/14.0/lib64/libmpi.so
/opt/mpich3/intel/14.0/lib64/libmpi.so.12
/opt/mpich3/intel/14.0/lib64/libmpi.so.12.0.1
/opt/mpich3/gnu/lib64/libmpi.so
/opt/mpich3/gnu/lib64/libmpi.so.12
/opt/mpich3/gnu/lib64/libmpi.so.12.0.1
```
I linked TRIQS against the ompi version.

I am now installing some TRIQS applications. Let us take cthyb for instance (I did not post this on the cthyb issue list because I think it is relevant to TRIQS in general). The c++ tests pass, but the python tests fail. For instance, the error log for single_site_bethe is
```bash
Starting on 1 Nodes at : 2017-05-01 18:03:25.981063
[rupc03:24069] *** Process received signal *** 
[rupc03:24069] Signal: Segmentation fault (11)
[rupc03:24069] Signal code: Address not mapped (1) 
[rupc03:24069] Failing at address: 0x44000098
[rupc03:24069] [ 0] /lib64/libpthread.so.0(+0xf9f0)[0x2aedebdc19f0]
[rupc03:24069] [ 1] /opt/ompi/intel/14.0/lib64/libmpi.so.1(MPI_Comm_rank+0x58)[0x2aeded1ba448]
```
As you can see, the wrong MPI is "chosen" when I run pytriqs (note: I put /opt/ompi/gnu/lib64 in the LD_LIBRARY_PATH)... Do you know how I could fix this?
Thanks
Thomas

**Comment by Wentzell** [comment]
Isn't the mpi version that pytriqs uses decided with the mpi4py installation?

**Comment by tayral** [comment]
I tried to reconfigure mpi4py by modifying mpi.cfg in .../lib/python2.7/site-packages/mpi4py/, but I still get the error... I don't really understand where the information about which libmpi to use is stored...

**Comment by Wentzell** [comment]
That is strange.
Maybe the ompi/intel/14.0 is still floating somewhere in your environment variables?

What do you get with 
```printenv | grep mpi```
?

What does 
```ldconfig -p | grep libmpi``` 
give you?

**Comment by tayral** [comment]
Hi Nils,
Here is the output of the command
```bash
$ printenv | grep ompi
LIBRARY_PATH=/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/intel64:/opt/intel/composer_xe_2013_sp1.3.174/ipp/../compiler/lib/intel64:/opt/intel/composer_xe_2013_sp1.3.174/ipp/lib/intel64:/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/intel64:/opt/intel/composer_xe_2013_sp1.3.174/mkl/lib/intel64:/opt/intel/composer_xe_2013_sp1.3.174/tbb/lib/intel64/gcc4.4
MIC_LD_LIBRARY_PATH=/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/mic:/opt/intel/composer_xe_2013_sp1.3.174/mpirt/lib/mic:/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/mic:/opt/intel/composer_xe_2013_sp1.3.174/mkl/lib/mic:/opt/intel/composer_xe_2013_sp1.3.174/tbb/lib/mic
LD_LIBRARY_PATH=/opt/gnu/gcc-6.2.0/lib64/:/opt/slurm/16.05.6/lib64/:/opt/fftw/lib64/:/opt/intel/mkl/lib/intel64/:/opt/intel/lib/intel64/:/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/intel64/
NLSPATH=/opt/intel/composer_xe_2013_sp1.3.174/compiler/lib/intel64/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.3.174/ipp/lib/intel64/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.3.174/mkl/lib/intel64/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.3.174/debugger/gdb/intel64_mic/py27/share/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.3.174/debugger/gdb/intel64/py27/share/locale/%l_%t/%N:/opt/intel/composer_xe_2013_sp1.3.174/debugger/intel64/locale/%l_%t/%N

```
(no trace of ompi/intel) and ``ldconfig -p |grep libmpi`` does not yield any output...

**Comment by Wentzell** [comment]
Hey Thomas,

The ldconfig is often not in the path. Try /usr/sbin/ldconfig -p | grep libmpi
or just /sbin/ldconfig, maybe that works?

The  /opt/ompi/gnu/lib64 folder seems to be missing in the environment you posted.
Try adding the following lines to your ~/.bashrc
```
CPATH=/opt/ompi/gnu/include:$CPATH
LD_LIBRARY_PATH=/opt/ompi/gnu/lib64:$LD_LIBRARY_PATH
LIBRARY_PATH=/opt/ompi/gnu/lib64:$LIBRARY_PATH
```
then relog, clear your build dir, and recompile triqs.

Also could you check what your mpi4py is linked against?
``` 
ldd PATH_TO_PYTHON/lib/python2.7/site-packages/mpi4py/MPI.so
```

**Comment by parcollet** [comment]
Has this been solved by now ?

**Comment by parcollet** [comment]
Closed due to inactivity. Reopen if needed.
Not a TRIQS issue anyway, it is an installation issue on this machine,.
