### ISSUE TITLE
[mc_tools] autocorrelation_jacknife test fails after update to boost 1.64 

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#412]
There was a change in the boost RNG which causes the autocorrelation_jacknife
test to fail:
[autocorr.txt](https://github.com/TRIQS/triqs/files/992975/autocorr.txt)

**Comment by parcollet** [comment]
Ok, what should we do about this ?

**Comment by Wentzell** [comment]
The quick solution is to put to different hdf5 reference files that should be used depending on the boost version ....  What do you think?
In the longer run we should replace the boost rng as by the one of std as discussed.

**Comment by parcollet** [comment]
what if boost changes again ??

**Comment by Wentzell** [comment]
Well till then we should have switched to std
