### ISSUE TITLE
downloading ctseg - authorization required?

### ISSUE THREAD

**Issue by pbakalov** [TRIQS/triqs#413]
I tried downloading the CTSEG code from bitbucket (following the instructions [here](https://triqs.ipht.cnrs.fr/1.3/applications/cthyb_segment/install.html)), but I got "authorization failed".

Since the [about CTSEG](https://triqs.ipht.cnrs.fr/1.3/applications/cthyb_segment/about.html) page states that the solver is published under GNU's GPL, I thought that this might be an error.

Or is the code supposed to be hidden?

**Comment by Wentzell** [comment]
I am getting the same thing.

@parcollet Did you change the access rights?

**Comment by pbakalov** [comment]
I'm interested in CTSEG because [it allows](https://triqs.ipht.cnrs.fr/1.3/applications/cthyb_segment/observables.html) measurements of two- and three-frequency quantities.

As far as I know CT-HYB doesn't offer such functionality (yet), correct?

**Comment by HugoStrand** [comment]
Dear Petar,
In case you are interested in measuring two-particle Green's functions, this feature do exist in `triqs/cthyb` and is currently being tested, see
https://github.com/TRIQS/cthyb/tree/dev_measures/c%2B%2B/measures
Whether this is useful for you of course depends on what kind of problems you would like to tackle.

The `triqs/ctseg` code is currently being cleaned up and is unfortunately not yet publicly available.

Please contact me if you have questions about `trisq/cthyb` or if you would like some support on using the two-particle Green's function measurements.

Best regards,
Hugo

**Comment by pbakalov** [comment]
Dear Hugo, 
Thanks for the information! I'll check that out.
Best regards,
Petar

**Comment by parcollet** [comment]
The CT-SEG code should be published this summer, 
as soon as some cleaning and the CPC paper is finished.
