### ISSUE TITLE
[triqs/operators] Coefficients extraction for two-body terms: odd behavior

### ISSUE THREAD

**Issue by francescopt** [TRIQS/triqs#414]
Hi,
when extracting the two-body terms using the function `extract_U_dict4`, the resulting map contains "duplicated" elements, that is, set of indices which are equivalent under an operator reordering.
Consider, e.g., the following program:

```
#include <iostream>
#include <tuple>
#include <triqs/operators/util/extractors.hpp>
#include <triqs/operators/many_body_operator.hpp>

using namespace std;
using namespace triqs::operators;
using namespace triqs::operators::util;

int main()
{
  many_body_operator op = c_dag(1) * c(0) + c_dag(1) * c_dag(0) * c(0) * c(2);
  auto hdict = extract_h_dict(op, true);
  auto Udict = extract_U_dict4(op, true);
  cout << op << endl;

  cout << "coefficient operator" << endl;
  for (auto const& elem : hdict)
    cout << get<1>(elem) << " " << c_dag(get<0>(get<0>(elem))) * c(get<1>(get<0>(elem))) << endl;
  
  for (auto const& elem : Udict)
    cout << get<1>(elem) << " " << c_dag(get<0>(get<0>(elem))) * c_dag(get<1>(get<0>(elem))) * c(get<3>(get<0>(elem))) * c(get<2>(get<0>(elem))) << endl;

  return 0;
}
```

The program defines an `many_body_operator op`, prints it, and then lists for each one-/two-body term the coefficient and the corresponding operator. The output of the program is:

```
1*C^+(1)C(0) + 1*C^+(0)C^+(1)C(2)C(0)
coefficient operator
1 1*C^+(1)C(0)
0.5 1*C^+(0)C^+(1)C(2)C(0)
-0.5 -1*C^+(0)C^+(1)C(2)C(0)
-0.5 -1*C^+(0)C^+(1)C(2)C(0)
0.5 1*C^+(0)C^+(1)C(2)C(0)
```

The extracted two-body dictionary `Udict` contains 4 equivalent operators. The sum / 2 gives the original operator, in agreement with the documentation of `extract_U_dict4`.
However, I find this behavior rather incovenient. For instance, as in the example above, if one wants to analyse coefficient-by-coefficient a `many_body_operator`, one gets multiple terms which are actually identical.

Would it be possible to change the behavior or `extract_U_dict4` so that it returns a map where each nonequivalent operator appears only once? In this case, the output of the previous program should be

```
1*C^+(1)C(0) + 1*C^+(0)C^+(1)C(2)C(0)
coefficient operator
1 1*C^+(1)C(0)
1 1*C^+(0)C^+(1)C(2)C(0)
```

Best,

        Francesco

**Comment by parcollet** [comment]
@Wentzell 
this function should be replaced as discussed.

**Comment by krivenko** [comment]
Hi Francesco,

`extract_U_dict4()` was designed to return all non-zero elements of the U-tensor. As you correctly pointed out, one quartic monomial of an operator generates 4 such elements.
I can consider changing the function in the way you suggest, but this will also require a change to another function, `dict_to_matrix()`. And this is something I am reluctant to do.

To achieve your goal you could simply use the iterator interface of `many_body_operator`,
```c++
for(auto const & term : op){
  auto coef = term.coef; // coefficient
  auto const& m = term.monomial; // monomial
  auto const& x = m[0]; // first c^+/c of the monomial
  x.dagger; // c or c^+ ?
  x.indices; // vector of indices of x
}
``` 

@tayral Could you comment on this, Thomas? You used the extractors in `ctseg`...

@parcollet @Wentzell What are you going to do?

**Comment by parcollet** [comment]
We think that these functions are too complex and
need to be redesigned.
@Wentzell : please discuss this with Igor.

**Comment by Wentzell** [comment]
Hey Igor,

I found it strange that you put only a factor 0.5 in ```extract_U_dict4()```. 
To my knowledge this is commen practice for density-type interactions,
e.g. to rewrite ``` U * n(0) n(1) ``` as ``` 0.5 \sum_{ij} U_{ij} n(i) n(j)```

For general interactions however I think it is much more common to introduce the U-tensor as ``` 0.25 \sum_{ijkl} U_{ijkl} c(i) c(j) c^+(k) c^+(l) ```, which would mean a prefactor 0.25 in ```extract_U_dict4()```

What was the reasoning behind the factor 0.5 instead?

**Comment by krivenko** [comment]
Hey Nils,

> For general interactions however I think it is much more common to introduce the U-tensor as 0.25 \sum_{ijkl} U_{ijkl} c(i) c(j) c^+(k) c^+(l), which would mean a prefactor 0.25 in extract_U_dict4()

My personal experience is rather different...

Anyhow, factor `0.5` naturally emerges in the derivation of the U-tensor. With this particular prefactor one has a simple relation `U_{ijkl} = <ij|H_{int}|kl>`.

Moreover, this factor must be consistent with what we have in the Hamiltonian construction routines, ` pytriqs.operators.util.U_matrix.U_matrix` and `pytriqs.operators.util.hamiltonians.h_int_slater`.

**Comment by Wentzell** [comment]
Ok. 
The functions are anyways working exactly as documented and the 
for loop construct provides the functionality to loop through all the terms.

This can be closed
