### ISSUE TITLE
Python wrapping of gf_view crashes

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#421]
I want to wrap some functions taking `gf_view<cartesian_product<imtime, imtime, imtime>, tensor_valued<4>>` arguments, which is rather cumbersome to write out all the time. So I decided to define a little intermediate type

```c++ 
using gf_view_t = gf_view<cartesian_product<imtime, imtime, imtime>, tensor_valued<4>>;
```

to use with the wrapped functions. 

However this causes the wrapped functions to crash complaining that the meshes of the passed python gf does not agree with the type of the wrapped function. The error message is

```
libc++abi.dylib: terminating with uncaught exception of type triqs::runtime_error: .. 
Triqs runtime error at /Users/hugstr/apps/triqs_devel/include/triqs/./gfs/gf/gf.hxx : 1786

Gf Assignment in View : incompatible meshProduct Mesh vs Product Mesh
.. Error occurred on node 
Abort trap: 6
```

I have put together a jupyter notebook that reproduces the error (crashing the kernel).

[Error passing gf_view<cartesian_product<...>, ...>.ipynb.zip](https://github.com/TRIQS/triqs/files/1039415/Error.passing.gf_view.cartesian_product.ipynb.zip)

Here is a short summary:

```python
%reload_ext pytriqs.magic
```
```python
from pytriqs.gf import Gf, MeshImFreq, MeshImTime, MeshProduct

nt = 10
beta = 1.2345
imtime = MeshImTime(beta, 'Fermion', nt)
imtime3 = MeshProduct(imtime, imtime, imtime)

g4_tau = Gf(name=r'$g(\tau_1, \tau_2, \tau_3)$', mesh=imtime3,
             target_shape=[1, 1, 1, 1])
```

```c++
%%triqs             
#include <triqs/gfs.hpp>
using namespace triqs::gfs;

void eater(gf_view<cartesian_product<imtime, imtime, imtime>, tensor_valued<4>> gv) {
    auto mesh = std::get<0>(gv.mesh());
    double beta = mesh.domain().beta;
    std::cout << "beta = " << beta << "\n";
}
```

```python
# This works just fine
eater(g4_tau)
```
However defining a type alias instead
```c++
%%triqs             
#include <triqs/gfs.hpp>
using namespace triqs::gfs;

using gf_view_t = gf_view<cartesian_product<imtime, imtime, imtime>, tensor_valued<4>>;

void eater_2(gf_view_t gv) { 
    auto mesh = std::get<0>(gv.mesh());
    double beta = mesh.domain().beta;
    std::cout << "beta = " << beta << "\n";
}
```
```python
# Using a type that is a gf_view but not specified verbatim is a problem...
# Why?

eater_2(g4_tau) # Crashes and burns
```

**Comment by krivenko** [comment]
Hi Hugo,

`cpp2py` treats function arguments of regular types and of view types differently.
And, as far as I understand, the only way for `cpp2py` to decide whether a type is a view is to parse its literal name. Resolution of typedefs is beyond its competence.

Take a look here:
https://github.com/TRIQS/triqs/blob/unstable/tools/cpp2py/wrap_generator.py#L43
https://github.com/TRIQS/triqs/blob/unstable/tools/cpp2py/mako/xxx_wrap.cpp#L584

Also, commit 7185f2d6b95c121fa101b3fc228bb2554ed78455 made it possible to default-construct array and GF views. Before that commit your code would not even compile, I guess (see line 592 of xxx_wrap.cpp).

**Comment by parcollet** [comment]
cpp2py can easily use the canonical type, which resolves alias.
Now, probably it is not done, and should be ...
Assigned to me.

**Comment by HugoStrand** [comment]
@krivenko , thank you for the response and explanation. 👍 

That the `wrap_generator.py` magically acts differently on types ending with `::view_type` looks a bit fragile. This causes the use of `::view_type` as in `gf` and `block_gf` to behave differently than using `::view_t` which is used pretty much every where else. It is not what I would have assumed.

@parcollet Could you use the `assigned to` and `labels` functionality for issues on Github so that we can get a better overview of open issues?

Cheers, H

**Comment by parcollet** [comment]
Normally fixed in 1.6-dev
To be rechecked and postponed to 1.6
do not alias in 1.5

**Comment by parcollet** [comment]
@HugoStrand 
Should be fixed by now on unstable. Can we close ?

**Comment by Wentzell** [comment]
I can confirm that this issue has been resolved.
