### ISSUE TITLE
Problem in installation

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/triqs#422]
I am trying to install TRIQS in Ubuntu 17.04 Zesty following the instructions in the website. First of all,
the package **openmpi-checkpoint** cannot be found and one should search for openmpi-doc probably. Secondly, after downloading the source files and trying to **make** I get:

`In file included from /home/daniel/Sources/triqs.src/triqs/h5.hpp:23:0,
                 from /home/daniel/Sources/triqs.src/triqs/arrays/h5/./simple_read_write.hpp:24,
                 from /home/daniel/Sources/triqs.src/triqs/arrays/h5/simple_read_write.cpp:21:
/home/daniel/Sources/triqs.src/triqs/./h5/base_public.hpp:24:22: fatal error: H5Ipublic.h: No such file or directory
 #include<H5Ipublic.h>
                      ^
compilation terminated.
triqs/CMakeFiles/triqs.dir/build.make:62: recipe for target 'triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o' failed
make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o] Error 1
CMakeFiles/Makefile2:1238: recipe for target 'triqs/CMakeFiles/triqs.dir/all' failed
make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2`

Any ideas what I should do?? 

Thanks!

P.S: The compiler that I use is gcc 6.3.0

**Comment by parcollet** [comment]
- have you installed libhdf5-dev ? Apparently it is not libdhf5-serial-dev any more ...
- openmpi-checkpoint : I have no clue what it was included before ...

**Comment by dmantadakis** [comment]
I have installed **libhdf5-dev** (1.10.0-patch1+docs-3)

**Comment by parcollet** [comment]
dpkg -L  libhdf5-dev 
?

**Comment by dmantadakis** [comment]
This command returns me I bunch of files

**Comment by parcollet** [comment]
Sure ... the list of files in the package. H5Ipublic.h is not in it ??

**Comment by dmantadakis** [comment]
Its inside... I can grep it

**Comment by dmantadakis** [comment]
/usr/include/hdf5/serial/H5Ipublic.h

**Comment by parcollet** [comment]
how can this happen then ?
/home/daniel/Sources/triqs.src/triqs/./h5/base_public.hpp:24:22: fatal error: H5Ipublic.h: No such file or directory #include<H5Ipublic.h> ^ compilation terminated.

**Comment by parcollet** [comment]
cmake .
-> give me the HDF5 section (in a gist ?).

**Comment by dmantadakis** [comment]
-- -------- HDF5 detection -------------
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- Found HDF5: /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so (found version "1.10.0.1") found components:  C HL 
--  HDF5_LIBRARIES = /usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so;/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so
-- hdf5 version: 1.10.0

I am not sure If I gave you what you asked for...

**Comment by parcollet** [comment]
-locate FindHDF5.cmake
- vim it, and look in the long comment at the begin, it is its doc
- there is a line which says 
# This module will define the following variables:
#  HDF5_INCLUDE_DIRS - Location of the hdf5 includes
#  HDF5_INCLUDE_DIR - Location of the hdf5 includes (deprecated)

or something like this...
yes ?

**Comment by dmantadakis** [comment]
I cannot find anywhere **FindHDF5.cmake**

**Comment by parcollet** [comment]
it is part of cmake package... locate it?

**Comment by dmantadakis** [comment]
I try to locate it in the directory (and subdirectories) but I get no match...

**Comment by dmantadakis** [comment]
//Details about finding HDF5
FIND_PACKAGE_MESSAGE_DETAILS_HDF5:INTERNAL=[/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5.so;/usr/lib/x86_64-linux-gnu/libpthread.so;/usr/lib/x86_64-linux-gnu/libsz.so;/usr/lib/x86_64-linux-gnu/libz.so;/usr/lib/x86_64-linux-gnu/libdl.so;/usr/lib/x86_64-linux-gnu/libm.so][/usr/lib/x86_64-linux-gnu/hdf5/serial/libhdf5_hl.so][cfound components:  C HL ][v1.10.0.1()]

**Comment by dmantadakis** [comment]
That's in the CMakeCashe.txt

**Comment by HugoStrand** [comment]
Dear dmantadakis,

You will have to tell `cmake` how to find the missing `HDF5` header files somehow. A drastic way is simply to point `cmake` to the correct path by adding 

```
    -DCMAKE_INCLUDE_PATH="/usr/include"
```

to the command line when you call cmake.

**Comment by parcollet** [comment]
I think it is simply due to the fact that 
HDF5_INCLUDE_DIR  which was deprecated has been removed 
and replaced by 
HDF5_INCLUDE_DIRS

- in CmakeLists.txt, line 316 (top level)
try to replace 
set(TRIQS_INCLUDE_HDF5 ${HDF5_INCLUDE_DIR})
by
set(TRIQS_INCLUDE_HDF5 ${HDF5_INCLUDE_DIRS})

-to confirm this is the issue, you can also say : 
locate FindHDF5.cmake 
(use the locate command)
then look at the file, in the comments at the top (or send me the file by email !).

**Comment by parcollet** [comment]
PS:  we should also print the HDF5_INCLUDE_DIR, HDF5_INCLUDE_DIRS
in the cmake (with message), just to have an idea of the pb.

**Comment by parcollet** [comment]
which version of cmake do you have ?
cmake --version ?

**Comment by dmantadakis** [comment]
cmake version 3.7.2

**Comment by Wentzell** [comment]
Hey Dani!

Ubuntu installs the hdf5 headers in a non-standard directory in order not to mix the 
parallel and serial version.  The FindHDF5.cmake should however find that directory properly...

@parcollet 
With cmake 3.7.2 the HDF5_INCLUDE_DIR variable is deprecated but still properly set,
so from that side we should be fine. See here
https://github.com/Kitware/CMake/blob/v3.7.2/Modules/FindHDF5.cmake

I will look at the problem on our ubuntu machine the next days.

As a workaround you can tell cmake the location of the serial directory
```
-DCMAKE_INCLUDE_PATH="/usr/include/hdf5/serial"
```

**Comment by dmantadakis** [comment]
Hey Nils!

Even if I tell cmake the location of the serial directory, I still get the same problem... No idea why...

**Comment by dmantadakis** [comment]
Hey Nils!

I exported directly variable CPLUS_INCLUDE_PATH with path "/usr/include/hdf5/serial" right before compiling with make and it did work.

**Comment by aichhorn** [comment]
Same here on our cluster, had this a couple of weeks ago. Since this is an hdf5 issue, where it puts its headers, one should solve it outside TRIQS (the same problem occurs for other codes). In general, setting CPATH to point to the include directory usr/lib/hdf5/serial should be enough.

**Comment by dmantadakis** [comment]
my mistake,,, issue not closed

**Comment by Wentzell** [comment]
> I exported directly variable CPLUS_INCLUDE_PATH with path "/usr/include/hdf5/serial" right before compiling with make and it did work.

My bad. CMAKE_INCLUDE_PATH affects only the directories searched by some
cmake specific functions, e.g. find_path(..)

CPATH is indeed the easiest workaround to tell your compiler where to find the include files.
```
export CPATH=/usr/include/hdf5/serial:$CPATH
```

> So the problem is the fact that hdf5 creates this tree of subdirectories which seems that they cannot be accessed automatically, or I got something wrong??

Indeed. These subdirectories are not automatically considered by the compiler.
Cmake should however find them and add them as include directories to the compiler...

I checked again the FindHDF5.cmake and it seems that it does in fact use the hdf5 compiler wrappers, e.g. h5c++, to locate the installation. See here:
https://cmake.org/cmake/help/v3.7/module/FindHDF5.html
The wrappers are however installed only with the Ubuntu package **hdf5-helpers**

Could you install the **hdf5-helpers** package and try again the installation without setting
any additional environment variables?

**Comment by dmantadakis** [comment]
Hey Nils,

When **sudo apt install hdf5-helpers** I get that the package is already installed, meaning that still all these problems are there even with this package. With the workaround of exporting, I managed to install everything (only the last test of the DFT tools didn't pass).

If you have any other ideas that you want to try for the new Ubuntu please let me know...

**Comment by Wentzell** [comment]
Should be fixed, just waiting for review and merge.
The problem was indeed that HDF5_INCLUDE_DIR is no longer properly set!

**Comment by JATIN199604** [comment]
Dear TRIQS developer, 
I want to use TRIQS as an interface to WIEN2k . During installation i am gatting an error at make . Your help is necessary for me . 


jatin@jatin-HP-Laptop-14s-cr1xxx:~/DMFT/triqs.build$ make
[  1%] Built target cpp2py
[  2%] Built target gtest
[  3%] Linking CXX shared library libtriqs.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
triqs/CMakeFiles/triqs.dir/build.make:1044: recipe for target 'triqs/libtriqs.so' failed
make[2]: *** [triqs/libtriqs.so] Error 1
CMakeFiles/Makefile2:339: recipe for target 'triqs/CMakeFiles/triqs.dir/all' failed
make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

How should i solve this error

**Comment by Wentzell** [comment]
Hi @JATIN199604,

What operating system and version thereof are you using?
How did you install your dependencies, in particular fftw3?
Which compiler are you using?

**Comment by JATIN199604** [comment]
sir i am using Ubuntu 18.04.2 . I followed the TRIQS installation steps through https://triqs.github.io/triqs/1.4/install.html. I am using gcc version 7.4.0 compiler.

**Comment by Wentzell** [comment]
Is there a reason why you want to install triqs 1.4?

I would recommend you to install the Ubuntu debian packages for version 2.1.0
In that case please follow the steps listed [here](https://triqs.github.io/triqs/2.1.x/install.html#ubuntu-debian-packages-experimental)

**Comment by cmtcl18** [comment]
Dear All,
During make, I am getting the following error. 

~/TRIQS/triqs.build$ make
[  1%] Built target cpp2py
[  2%] Built target gtest
[ 11%] Built target triqs
[ 12%] Linking CXX shared module block_matrix.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
pytriqs/arrays/CMakeFiles/block_matrix.dir/build.make:132: recipe for target 'pytriqs/arrays/block_matrix.so' failed
make[2]: *** [pytriqs/arrays/block_matrix.so] Error 1
CMakeFiles/Makefile2:470: recipe for target 'pytriqs/arrays/CMakeFiles/block_matrix.dir/all' failed
make[1]: *** [pytriqs/arrays/CMakeFiles/block_matrix.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

Any suggestion is appreciated.

Best Regards,
CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

Please do not use previous issue threads for an unrelated problem.
Open a new issue instead.

Thank you
