### ISSUE TITLE
[unstable] gcc 5 - namespaces

### ISSUE THREAD

**Issue by gkraberger** [TRIQS/triqs#423]
Hi everyone,

Is gcc 5 supposed to be still supported by the unstable branch? If yes, there is a bug (see below), if no, the cmake FindCompilerCheck should be updated.

Trying to compile triqs/unstable with gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, I run into the problem that nested namespace definitions in the form (e.g.)
``namespace triqs::gfs {...}``
instead of
``namespace triqs{ namespace gfs {...}}``
are not supported; however they appear in ``pytriqs/gf/wrapped_aux_desc.py`` and ``triqs/utility/optional_compat.hpp``.

According to https://gcc.gnu.org/projects/cxx-status.html this feature is only available in gcc >= 6.

Maybe the compilation of the unstable branch with the minimum required compiler should be added to Jenkins.

Best 
Gernot

**Comment by parcollet** [comment]
Hi Gernot, 
I think we should move to gcc 6 for unstable.
@Wentzell ? @mferrero ? opinion?

**Comment by HugoStrand** [comment]
I have been avoiding namespace nesting in `TRIQS/cthyb/unstable` to avoid this class of problems before the upcoming move to c++17.

**Comment by Wentzell** [comment]
Hey Gernot,

Did you try changing only those two parts? Does it compile if you do?

If these parts are indeed the only thing that stops unstable from compiling with gcc 5 then
it might be worth to change them back at least till the upcoming merge to master.

**Comment by gkraberger** [comment]
Yes, if I change it in these two files the whole thing compiles and it passes all tests.
I agree with you, Nils, that it may be worth supporting gcc 5 still until the merge as it can be done with minimal effort.

Hugo, indeed compiling cthyb/unstable works flawlessly out of the box with my setup.

**Comment by HugoStrand** [comment]
Gernot, good! Thank you for testing and giving feedback. 👍
