### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by Mi-chael** [TRIQS/triqs#429]
Hi, I am trying to install TRIQS on Ubuntu 16.04 LTS. **make** fails while trying to import **my_module** and **make test** returns:

>The following tests FAILED:
	168 - wrap_a (Failed)
	169 - wrap_B (Failed)
	170 - wrap_g (Failed)
	171 - wrap_multivar (Failed)
	172 - blockgf (Failed)

What could be causing this and what should I do?

Thank you!

**Comment by Wentzell** [comment]
Hey!

Could you post the content of the file test/pytriqs/wrap_test/wrap_a.err in your build directory?

**Comment by Mi-chael** [comment]
Hi,
Thank you very much for your response!
I am using the master branch and the contents of the file you mentioned are:

> Traceback (most recent call last):
  File "\<stdin\>", line 1, in \<module\>
ImportError: No module named my_module

The same is true for **wrap_B.err**.
In **wrap_g.err**, **wrap_multivar.err** and **blockgf.err** the story is similar, only that the missing modules are **test_g**, **test_multivar** and **test_bl** respectively.

**Comment by parcollet** [comment]
@Wentzell : run it in docker.

**Comment by Wentzell** [comment]
That is indeed strange. It might be linked to a problem in your Python setup somehow.
But this is hard to figure out remotely.

We just rebuilt triqs/master on a clean Ubuntu 16.04 installation and we can unfortunately not reproduce your problem.

**Comment by Mi-chael** [comment]
interesting... The installation of Ubuntu 16.04 I used was pretty clean aswell. I will reinstall it and hope it'll work. In the meantime I got it running on my universities cluster, so I can still get some work done.

Thank you very much for your time and effort!

**Comment by Mi-chael** [comment]
I reinstalled the operating system and everything is fine now.
