### ISSUE TITLE
histograms : doc, serialization

### ISSUE THREAD

**Issue by parcollet** [TRIQS/triqs#431]
To be implemented in histograms : 
- serialize + python via "tuple" + test.

Documentation to be written ?

**Comment by krivenko** [comment]
I can take care of this, but not immediately (in 1-2 months).
1.6 is not going to be released by this October, I guess.

I would also like to add 3 simple free functions, `mean()`, `median()` and `mode()`.

**Comment by krivenko** [comment]
I've been working on this issue...

Adding `mean()` and friends is not as straightforward as it seems. It raises the old question about how to treat edge bins. The same `histogram` class can be used to accumulate both integers and real numbers. In the case of integers, it's natural to treat all bins equally, whereas for the real numbers the edge bins should be thought of as half-bins.

My conclusion here is that I will probably not implement those functions at all.
