### ISSUE TITLE
compilation error/h5

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#433]
Hi,
I get the following error while compiling triqs on a cluster (hedin):

h5_stack.cpp:(.text._ZN5triqs6arrays16array_stack_implISt7complexIdELi0EEC2ENS_2h55groupERKSsRKNS_7utility11mini_vectorImLi0EEEm[_ZN5triqs6arrays16array_stack_implISt7complexIdELi0EEC5ENS_2h55groupERKSsRKNS_7utility11mini_vectorImLi0EEEm]+0x149): undefined reference to `H5P_CLS_DATASET_CREATE_ID_g'

HDF5 version 1.1.18 compiler gcc 4.9.3

**Comment by Wentzell** [comment]
What is the output you get when you configure triqs? (cmake ../ .. )

**Comment by Wentzell** [comment]
It looks like the hdf5 header's you are using are not compatible with the library.

**Comment by parcollet** [comment]
Looks like an issue with the machine, not with TRIQS.
@mferrero : can you help Leonid with this ?
I am closing it, nothing to do on the lib.

**Comment by leopo** [comment]
The problem was resolved after hdf5 library on this cluster was reinstalled.
