### ISSUE TITLE
[OSX] wrap_multivar test gets stuck on OSX Sierra with gcc 7.1.0

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#434]
The current TRIQS/unstable compiles fine with gcc 7.1.0 under OSX Sierra.

When running the tests however it get's stuck on wrap_multivar.py:5
```
gamma1 = make_vertex(1.0)
``` 
without any errors.

**Comment by parcollet** [comment]
Stops at a Python API call.
Looks like a gcc/clang issue (Python is compiled with clang ...).
Can not fix.

**Comment by dylex** [comment]
I'm seeing the same problem on OSX. It appears to be an infinite loop in test_multivar.so `cpp2py::py_converter<triqs::gfs::gf_mesh<triqs::gfs::imfreq> >::py2c(_object*)` where `pytriqs.gf.meshes._exported_wrapper_convert_fnt` points back to `convert_from_python<triqs::gfs::gf_mesh<triqs::gfs::imfreq>>`.

**Comment by parcollet** [comment]
Fixed by 29a2bd0b980e4b8e76d5f5bbfd7a54f32c466f5d in cpp2py.
