### ISSUE TITLE
pytriqs create a new Green's function from an existing one, broken.

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#449]
Dear @parcollet,

I want to create a new Green's function that is equal to an existing one with the difference that the `dtype` of the new should be `np.complex` instead of `np.float`. Trying to do this I stumbled on the following bug?

```python
from pytriqs.gf import *
g = GfImTime(beta=1., statistic='Fermion')
g_new = Gf(mesh=g.mesh, target_shape=g.target_shape)
```
which complains about the tail not being handled correctly.

```python
/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/gf/gf.pyc in __init__(self, **kw)
    186             self.__check_invariants()
    187 
--> 188         delegate(self, **kw)
    189 
    190     def __check_invariants_tail(self):

/Users/hugstr/apps/triqs_devel/lib/python2.7/site-packages/pytriqs/gf/gf.pyc in delegate(self, mesh, data, target_shape, singularity, indices, name, is_real, _singularity_maker)
    181             s = '_x_'.join( m.__class__.__name__[4:] for m in self.mesh._mlist) if isinstance(mesh, MeshProduct) else self._mesh.__class__.__name__[4:]
    182             proxyname = 'CallProxy%s_%s%s'%(s, self.target_rank,'_R' if data.dtype == np.float64 else '')
--> 183             self._c_proxy = all_call_proxies.get(proxyname, CallProxyNone)(self)
    184 
    185             # check all invariants. Debug.

TypeError: Python object is not a TailGf
```
Is this a bug, or `pebkac` ?

Best, Hugo

**Comment by parcollet** [comment]
This now leads to
AssertionError: Without data, target_shape, I need the indices to compute the shape !
which is normal error

If you correct your code : 

from pytriqs.gf import *
g = GfImTime(indices = [1], beta=1., statistic='Fermion')
_new = Gf(mesh=g.mesh, target_shape=g.target_shape) 

It will be correct, with an empty tail for _new.
