### ISSUE TITLE
Python wrapping of gf_const_view crashes

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#452]
Similarly to the previous bug with wrapping of `gf_view`, see issue #421, the `gf_const_view` also crashes when used with a `typedef`. As an example this code compiles
```c++
%%triqs         
#include <triqs/gfs.hpp>
using namespace triqs::gfs;
        
typedef gf_view<cartesian_product<imfreq, imfreq, imfreq>, tensor_valued<4>> g_iw_view_t;
void pass_g_iw_view_t(g_iw_view_t g) { std::cout << "Hello gf_view!\n"; }
```
while the same thing using `gf_const_view` crashes and burns.
```c++
%%triqs         
#include <triqs/gfs.hpp>
using namespace triqs::gfs;
        
typedef gf_const_view<cartesian_product<imfreq, imfreq, imfreq>, tensor_valued<4>> g_iw_const_view_t;
void pass_g_iw_const_view_t(g_iw_const_view_t g) { std::cout << "Hello gf_const_view!\n"; }
```
the error message is a bit confusing
```
-----------------------------make error -----------------------------
Scanning dependencies of target ext
[ 50%] Building CXX object CMakeFiles/ext.dir/ext_wrap.cpp.o
/Users/hugstr/.ipython/triqs/_triqs_magic_1ea5d815786d58cdffe322b48364f2ca/ext_wrap.cpp:98:8: error: unknown type name 'g_iw_view_t'
       g_iw_view_t g ; //  g_iw_view_t is a regular type
       ^
/Users/hugstr/.ipython/triqs/_triqs_magic_1ea5d815786d58cdffe322b48364f2ca/ext_wrap.cpp:101:106: error: use of undeclared identifier 'g_iw_view_t'
     if (PyArg_ParseTupleAndKeywords(args, keywds, format, kwlist ,converter_for_parser_non_wrapped_type<g_iw_view_t> ,&g))
                                                                                                         ^
2 errors generated.
make[2]: *** [CMakeFiles/ext.dir/ext_wrap.cpp.o] Error 1
make[1]: *** [CMakeFiles/ext.dir/all] Error 2
make: *** [all] Error 2
```
since it looks like it is trying to use a type that is not defined in the `c++` code.

@Wentzell when should we use `gf_const_view<...>` rather than a `gf<...> const &`? I saw that you used the const view type in your inversion example ( #445 ).

Best regards,
Hugo

**Comment by parcollet** [comment]
yes, the branch cpp2y will fix this as well

**Comment by parcollet** [comment]
Should be fixed in 1.6-dev, as previous issue.
Do not use alias in 1.5 for the moment.
Rescheduled for 1.6

**Comment by Wentzell** [comment]
> @Wentzell when should we use gf_const_view<...> rather than a gf<...> const &? I saw that you used the const view type in your inversion example ( #445 ).

If the function might be called with a view, it should also be taking a view_type. Otherwise a  copy of the Green function will be made. In case it is always called with a gf, a gf const & could be used, however this is error prone and can lead to hidden copy performance penalties.

The construction of the view should be very cheap, however access to the gf via the view might still be slower than accessing the gf directly. @parcollet This is still the case no?
So it seems there is a trade-off here between using gf const & and gf_const_view.

**Comment by Wentzell** [comment]
The error is fixed in the latest version of [TRIQS/cpp2py](https://github.com/triqs/cpp2py).

> The construction of the view should be very cheap, however access to the gf via the view might still be slower than accessing the gf directly. @parcollet This is still the case no? So it seems there is a trade-off here between using gf const & and gf_const_view.

Performance of accessing Green Function data through the view is on par with direct access. For wrapping purposes
