### ISSUE TITLE
U_J_to_radial_integrals for l=1

### ISSUE THREAD

**Issue by Mi-chael** [TRIQS/triqs#455]
Hi, I was curious about the function **U_J_to_radial_integrals** in **pytriqs.operators.util.U_matrix**. It is only implemented for l = 2 and l = 3, so I was wondering if I might be able to extend the definition to l = 1 by calculating F0 and F2 for this case, but the definitions of the Slater-Integrals yield different numbers. Especially they don't yield F0 = U.
Therefore my question is: How where the numbers in U_J_to_radial_integrals calculated?
```
# Convert U,J -> radial integrals F_k
def U_J_to_radial_integrals(l, U_int, J_hund):
    r"""
    Determine the radial integrals F_k from U_int and J_hund.
    Parameters
    ----------
    l : integer
        Angular momentum of shell being treated (l=2 for d shell, l=3 for f shell).
    U_int : scalar
            Value of the screened Hubbard interaction.
    J_hund : scalar
             Value of the Hund's coupling.
    Returns
    -------
    radial_integrals : list
                       Slater integrals [F0,F2,F4,..].
    """

    F = np.zeros((l+1),dtype=float)
    if l == 2:
        F[0] = U_int
        F[1] = J_hund * 14.0 / (1.0 + 0.63)
        F[2] = 0.630 * F[1]
    elif l == 3:
        F[0] = U_int
        F[1] = 6435.0 * J_hund / (286.0 + 195.0 * 451.0 / 675.0 + 250.0 * 1001.0 / 2025.0)
        F[2] = 451.0 * F[1] / 675.0
        F[3] = 1001.0 * F[1] / 2025.0
    else: raise ValueError("U_J_to_radial_integrals: implemented only for l=2,3")

return F
```

Thank you very much,
Michael

**Comment by parcollet** [comment]
Hi, 
Sorry for the late answer, 
the maintainer of this precise file/part has left the field.

@aichhorn 
Markus, can you answer this ?

**Comment by mzingl** [comment]
Hi,
you can find the definition of U and J e.g. in 
[https://arxiv.org/abs/1206.3533 ](url)
or in [volga.eng.yale.edu/sites/default/files/files/UJ-form-of-Vee.pdf](url)
In the latter see page 13. 
For l = 2 I get J = (F2 + F4)/14, like it is implemented in TRIQS.
For l = 1 I obtain J = F2/10.  
U is always F0. 
Is this what you are looking for?

**Comment by Mi-chael** [comment]
Hi,
Thank you very much!
I read the documents and obtain the same results as you. 
As there is no further condition needed to make the l = 1 case bijective I have added it to both U_J_to_radial_integrals and radial_integrals_to_U_J and opened a pull request.
