### ISSUE TITLE
GfImTime product destroys tail expansion

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#460]
A product of two GfImTime objects should be able to determine the tail correction of the corresponding product. Currently the product simply yields an empty tail. Here is a minimal example:

```python
from pytriqs.gf import *

gw = GfImFreq(indices = [1], beta = 50, name='gw')
g2w = GfImFreq(indices = [1], beta = 50, name='g2w')

gw << SemiCircular(half_bandwidth = 1)
print 'gw.tail =', gw.tail, '\n'

g2w << gw * gw
print 'g2w.tail =', g2w.tail
```
which prints the tail of `gw` and then the surprisingly empty tail of `g2w`
```
gw.tail = 
 ...  Order -2 = 
[[(0,0)]]
 ...  Order -1 = 
[[(0,0)]]
 ...  Order 0 = 
[[(0,0)]]
 ...  Order 1 = 
[[(1,0)]]
 ...  Order 2 = 
[[(0,0)]]
 ...  Order 3 = 
[[(0.25,0)]]
 ...  Order 4 = 
[[(0,0)]]
 ...  Order 5 = 
[[(0.125,0)]]
 ...  Order 6 = 
[[(0,0)]] 

g2w.tail = empty tail
```

**Comment by krivenko** [comment]
Hey Hugo,

You are saying there is a problem with `GfImTime`, while your example script is about `GfImFreq`.
Which one do you actually mean?

**Comment by krivenko** [comment]
Check #404 and commit 3ce348e423c76087f03117f28bdea4ccfb2c9387, which fixed it.
So basically any product of GFs will have an empty tail.
