### ISSUE TITLE
[pytriqs/gfs] Gf.name attribute is modified by (certain) stacked operations

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#461]
The `name` attribute of Green's functions are useful to keep track of response functions. However some operations do not preserve the names. 

In particular `g0w << inverse(gw)` sets `g0w.name` using `gw.name`, while the operation `g0w << inverse(iOmega_n - gw)` do not modify `g0w.name`.

I find this behaviour inconsistent, can we decide that `g << [expression]` does *not* modify `g.name`?

Here is the full example:

```python
from pytriqs.gf import *

gw_name = 'gw'
g0w_name = 'g0w'

def get_gfs():
    gw = GfImFreq(indices = [1], beta = 50, name=gw_name)
    g0w = GfImFreq(indices = [1], beta = 50, name=g0w_name)

    g0w << inverse( iOmega_n - 1.0 )
    gw << SemiCircular(half_bandwidth = 1)

    return g0w, gw

def print_name(g0w):
    print 'g0w.name =', g0w.name, '<-- NB! name change' if g0w.name != g0w_name else ''
    print 

# -- 
    
print 'Name from intitalization'
g0w, gw = get_gfs()
print_name(g0w)

print 'Name after single inversion with inverse(gw)'
g0w, gw = get_gfs()
g0w << inverse(gw)
print_name(g0w)

print 'Name after single inversion with inverse(iOmega_n - gw)'
g0w, gw = get_gfs()
g0w << inverse(iOmega_n - gw)
print_name(g0w)

print 'Name after double inversion with inverse( inverse(gw) - iOmega_n )'
g0w, gw = get_gfs()
g0w << inverse( inverse(gw) - iOmega_n )
print_name(g0w)
```
producing
```
Name from intitalization
g0w.name = g0w 

Name after single inversion with inverse(gw)
g0w.name = gw <-- NB! name change

Name after single inversion with inverse(iOmega_n - gw)
g0w.name = g0w 

Name after double inversion with inverse( inverse(gw) - iOmega_n )
g0w.name = gw <-- NB! name change
```

**Comment by krivenko** [comment]
> I find this behaviour inconsistent, can we decide that g << [expression] does not modify g.name

I agree, there should be no change of the name.
Otherwise, it's unclear what to do with expressions like `g0w << inverse(g - delta)`, where `g` and `delta` have different names.

**Comment by parcollet** [comment]
name should simply go.
There is no consistent way to manipulate it without breaking the fact that 
gf is a regular type.
It is only used in the plotting, I think as an internal implementation detail.

@mferrero, @aichhorn: if you do not agree, please object quickly.

**Comment by parcollet** [comment]
Finally : 
- I leave it in python, and fix the plot function
- removed in C++.
- removed from all operations.
Just a little field, in python, which is not changed by anyone.
