### ISSUE TITLE
c++2doc crashes on singleton struct

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#472]
Hi, I am trying to build the documentation of triqs with some new code and `c++2py` breaks down when parsing singleton structs. Here is a minimal example:

```c++
#include <iostream>

namespace foobar {
/// my constant struct
const struct {
  int val = 1337;
} my_struct;
}

int main() {
  using namespace foobar;
  std::cout << my_struct.val << "\n";
  return 0;
}
```
running `c++2doc.py -N foobar example.cpp` crashes when trying to make a new folder for the struct that has an empty typename since it tries to use an empty string as folder name.
```
[cpp2doc_bug_anonstruct] $ c++2doc.py example.cpp -N foobar
Welcome to the C++ doc generator, based on libclang!
Parsing the C++ file (may take a few seconds) ...
... done. 
Extracting ...
Analysing 
... done
functions
classes
class :
  my constant struct


Generating the documentation ...
 ... class foobar::
Traceback (most recent call last):
  File "/Users/hugstr/apps/triqs_devel/bin/c++2doc.py", line 184, in <module>
    mkchdir(c.name)
  File "/Users/hugstr/apps/triqs_devel/bin/c++2doc.py", line 129, in mkchdir
    os.chdir(d)
OSError: [Errno 2] No such file or directory: ''
```

**Comment by parcollet** [comment]
yes it is hard to document a type which has no name indeed...
shall we just ignore them ?

**Comment by HugoStrand** [comment]
Maybe, check that `c.name` for the class found by `clang-lib` is not empty before trying to create the directory, print a warning, and then continue with next class?

I have worked around the problem by not putting any doc tags on my singleton structs.

**Comment by parcollet** [comment]
Fixed in cpp2py
