### ISSUE TITLE
Compiling triqs on a Rocks-6.2

### ISSUE THREAD

**Issue by rhysaph** [TRIQS/triqs#483]
Hi,

I'm building triqs on a Rocks-6.2 cluster which is basically Centos 6.6.

 more /etc/issue
CentOS release 6.6 (Final)

I have finally got the configure stage to complete with the following line:

 env \
PYTHON=/share/apps/bin/python \
CC=/share/apps/bin/gcc \
BOOSTROOT=/share/apps/boost_1_65_1 \
HDF5=/share/apps/hdf5-1.8.18 \
cmake -DCMAKE_INSTALL_PREFIX=/share/apps ../triqs.src

and make falls over around 53% of the way through with the following errors:

[ 53%] Building CXX object test/triqs/utility/CMakeFiles/h5_seria.dir/h5_seria.cpp.o
Linking CXX executable h5_seria
CMakeFiles/h5_seria.dir/h5_seria.cpp.o: In function `triqs::arrays::array<double, 1, void> triqs::h5::deserialize<triqs::arrays::array<double, 1, void> >(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
h5_seria.cpp:(.text._ZN5triqs2h511deserializeINS_6arrays5arrayIdLi1EvEEEET_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5triqs2h511deserializeINS_6arrays5arrayIdLi1EvEEEET_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x5d): undefined reference to `H5P_CLS_FILE_ACCESS_ID_g'
h5_seria.cpp:(.text._ZN5triqs2h511deserializeINS_6arrays5arrayIdLi1EvEEEET_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN5triqs2h511deserializeINS_6arrays5arrayIdLi1EvEEEET_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x95): undefined reference to `H5Pset_file_image'
CMakeFiles/h5_seria.dir/h5_seria.cpp.o: In function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > triqs::h5::serialize<triqs::arrays::array<double, 1, void> >(triqs::arrays::array<double, 1, void> const&)':
h5_seria.cpp:(.text._ZN5triqs2h59serializeINS_6arrays5arrayIdLi1EvEEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN5triqs2h59serializeINS_6arrays5arrayIdLi1EvEEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x1f): undefined reference to `H5P_CLS_FILE_ACCESS_ID_g'
h5_seria.cpp:(.text._ZN5triqs2h59serializeINS_6arrays5arrayIdLi1EvEEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN5triqs2h59serializeINS_6arrays5arrayIdLi1EvEEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x1dc): undefined reference to `H5Fget_file_image'
h5_seria.cpp:(.text._ZN5triqs2h59serializeINS_6arrays5arrayIdLi1EvEEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_[_ZN5triqs2h59serializeINS_6arrays5arrayIdLi1EvEEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKT_]+0x20d): undefined reference to `H5Fget_file_image'
collect2: error: ld returned 1 exit status
make[2]: *** [test/triqs/utility/h5_seria] Error 1
make[1]: *** [test/triqs/utility/CMakeFiles/h5_seria.dir/all] Error 2
make: *** [all] Error 2

Can anyone tell me what I need to do to get triqs to compile.

Thanks,
Rhys Morris
--------------------------------------------
Rhys Morris
Bristol Astrophysics Group 
Room 4.13, HH Wills Physics Lab
University of Bristol
--------------------------------------------

**Comment by krivenko** [comment]
Dear Rhys,

I am not sure that `HDF5` environment variable is recognized by CMake. Try setting `HDF5_ROOT=/share/apps/hdf5-1.8.18 ` instead.
If this does not help, please, post the complete output from CMake.

**Comment by rhysaph** [comment]
Hi Igor,
Yes, that was it. I had also forgotten to delete all the files in triqs.build before running cmake. So my command sequence was:

cd /share/apps/triqs.build
\rm -rf *
env PYTHON=/share/apps/bin/python \
CC=/share/apps/bin/gcc BOOSTROOT=/share/apps/boost_1_65_1 \
HDF5_ROOT=/share/apps/hdf5-1.8.18 \
cmake -DCMAKE_INSTALL_PREFIX=/share/apps ../triqs.src
make
make install

/share/apps is the area of the head node on a Rocks cluster that all the worker nodes can see.

Thanks for your help,
Rhys
