### ISSUE TITLE
triqs

### ISSUE THREAD

**Issue by ghragoozloo** [TRIQS/triqs#487]
Hi all
In triqs code for NiO compound I have the below error when I use This command:"pytriqs tut_dmft-ex1.py"
 mpirun -np 1 pytriqs tut_dmft_ex1.py
 /opt/intel/composer_xe_2013.5.192/mpirt/bin/intel64/mpirun: line 96: /opt/intel/composer_xe_2013.5.192/mpirt/bin/intel64/mpivars.sh: No such file or directory

**Comment by aichhorn** [comment]
I guess you are using the tutorial files from the VICOM winter school...
The error you see is a problem of your mpi installation and has nothing to do with triqs. The error means that mpirun cannot be execute properly. This would happen with any other code you try to run on your MPI system. You need to check your system installation first.

**Comment by Wentzell** [comment]
Yeah this sounds like a broken mpi setup. This is not a triqs issue.

**Comment by ghragoozloo** [comment]
Thankful
