### ISSUE TITLE
run triqs code

### ISSUE THREAD

**Issue by ghragoozloo** [TRIQS/triqs#489]
Hi all 
When I use triqs code for  NiO compound my calculations I need to use "tut-dmft ex1.py" files(TRIQS TUTORIAL VICOM School Vienna Markus Aichhorn February 2017). But I can not find these files. Is there a specific path for finding these files?
Thanks all

**Comment by parcollet** [comment]
This is not an issue with TRIQS library. 
@aichhorn :what is the relevant repository ?

**Comment by aichhorn** [comment]
These files have been distributed in the school, they are not part of any TRIQS repo. If you contact me by email, I can send you the files.

**Comment by ghragoozloo** [comment]
Thankful
