### ISSUE TITLE
Windowing and evaluator_fnt_on_mesh : problem at the edge of the mesh. 

### ISSUE THREAD

**Issue by lmessio** [TRIQS/triqs#49]
Hello,
With a half_bin mesh (as it is the case by default in a imtime Green function), mesh.x_min() is not zero, but it is delta/2.
The windowing function (in meshes/linear.hpp) then says that a point between 0 and delta/2 in not "in" the part of the domain described by the mesh. But even with a modification of this function to have the correct answer (in=true), what value do we choose to give to the evaluated GF at this point ? 
(The same problem occurs at the end of the mesh  for meshk = without_last)

**Comment by parcollet** [comment]
@mferrero : shall we close this now ?
