### ISSUE TITLE
run triqs

### ISSUE THREAD

**Issue by ghragoozloo** [TRIQS/triqs#494]
Hi all 
I am getting a error message  when running the following code in a pytriqs Ce-gamma.py :

[hadi@localhost NiO]$ pytriqs Ce-gamma.py 
Starting on 1 Nodes at : 2017-10-11 02:20:50.794648
Reading input from NiO.ctqmcout...
Reading input from NiO.symqmc...
Reading input from NiO.oubwin...
Reading input from NiO.struct...
Reading input from NiO.outputs...
Dichotomy adjustment of Chemical Potential to obtain Total Density = 13.992000 +/- 0.000001
    Chemical Potential = -0.500000  
    Total Density = 12.871273
    0.000000 < Chemical Potential < -0.500000
    14.077033 < Total Density < 12.871273
    -0.035261 < Chemical Potential < -0.500000
    14.052415 < Total Density < 12.871273
    -0.059032 < Chemical Potential < -0.500000
    14.022850 < Total Density < 12.871273
    -0.070846 < Chemical Potential < -0.500000
    14.003540 < Total Density < 12.871273
    -0.075220 < Chemical Potential < -0.500000
    13.995464 < Total Density < 12.871273
    -0.076528 < Chemical Potential < -0.500000
    13.992940 < Total Density < 12.871273
    -0.076883 < Chemical Potential < -0.500000
    13.992247 < Total Density < 12.871273
    -0.076977 < Chemical Potential < -0.500000
    13.992064 < Total Density < 12.871273
    -0.077001 < Chemical Potential < -0.500000
    13.992017 < Total Density < 12.871273
    -0.077007 < Chemical Potential < -0.500000
    13.992004 < Total Density < 12.871273
    -0.077009 < Chemical Potential < -0.500000
    13.992001 < Total Density < 12.871273
    -0.077009 < Chemical Potential < -0.500000
    13.992000 < Total Density < 12.871273
    Chemical Potential found in 12 iterations : 
    Total Density = 13.992000;Chemical Potential = -0.077009
Traceback (most recent call last):
  File "Ce-gamma.py", line 71, in <module>
    S.G <<= SK.extract_G_loc()[0]
  File "/home/hadi/triqs/install/lib/python2.7/site-packages/pytriqs/gf/local/block_gf.py", line 257, in __ilshift__
    for (i,g) in self: g.copy_from(A[i])
RuntimeError: .. Error occurred at Wed Oct 11 02:21:21 2017

.. Error .. calling C++ overload 
.. copy_from(gf_view<imfreq,matrix_valued,tail> other) -> void 
.. in implementation of method GfImFreq.copy_from
.. C++ error was : 
.. Triqs runtime error at /home/hadi/triqs/triqs.src/triqs/./gfs/./impl/../singularity/tail.hpp : 306

tails are incompatible
.. Error occurred on node 0

 [hadi@localhost NiO]$

**Comment by parcollet** [comment]
What is the difference with #495 ?
Closing.
