### ISSUE TITLE
Non-uniform real-axis meshes

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#50]
Do we have in triqs1.0 any constructor to define a real-axis GF on some arbitrary non-uniform mesh (logarithmic etc.)? 
So far I found only this constructor for MeshGF:

 def __init__(self, double omega_min, double omega_max, int n_max, kind):

from mesh_refreq.pyx

which, I guess, creates a linear mesh within the window. Before, as far as I remember, one could just provide a numpy real array of mesh point positions.

**Comment by parcollet** [comment]
Same as #217
