### ISSUE TITLE
[unstable] Python.h included from first_include.hpp

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#500]
Hi all,

I am trying to reanimate `cthyb` unstable branch after the recent separation of cpp2py. I seem to more or less understand how the new system works, except two things.

* What happened to `$TRIQS_CXX_DEFINITIONS`? Are applications supposed to use their own compilation flags at will?

* I get the following compilation failure
```
In file included from /home/igor/Physics/TRIQS/installed.unstable/include/triqs/mc_tools/mc_generic.hpp:22:0,
                 from /home/igor/Physics/TRIQS/installed.unstable/include/triqs/mc_tools.hpp:24,
                 from /home/igor/Physics/TRIQS/cthyb.git/c++/./solver_core.hpp:23,
                 from /home/igor/Physics/TRIQS/cthyb.git/c++/solver_core.cpp:21:
/home/igor/Physics/TRIQS/installed.unstable/include/triqs/utility/first_include.hpp:62:20: fatal error: Python.h: No such file or directory
```
What is wrong here? I expected all relevant include paths to be pulled in via `triqs` imported target.

**Comment by parcollet** [comment]
Changing the cmake for cthyb is on the todo list, I am working on it,
also to write the changelog .
The bottom line : the cmakelists of triqs now provide a imported target "triqs", it is 
sufficient to link to this target.

**Comment by krivenko** [comment]
Ok, thanks.
A change log or a porting guide would indeed be helpful, as I have to port my other application (pomerol2triqs).

>  The bottom line : the cmakelists of triqs now provide a imported target "triqs", it is
sufficient to link to this target.

If so, the missing include path to `Python.h` must be a bug.
Also, the `triqs` target does not seem to propagate `-std=c++14` and other compile flags.

**Comment by parcollet** [comment]
1- Python.h is included in the dependencies of triqs...
2- std=c++14 is not propagated, since we have c++17 apps here too
and it collides. Each app has to say which standard it uses.
3- More later, I will "port" ctint_demo and cthyb and then 
you can port pomerol2triqs using the changelog (to test it).

**Comment by parcollet** [comment]
cthyb "ported" and pushed on unstable.
ctint_tutorial and a small changelog to follow.

**Comment by parcollet** [comment]
@krivenko : can we close this ?

**Comment by parcollet** [comment]
This is a cthyb issue. Closing. It passes on CI, except one test on naff.
@krivenko @Wentzell 
https://travis-ci.org/TRIQS/cthyb

**Comment by krivenko** [comment]
I still think there is an issue in the library.

In my `CMakeLists.txt` I am trying to link a c++ executable to triqs,
```cmake
target_link_libraries(my_executable PRIVATE triqs)
```
That executable has nothing to do with Python, yet it complains about missing `Python.h` (included from `first_include.hpp`).
The problem is solved if I put
```cmake
find_package(Cpp2Py REQUIRED)
```
in the top-level `CMakeLists.txt`.

Shouldn't the `triqs` target propagate the include path to `Python.h` without me asking for Cpp2Py?

**Comment by parcollet** [comment]
@Wentzell : same pb in ctint

yes it should but this is the reason why find_package triqs 
should automatically import cpp2py:
- triqs depends on imported target python_and_numpy which is defined in cpp2y (where python is   detected), and has the proper include.
- exporting the target, it still depends on python_and_numpy. If not present, it does not complain in running cmake (which is strange)
and  in particular it does NOT replace python_and_numpy by its dependencies, includes ... 
this at the end the include is missing.

Seems to be the proper fix is to find_package (Cpp2py) in triqsConfig.
@Wentzell : opinion ? Can you review this and fix it ?

**Comment by Wentzell** [comment]
We have split the triqs library target into two parts, one called `triqs` and another one called `triqs_py`.
Only the latter one is dependent on Python and provides all the libpython dependent symbols.
This is resolved.
