### ISSUE TITLE
make test det_manipc1 and det_manipc2 failed

### ISSUE THREAD

**Issue by francescopt** [TRIQS/triqs#507]
I am trying to install the TRIQS library on the Jureca supercomputer. As I only need the C++ libraries, I compiled with disabled Python support.
I am using the git commit ```d54b4fb8ca206cb23172e945a6523aa003c9d662```.

These are the libraries/compiler I have used:

- Intel icc 18.0.0

- CMake 3.9.4

- Boost 1.65.1-Python-3.6.3

- GMP 6.1.2

- FFTW 3.3.6

- HDF5 1.8.19-serial

Also, I had to manually specify the location of some headers/libraries, since they were not found by CMake. This is the command line I used for CMake:

```cmake -DCMAKE_C_COMPILER=`which icc` -DCMAKE_CXX_COMPILER=`which icc` -DCMAKE_INSTALL_PREFIX=$HOME/triqs -DPythonSupport=OFF -DFFTW_INCLUDE_DIR=$EBROOTFFTW/include -DFFTW_LIBRARIES=$EBROOTFFTW/lib/libfftw3.so -DGMP_INCLUDE_DIR=$EBROOTGMP/include -DGMP_LIBRARIES=$EBROOTGMP/lib/libgmp.so -DGMPXX_LIBRARIES=$EBROOTGMP/lib/libgmpxx.so ../triqs.src```

The output of cmake is here:

https://gist.github.com/francescopt/ddff096de0d6f58abce676636f876e1f

```make``` was successful, however there were some warnings _warning #1595: non-POD (Plain Old Data) class type passed through ellipsis_ on compiling ```tuple_tools```. The complete output of make is here:

https://gist.github.com/francescopt/29085553d3b08b04f6799cf7f8a510a6

```make test``` reported 2 failed tests: ```det_manipc1``` and ```det_manipc2```. The file ```LastTest.log``` is here:

https://gist.github.com/francescopt/167c36f146b077afdbc0345d17395e64

The file ```CMakeCache.txt`` is here:

https://gist.github.com/francescopt/f56b392b6863c274b4a781e1df404dc7

Edit: added git commit hash

**Comment by parcollet** [comment]
Hi, Sorry to the late answer,
is this still open ? the det_manipc1/2 issue should come from a problem with the Lapack installation.

**Comment by francescopt** [comment]
Hi,
yes the issue is still here. There has been in the meantime an update on the software on Jureca. Now the compiler/libraries version is

- Intel icc 18.0.2
- MKL  2018.2.199
- CMake 3.11.1
- Boost 1.66.0-Python-3.6.5
- GMP 6.1.2
- FFTW 3.3.7
- HDF5 1.8.20-serial

Lapack should be obtained via the intel MKL library.

I get again the same tests failed, and they fail at the same assert with the same output as before.

**Comment by Wentzell** [comment]
We are not supporting ICC as a compiler at this stage.
We cannot reproduce this problem, even with MKL, using clang or gcc.
