### ISSUE TITLE
[unstable][arrays] matrix transpose() + broadcast()

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#508]
The following test fails for me when run on >1 cores.
```c++
TEST(Arrays, transpose_bcast) {

 mpi::communicator world;

 matrix<dcomplex> A = {{1, 2, 3},
                       {4, 5, 6}};
 matrix<dcomplex> At = A.transpose();

 matrix<dcomplex> B;
 if(world.rank() == 0) B = At;

 mpi_broadcast(B, world, 0);

 EXPECT_ARRAY_EQ(At, B);
}
```
(`B` ends up having the same shape as `At`, but different traversal order).

This problem apparently has something to do with  #451.

**Comment by krivenko** [comment]
Ok, I guess I know what's wrong here.

At the point where `mpi_broadcast(B, world, 0)` is called, `B.indexmap()` has different ordering on different MPI ranks.
```
Rank 0:  ordering = {(1 0)}
  Lengths  :  (3 2)
  Stride  : (1 3)
Rank 1:  ordering = {(0 1)}
  Lengths  :  (0 0)
  Stride  : (0 0)
```

`broadcast()` ignores this difference. It first broadcasts the shape and calls `resize()` on the receiving side, which changes lengths but not strides/ordering of the receiving matrix.
https://github.com/TRIQS/triqs/blob/3afd07ff03c263f66eb4f7918b0b365b0d87dfc6/triqs/arrays/impl/indexmap_storage_pair.hpp#L331-L337

Must the entire index map be broadcast for this to work?

@parcollet @Wentzell Could you please have a look at this issue? I'd much appreciate it fixed a.s.a.p.

**Comment by parcollet** [comment]
I guess that MPI is simply not transferring the memory_layout, no ?

**Comment by krivenko** [comment]
> I guess that MPI is simply not transferring the memory_layout, no ?

All it transfers is the shape.

**Comment by parcollet** [comment]
yes, I just checked the code.
