### ISSUE TITLE
Convention used in transformation of second quantized operators?

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#512]
Dear Igor,
Can you document the definition of the transformation matrix used as an input to transform_U_matrix (see https://triqs.ipht.cnrs.fr/1.x/reference/operators/util/U_matrix.html)? (or can you point me to the place where this is documented?)
Thanks!

Thomas

PS: I would have expected something like:
\tilde{a}^dagger_{i,sig} = sum_j a^dagger_{j,sig} T_{ji}
(where \tilde{a} [resp a] stands for the operators in the new [resp old] basis), but it is not the case...

**Comment by krivenko** [comment]
Hi Thomas,

I checked what `transform_U_matrix()` does, and the definition from your postscriptum looks fine to me. Updated docstrings are on `unstable` now.

**Comment by gkraberger** [comment]
Hi Igor & Thomas,

I think the definition should be
``\tilde{c}_i = \sum_j T_{ij}^* c_j``

I wrote it up in Latex (for simplicity without explicit spin):

![\begin{align*} \tilde{c}_i &= \sum_j T_{ij}^* c_j, & \tilde{c}^\dagger_i &= \sum_j T_{ij} c_j^\dagger,\\ c_j &= \sum_i T_{ij} \tilde{c}_i, & c_j^\dagger &= \sum_i T_{ij}^* \tilde{c}_i^\dagger.  \end{align*} The interaction tensor $U$ follows the convention \begin{equation*} H_{int} = \sum_{jlmo} U_{jlmo} c^\dagger_j c^\dagger_l c_o c_m.  \end{equation*} By inserting the transformation, one gets \begin{equation*} H_{int} = \sum_{iknp} \sum_{jlmo} T_{ij}^* T_{kl}^* U_{jlmo} T_{po} T_{nm} \tilde{c}^\dagger_i \tilde{c}^\dagger_k \tilde{c}_p \tilde{c}_n.  \end{equation*} Thus, the transformed interation matrix is \begin{equation*} \tilde{U}_{iknp} = \sum_{jlmo} T_{ij}^* T_{kl}^* U_{jlmo} T_{po} T_{nm}.  \end{equation*} The function \texttt{transform\_U\_matrix} in \texttt{pytriqs.operators.U\_matrix} uses the following line to do the transformation: \begin{quote}{\ttfamily \raggedright \noindent \footnotesize np.einsum("ij,kl,jlmo,mn,op",np.conj(T),np.conj(T),U\_matrix,np.transpose(T),np.transpose(T)) } \end{quote}](https://cloud.tugraz.at/index.php/s/D7dBSA4BcQBrUPn/download)

So, I think my convention is compatible to what the code does. Or is there an error in my reasoning?

Best
Gernot

**Comment by krivenko** [comment]
Thank you, Gernot. Indeed, I forgot to transpose `T` at some point of my derivation.

**Comment by tayral** [comment]
Thanks Gernot and Igor, I agree with the conclusion!
