### ISSUE TITLE
make test can't pass

### ISSUE THREAD

**Issue by bcmaton** [TRIQS/triqs#513]
Dear all,

I met a problem with passing make test. The main issue is due to 

1/188 Testing: algorithms
1/188 Test: algorithms
Command: "/Users/kun/triqs.build/test/triqs/arrays/algorithms"
Directory: /Users/kun/triqs.build/test/triqs/arrays
"algorithms" start time: Nov 19 20:16 EST
Output:
----------------------------------------------------------
dyld: Symbol not found: _PyCObject_Type
  Referenced from: /Users/kun/triqs.build/triqs/libtriqs.dylib
  Expected in: flat namespace
 in /Users/kun/triqs.build/triqs/libtriqs.dylib
<end of output>

All the problem is due to this.  I have no idea the origin of this problem.
I can make install both triqs and cthyb without passing the test.  However, I cannot run solver from cthyb.

Thanks a lot.

**Comment by Wentzell** [comment]
Sounds like a problem with your python setup on your computer.
Most likely it is due to using a Python.h which is incompatible with the libpython.dyld

Check the libpython with ```otool -L /Users/kun/triqs.build/triqs/libtriqs.dylib``` 
To check the python include directory used you could check the verbose output of the make
```bash
cd /Users/kun/triqs.build/test/triqs/arrays
rm algorithms
make algorithms -j1 VERBOSE=1
```

**Comment by bcmaton** [comment]
Wentzell, thanks a lot. I solve the problem with brew install python. It seems that I always fail with anaconda package.
