### ISSUE TITLE
[unstable][doc] triqs_example is broken

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#515]
All uses of `.. triqs_example::` in RST files end up being blank spaces in HTML. It wasn't like this in TRIQS 1.4.

I am using Sphinx 1.6.x.

**Comment by Wentzell** [comment]
@krivenko Do you still observe this behavior? The documentation generation is incorporating the proper example code for me and also for our CI. (Cf. e.g. [arrays/concecpts](https://triqs.github.io/triqs/master/reference/arrays/concepts.html)

**Comment by Wentzell** [comment]
Hey Igor,

Just to confirm, were you using both the very latest cpp2py/master and triqs/unstable?

**Comment by Wentzell** [comment]
> What is the minimum required version of libclang for `unstable`? Mine is 6.0.1.

I guess the libclang version is identical to your llvm/clang install? In that case 6.0.1 should be
absolutely fine.

**Comment by Wentzell** [comment]
So your clang version is also 6.0.1? Can you compile triqs (without doc) using this install llvm or do you run into trouble?

**Comment by Wentzell** [comment]
It is very hard to analyze whats going on as the `TranslationUnitLoadError` seems to have no additional error information whatsoever. Also we can not reproduce this problem on any of our machines.
You could try if updating to the latest llvm stable release which is 7.0.1 (and the corresponding libclang)
resolves the problem for you.

@parcollet Any idea?

**Comment by parcollet** [comment]
Ok, closing.
Anyway, we are going to remove the need of lib clang to build the doc
(by putting the generated rst files in the sources, simply...), so the pb will disappear anyway.
