### ISSUE TITLE
Missing ${TRIQS_LIBRARY_LAPACK} when porting dft_tools/unstable to cpp2py+triqs/unstable

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#519]
Dear @parcollet,

I am trying to port `dft_tools` to `cpp2py` and `triqs/unstable` but I have gotten stuck on getting the lapack libraries from `triqs`. This was previously available in the variable `${TRIQS_LIBRARY_LAPACK}` and is used in `dft_tools` to link som fortran code to Lapack.

Where can I get this information now in the reworked version of `cpp2py+triqs/unstable`?

Best regards,
Hugo

**Comment by HugoStrand** [comment]
In particular I can not link with the exported `triqs` target. Doing so gives the error:
```
gfortran: error: unrecognized command line option '-stdlib=libc++'
```
since the code I am trying to link with is fortran...

**Comment by HugoStrand** [comment]
Would the correct way be to export a `triqs_fortran` target that is stripped of `c++` libraries/flags?

**Comment by HugoStrand** [comment]
This issue is directly connected to the pull request on `dft_tools/unstable`

https://github.com/TRIQS/dft_tools/pull/82

**Comment by parcollet** [comment]
@HugoStrand : is it still open ?
