### ISSUE TITLE
Reading GfImFreq from text file

### ISSUE THREAD

**Issue by DerWeh** [TRIQS/triqs#520]
I would like to import Green's functions produced by a different code into TRIQS (using python). My data is provided in a form `(n, Re(G), Im(G), error Re(G), error Im(G))`, no fitting is done.

While [pytriqs.gf.local.tools](https://triqs.ipht.cnrs.fr/1.x/reference/gfs/py/tools.html) provides functions to write both imaginary and real time Green's functions, the function to read is only provided for `GfReFreq`.

Looking at the code, I would guess it can be done for `GfImFreq` in the same fashion, I just need to provide beta:

```python
def read_gf_from_txt(block_txtfiles, beta, block_name):
    """
    Read a GfImFreq from text files with the format (n, Re(G), Im(G)) for a single block.
    """
    block_txtfiles = np.array(block_txtfiles) # Must be an array to use certain functions
    N1,N2 = block_txtfiles.shape
    mesh = np.genfromtxt(block_txtfiles[0,0], usecols=[0]) # Mesh needs to be the same for all blocks
    g = GfImFreq(indices=range(N1), beta=beta, n_points=len(mesh), name=block_name)
    for i, j in product(range(N1), range(N2)):
        data = np.genfromtxt(block_txtfiles[i,j],usecols=[1,2])
        g.data[:, i, j] = data[:,0] + 1j*data[:,1]
    return g
```

However, in the [reference](https://triqs.ipht.cnrs.fr/1.4/reference/gfs/py/block.html#direct-access-to-data-points-and-tails-not-for-the-legendre-version) it is warned explicitly, that when the data is modified directly the tail must be checked for consistency. To I have to do something here?

When I would like to fit the tail using TRIQS' `pytriqs.gf.local.tools.tail_fit`I would have to just read the data for `Sigma_iw`, `G0_iw` and `G_iw`, right?

**Comment by Wentzell** [comment]
If you want to achieve this goal, please use `np.loadtext` and convert your array into the proper shape
and then assign it to `g.data`. The tail has been removed from the Green function object in the 2.0 release.
