### ISSUE TITLE
[unstable] Boost still depends on std::auto_ptr, which has been removed from C++17

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#523]
All recent versions of Boost, including 1.66 beta 1 make use of now removed `std::auto_ptr`.
```
In file included from /home/igor/Physics/TRIQS/libs/libs.git/triqs/atom_diag/impl/worker.cpp:28:
In file included from /home/igor/Physics/TRIQS/libs/libs.git/triqs/hilbert_space/space_partition.hpp:28:
In file included from /usr/include/boost/pending/disjoint_sets.hpp:15:
In file included from /usr/include/boost/graph/properties.hpp:19:
In file included from /usr/include/boost/property_map/property_map.hpp:601:
In file included from /usr/include/boost/property_map/vector_property_map.hpp:14:
In file included from /usr/include/boost/shared_ptr.hpp:17:
In file included from /usr/include/boost/smart_ptr/shared_ptr.hpp:28:
/usr/include/boost/smart_ptr/detail/shared_count.hpp:402:33: error: no template named 'auto_ptr' in namespace 'std'
    explicit shared_count( std::auto_ptr<Y> & r ): pi_( new sp_counted_impl_p<Y>( r.get() ) )
                           ~~~~~^
```
Compiler: clang 5.0.0 with libcxx 5.0.0 (I cannot use GCC 7 and its standard library).

**Comment by parcollet** [comment]
Hi, 

1- use  -D_LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR
Cf : https://libcxx.llvm.org/docs/UsingLibcxx.html#c-17-specific-configuration-macros

2- We should add this in the cmakeLists for OS X

3- We should get rid of boost ... it duplicates the std lib, and create problem recurrently.
disjoint_set seems to me the only non trivial usage of it in the triqs lib, 
the rest will be cleaned step by step.

**Comment by parcollet** [comment]
@Wentzell : cc

**Comment by parcollet** [comment]
@Wentzell 
2- PS : maybe we should just add it on top of triqs/atom_diag/impl/worker.cpp
#define ....
it is only useful there, no need to pass such a strange option everywhere, it is a local fix.
3- PS : my first goal is to limit boost usage to a few cpp.

**Comment by parcollet** [comment]
PS : 
Still, I do not see the pb on OS X here. Strange.

**Comment by Wentzell** [comment]
I didn't see it either on my Mac. Strange indeed.

2017-12-15 11:04 GMT+01:00 Olivier Parcollet <notifications@github.com>:

**Comment by Wentzell** [comment]
Putting a local define in the worker.cpp seems like a clean fix.

```c++
#define _LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR
```

Igor can you check if that solves your problem?

**Comment by krivenko** [comment]
> #define _LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR
>
> Igor can you check if that solves your problem?

Thank you for the workaround.
I had to add that `#define` to the following files to make the library compile.
```
test/triqs/hilbert_space/space_partition.cpp
test/triqs/operators/operator_test.cpp
triqs/atom_diag/impl/worker.cpp
```
There is at least one example, which also needs fixing, `doc/reference/arrays/IO_0.cpp`. I would probably find more of those if I could compile docs (cpp2doc doesn't like libcxx for some reason, I see https://github.com/TRIQS/triqs/issues/141 again).

**Comment by parcollet** [comment]
Hum, that is a lot of "define".
Shouldn't we rather put it once , e.g. 
in first_include.hpp ?

**Comment by parcollet** [comment]
If I put it on my Mac, it does *not* compile...
@HugoStrand @Wentzell  : what is the status of this ?

**Comment by Wentzell** [comment]
This is indeed quite strange.
I tried on my mac with clang 5.0.1 and libc++ and I cannot reproduce the problem when compiling triqs.

In fact, adding
```c++
#define _LIBCPP_ENABLE_CXX17_REMOVED_AUTO_PTR
```
to ```first_include.hpp``` leads to exactly the aforementioned error in the first place.

@krivenko Could you please try to add 
```c++
#define BOOST_NO_AUTO_PTR
```
to ```first_include.hpp``` instead.

**Comment by parcollet** [comment]
Yes, I had the same pb as Nils.

**Comment by krivenko** [comment]
@Wentzell Yes, `BOOST_NO_AUTO_PTR` does fix compilation for me.

**Comment by dylex** [comment]
I had the same problem on the build machine a while ago, and it turned out to be due to boost's config stdlib autodetection not using the right set of system header files.  I believe adding `CXXFLAGS=-I/usr/local/opt/llvm/include LDFLAGS=-L/usr/local/opt/llvm/lib` to the environment fixed it.
