### ISSUE TITLE
Speed comparison to Eigen

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#525]
Dear developers,
Fyi, here is a small speed comparison of matrix multiplication with TRIQS and Eigen 
[benchmark.cpp.txt](https://github.com/TRIQS/triqs/files/1612991/benchmark.cpp.txt) (this code compiles with the current master branch). As you can see, TRIQS is faster by a factor 5-6:

Matrices de taille 50 / Moyenne sur 160000 itérations
     Temps moyen pour Eigen : 0.000107116 secondes.
     Temps moyen pour TRIQS : 1.25404e-05 secondes.

Matrices de taille 500 / Moyenne sur 400 itérations
     Temps moyen pour Eigen : 0.0988922 secondes.
     Temps moyen pour TRIQS : 0.0179787 secondes.

Matrices de taille 5000 / Moyenne sur 1 itérations
     Temps moyen pour Eigen : 96.484 secondes.
     Temps moyen pour TRIQS : 17.2765 secondes.

At some point it would be nice to document this somewhere, and understand the difference in speed (I did not carry out these runs, and could not check if Eigen uses lapack as it should... but in principle both should and the performances should therefore by equivalent... unless I am missing something?).
Best,
Thomas

**Comment by HugoStrand** [comment]
Dear Thomas,

By default Eigen uses its own kernels for linear algebra operations. To get Eigen to call BLAS/LAPACK you have to set some defines at compile time, see

https://eigen.tuxfamily.org/dox/TopicUsingBlasLapack.html

The difference you see is the difference between Eigen's own matrix-matrix multiplication "kernel" and your BLAS library (used by Triqs).

Cheers, Hugo

**Comment by TimGdB** [comment]
Hello,

Actually the code is timing complex double matrix multiplication with Eigen and double matrix multiplication with TRIQS. If I add random imaginary part to TRIQS matrices I have the following run : 

Matrices de taille 50 / Moyenne sur 160000 itérations
    Temps moyen pour Eigen : 0.000108285 secondes. 
    Temps moyen pour TRIQS : 0.000127884 secondes. 

Matrices de taille 500 / Moyenne sur 400 itérations
    Temps moyen pour Eigen : 0.0995539 secondes. 
    Temps moyen pour TRIQS : 0.10471 secondes. 

Matrices de taille 5000 / Moyenne sur 1 itérations
    Temps moyen pour Eigen : 97.1202 secondes. 
    Temps moyen pour TRIQS : 100.023 secondes.

Here both times are very close, as expected !

Best regards,
Timothée

**Comment by parcollet** [comment]
No issue here. Closing.
