### ISSUE TITLE
Hd5f storage scheme tag changed for Operators from "Operator" to "Operators"

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#539]
The commit 4c5b76344dab6a15b94ea55dd643d65fe02c1ef6 breaks backwards compatibility with all previous storage of operators by changing the hdf5 tag for the Operator class. Nils can you revert this change?
```c++
 inline std::string get_triqs_hdf5_data_scheme(many_body_operator const&) { return "Operator"; }
```
was changed to 
```c++
static std::string hdf5_scheme() {return  "Operators";}
```
This breaks all my tests with reference operators stored in hdf5.

please fix.

**Comment by Wentzell** [comment]
Fixed in da793fbdb2cd9375cfd184631751bcb091b0b841
