### ISSUE TITLE
g_k_tail still stuck in infinite loop in Debug mode with -O0 on gcc7.2

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#540]
the `g_k_tail` test does not pass when compiling triqs in `Debug` mode without optimization `-O0` using `gcc7.2` the test seems stuck in an infinite loop.

Olivier, can you reproduce this?

**Comment by parcollet** [comment]
Are you sure it is not just very long with O0 ?
Reduce the parameters in the test and retry ...

**Comment by HugoStrand** [comment]
Good point, I will try that now.

**Comment by HugoStrand** [comment]
Thank you for the comment. That was of course the problem. Thank you.
