### ISSUE TITLE
Closest_mesh_pt for real-time Green's functions

### ISSUE THREAD

**Issue by amoutenet** [TRIQS/triqs#545]
Hi all,

It appears that the closest_mesh_pt function hasn't been implemented for real-time Green's functions. Would it be possible to have it?

Cheers,
Alice

**Comment by Wentzell** [comment]
Indeed, that should work! To be looked into.

**Comment by amoutenet** [comment]
@parcollet Can we close the issue?

**Comment by Wentzell** [comment]
@parcollet Is this fixed with 1df5a538 ?

**Comment by parcollet** [comment]
Really ? Was it implemented and tested ?

**Comment by amoutenet** [comment]
Sure it was implementing I’m using it!

Le mer. 6 juin 2018 à 10:16, Olivier Parcollet <notifications@github.com> a
écrit :

**Comment by Wentzell** [comment]
I even mentioned the explicit commit number above ... 

1df5a53
