### ISSUE TITLE
LS coupling operator incorrect?

### ISSUE THREAD

**Issue by j-otsuki** [TRIQS/triqs#547]
Dear TRIQS team,

It seems that the spin-orbit coupling operator in pytriqs is incorrect.

The LS coupling term is actually a one-body operator, namely, linear combination of ``C^+(a)C(b)``, but the ``LS_op`` in pytriqs includes two-body operators such as ``C^+(u,0)C^+(u,1)C(u,1)C(d,1)``.
See the following test script and the result
```
$ cat ls_coupling.py
from pytriqs.operators.util.observables import LS_op
l=1
spin_names = ("u", "d")
orb_names = range(-l, l+1)
ls = LS_op(spin_names, orb_names, off_diag=True, basis = 'spherical')
print ls

$ pytriqs ls_coupling.py
0.5*C^+(d,-1)C(d,-1) + 0.707107*C^+(d,0)C(u,-1) + 0.707107*C^+(d,1)C(u,0) + -0.5*C^+(d,1)C(d,1) + -0.5*C^+(u,-1)C(u,-1) + 0.707107*C^+(u,-1)C(d,0) + 0.707107*C^+(u,0)C(d,1) + 0.5*C^+(u,1)C(u,1) + -0.707107*C^+(d,-1)C^+(d,0)C(u,-1)C(d,-1) + 0.5*C^+(d,-1)C^+(d,0)C(d,0)C(d,-1) + -0.707107*C^+(d,-1)C^+(d,1)C(u,-1)C(d,0) + -0.707107*C^+(d,-1)C^+(u,-1)C(d,0)C(d,-1) + -0.5*C^+(d,-1)C^+(u,0)C(u,0)C(d,-1) + -1*C^+(d,-1)C^+(u,1)C(u,1)C(d,-1) + 0.707107*C^+(d,-1)C^+(u,1)C(u,0)C(u,-1) + 0.707107*C^+(d,-1)C^+(u,1)C(d,1)C(d,0) + 0.707107*C^+(d,0)C^+(d,1)C(u,1)C(d,-1) + -0.707107*C^+(d,0)C^+(d,1)C(u,0)C(d,0) + -0.5*C^+(d,0)C^+(d,1)C(d,1)C(d,0) + 0.5*C^+(d,0)C^+(u,-1)C(u,-1)C(d,0) + -0.707107*C^+(d,0)C^+(u,-1)C(d,1)C(d,-1) + -0.707107*C^+(d,0)C^+(u,0)C(u,0)C(u,-1) + -0.707107*C^+(d,0)C^+(u,0)C(d,1)C(d,0) + -0.5*C^+(d,0)C^+(u,1)C(u,1)C(d,0) + 1*C^+(d,1)C^+(u,-1)C(u,-1)C(d,1) + -0.707107*C^+(d,1)C^+(u,0)C(u,1)C(u,-1) + 0.5*C^+(d,1)C^+(u,0)C(u,0)C(d,1) + -0.707107*C^+(d,1)C^+(u,1)C(u,1)C(u,0) + 0.707107*C^+(u,-1)C^+(u,0)C(u,1)C(d,-1) + -0.5*C^+(u,-1)C^+(u,0)C(u,0)C(u,-1) + -0.707107*C^+(u,-1)C^+(u,0)C(u,0)C(d,0) + -0.707107*C^+(u,-1)C^+(u,1)C(u,0)C(d,1) + 0.5*C^+(u,0)C^+(u,1)C(u,1)C(u,0) + -0.707107*C^+(u,0)C^+(u,1)C(u,1)C(d,1)
```

The reason is that the LS coupling is implemented by the product of S op and L op.
https://triqs.ipht.cnrs.fr/1.4/_modules/pytriqs/operators/util/observables.html#LS_op
This evaluation is something like
```
C^+(s1,m3) S_matrix(s1,s2) C(s2,m3) * C^+(s3,m1) L_matrix(m1,m2) C(s2,m2)
```
(take contraction over the same indices)
Actually, we have to construct it in the way like
```
C^+(s1,m1) S_matrix(s1,s2) L_matrix(m1,m2) C(s2,m2)
```

Please check it.

Best,
Junya Otsuki

**Comment by RobertTriebl** [comment]
Dear Mr. Otsuki, 

You are right that the LS operator as implemented has two-body contributions. It is actually the operator of the Russell-Saunders Coupling (LS coupling), the single-electron spin-orbit operator ls is not implemented yet. 
The spin-orbit operator is a one particle term, as you highlighted. In a many body picture the full operator is thus sum_i l_i s_i, where the sum is over all electrons. For small spin-orbit couplings it can be approximated by c*LS, where L = sum_i l_i is the total orbital angular momentum, S =  sum_i s_i the total spin, and c a constant that depends on the filling.  
Thus, for small spin-orbit couplings the full Triqs LS operator can be used as an approximation. If you take only the one particle contributions of the Triqs LS, it should give the correct ls operator, though. So far, users implemented an ls term on their own, but in the future an implementation of the one-particle spin-orbit coupling would be nice for completeness.
 
Note that if you add a ls term to the local Hamiltonian with a diagonal hybridization, the CTHYB result will be wrong because it expands in hybridization. This of course only applies if you intend to use CYHYB. 

Best regards, 
Robert Triebl

**Comment by j-otsuki** [comment]
Dear Robert Triebl,

thank you for your reply.
Okay, I understand that two-body LS coupling is implemented (on purpose) and one-body ls coupling is not. I was confused because the manual just says "spin-orbital coupling".
I'll implement the ls coupling by my own if needed. 

Best,
Junya Otsuki

**Comment by krivenko** [comment]
Dear Junya,

I basically agree with Robert. Terms "Russell-Saunders Coupling", "LS coupling" and "spin-orbit coupling" are often used interchangeably (https://en.wikipedia.org/wiki/Term_symbol). `LS_op()` returns the many-electron version of the coupling operator (the Russell-Saunders coupling) in full agreement with the documentation comment attached to it.

I do not think that changing behavior of `LS_op()` is a good idea. It would certainly catch current users of this function by surprise.

On the other hand, it totally makes sense to have the single-particle version in the library too (`ls_op()` would be a good name, I guess).

Cheers,
Igor

**Comment by j-otsuki** [comment]
Thank you, Igor, for your comment.

Actually, I already implemented ls_op() for myself, by copying some part from the pytriqs library. I paste it below for somebody who are interested in. I'm not sure if I should submit PR because existing functions need to be modified (to avoid duplication of, e.g., construction of L matrix). It would be too much modifications beyond PR.

Best,
Junya

------
one-body spin-orbit coupling operator

```
import numpy as np
from pytriqs.operators.operators import Operator, n, c_dag, c
from pytriqs.operators.util.op_struct import get_mkind
from pytriqs.operators.util.U_matrix import spherical_to_cubic
from itertools import product

def ls_op(spin_names, orb_names, off_diag = None, map_operator_structure = None, basis='spherical', T=None):
    """one-body spin-orbit coupling operator"""

    spin_range = range(len(spin_names))

    l = (len(orb_names)-1)/2.0
    orb_range = range(int(2*l+1))

    pauli_matrix = {'x' : np.array([[0,1],[1,0]]),
                    'y' : np.array([[0,-1j],[1j,0]]),
                    'z' : np.array([[1,0],[0,-1]]),
                    '+' : np.array([[0,2],[0,0]]),
                    '-' : np.array([[0,0],[2,0]])}

    L_melem_dict = {'z' : lambda m,mp: m if np.isclose(m,mp) else 0,
                    '+' : lambda m,mp: np.sqrt(l*(l+1)-mp*(mp+1)) if np.isclose(m,mp+1) else 0,
                    '-' : lambda m,mp: np.sqrt(l*(l+1)-mp*(mp-1)) if np.isclose(m,mp-1) else 0,
                    'x' : lambda m,mp: 0.5*(L_melem_dict['+'](m,mp) + L_melem_dict['-'](m,mp)),
                    'y' : lambda m,mp: -0.5j*(L_melem_dict['+'](m,mp) - L_melem_dict['-'](m,mp))}

    # define S matrix
    S_matrix = {}
    for component in ['z', '+', '-']:
        pm = pauli_matrix[component]
        S_matrix[component] = np.array([[ 0.5*pm[n1,n2] for n2 in spin_range ] for n1 in spin_range ])

    # define L matrix
    L_matrix = {}
    for component in ['z', '+', '-']:
        L_melem = L_melem_dict[component]
        L_matrix[component] = np.array([[L_melem(o1-l,o2-l) for o2 in orb_range] for o1 in orb_range])

        # Transform from spherical basis if needed
        if basis == "cubic":
            if not np.isclose(np.mod(l,1),0):
                raise ValueError("L_op: cubic basis is only defined for the integer orbital momenta.")
            T = spherical_to_cubic(l)
        if basis == "other" and T is None: raise ValueError("L_op: provide T for other bases.")
        if T is not None: L_matrix = np.einsum("ij,jk,kl",np.conj(T),L_matrix,np.transpose(T))

    # LS_matrix[n1,n2,o1,o2] = sum_x S_matrix[x][n1,n2] * L_matrix[x][o1,o2]
    LS_matrix = np.einsum("ij,kl", S_matrix['z'], L_matrix['z'])\
              + np.einsum("ij,kl", S_matrix['+'], L_matrix['-']) * 0.5\
              + np.einsum("ij,kl", S_matrix['-'], L_matrix['+']) * 0.5

    mkind  = get_mkind(off_diag,map_operator_structure)
    ls = Operator()
    for n1, n2 in product(spin_range,spin_range):
        for o1, o2 in product(orb_range,orb_range):
            ls += c_dag(*mkind(spin_names[n1],orb_names[o1])) * LS_matrix[n1,n2,o1,o2] * c(*mkind(spin_names[n2],orb_names[o2]))
    return ls
```

**Comment by gkraberger** [comment]
Hi everyone,

another possibility would be to provide a function ``quadratic_part``, in analogy to ``diagonal_part``, that extracts the one-particle part of an Operator.

Like this:

```
from pytriqs.operators import *
import operator

def quadratic_part(H):
    r"""
    Extract the quadratic part from an operator H.

    The quadratic part is a sum of all those monomials of H that are
    products of two creation/annihilation operators. 

    Parameters
    ----------
    H : Operator
        The operator from which the quadratic part is extracted.

    Returns
    -------
    q_part : Operator
             The quadratic part of H.
    """
    q_part = Operator()
    for indices, coeff in H:
        if len(indices) > 2: continue
        q_part += coeff * reduce(operator.mul,
                          map(lambda (dag,ind): c_dag(*ind) if dag else c(*ind),indices),
                          Operator(1))
    return q_part
```

I tested it quickly and it seems to work.

With this, we would not need to provide different versions for ``L2``, ``S2`` and ``LS``, and that function might come in handy anyway.

Best
Gernot
