### ISSUE TITLE
Wrapping histograms and calling hist.data crashes in python

### ISSUE THREAD

**Issue by amoutenet** [TRIQS/triqs#552]
Hi all,

I'm using the unstable branch and trying to wrap histogram in Python. It does work, but when I'm calling .data **twice** on my histogram, it crashes. 
I reproduced the bug with a minimal example.

_The class in c++: (solver_core.hpp)_
```c++
#include <triqs/statistics/histograms.hpp>
class solver_core {
 public:
 triqs::statistics::histogram times_histogram;
 solver_core(): times_histogram{0,1,10} {}
};
```

_The CMakeLists.txt:_
```cmake
set (Test_VERSION "1.5")
cmake_minimum_required(VERSION 2.8)
find_package(TRIQS 1.5 EXACT REQUIRED)
find_package(Cpp2Py REQUIRED)
add_cpp2py_module(solver_core solver_core.hpp)
target_link_libraries(solver_core PUBLIC triqs)
target_compile_options(solver_core PUBLIC -std=c++17)
target_include_directories(solver_core PRIVATE ${CMAKE_SOURCE_DIR})
```

And then , after wrapping, if I do in python:
```python
from solver_core import *
S = SolverCore()
S.times_histogram.data
S.times_histogram.data
```

The first call works well, and the second call crashes, with the following error message:
```
terminate called after throwing an instance of 'triqs::runtime_error'
  what():  .. Triqs runtime error at /mnt/home/alice.moutenet/triqs/triqs.src/triqs/arrays/impl/indexmap_storage_pair.hpp : 178

Error : trying to return an empty array/matrix/vector to python
.. Error occurred on node 
Aborted (core dumped)
```

It looks to me that the first call to .data empties the histogram when returning it.

Best,
Alice

**Comment by Wentzell** [comment]
This is indeed a serious problem. 
I observe a similar behavior when wrapping a member of type 
```
triqs::operators::many_body_operator
```

**Comment by amoutenet** [comment]
Hi Nils and Olivier,
The same problem appears when @mferrero  tries to wrap the atom diag class in python (currently critical in the NCA project). Any news on where this could come from?

**Comment by amoutenet** [comment]
Yes it seems to have fixed it, thanks a lot Nils!
@mferrero does it also solve your atom_diag wrapping problem?

**Comment by Wentzell** [comment]
> Yes it seems to have fixed it, thanks a lot Nils!

Great! I am closing this issue.

@mferrero Reopen if needed
