### ISSUE TITLE
Problem with $ make

### ISSUE THREAD

**Issue by qa11** [TRIQS/triqs#56]
Dear All,

I have encountered this problem after performing 
$ cmake -DCMAKE_INSTALL_PREFIX=path_to_install_directory ../src successfully.

$ make throws the following result after [ 10%] Building CXX object triqs/CMakeFiles/triqs.dir/lattice/tight_binding.cpp.o

Linking CXX shared library libtriqs.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(mapflags.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libfftw3.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[2]: **\* [triqs/libtriqs.so] Error 1
make[1]: **\* [triqs/CMakeFiles/triqs.dir/all] Error 2
make: **\* [all] Error 2

Could anyone please tell me where I am going wrong?

**Comment by JATIN199604** [comment]
Dear qa11 i am Jatin.
I am installing TRIQS as an interface to WIEN2k . I am also getting the same error during make  can you say how should i solve it.  I am showing my error here .
jatin@jatin-HP-Laptop-14s-cr1xxx:~/DMFT/triqs.build$ make
[  1%] Built target cpp2py
[  2%] Built target gtest
[  3%] Linking CXX shared library libtriqs.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
triqs/CMakeFiles/triqs.dir/build.make:1044: recipe for target 'triqs/libtriqs.so' failed
make[2]: *** [triqs/libtriqs.so] Error 1
CMakeFiles/Makefile2:339: recipe for target 'triqs/CMakeFiles/triqs.dir/all' failed
make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2





> Dear Andrey,
> 
> I seem to have successfully installed triqs now. You were correct in saying that make distclean only cleans the directory. So i did what was suggested on http://englanders.us/~jason/howtos.php?howto=fftw
> 
> Basically removed fftw.
> 
> After removing fftw, I did cmake, then make, make test and make installed. All seems to have been done successfully.
> 
> Is there a test suite that I can run (which generates data and plot) which may then indicate that: yes, all libraries are indeed working?
> 
> I am really thankful to Olivier and Andrey! Thank you
