### ISSUE TITLE
Feature Request: MPI parallel loops over gf_meshes

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#562]
Dear All,

I would like to distribute a gf_mesh-loop, in particular `gf_mesh<brillouin_zone>` over MPI-ranks. This would enable me to make larger response function calculations in `tprf`.

In pseudo code I want to be able to write
```c++
for( auto const &k : mpi_distribute_mesh(kmesh) ) {
 G[k] += (... long calculation ...);
}
```
I think this could be achieved by writing a new `mesh_point_generator` class that is MPI "aware".

Any opinions?

Best regards,
Hugo

**Comment by parcollet** [comment]
Do you want 
1) to have the same data on each nodes and just iterate on a portion on each node ?
2) share/distribute (??) the data between the nodes ? (i.e. have only a piece on each node ?).
(e.g. share a big vertex on multiple nodes ?).

If 1), indeed, specially if mesh_point iterators are random access, it looks a priori easy to 
make a mpi_xxx function ?

There was an attempt to have a "windowing" on the imfreq  mesh for 2), but it was never really used or documented. But here also, it should probably be done at higher level, not inside the mesh.

**Comment by Wentzell** [comment]
This was now implemented. C.f. https://github.com/TRIQS/mpi/blob/unstable/test/c%2B%2B/mpi_chunk.cpp
