### ISSUE TITLE
cpp2py not found during installation [unstable,new_tail]

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#564]
Hi,
I am trying to install the unstable (or new_tail) branch. First I got the following error during the initialization:

>   Could not find a package configuration file provided by "Cpp2Py" (requested
>   version 1.5) with any of the following names:
> 
>     Cpp2PyConfig.cmake
>     cpp2py-config.cmake
> 
>   Add the installation prefix of "Cpp2Py" to CMAKE_PREFIX_PATH or set
>   "Cpp2Py_DIR" to a directory containing one of the above files.  If "Cpp2Py"
>   provides a separate development package or SDK, be sure it has been
>   installed.

I download and installed cpp2py and added 
-DCpp2Py_DIR=/.../cpp2py/install/share/cmake
 to the initialization, as Cpp2PyConfig.cmake is found in /.../cpp2py/install/share/cmake 

then the initialization passes but then it crushes on compilation with the error

> /home/leonid/TRIQS1.4_unst/triqs/src/triqs/gfs/transform/../.././gfs/../utility/first_include.hpp:23:10: fatal error: cpp2py.hpp: No such file or directory
>  #include <cpp2py.hpp>

How to tell it where the cpp2py is?

**Comment by mferrero** [comment]
Hi Leonid. In the folder where you installed cpp2py, there is a file share/cpp2pyvars.sh. You should source this file. It then sets a number of environment variables that will ensure that cmake and the compiler will find the necessary files.

**Comment by leopo** [comment]
Thanks, Michel, it worked!
