### ISSUE TITLE
Many_body operators with generic fields

### ISSUE THREAD

**Issue by francescopt** [TRIQS/triqs#567]
I am trying to use the c++ ```many_body_operator_generic``` class with a user-defined ```ScalarType```. Specifically, I am using the GiNaC library to have a symbolic ```ScalarType```, but the issue I found is more general. It appears that in some parts the code assumes that the identity elements of ```ScalarType``` is (possibly automatically) converted from the numerical value 1.0. For example, around line 155 of many_body_operator.hpp, method ```make_canonical``` :

```
   auto m = monomial_t{canonical_ops_t{is_dag, indices}};
   res.monomials.insert({m, scalar_t(1.0)});
   return res;
```

If my ```ScalarType``` is a class for rational number, the above code may not work at all (because it cannot convert a floating number to an exact fraction), or it may "degrade" the coefficients to a floating point number (if ```ScalarType``` is allowed to be either an exact rational or a floating point number).

Similar issues are found in imperative_operator.hpp, around line 223

```
#ifdef GCC_BUG_41933_WORKAROUND
    target_st(ind) += amplitude * apply_if_possible(M.coeff,args_tuple) * (sign_is_minus ? -1.0 : 1.0);
#else
    target_st(ind) += amplitude * apply_if_possible(M.coeff,args...) * (sign_is_minus ? -1.0 : 1.0);
#endif
```

and in space_partition.hpp on lines 74, 116

```
tmp_state(i) = amplitude_t(1.0);
```

and on line 225

```
initial_state(i) = amplitude_t(1.0);
```

I think a safer solution would be to replace everywhere the ```1.0``` with ```ScalarType(1)```, or, better, with the specific type-alias of the class, say, ```scalar_t(1)``` for the method ```make_canonical```, etc...

**Comment by krivenko** [comment]
Dear Francesco,

Thank you for the good point. I actually had muParser, GiNaC and similar libraries in mind and tried to keep `many_body_operator_generic` generic indeed. I agree, `scalar_t(1)` would make more sense.
