### ISSUE TITLE
[gcc] Compilation with gcc 8.1 fails due to updates in `math.h`

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#570]
gcc 8.1 currently fails to compile triqs/unstable

The problem is a change in the 'math.h' header (compare [old](https://gcc.gnu.org/onlinedocs/gcc-7.3.0/libstdc++/api/a00011_source.html) vs [new](https://gcc.gnu.org/onlinedocs/gcc-8.1.0/libstdc++/api/a00011_source.html))..

By changing from

```c++
#if __STDCPP_WANT_MATH_SPEC_FUNCS__ == 1
```

to 
```c++
#if _GLIBCXX_USE_STD_SPEC_FUNCS
```

all the math special functions, including ```std::beta```, ```std::legendre``` and others, are moved up into the global namespace when you compile in c++17 mode. This is problematic for any physics c++ code I guess.

This leads to name collisions in multiple files. This minimal example summarizes the problem: [click](https://godbolt.org/g/zii9md)

This means we have to hide any `math.h` header inclusions in cpp files (`<cmath>` seems to be _mostly_ fine in that regard). The current origins are inclusion via `clef/adapters/math.hpp` `mc_tools/mc_generic.hpp` and `mc_tools/random_generator.hpp`, which is easily fixed, but also via  `Python.h`. In the long run, the `Python.h` should be buried in the cpp files.

**Comment by parcollet** [comment]
There is no way to fix that quickly.
It will be fixed with the "nda" branch, cleaning the array class and its inclusion of Python.

**Comment by Wentzell** [comment]
Ok this issue is finally resolved on triqs/unstable!
