### ISSUE TITLE
h5py: Future warning, conversion from float to np.floating is deprecated

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#576]
Dear all,

I have been seeing this deprecation warning from `h5py` for a while now, and now it also appears in the tutorials when importing anything from `pytriqs`.
```
/soft/public_soft/python-2.7.15/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning:
Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. 
In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```
Can this be fixed?

Best, Hugo

**Comment by Wentzell** [comment]
This disappears for h5py versions >= 2.8.0
Cf. the [related h5py issue](https://github.com/h5py/h5py/issues/961)
