### ISSUE TITLE
oplot: UserWarning no name provided

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#577]
Dear all,

The `oplot` command currently produces a warning whenever a greens function object without an explicitly set name is plotted. E.g. the code from the Green's function tutorial:
```python
# Define g and fill it
g = GfImFreq(indices=[0], beta=10) # default: for fermions
g << inverse(iOmega_n - 0.2)

# Plot the Green's function
oplot(g, '-o')
plt.xlim(0,10)
```
Produces the warning:
```
/soft/public_soft/triqs/lib/python2.7/site-packages/pytriqs/gf/plot/plot_base.py:44: UserWarning: oplot of gf : no name provided !
  warn("oplot of gf : no name provided !")
```

Can we change the default behaviour of `oplot` to not produce an error and not attempt to add any y-label (and labels to the legend unless explicitly provided) if the name of the Green's function is `None`?

Best regards,
Hugo

**Comment by Wentzell** [comment]
Fixed
