### ISSUE TITLE
oplot: label keyword argument only modifies the label for the Real part

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#578]
Dear all,

When supplying a `label` keyword to `oplot` for an Matsubara Green's function only the label for the real part (not the imaginary) part is modified. See below for a screenshot from the tutorials.

Can this be modified so that the `label` keyword affects all labels?

Best regards,
Hugo

<img width="737" alt="oplot_label_bug" src="https://user-images.githubusercontent.com/1188035/40689585-ccf85270-6370-11e8-8d60-1c2424c16f7e.png">

**Comment by Wentzell** [comment]
This was fixed by 977f38662
