### ISSUE TITLE
Document OMP_THREAD for LAPACK

### ISSUE THREAD

**Issue by sabrygad** [TRIQS/triqs#579]
Dear Experts;

We have been struggling building TRIQS on our SLURM-based cluster (www.buffalo.edu/ccr.html). Below are the steps we used, using Intel-MPI.

# Preliminary Setup
  module load python/anaconda-5.0.1 cmake boost mkl intel-mpi gcc/7.2.0
  conda create -n dft python=2 numpy scipy matplotlib tornado mako jinja2 pyzmq h5py mpi4py
  source activate dft

# TRIQS Installation
  git clone https://github.com/TRIQS/triqs
  git checkout 1.4.1
  sed -i '43s/${MKL_PATH_WITH_PREFIX}/"${MKL_PATH_WITH_PREFIX}"/' cmake/FindLapack.cmake
  cd /projects/academic/kofke/software/TRIQS/triqsbuild
  CC=gcc CXX=g++ CFLAGS=-pthread cmake -DPTYHON_LIBRARY=/user/sabrygad/.conda/envs/dft/lib/libpython2.7.so ../triqs
  make -j12
  make test
  make install

The  "sed -i" line is there because we believe there should be double quotes around MKL_PATH_WITH_PREFIX. Let me know if I am wrong?

We then did similar steps with CTHYB and DFTTools. I ran some LDA+DMFT runs and it worked, however we found strange behaviour: the code slows down (5-10x) once we use more than one core. The CPU time should be roughly independent on number of cores, as each one is doing separate CTHYB QMC simulation. We also tried installing with Open-MPI, and did not work as well.
 

So, was wondering if someone can guide me on how to install it probably on SLURM cluster, it would be so much appreciated.

Thanks;
Sabry

**Comment by sabrygad** [comment]
... we also found that with using N nodes the code is still as fast as the 1 node & 1 core case only when setting number of cores to be one, "ntasks-per-node=1". This is not practical because we ask normally for >200 cores each job; so not practical to ask for 200 nodes!

**Comment by parcollet** [comment]
I would guess that your LAPACK is threaded, so each cores runs 
multiple thread. 
It is a common issue and can be hard to find.
Check this flag in the ENV variables.

@amoutenet : can you give us the proper command and add it to the doc ?

**Comment by the-hampel** [comment]
Hi, 
Sry I did not noticed this thread until now. I am running on SLURM as well and had a similar problem. I checked and indeed for example the chemical potential function spawned openMP threads in default behavior. To fix this I just set in my job file right before the srun command the following variable: 
`export OMP_NUM_THREADS=1`
this fixed the issue for me. 

Best,
Alex

**Comment by Wentzell** [comment]
We have added a section in the documentation that addresses this. See [here](https://triqs.github.io/triqs/unstable/installation/environment_vars.html#environment-variables-affecting-openmp).
