### ISSUE TITLE
h5_write for a result of partial_eval or curry

### ISSUE THREAD

**Issue by lmessio** [TRIQS/triqs#58]
Hello, 

To visualize 2 times GF's in a ipython notebook, I need to save slices of them in my c++ code and then import them in python from h5 files. A home-made slice function works, but the result of the partial_eval or curry functions from the lib does not work. 

A simple example : by adding these two lines at the end of the test file gfs/curry1.cpp
 h5_write(file, "g_w_wn1", G_w_wn_sl0_a);
 h5_write(file, "g_w_wn2", G_w_wn_curry0[8]);

I get 

 Triqs runtime error at /users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/triqs/arrays/h5/simple_read_write.hpp : 42

 Trace is :

 ./curry1 H5::DataSpace triqs::arrays::h5_impl::data_space<triqs::arrays::array_view<long, 2, 0ull, 0ull, false, true> >(triqs::arrays::array_view<long, 2, 0ull, 0ull, false, true> const&) 0x2b6 [0x42f816]
 ./curry1 void triqs::arrays::h5_impl::write_array_impl<long, 2>(triqs::h5::group, std::string const&, triqs::arrays::array_view<long, 2, 0ull, 0ull, false, true>, bool) 0x19b [0x42d7bb]
 ./curry1 void triqs::arrays::h5_impl::write_array_impl<long, 2>(triqs::h5::group, std::string const&, triqs::arrays::array_view<long, 2, 0ull, 0ull, false, true>, bool) 0x12f [0x42d74f]
 ./curry1 void triqs::arrays::h5_impl::write_array<triqs::arrays::array_view<long, 2, 0ull, 0ull, false, true> >(triqs::h5::group, std::string const&, triqs::arrays::array_view<long, 2, 0ull, 0ull, false, true> const&, bool) 0xb3 [0x42d493]
 ./curry1 _ZN5triqs6arrays8h5_writeINS0_10array_viewIlLi2ELy0ELy0ELb0ELb0EEEEEN5boost11enable_if_cIXaasr26is_amv_value_or_view_classIT_EE5valuesr31has_scalar_or_string_value_typeIS6_EE5valueEvE4typeENS_2h55groupERKSsRKS6_ 0xb2 [0x429692]
 ./curry1 triqs::gfs::local::h5_write(triqs::h5::group, std::string, triqs::gfs::local::tail_impl<true> const&) 0x14a [0x425d5a]
 ./curry1 triqs::gfs::gfs_implementation::h5_rw<triqs::gfs::imfreq, triqs::gfs::scalar_valued>::write(triqs::h5::group, triqs::gfs::gf_view<triqs::gfs::imfreq, triqs::gfs::scalar_valued, true>) 0x137 [0x425297]
 ./curry1 triqs::gfs::h5_write(triqs::h5::group, std::string, triqs::gfs::gf_impl<triqs::gfs::imfreq, triqs::gfs::scalar_valued, true, false> const&) 0xa1 [0x413341]
 ./curry1 main 0x285c [0x41162c]
 /lib64/libc.so.6 __libc_start_main 0xf5 [0x3ef1221b45]
 ./curry1 [0x40ed01]

 negative strides not permitted in h5

Thanks !
Laura.

**Comment by parcollet** [comment]
It was supposed to work. Partial_eval and curry are made for view in local code only, one is not supposed to save them.
