### ISSUE TITLE
Installs /usr/local/share/triqs.modulefile which is probably at a wrong location

### ISSUE THREAD

**Issue by yurivict** [TRIQS/triqs#590]
The directory ```/usr/local/share/``` is for ports' data files. It has directories in it.
Inside of this file it says ```To be installed as ${MODULEPATH}/triqs/```
But it isn't installed into such path.

Could you please also explain in this file what it is for?

**Comment by Wentzell** [comment]
> The directory `/usr/local/share/` is for ports' data files. It has directories in it.
> Inside of this file it says `To be installed as ${MODULEPATH}/triqs/`
> But it isn't installed into such path.
> 
> Could you please also explain in this file what it is for?

The triqs.modulefile is a file to be used with the [modules](http://modules.sourceforge.net) project that is commonly employed on HPC clusters to allow users to easily load the environment for different software packages. You are correct however that this file should not be installed by default. I have removed the installation with commit eb012d1b

> It also installs the file /usr/local/share/triqsvars.sh which also looks like it is misplaced.

The triqsvars.sh file sets the relevant triqs environment variables for the user.
@yurivict Where would you suggest this file to live?
@parcollet CMakePrefixPath is still need as far as I know even when the ..Config.cmake is installed into /usr/local/share/cmake

**Comment by Wentzell** [comment]
As mentioned, the installation of the module-file has been removed.
If and only if the MODULEPATH environment variable exists on the do we suggest
to the user to copy the file into one of the module directories on the host.

We will keep the environment setup file ```triqsvars.sh``` in share for now.
As @parcollet mentioned, this file might well be obsolete if you install into a standard location such as
```/usr```, so you can remove it in the packaging process. Please double check if CMAKE_PREFIX_PATH
is indeed not necessary when the ```Config.cmake``` files live in ```/usr/lib/cmake/triqs```
