### ISSUE TITLE
cmake/FindNFFT.cmake share/cmake/FindTest.cmake are installed when you don't provide such packages

### ISSUE THREAD

**Issue by yurivict** [TRIQS/triqs#591]

**Comment by Wentzell** [comment]
Indeed the ```FindTest.cmake``` should be installed as it is a triqs-internal cmake module.
This was removed in 1ddd8983

```FindNFFT.cmake``` and ```FindTriqsTest.cmake``` however are cmake Modules that are used by other triqs applications and should be installed in ```$INSTALL_PREFIX/share/cmake/Modules```. There is no need to provide NFFT only because you are providing a cmake Module for it.
