### ISSUE TITLE
Chemical potential in tight-binding model

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/triqs#595]
Dear All,

Given the density is there any implemented function to evaluate the chemical potential for a simple tight-binding model? Or the only way is to use the dft-tools converters+sumk_dft ?

Best,
Danny

**Comment by mzingl** [comment]
Hi Danny,

you mean within the lattice tools? 
No, as far as I know this is not implemented. If you do this yourself you might 
consider using the Dichotomy implemented in TRIQS.

Best,
Manuel

**Comment by parcollet** [comment]
Ok, this is not an issue.
