### ISSUE TITLE
Please allow to build the python module selarately from the C++ library

### ISSUE THREAD

**Issue by yurivict** [TRIQS/triqs#598]
The C++ library is built once, but the python module can be built many times for various python versions.
Please have cmake flags allowing to build only the C++ library and only the python module.

**Comment by Wentzell** [comment]
What you ask is, at this stage, not easily possible as the Python Version is detected during 
the cpp2py configuration and then propagated to the cmake of triqs.

Also, this is a very niche use-case as most users will have a particular python version they
want to build their module against.
