### ISSUE TITLE
Fix delta() in tools.py

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#601]
Please fix this function, it is not obsolete in my opinion.
See also TRIQS/dft_tools#98
Thanks,
Manuel

**Comment by mzingl** [comment]
Quick question on this: Will the Delta() function be removed from the library, or will it be made 'un-obsolete' and fixed to work with the new tails?

**Comment by Wentzell** [comment]
Hey @mzingl. I will close this issue as discussed earlier.

As the extraction of Delta involves fitting of high-frequency moments and can be numerically delicate
in certain cases we will refrain from providing a function that automates this.
The steps for the extraction of delta should rather be explicitly performed by the user/application.
