### ISSUE TITLE
Tags and versions

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#603]
Dear all,

I'd like to add a issue related to #602.

My understanding is that checking out TRIQS + packages on a specific tag should work seamlessly.
Further, I thought that I should be able to use the same tag for all projects. This does not work and was probably not tested thoroughly.
I give two quick examples, I guess one can find more:
1.) TRIQS 2.0 requires cpp2py 1.5, there is no 2.0 in cpp2py. Why not add a tag?
2.) On 1.5 two cthyb tests in the complex version are broken. This was fixed later on 2.0, but even
cherry-picking the fix does not make the tests pass. In that stage I would say 1.5 is not operational.

This brings me to my questions:
Are we doing bug fixes for the releases 1.4, 1.5, 2.0 and should these tags be fully operational versions?
If yes, how are the bug fixes applied, e.g. on a bugfix_1.5 branch? Or will there be a separate 1.5.x branch?

For which version/branches are support, documentation and bugfixes provided? Is it master, 1.5 or 2.0?

My personal opinion is that 1.5 should get bugfixes, because it is the last stable version before the tails were removed.

Best,
Manuel

**Comment by mzingl** [comment]
Btw. also TRIQS tag 2.0 does not compile on ubuntu, the master does...

**Comment by Wentzell** [comment]
Hey Manuel

> My understanding is that checking out TRIQS + packages on a specific tag should work seamlessly.

Yes, this should be the case! If critical bugfixes are necessary these will be replayed on 1.5.x
So instead of using the 1.5 tag, it would be best to check out the respective bugfix branch.

> Are we doing bug fixes for the releases 1.4, 1.5, 2.0 and should these tags be fully operational versions?
> If yes, how are the bug fixes applied, e.g. on a bugfix_1.5 branch? Or will there be a separate 1.5.x branch?

In principle we will replay bugfixes on one release before the latest one (i.e. 1.5 atm with bugfix branch 1.5.x).
But since 1.5 and 2.0 followed so closely in succession we decided to also create 1.4.x.
There is no 2.0.x because this is exactly what master corresponds to.

> Further, I thought that I should be able to use the same tag for all projects.

This restriction has been lifted. The idea of semantic versioning is that the version number describes the progress of the application! It is quite counterintuitive to have an application change the major version number just because it was ported to the latest major version of triqs.
The requirements on the triqs version should be encoded in the top-level CMakeLists.txt 

I hope I managed to clarify all points?

**Comment by mzingl** [comment]
Thanks for your answer, but I have more questions.

1.) Would be nice to make sure that all supported branches of TRIQS/cpp2py/cthyb/dfttools work. Is this done by Jenkins? Please, also don't forget the complex ctyhb version.

2.) I agree that the version numbers must not be the same, however this is easy to fulfill if the downstream project is moving faster,  e.g. cpp2py is on 1.5 and TRIQS on 2.0. But take the following example of DFTTools:
release 1.5 - bugfix - bugfix - bugfix - bugfix - move to TRIQS 2.0 - bugfix - bugfix - bugfix
Now we are still on DFTTools version 1.5, however if I want to get all bugfixes I will need to upgrade my TRIQS installation to TRIQS 2.0. Maybe my understanding is wrong, but 'forcing' a major TRIQS upgrade on people on the 1.5 DFTTools branch is not ideal. The only way around is then to introduce a DFTTools1.6 (or easier DFTTools2.0) and replay bugfixes on 1.5.

3.) Only if my reasoning in 2.) is correct: Having a fast moving TRIQS (many versions in a few months) creates a lot of work on the application side. We would basically have to maintain multiple versions of e.g. DFTTools which are very similar. IMHO the only way out is to put the adjustments for newer TRIQS versions on a separate branch and merge them for the next major DFTTools release.

3.) Without looking into the CmakeLists.txt or running cmake understanding which versions go together is not that clear to me (and probably also to others).

Thanks,
Manuel

**Comment by Wentzell** [comment]
Hey Manuel

The agenda for versioning/CI has recently undergone some changes. Let me address your questions.

> 1.) Would be nice to make sure that all supported branches of TRIQS/cpp2py/cthyb/dfttools work. Is this done by Jenkins? Please, also don't forget the complex ctyhb version.

Jenkins is continuously checking master/unstable and any release branch (see below). Other (dev) branches have to be explicitly enabled for testing/CI.

> release 1.5 - bugfix - bugfix - bugfix - bugfix - move to TRIQS 2.0 - bugfix - bugfix - bugfix
> Now we are still on DFTTools version 1.5, however if I want to get all bugfixes I will need to upgrade my TRIQS installation to TRIQS 2.0

Importand Bug-Fixes should be back-ported to older releases. The agenda for this is the following

*  With every MAJOR.MINOR release, take for example `2.0`, there should be an associated branch, e.g. `2.0.x`. The initial release tag `2.0.0` (and a release candidate before that) should live on this branch, while master and unstable will continue independently.
Important bug-fixes should be back-ported to this branch with e.g. `git cherry-pick some_commit_on_master` and then grouped into patch-releases like `2.0.1`, `2.0.2` and so on.
This way we can easily keep older versions up to date without forcing an update to a newer TRIQS/application version onto users.

> 3.) Without looking into the CmakeLists.txt or running cmake understanding which versions go together is not that clear to me (and probably also to others).

The applications should either directly mirror the MAJOR.MINOR version number of triqs and/or explicitly list the compatible TRIQS releases in the CMakeLists.txt. People using triqs and applications in production should refrain from using master or even unstable, but stick to releases or release branches.
As we are moving to a more frequent release cycle (c.f. the recent `2.1-rc1`) the latest features/bug-fixes should be available with little delay.

Let me know if this answers all open questions.

Best,

Nils

**Comment by mzingl** [comment]
Thanks for clarifying this, Nils.
Best,
Manuel
