### ISSUE TITLE
Doc does not compile on Ubunutu 16.04

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#605]
Compiling the TRIQS doc on the master branch (new installation, also following the guide for 16.04 [doc](https://triqs.github.io/triqs/master/installation/ubuntu.html#c-2py)) produces the following error:

> Traceback (most recent call last):
  File "/home/manuel/Tools/cpp2py/bin/c++2rst", line 36, in <module>
    libclang_location = args.libclang_location
  File "/home/manuel/Tools/cpp2py/lib/python2.7/site-packages/cpp2rst/cpp2rst.py", line 60, in __init__
    self.root = CL.parse(filename, compiler_options, includes, libclang_location, parse_all_comments)
  File "/home/manuel/Tools/cpp2py/lib/python2.7/site-packages/cpp2py/clang_parser.py", line 356, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file /usr/lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/cstdlib line 75 col 15
'stdlib.h' file not found
... Your code must compile before using clang-parser !
doc/CMakeFiles/docs_cpp2rst.dir/build.make:60: recipe for target 'doc/cpp2rst.log' failed
make[2]: *** [doc/cpp2rst.log] Error 1
make[2]: *** Deleting file 'doc/cpp2rst.log'
CMakeFiles/Makefile2:10142: recipe for target 'doc/CMakeFiles/docs_cpp2rst.dir/all' failed
make[1]: *** [doc/CMakeFiles/docs_cpp2rst.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I played a bit around, changing -isystem back to -I does resolve this bug, but I brings another one:

> Traceback (most recent call last):
  File "/home/manuel/Tools/cpp2py/bin/c++2rst", line 36, in <module>
    libclang_location = args.libclang_location
  File "/home/manuel/Tools/cpp2py/lib/python2.7/site-packages/cpp2rst/cpp2rst.py", line 60, in __init__
    self.root = CL.parse(filename, compiler_options, includes, libclang_location, parse_all_comments)
  File "/home/manuel/Tools/cpp2py/lib/python2.7/site-packages/cpp2py/clang_parser.py", line 356, in parse
    raise RuntimeError, s + "\n... Your code must compile before using clang-parser !"
RuntimeError: Clang reports the following errors in parsing
 file /usr/include/python2.7/unicodeobject.h line 534 col 5
ISO C++17 does not allow 'register' storage class specifier file /usr/include/python2.7/unicodeobject.h line 553 col 5
ISO C++17 does not allow 'register' storage class specifier file /usr/include/python2.7/unicodeobject.h line 575 col 5
ISO C++17 does not allow 'register' storage class specifier file /usr/include/python2.7/unicodeobject.h line 593 col 5
ISO C++17 does not allow 'register' storage class specifier file /usr/include/python2.7/stringobject.h line 173 col 5
ISO C++17 does not allow 'register' storage class specifier file /usr/include/python2.7/stringobject.h line 174 col 5
ISO C++17 does not allow 'register' storage class specifier file /usr/include/python2.7/stringobject.h line 175 col 5
ISO C++17 does not allow 'register' storage class specifier
... Your code must compile before using clang-parser !
doc/CMakeFiles/docs_cpp2rst.dir/build.make:60: recipe for target 'doc/cpp2rst.log' failed

**Comment by Wentzell** [comment]
Hey Manuel,

Can you retry with the latest version of c++2py? This should be fixed with triqs/cpp2py@1b7c7b64371fe41797f82f18dfc3c0a348a32602

**Comment by mzingl** [comment]
Great, works. However the next commit TRIQS/cpp2py@2e7705e breaks my installation. I'll open a separate issue for this or just talk to you.

We can close this one.
Thanks

**Comment by Wentzell** [comment]
There was indeed an additional problem with TRIQS/cpp2py@2e7705e which should be fixed by TRIQS/cpp2py@994731d65ddf3a1052c06c66a2b279ce2dc78cb0

**Comment by mzingl** [comment]
Well, in my case TRIQS/cpp2py@1b7c7b6 finds the following PYTHON_LIBRARY path:
/usr/lib/python2.7/config-x86_64-linux-gnu/libpython2.7.so
This is currently not covered in the newest commit.

Best,
Manuel

**Comment by Wentzell** [comment]
We explicitly do not want to cover this one. You should also have the file `/usr/lib/x86_64-linux-gnu/libpython2.7.so` no?

**Comment by Wentzell** [comment]
Everything should be working with TRIQS/cpp2py@c0d5013
Reopen if needed.
