### ISSUE TITLE
version tags

### ISSUE THREAD

**Issue by mzingl** [TRIQS/triqs#613]
Hi,
somehow the version tags are still messed up.
The 1.4 tag is later in time than the 1.4.1 and the 1.4.2 tag. 
My understanding is that the 1.4 version is before the separation of cpp2py. If this should be case the tag needs to be placed accordingly.

Also, it would be good to check that the tagged versions compile (also with doc) and the tests pass.
For me this was not the case with the 1.4 and 2.0 tag (on ubuntu).

Thanks,
Manuel

**Comment by Wentzell** [comment]
Hey Manuel

> The 1.4 tag is later in time than the 1.4.1 and the 1.4.2 tag.

For me the dates look fine.

1.4    Tue Jan 17 16:12:34 2017
1.4.1 Tue Sep 19 23:43:09 2017
1.4.2 Thu Apr 19 14:53:33 2018

> Also, it would be good to check that the tagged versions compile (also with doc) and the tests pass.
> For me this was not the case with the 1.4 and 2.0 tag (on ubuntu).

Indeed I can reproduce a failure of the gf_inplace test on 1.4, 1.4.1, 1.4.2. Do you experience any other test failures?
This test failure is however tied to a recent change in Numpy Print formatting. We can however not retroactively fix this on all previous tags. I have implemented a work-around in the 1.4.x branch.

For 2.0, the only problem I can see arises from a change in the Cpp2Py versioning that happened only after the 2.0 release. I have fixed this problem on the 2.0.x branch.
Note that for future releases we will lock the Cpp2Py version for every TRIQS release which would have avoided this problem in the first place.

Concerning the doc, we have taken care that both the 1.4.x and the 2.0.x properly compile. Also, the doc for these branches is available at [triqs.github.io/triqs/1.4](https://triqs.github.io/triqs/1.4.x) and [triqs.github.io/triqs/2.0](https://triqs.github.io/triqs/2.0.x).

**Comment by mzingl** [comment]
Yes, sure, there was also some confusion from my side involved... Thanks Nils!
