### ISSUE TITLE
Access to specific block of BlockGf

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/triqs#614]
Dear All,

**A very simple/basic question:** In python side  it's possible to access a specific block of a BlockGf object directly as 

`
GF[block_name] << DO_SOMETHING 
`

I know how to 'iterate' over the blocks in c++ side , e.g.

`
for ( auto& gf : myblockGF ) { 
    // DO SOMETHING 
}
`

but I can't find the absolute equivalent of the python snippet.

Thanks

**Comment by Wentzell** [comment]
Dear Dani,

For the C++ interface of the Block Green function, there is no string accessor.
You can access particular blocks only with the block index, e.g.

```c++
for (int i : range(G.size())) { G[i] << f(i); }
```
