### ISSUE TITLE
Tutorial page update

### ISSUE THREAD

**Issue by pjc277** [TRIQS/triqs#615]
In regards to the Tutorials > Getting Started page: https://triqs.github.io/triqs/master/tour/getting_started/get_started.html

The instructions for using ipytriqs do not seem to work under the latest TRIQS package.

**Comment by Wentzell** [comment]
Thank you for the issue!
This is now fixed in commit 1831ad51328b2769f6ba62dcd1d5986005388387 and will soon be merged to master.
