### ISSUE TITLE
HDF5 problem in Ubuntu package

### ISSUE THREAD

**Issue by pjc277** [TRIQS/triqs#617]
I installed TRIQS using the Ubuntu Debian package install instructions to my system (Ubuntu 18.04). In the process of running the TRIQS tutorial "03 Archiving your data" I had an error message on the third code cell:

In:
from pytriqs.gf import *
g = GfReFreq(indices=[0], window=[-2,2], name='GF')
g << SemiCircular(1.0)

with HDFArchive("my_archive.h5",'w') as A:
    A['number'] = 12
    A['GF'] = g

Out:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-06b910601dc0> in <module>()
      5 with HDFArchive("my_archive.h5",'w') as A:
      6     A['number'] = 12
----> 7     A['GF'] = g

/usr/lib/python2.7/dist-packages/pytriqs/archive/hdf_archive.py in __setitem__(self, key, val)
    192             if not isinstance(d,dict) : raise ValueError, " __reduce_to_dict__ method does not return a dict. See the doc !"
    193             SUB = HDFArchiveGroup(self,key)
--> 194             for n,v in d.items() : SUB[n] = v
    195             write_attributes(SUB)
    196         elif isinstance(val,numpy.ndarray) : # it is a numpy

/usr/lib/python2.7/dist-packages/pytriqs/archive/hdf_archive.py in __setitem__(self, key, val)
    182 
    183         if hasattr(val,'__write_hdf5__') : # simplest protocol
--> 184             val.__write_hdf5__(self._group,key)
    185             self.cached_keys.append(key) # I need to do this here
    186             # Should be done in the __write_hdf5__ function

TypeError: Internal error : invalid id from h5py !

A screenshot of the same is attached.
![screenshot from 2018-07-31 11-30-54](https://user-images.githubusercontent.com/37344013/43469915-45956fe0-94b5-11e8-8c96-3cc2fc30d416.png)

**Comment by parcollet** [comment]
The issue was due to a local installation of h5py in home directory
conflicting with the system one.
Nothing to fix.
