### ISSUE TITLE
cthyb 1.4.1 CLANG 4.0 FreeBSD 11.2-RELEASE test fail: det_manip4

### ISSUE THREAD

**Issue by mike402** [TRIQS/triqs#618]
`77/189 Testing: det_manip4
77/189 Test: det_manip4
Command: "/tmp/tr/test/triqs/det_manip/det_manip4"
Directory: /tmp/tr/test/triqs/det_manip
"det_manip4" start time: Aug 03 15:08 CEST
Output:
----------------------------------------------------------
[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from det_manip
[ RUN      ] det_manip.det_manip_refill_0
matrix = 
[[1,0.666667,0.5]
 [0.666667,0.5,0.4]
 [0.5,0.4,0.333333]]
det    = 0.000185185
[       OK ] det_manip.det_manip_refill_0 (1 ms)
[ RUN      ] det_manip.det_manip_refill_2
matrix = 
[[1,0.666667,0.5]
 [0.666667,0.5,0.4]
 [0.5,0.4,0.333333]]
det    = 0.000185185
[       OK ] det_manip.det_manip_refill_2 (0 ms)
[ RUN      ] det_manip.det_manip_refill_4
matrix = 
[[1,0.666667,0.5]
 [0.666667,0.5,0.4]
 [0.5,0.4,0.333333]]
det    = 0.000185185
/home/md/src/git/TRIQS/triqs/test/triqs/det_manip/det_manip4.cpp:70: Failure
Value of: array_are_close(matrix{{100,-600, 1050, -560}, {-600, 4050, -7560, 4200}, {1050, -7560, 14700, -8400}, {-560, 4200, -8400, 4900}}, dm.inverse_matrix(), 1e-8)
  Actual: false (max_element(abs(x-y)) = 1.0200892575085163e-08
 X = 
[[100,-600,1050,-560]
 [-600,4050,-7560,4200]
 [1050,-7560,14700,-8400]
 [-560,4200,-8400,4900]]
 Y = 
[[100.00000000005565,-600.0000000003929,1050.0000000007549,-560.00000000042814]
 [-600.00000000039313,4050.000000002768,-7560.0000000053151,4200.0000000030122]
 [1050.0000000007553,-7560.0000000053142,14700.000000010201,-8400.0000000057789]
 [-560.00000000042814,4200.0000000030113,-8400.0000000057789,4900.0000000032733]])
Expected: true
[  FAILED  ] det_manip.det_manip_refill_4 (0 ms)
[ RUN      ] det_manip.det_manip_refill_empty
matrix = empty 
det    = 1
[       OK ] det_manip.det_manip_refill_empty (0 ms)
[----------] 4 tests from det_manip (1 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] det_manip.det_manip_refill_4

 1 FAILED TEST
<end of output>
Test time =   0.07 sec
----------------------------------------------------------
Test Failed.
"det_manip4" end time: Aug 03 15:08 CEST
"det_manip4" time elapsed: 00:00:00
----------------------------------------------------------`

**Comment by Wentzell** [comment]
Will be fixed as soon as cb7cd927e12ecc751b56a3d4f57d8891adc7f8d5 gets merged into master.
You can ignore this test failure.
The minor precision violation you see is associated most likely with your particular lapack version.
