### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/triqs#619]
Dear All,

I am trying to install TRIQS in Hydra center. Having installed cpp2py first, when I try to build TRIQS I get the following error message:

/usr/bin/ld: /u/mantadak/anaconda2/lib/python2.7/config/libpython2.7.a(ceval.o): unrecognized relocation (0x29) in section `.text'

Any ideas?

Best,
Danny

**Comment by Wentzell** [comment]
This issue is unrelated to TRIQS. It looks like the libpython2.7 you are trying to link is incompatible with
the system linker (/usr/bin/ld). Please contact the system admin to arrange for a proper libpython setup.
