### ISSUE TITLE
BlockGf error with name_block_generator

### ISSUE THREAD

**Issue by gkraberger** [TRIQS/triqs#620]
Hi everyone,

I am trying to run the following code

```
from pytriqs.gf import *
G1 = GfImFreq(beta=40,indices=[2])
G = BlockGf(name_block_generator=[('up',G1),('down',G1)])
```

and get the error

```
RuntimeError: BlockGf construction: error in parameters, see the documentation
```

I use commit dc2cbc572478bcd5c35ba4777f6bbdeacd3f2262 (=master).

The documentation tells me that I can use
```
BlockGf(name_block_generator, make_copies = False, name = '')
```

If I explicitly give the ``make_copies`` argument, it works.

This is a regression, since in 1.4.x it works.

- I think the problem is that in ``pytriqs/gf/block_gf.py``, line 62, the default argument ``make_copies`` does not get set for the ``name_block_generator`` case.
- In general, the implementation with comparing the kwargs to set seems quite fragile to me - furthermore, it does not allow user-friendly error messages (the error message is not very specific and itself wrong, because I was using it according to the cited documentation).
- The possible arguments ``note`` and ``rename_gf`` are, by the way, not documented although they exist.
- The default value of ``target_rank`` is not documented.

I wrote a test that checks all constructors of BlockGf, see https://gist.github.com/gkraberger/347c748fd07eabda1d3b80793a8d80b5.

Best
Gernot

**Comment by Wentzell** [comment]
Thank you @gkraberger for pointing out the issue.
This is resolved in [e979031](https://github.com/TRIQS/triqs/commit/e9790313d8cc2f376fc72f282418448c51441dbb).
Also added your test in e4a11189e
