### ISSUE TITLE
Build fails with GLIBCXX error

### ISSUE THREAD

**Issue by jq14** [TRIQS/triqs#627]
Hi all,

I am trying to install TRIQS on a school cluster with CentOS release 6.8 Kernel 2.6.32-642.el6.x86_64 on an x86_64 with the following flags:

> export CC="/home/jq14/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icc"
> export CXX="/home/jq14/intel/compilers_and_libraries_2018.3.222/linux/bin/intel64/icpc"
> export MKLROOT="/home/jq14/intel/compilers_and_libraries_2018.3.222/linux/mkl"
> export CFLAGS=" -std=c++14 -DMKL_ILP64 -I${MKLROOT}/include "
> export CXXFLAGS=" -std=c++14 -DMKL_ILP64 -I${MKLROOT}/include "
> export LIBRARY_PATH=" -Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_ilp64.a ${MKLROOT}/lib/intel64/libmkl_intel_thread.a ${MKLROOT}/lib/intel64/libmkl_core.a ${MKLROOT}/lib/intel64/libmkl_blacs_intelmpi_ilp64.a -Wl,--end-group -liomp5 -lpthread -lm -ldl"
> 
> cmake -DBLAS_LIBRARY=-lmkl_core -DLAPACK_LIBRARY="-lgm;-lmkl_intel_ilp64;-lmkl_intel_thread;-lpthread"  -DCBLAS_INCLUDE_DIR="/home/jq14/intel/compilers_and_libraries_2018.3.222/linux/mkl/include" -DLAPACK_LINKER_FLAGS="-L/home/jq14/intel/compilers_and_libraries_2018.3.222/linux/mkl/lib/intel64_lin"

The build fails with these errors:

> [  0%] Generating ../py_copy_test.tar
> [  1%] Building CXX object google_test/CMakeFiles/gtest.dir/gtest-all.cc.o
> icpc: command line warning #10006: ignoring unknown option '-Wno-register'
> [  1%] Built target py_copy_test
> [  1%] Building CXX object triqs/CMakeFiles/triqs.dir/arrays/python/numpy_extractor.cpp.o
> [  1%] Building CXX object triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o
> [  1%] Building CXX object triqs/CMakeFiles/triqs.dir/arrays/storages/mem_block.cpp.o
> icpc: command line warning #10006: ignoring unknown option '-Wno-register'
> icpc: command line warning #10006: ignoring unknown option '-Wno-register'
> icpc: command line warning #10006: ignoring unknown option '-Wno-register'
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../common.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./domain.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/map.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/array.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/./simple_read_write.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/simple_read_write.cpp(21):
> /home/jq14/common/aos/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(noexcept, true_type, true_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../common.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./domain.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/map.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/array.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/./simple_read_write.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/simple_read_write.cpp(21):
> /home/jq14/common/aos/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(& noexcept, true_type, false_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../common.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./domain.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/map.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/array.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/./simple_read_write.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/simple_read_write.cpp(21):
> /home/jq14/common/aos/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(&& noexcept, false_type, true_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./mem_block.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/mem_block.cpp(2):
> /home/jq14/common/aos/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(noexcept, true_type, true_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./mem_block.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/mem_block.cpp(2):
> /home/jq14/common/aos/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(& noexcept, true_type, false_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/numpy_extractor.cpp(21):
> /home/jq14/common/aos/include/c++/7.3.0/functional(139): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(noexcept, true_type, true_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./mem_block.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/mem_block.cpp(2):
> /home/jq14/common/aos/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(&& noexcept, false_type, true_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/numpy_extractor.cpp(21):
> /home/jq14/common/aos/include/c++/7.3.0/functional(140): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(& noexcept, true_type, false_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/utility/./c14.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/utility/tuple_tools.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/numpy_extractor.cpp(21):
> /home/jq14/common/aos/include/c++/7.3.0/functional(141): error: class template "std::_Mem_fn_traits" has already been defined
>   _GLIBCXX_MEM_FN_TRAITS(&& noexcept, false_type, true_type)
>   ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./../common.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/./domain.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/indexmaps/cuboid/map.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/array.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/./simple_read_write.hpp(22),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/h5/simple_read_write.cpp(21):
> /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(321): warning #3058: GNU attributes on a template redeclaration have no effect
>       template <typename T, typename... Pairs> FORCEINLINE decltype(auto) eval(T const &ex, Pairs const &... pairs) {
>                                                ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/./mem_block.hpp(23),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/storages/mem_block.cpp(2):
> /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(321): warning #3058: GNU attributes on a template redeclaration have no effect
>       template <typename T, typename... Pairs> FORCEINLINE decltype(auto) eval(T const &ex, Pairs const &... pairs) {
>                                                ^
> 
> In file included from /home/jq14/dmft/triqs.src/triqs/clef.hpp(1),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/../impl/common.hpp(24),
>                  from /home/jq14/dmft/triqs.src/triqs/arrays/python/numpy_extractor.cpp(21):
> /home/jq14/dmft/triqs.src/triqs/./clef/clef.hpp(321): warning #3058: GNU attributes on a template redeclaration have no effect
>       template <typename T, typename... Pairs> FORCEINLINE decltype(auto) eval(T const &ex, Pairs const &... pairs) {
>                                                ^
> 
> compilation aborted for /home/jq14/dmft/triqs.src/triqs/arrays/storages/mem_block.cpp (code 2)
> make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/storages/mem_block.cpp.o] Error 2
> make[2]: *** Waiting for unfinished jobs....
> compilation aborted for /home/jq14/dmft/triqs.src/triqs/arrays/python/numpy_extractor.cpp (code 2)
> make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/python/numpy_extractor.cpp.o] Error 2
> compilation aborted for /home/jq14/dmft/triqs.src/triqs/arrays/h5/simple_read_write.cpp (code 2)
> make[2]: *** [triqs/CMakeFiles/triqs.dir/arrays/h5/simple_read_write.cpp.o] Error 2
> make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....

If it is relevant, I have also gcc 7.3 installed. It still fails when I change the compiler to gcc. Is there anything I am missing or is it actually a collision? Any help would be appreciated.

**Comment by parcollet** [comment]
It looks like an issue with Intel compiler and gcc stdlib.
We do not support Intel compiler, in particular because it does not provide its own std library, which yields a lot of machine specific problems of this kind, which are beyond our control.

gcc 7.3 is our main compiler, in particular for the Continuous Integration, 
so it should work. What is the error message in that case ?

**Comment by jq14** [comment]
Hi,

Thanks for the quick response. I just changed the icc and icpc to gcc and g++ and now it works. I must have forgotten to delete the build directory and redo the build from scratch previously.

Is there any version of Intel compiler that can compile? I have multiple versions of Intel compiler installed  that I want to try with.

**Comment by jq14** [comment]
Hi,

I have decided that since Intel compilers are not supported, I shall stick with GCC. Intel Python works fine though. Thanks for the help.

**Comment by JATIN199604** [comment]
Hii everyone .
i want to use TRIQS as an interface to WIEN2k . during make command i am gatting an error .
jatin@jatin-HP-Laptop-14s-cr1xxx:~/DMFT/triqs.build$ make
[  1%] Built target cpp2py
[  2%] Built target gtest
[  3%] Linking CXX shared library libtriqs.so
/usr/bin/ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
triqs/CMakeFiles/triqs.dir/build.make:1044: recipe for target 'triqs/libtriqs.so' failed
make[2]: *** [triqs/libtriqs.so] Error 1
CMakeFiles/Makefile2:339: recipe for target 'triqs/CMakeFiles/triqs.dir/all' failed
make[1]: *** [triqs/CMakeFiles/triqs.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
your help is much more necessary for me .
