### ISSUE TITLE
Try function for change_one_row_and_one_col in det_manip class?

### ISSUE THREAD

**Issue by amoutenet** [TRIQS/triqs#628]
Hi all,

I am using the change_one_row_and_one_col function of det_manip in a movement in my MC code, but I noticed there is no try function (like try_insert). Hence I do the full change in the attempt() function, and if the move is rejected, I reconstruct my det_manip by using change_one_row_and_one_col once again.

However I suspect this procedure to not be fully stable, as I get sometimes matrix conditioning errors ("det_manip deviation above critical threshold").
Would it be possible to get a try_ function for change_one_row_and_col, first because it would be more efficient, and second to see if my problem truly comes from here or is more subtle?

Thanks a lot!
Alice

**Comment by parcollet** [comment]
Ok, let's discuss this directly.

**Comment by parcollet** [comment]
Done and merged.
