### ISSUE TITLE
[cmake] Add header directories to exported triqs target

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#629]
For the exported cmake target `triqs` it would be good practice to add the header install directories to the `INTERFACE_INCLUDE_DIRECTORIES`

**Comment by parcollet** [comment]
ok.

**Comment by Wentzell** [comment]
Fixed with 893fbdcc and triqs/cpp2py@b144f9b
@phdum Let me know if you still have trouble to get the includes to propagate.
