### ISSUE TITLE
gf_brillouinzone_mesh interpolator broken for non-orthogonal lattices

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#632]
Dear all,

I mentioned this in discussions before but put out an issue on it here so that it does not disappear.

The k-space interpolator is implemented assuming that the Brillouin zone basis vectors are orthogonal.  This is not tested for in the implementation and it gives incorrect results for non-orthogonal systems.

I consider this a hard bug.

Best, Hugo

**Comment by Wentzell** [comment]
This bug has been fixed in TRIQS/unstable and also TRIQS/3.0.x
