### ISSUE TITLE
MPI Crashes when trying to reduce an empty vector

### ISSUE THREAD

**Issue by phdum** [TRIQS/triqs#638]
When using mpi_reduce on an empty vector, MPI throws a fatal error. Should ideally return an empty vector.

Simplest example: 

```
std::vector<double> v1{};
std::vector<double> v2 = triqs::mpi::mpi_reduce(v1, world);
```

results in

```
*** MPI_ERR_ARG: invalid argument of some other kind
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
```

**Comment by HugoStrand** [comment]
Dear phdum,

Thank you for reporting the issue. I am not sure what is going wrong. Is it possible to boil down the issue to a small (complete) example program? So that we can reproduce your problem. Could you also let us know what version/commit of `triqs` that you are using.

Best, Hugo

**Comment by HugoStrand** [comment]
It might be that you are hitting the issue I had with empty arrays #622.

**Comment by HugoStrand** [comment]
You can find the description of the problem in this issue  #621.

**Comment by HugoStrand** [comment]
I have added a pull request #639 with a test containing the failing `mpi_reduce`.

**Comment by parcollet** [comment]
Great I have a fix
Will retest and push

**Comment by parcollet** [comment]
Done in unstable.
