### ISSUE TITLE
Moving to Python3?

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#640]
Dear all,

We have been talking about Python 3 for a while now. Maybe this is a relevant piece of info:
https://www.numpy.org/neps/nep-0014-dropping-python2.7-proposal.html
Numpy will stop feature development in Python2 by the end of the year.

Best, Hugo

**Comment by mzingl** [comment]
There is already issue #263 for this, but I agree with Hugo that we should make an effort to move.
I have for example a case where I need to connect a python3 code with TRIQS.
Right now I am doing this via cumbersome reading/writing of files and running the codes separately.

Best, Manuel

**Comment by HugoStrand** [comment]
Dear Manuel, Thank you for pointing out #263. I was just so shocked when I read that `numpy` will stop porting things. I will close this and move my post to the actual thread. Cheers, H
