### ISSUE TITLE
error: triqs/dmft (GdIn3+sp)

### ISSUE THREAD

**Issue by ghragoozloo** [TRIQS/triqs#641]
Dear all
Hi
I want to run dmft calculation for GdIn3 compound in antiferromagnetic phase by using triqs code. I used the supercell (2 2 2) of this compound for my study. I also used the following "case.indmftpr" in my calculation:

2 ! Nsort
1 3 ! Mult(Nsort)
3 ! lmax
complex ! choice of angular harmonics
1 1 1 2 ! l included for each sort
0 0 0 2 ! If split into ireps, gives number of ireps. for a given orbi$
01 !
0 ! SO flag
cubic ! choice of angular harmonics
1 1 1 0 ! l included for each sort
0 0 0 0 ! If split into ireps, gives number of ireps. for a given orbi$
! t2g + eg + Op! 0.4 0.4

I run dmft calculation I as sent below for you:

X lapw2 -almd –up
X lapw2 –almd –down
Dmftproj –sp

But when I run these, I encounter the following errors that I sen here for your consideration:
Thanks a lot .

Errors:

Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS
This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.
You are performing a computation
without Spin-Orbit.
using Spin-Polarized Wien2k input files.
Sorts of atoms = 2
Equivalent sites per each sort: 1 3
For the sort 1 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.
The orbital l= 3 is included.
For the sort 2 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.
The Eigenstates are projected in an energy window from -0.40000 Ry to 0.40000 Ry around the Fermi level.
Basis representation for each sort.
For the sort 1 :
The atomic sort 1 is studied in the complex basis representation
For the sort 2 :
The atomic sort 2 is studied in the cubic basis representation.

The basis for s-orbital is still 1.000000
The basis for orbital l= 1 has the following properties :

number of ireps : 1
degree of each ireps : 3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
0.707107 0.000000 0.000000 0.707107 0.000000 0.000000
0.000000 0.000000 0.000000 0.000000 1.000000 0.000000
-0.707107 0.000000 0.000000 0.707107 0.000000 0.000000
The basis for orbital l= 2 has the following properties :

number of ireps : 2
degree of each ireps : 2 3
The transformation matrix is block diagonal in the spin-space. The up/up and down/down blocks are the same and defined as :
0.000000 0.000000 0.707107 0.000000 -0.707107 0.000000 0.000000 0.000000 0.000000 0.000000
0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.707107 0.000000 0.707107 0.000000
1.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 0.000000
0.000000 0.000000 0.000000 0.000000 0.000000 0.000000 -0.707107 0.000000 0.707107 0.000000
0.000000 0.000000 0.707107 0.000000 0.707107 0.000000 0.000000 0.000000 0.000000 0.000000
=======================================
Precisions about correlated orbitals.
For the sort 1 :
The number of ireps considered for the orbital l= 3 is wrong.
END OF THE PRGM

**Comment by Wentzell** [comment]
This is not a triqs issue. Post this on the dft_tools issue list.

Also, please consider marking your input files and output as ```such``` using the [github highlighting](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

**Comment by mzingl** [comment]
This is a duplicate of the dft_tools issue TRIQS/dft_tools#107
