### ISSUE TITLE
Machinery for integrations in the Matsubara axis 

### ISSUE THREAD

**Issue by dmantadakis** [TRIQS/triqs#642]
Dear All, 

Are there any build-in tools, developed or being developed,  to perform integrals ( in particular to take care of the high-frequencies ) of the form F(iw)/(iw-z) where F is a container of numerical data, on the matsubara axis or one has to implement a tail-model ( in the same spirit as in the calculation of the density ) 

Best 
Danny

**Comment by Wentzell** [comment]
Hey Dani,

We do indeed have an implementation of the [hilbert_transform](https://triqs.github.io/triqs/master/reference/lattice_tools/hilbert.html?highlight=hilbert_transform#module-pytriqs.dos.hilbert_transform). Note that the DOS object passed to the HilbertTransform can also be constructed from a function using [DOSFromFunction](https://triqs.github.io/triqs/master/reference/lattice_tools/dos.html?highlight=dosfromfunction).
