### ISSUE TITLE
[cmake] Cpp2Py module generation fails to pick up proper libtriqs.so when loading dependent modules

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/triqs#656]
When we register e.g. the meshes module with the [add_cpp2py_module](https://github.com/TRIQS/cpp2py/blob/c243518f289574eefec6d95971b454508211bbc4/cmake/Cpp2PyConfig.cmake.in#L71) macro we introduce a custom target to generate the meshes_wrap.cxx.

In the case of the gf_fnt module we have a dependency on the previously generated meshes module, which is [imported](https://github.com/TRIQS/triqs/blob/401e01a7ffb87c3f76e62444f93b5a1734a93cc8/pytriqs/gf/gf_fnt_desc.py#L7) in the gf_fnt_desc.py.

As the meshes.so links dynamically against libtriqs.so we need to make sure to adjust the dynamic linking environment of the cmake_custom_command that executes the gf_fnt_desc.py (with e.g. LD_LIBRARY_PATH).
This will guarantee that the proper ```build_dir/triqs/libtriqs.so``` is found during the import, which is currently not the case and can lead to unresolved symbols.

**Comment by parcollet** [comment]
The need for importing will be gone as soon as we merge the few simplifications in cpp2py
which are waiting... I suggest to postpone this until I have merged those changes.

**Comment by Wentzell** [comment]
> The need for importing will be gone as soon as we merge the few simplifications in cpp2py
> which are waiting... I suggest to postpone this until I have merged those changes.

Yeah, avoiding the import sounds like the easiest solution.

**Comment by Wentzell** [comment]
This is fixed after the recent commits 81eb2e94, 98efc8c2 and 97939b8a
