### ISSUE TITLE
Question on fit_hermitian_tail_on_window

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#661]
Dear Nils,

I am wondering what the `fit_hermitian_tail_on_window` is doing in the fit when I specify `expansion_order`. Is the order returned the same as the order used in the fit?

The reason for this question is that I see in the `single_band_bethe` cthyb-regression test that I get differences in the fitted tail on the order of 1e-5 just between the different platforms in the CI.

Best, Hugo

**Comment by Wentzell** [comment]
Hey Hugo,

> I am wondering what the `fit_hermitian_tail_on_window` is doing in the fit when I specify `expansion_order`.

If you pass an `expansion_order`, the fitting routines will fit a all high-frequency moments up to that order (starting from 0). With an expansion order of e.g. 3, we will thus perform a least square fit of the function

``` a_0 + a_1 / iw + a_2 / iw**2 + a_3 / iw**3 ```

to the specified high frequency window of the data while assuming hermiticity of the a_i matrices.

> The reason for this question is that I see in the `single_band_bethe` cthyb-regression test that I get differences in the fitted tail on the order of 1e-5 just between the different platforms in the CI.

We have been observing similar problems for our TRILEX regression tests. The deviations seem to depend on the lapack implementation/version and are often of order `~1e-7`. Dominic Bergeron observed a similar behavior in his own tail-fitting implementation inside omegamaxent.
I do not see an easy solution for this problem other than choosing the error thresholds accordingly for the regression tests.

**Comment by HugoStrand** [comment]
Ok! Super thank you. Cheers, H
