### ISSUE TITLE
how we can conversion Sigma_iw to Sigma_w ?

### ISSUE THREAD

**Issue by Reyhanehe** [TRIQS/triqs#665]
Dear all
I want to conversion Sigma_iw in to Sigma_w from "case.h5" that I calculated from DFT+DMFT .
Can Is here any one who can help me how can I do it?
Thanks a lot

**Comment by HugoStrand** [comment]
Dear Reyhanehe,

I assume that you would like to determine the real frequency self-energy from the computed Matsubara frequency self energy? This is in itself a "hard" problem which commonly is called "analytic continuation". One way to do it is to use the so called "maximum entropy method", which is implemented in the `Triqs/maxent` package. 

Please have a look at: https://triqs.github.io/maxent/master/

Cheers, Hugo
