### ISSUE TITLE
conjugate of tail of ImFreq Greens functions

### ISSUE THREAD

**Issue by aichhorn** [TRIQS/triqs#67]
there is a problem with the conjugate of the tail of a Greens function. Because of the expansion in 1/iomega, one has to conjugate to whole tail, not only its coefficients.
bug is in tail.pyx
maybe put a special function for ImFreq GF's, since it is not needed anywhere else.

**Comment by pseth** [comment]
We need to fix this asap.

**Comment by parcollet** [comment]
Ah, ok. @mferrero : Can you be more precise what you mean by specialized ?

**Comment by mferrero** [comment]
Take 1/i\omega_n. Its first moment is 1. The complex conjugate is -1/i\omega_n with first moment -1. Clearly the tail of the conjugate is not the conjugate of the tail. It has an extra -1 factor. On the other hand, take the function 1/\omega. The complex conjugate is 1/\omega. Both first moments are 1. In that case, no need to take an extra -1 factor. So according to the type of the Green's function, the procedure to get the tail of the conjugate is different. We will have to code a specialized version of conjugate for all Green's functions no?

**Comment by parcollet** [comment]
Ah right ... Needs to be done soon, Leonid needs it...

**Comment by tayral** [comment]
+1
