### ISSUE TITLE
[h5] HDFArchiveInert is not imported in pytriqs.archive

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#671]
`HDFArchiveInert` is a useful utility class that is documented but has somehow been forgotten.
I believe it should be added to the `__all__` list of `pytriqs.archive`.

https://github.com/TRIQS/triqs/blob/b99a06744eac6a07f7d4fb5015e1ef95cde45f2a/pytriqs/archive/__init__.py#L23-L24

**Comment by Wentzell** [comment]
Fixed in e2f2675
