### ISSUE TITLE
Bug: run() function of the MC class private

### ISSUE THREAD

**Issue by amoutenet** [TRIQS/triqs#676]
Hi all,

I installed the latest commit of unstable (906a9) and had a problem when running my code: the run() function of the MC class is said to be "private within this context". I indeed use this function instead of the warmup_and_accumulate because I need to precisely time the accumulate function while excluding the warmup. In this context I use run two times in the following manner:

```
MC.run(params.n_warmup_cycles, params.length_cycle, triqs::utility::clock_callback(-1), false);
MC.run(params.n_cycles, params.length_cycle, triqs::utility::clock_callback(params.max_MC_time), true);
```

Alice

PS: Related to the sign of the first configuration issue, I guess I will need to be able to pass the sign of the first config in run() too!

**Comment by Wentzell** [comment]
This issue was addressed in commit 4a6415c20d6c9637fef1698dca21984d8a091332

As discussed, we have added two separate functions ```warmup``` and ```accumulate```
```c++
int warmup(n_warmup_cycles, length_cycle, stop_callback);
int warmup(n_warmup_cycles, length_cycle, stop_callback, sign_init);
int accumulate(n_accumulation_cycles, length_cycle, stop_callback);
```

Reopen if needed.

**Comment by Wentzell** [comment]
Small corrections were added in 8ac2690c

**Comment by amoutenet** [comment]
@mferrero this might affect your codes
