### ISSUE TITLE
problem with dichotomy output

### ISSUE THREAD

**Issue by jkarp314** [TRIQS/triqs#682]
There seems to be an issue with the output of the dichotomy function. Sometimes, when I use it to calculate the chemical potential given a density, I get output with lines like:
larger number < chemical potential < smaller number 

An example code that gives this problem is:
```python
from pytriqs.lattice.tight_binding import *
from pytriqs.dos import HilbertTransform
from pytriqs.gf import GfImFreq
import pytriqs.utility.dichotomy as dichotomy
import numpy as np

# Define a DOS (here on a square lattice)
BL = BravaisLattice(units = [(1,0,0) , (0,1,0) ], orbital_positions= [(0,0,0)] )
t   = -1.00; tp  =  0.0*t               
hop= {  (1,0) :  [[ t]], (-1,0):  [[ t]], (0,1) :  [[ t]], (0,-1):  [[ t]], 
      (1,1) :  [[ tp]], (-1,-1):  [[ tp]],(1,-1):  [[ tp]], (-1,1):  [[ tp]]}

TB = TightBinding (BL, hop)
d = dos(TB, n_kpts= 500, n_eps = 101, name = 'dos')[0]
H = HilbertTransform(d)

Sigma0 = GfImFreq(indices = ['up','down'], beta = 20); Sigma0.zero()

F = lambda mu: np.real(H(Sigma = Sigma0,mu=mu).total_density())
density = 0.8
chemical_potential = dichotomy.dichotomy(function=F, x_init=0.0, y_value=density,
                                                      precision_on_y=1e-2, delta_x=0.5, max_loops=100,
                                                      x_name="Chemical Potential", y_name="Total Density",
                                                      verbosity=3)[0]
```

The output for this code is:

Dichotomy adjustment of Chemical Potential to obtain Total Density = 0.800000 +/- 0.010000
    Chemical Potential = -0.500000
    Total Density = 0.774462
    0.000000 < Chemical Potential < -0.500000
    1.000000 < Total Density < 0.774462
    0.000000 < Chemical Potential < -0.443383
    1.000000 < Total Density < 0.794793
    Chemical Potential found in 2 iterations :
    Total Density = 0.794793;Chemical Potential = -0.443383

I think the final result is fine. It's just that the output is confusing. The < signs should be changed to > signs, or the order should be switched.

**Comment by Wentzell** [comment]
This is now fixed on triqs/unstable. The output is now produced properly

```
    Chemical Potential = -0.500000  
    Total Density = 0.774462
    -0.500000 < Chemical Potential < 0.000000
    0.774462 < Total Density < 1.000000
    -0.443383 < Chemical Potential < 0.000000
    0.794793 < Total Density < 1.000000
    Chemical Potential found in 2 iterations : 
    Total Density = 0.794793;Chemical Potential = -0.443383
```
