### ISSUE TITLE
Update Website Tutorials for triqs 2.1

### ISSUE THREAD

**Issue by egcpvanloon** [TRIQS/triqs#683]
I was looking at the tutorial on lattice Green's functions in python (https://triqs.github.io/triqs/2.1.x/tutorials/gfs/lattice_gfs_tutorial_python.html), and it does not seem to be working with the current version of TRIQS: it complains that there is no module named multivar. The tuturial also mentions that this part of the library is experimental.

I was wondering how to fix the issue with the tutorial and what the currently preferred way to deal with lattice Green's functions in python is.

**Comment by Wentzell** [comment]
Hey @egcpvanloon 

Thank you for pointing this out!
The tutorials that can be found directly on the triqs website are currently very outdated and not operational. This needs to be fixed!

I would however like to point you to the [TRIQS/tutorials](github.com/TRIQS/tutorials) repository
which contains a set of operational IPython Notebook tutorials from basic to very advanced.
The tutorials contain exercises as well as the corresponding solutions.
For understanding the current functionality available in the lattice-tools of pytriqs the [TPSC](https://github.com/TRIQS/tutorials/blob/master/TRIQSTutorialsPython/TPSC) tutorial set is particularly useful.

**Comment by Wentzell** [comment]
Note however that the lattice-tools part of triqs is high on the priority list to be reworked
in the near future. This will involve changes in the associated API.
For this reason this part of the triqs library should in fact still be considered experimental / subject to change.

**Comment by Wentzell** [comment]
The website tutorials have now been replaced with embedded versions of the Notebooks from [TRIQS/tutorials](https://github.com/triqs/tutorials).
C.f. https://triqs.github.io/triqs/unstable/userguide.html#python-tutorials
