### ISSUE TITLE
DMFT Bethe tutorial broken

### ISSUE THREAD

**Issue by malteschueler** [TRIQS/triqs#685]
The tutorial on DMFT for the Bethe lattice on the main triqs page (https://triqs.github.io/triqs/2.1.x/tour/dmft.html) seems to be broken. It fails because S.G_tau does not exist before Solver.solve() is called.  The tutorial should be probably replaced by the Bethe lattice tutorial on the cthyb page (https://triqs.github.io/cthyb/master/guide/dmft.html).

I am using unstable branches of cthyb and triqs:
triqs commit: 2aa1d7f246fd671b96e03c8cc5d5b1f7e7c27cc5
cthyb commit: d37d81546bc81fd47a224ab0105d5ad5485bf404

**Comment by Wentzell** [comment]
Hey @malteschueler,

Thank you for pointing this out!
This is now fixed on TRIQS/unstable, cf. 7402718
