### ISSUE TITLE
[master/unstable] All Python tests fail on my machine

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#687]
Subject.

The reason is the following line,
https://github.com/TRIQS/triqs/blob/6e13d7981425c57f51c701c90f4c3c1a771e3ed8/cmake/FindTest.cmake#L1

`python` happens to be a symlink to the Python 3 interpreter on my system like, I believe, on many other systems these days. It would make much more sense to use `${PYTHON_INTERPRETER}` instead.

**Comment by Wentzell** [comment]
Hey @krivenko 
Thank you for the issue.

I agree that the Python Interpreter should be choosen accordingly. This is fixed with 0cc455c
