### ISSUE TITLE
extracting the iOmega mesh

### ISSUE THREAD

**Issue by sensudeshna** [TRIQS/triqs#688]
Dear TRIQS developers,

I am Sudeshna and am a new user of TRIQS (version 2.1.0) trying to use it in the context of DMFT. I have just begun using it and am testing the python scripts used to call the solver and post process the data. In this regard, I was wondering if it is possible to extract the iOmega_n? 
I have been able to extract the Greens function data, for e.g. by calling "S.G_iw['up'].data[:,0,0]", however can we also get the respective iOmega_n mesh used to calculate the quantities? 
Please note that this is just for a consistency check that I need to do for some benchmarking calculations with another solver (unrelated to TRIQS or CTHYB), and for that I need to make sure that I am using the same frequency mesh.

Regards,
Sudeshna

**Comment by Wentzell** [comment]
Hey @sensudeshna,

You can easily extract the mesh of the Green function with

```python
iw_mesh = S.G_iw['up'].mesh
```

This mesh is iterable of ```MeshPoint``` objects which have a ```value``` attribute

```python
for iw in iw_mesh:
    print iw.value
```

I hope this answers your question?

**Comment by dmantadakis** [comment]
Just for completeness to @Wentzell answer, if you only need to iterate over the values of the mesh you could use the implemented functionality as:

```python
for iw in iw_mesh.values(): 
    print iw
```

Note that the method `mesh.values()` returns a generator, which you can convert directly into a python-`list` as 

```python
iw_mesh_list = list(mesh.values())
```

**Comment by sensudeshna** [comment]
Hi Nils,

Thank you for the quick answer. This is exactly what I needed. I was in
fact calling S.G_iw['up'].mesh but was not being able to list out the
values as I was missing the second part.

I have one last question that I elaborate below: In order to complete the
DMFT self-consistency, I need to feed the new G0_iw calculated from the
lattice Green's function. My question is whether it is enough to feed back
only G0_iw into the solver and will the solver automatically take care of
the "High Frequency tail fitting" with the Legendre polynomials? Or does
the tail have to be fitted before feeding it back to the solver for the
second iteration?

Best Regards,

Sudeshna

**Comment by Wentzell** [comment]
@sensudeshna I am not sure I understood your question.
The triqs_cthyb solver needs to be initialized with G0_iw (i.e. the DMFT Weiss field)
and will internally fit the high-frequency moments in order to calculate the local hamiltonian `h_0`
as well as the hybridization-function delta(iw).

**Comment by sensudeshna** [comment]
I highly appreciate your reply. Thank you for your reply.

Best regards,

Sudeshna

**Comment by Wentzell** [comment]
@sensudeshna  Reopen if needed.
