### ISSUE TITLE
S2 operator question

### ISSUE THREAD

**Issue by johanjoensson** [TRIQS/triqs#692]
Dear all,
Let's say I have two electrons in a high spin configuration, what would be the value obtained from the S2 operator?
My guess would be 1, since I have 2 spin 1/2 particles. Is this correct?

Best regards
Johan

**Comment by Wentzell** [comment]
Hi @johanjoensson,

This is neither an issue with the triqs library nor a feature request so I am closing this.
The [documentation](https://triqs.github.io/triqs/2.1.x/reference/operators/util/observables.html?highlight=s2#pytriqs.operators.util.observables.S2_op) is very clear about the definition of S2.

Best,

Nils
