### ISSUE TITLE
Calculating the chemical potential for a fixed electron density in insulating phase

### ISSUE THREAD

**Issue by sreja** [TRIQS/triqs#695]
Hello, I was trying to calculate the chemical potential for a fixed electron density (in particular half-filling) for cubic lattice with Dichotomy.  As I understand, this takes a chemical potential to calculate the Greens function from which it gets the total density by integrating the density of states calculated. If this electron density is not the given one, then it adjusts the chemical potential to get the given electron density and continues until it gets the chemical potential which gives the given electron density.

The results are okay in the metallic phase, but in the insulating phase where two Hubbard bands are separated, the chemical potential stick to close to one of the Hubbard bands because the density of states is zero in the gap. So, chemical potential can be anywhere in between the two Hubbard bands. This has a large effect on self-energy (at least for small frequency region).  

Can anyone tell me how to ensure the chemical potential to be in the middle of the gap?

thanks,
sahinur

**Comment by Wentzell** [comment]
There is currently no way to generically enforce a chemical potential that will reside in the
middle of the gap using the dichotomy function.
If there is more than one solution for the chemical
potential for a fixed density the root finder will determine which one is found.
