### ISSUE TITLE
Autogenereated documentation links to local MathJax installation instead of online version

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#698]
Dear all,

I am having problem with the autogenerated documentation and the rendering of math in the TPRF applicaation. Currently TRIQS inserts the path to my local MathJax installation in the doc instead of the `https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js` link that is used everywhere else in the documentation.

The generated math in the doc renders nicely on my machine but does not render when hosted online.

How do I change this behavior to default to the online MathJax version?

Best regards,
Hugo

**Comment by Wentzell** [comment]
Hey @HugoStrand,

The FindMathJax.cmake module provided with triqs will always look for a local instance of MathJax first.
As of commit, ebacdae0249a22c0e5746dd461537173df44a16c, if it does not find a local instance it will fall back to the [2.7.5](https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js) online version.

If you want to explicitly enforce a particular path or url you can explicitly provide a MATHJAX_PATH during configuration

```bash
cmake path_to_src -DCMAKE_INSTALL_PREFIX=path_to_install -DMATHJAX_PATH=my_custom_mathjax_path
```
