### ISSUE TITLE
gf_mesh_brillouin_zone is a bit noisy when being serialized

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#706]
the gf_mesh_brillouin_zone prints to std::out whenever it is serialized. This makes my logs a bit noisy when running 400 mpi-ranks. The problem is here:
https://github.com/TRIQS/triqs/blob/2.1.x/triqs/lattice/gf_mesh_brillouin_zone.hpp#L146
Best, Hugo

**Comment by Wentzell** [comment]
Fixed in 508d66a
