### ISSUE TITLE
fit_legendre intermittent segfaults

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#709]
Dear all,

I have been experiencing intermittent segfaults in the fig_legendre function. This is a placeholder to remember the issue for the future.

The segfaults only occur for some polynomial orders. I suspect that there is some problem with the returned greens function and the handling of the memory...

Best, Hugo

**Comment by Wentzell** [comment]
Hey Hugo,

Did you manage to reproduce the problem more systematically?

**Comment by Wentzell** [comment]
This issue is closed due to inactivity. Also we have no means of reproducing the problem.
