### ISSUE TITLE
Remove all free standing functions from gf_fnt.py

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#713]
We have a serious bug in the python Gf, since it adds all functions in gf_fnt.py as member functions and that python module is polluted with a bunch of freestanding functions to build Gf's. These functions needs to be moved out of the gf_fnt.py module or the import of methods in the pytriqs.gf.Gf needs to be changed.

Best, Hugo

**Comment by Wentzell** [comment]
This was resolved in 9dc9ccd
