### ISSUE TITLE
GMP issue when building TRIQS 2.1

### ISSUE THREAD

**Issue by rokzitko** [TRIQS/triqs#721]
Is GMP a dependency for TRIQS 2.1? The documentation seems inconsistent on this point.

I get the following error during the build process:

[ 13%] Generating meshes_wrap.cxx
Traceback (most recent call last):
  File "/share/apps/TRIQS/TRIQS-2.1-foss2018b/triqs.src/pytriqs/gf/meshes_desc.py", line 4, in <module>
    import pytriqs.lattice
  File "/share/apps/TRIQS/TRIQS-2.1-foss2018b/triqs.build/pytriqs/lattice/__init__.py", line 22, in <module>
    from lattice_tools import *
ImportError: /share/apps/TRIQS/TRIQS-2.1-foss2018b/triqs.build/triqs/libtriqs.so: undefined symbol: __gmpf_clear

CMake fails to properly autodetect GMP and I had to tweak my build script which reads as follows (and contains version information):

#!/bin/sh
# Rok Zitko, June 2019

git clone https://github.com/TRIQS/triqs triqs.src

cd triqs.src
git tag
git checkout 2.1.0
cd ..

ROOT_DIR=`pwd`

mkdir triqs.build
cd triqs.build

module purge
module load foss/2018b
module load Python/2.7.15-foss-2018b
module load Boost/1.68.0-foss-2018b-Python-2.7.15
module load CMake/3.9.6
module load Clang/7.0.1-GCC-7.3.0-2.30
module load HDF5/1.10.4-foss-2018b-serial
module load GMP/6.1.2-GCCcore-7.3.0
module list

#pip install h5py
#pip install mako

export GMP_INCLUDE_DIR=$EBROOTGMP/include
export GMP_LIBRARIES=$EBROOTGMP/lib
export GMPXX_LIBRARIES=$EBROOTGMP/lib

cmake ../triqs.src -DCMAKE_INSTALL_PREFIX=$ROOT_DIR/triqs.install -DGMP_INCLUDE_DIR=$GMP_INCLUDE_DIR -DGMP_LIBRARIES=$GMP_LIBRARIES -DGMPXX_LIBRARIES=$GMPXX_LIBRARIES

echo BUILDING
make -j4
echo TESTING
make test
echo INSTALLING
make install

Please advise. I am inexperienced with CMake.

Kind regards,
Rok

**Comment by Wentzell** [comment]
Hey Rok,

Triqs indeed requires libgmp. It looks like on your machine libgmp is properly linked but not dynamically loaded. Can you run the following commands and provide the output?

* ```locate libgmp.so```
* ```locate /gmp.h```
* ```module show GMP/6.1.2-GCCcore-7.3.0```
* ```ldd your_work_dir/triqs.install/lib/libtriqs.so```
* ```printenv  | grep LIBRARY```

**Comment by Wentzell** [comment]
Also, if you run the previous (problematic) version of your build script, what does the CMake configuration for triqs show in that case during the GMP detection?

```
...
-- -------- GMP detection -------------
-- GMP libs: /usr/lib64/libgmp.so /usr/lib64/libgmpxx.so
-- Found GMP: /usr/include  
```

**Comment by rokzitko** [comment]
Dear Niels,

I've noticed this warning:

WARNING: Target "triqs" requests linking to directory "/share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib".  Targets may link only to libraries.  CMake is dropping the item.

A quick google search identified what I had to do. Changing

export GMP_LIBRARIES=$EBROOTGMP/lib/
export GMPXX_LIBRARIES=$EBROOTGMP/lib/

to

export GMP_LIBRARIES=$EBROOTGMP/lib/libgmp.so
export GMPXX_LIBRARIES=$EBROOTGMP/lib/libgmpxx.so

solved the problem for me and the build process now completes. Still, I think CMake should be able to find GMP automatically. Let’s try to troubleshoot this.

> Triqs indeed requires libgmp. It looks like on your machine libgmp is properly linked but not dynamically loaded. Can you run the following commands and provide the output?
> 
> locate libgmp.so
We have several versions. The relevant is this one:

[builduser@spinon lib]$ ls -l /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib/
total 1020
-rw-r--r-- 1 builduser users 1307470 Oct  7  2018 libgmp.a
-rwxr-xr-x 1 builduser users    1116 Oct  7  2018 libgmp.la
lrwxrwxrwx 1 builduser users      16 Oct  7  2018 libgmp.so -> libgmp.so.10.3.2
lrwxrwxrwx 1 builduser users      16 Oct  7  2018 libgmp.so.10 -> libgmp.so.10.3.2
-rwxr-xr-x 1 builduser users  539464 Oct  7  2018 libgmp.so.10.3.2
-rw-r--r-- 1 builduser users   52506 Oct  7  2018 libgmpxx.a
-rwxr-xr-x 1 builduser users    1099 Oct  7  2018 libgmpxx.la
lrwxrwxrwx 1 builduser users      17 Oct  7  2018 libgmpxx.so -> libgmpxx.so.4.5.2
lrwxrwxrwx 1 builduser users      17 Oct  7  2018 libgmpxx.so.4 -> libgmpxx.so.4.5.2
-rwxr-xr-x 1 builduser users   38632 Oct  7  2018 libgmpxx.so.4.5.2

> locate /gmp.h

[builduser@spinon include]$ ls -l /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/include/
total 65
-rw-r--r-- 1 builduser users  83703 Oct  7  2018 gmp.h
-rw-r--r-- 1 builduser users 116607 Oct  7  2018 gmpxx.h

> module show GMP/6.1.2-GCCcore-7.3.0

[builduser@spinon include]$ module show GMP/6.1.2-GCCcore-7.3.0
-------------------------------------------------------------------
/share/apps/eb2/modules/all//GMP/6.1.2-GCCcore-7.3.0:

module-whatis	 Description:
 GMP is a free library for arbitrary precision arithmetic, operating on signed
 integers, rational numbers, and floating point numbers.

module-whatis	 Homepage: http://gmplib.org/
conflict	 GMP
module		 load GCCcore/7.3.0
prepend-path	 CPATH /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/include
prepend-path	 LD_LIBRARY_PATH /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib
prepend-path	 LIBRARY_PATH /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib
setenv		 EBROOTGMP /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0
setenv		 EBVERSIONGMP 6.1.2
setenv		 EBDEVELGMP /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/easybuild/GMP-6.1.2-GCCcore-7.3.0-easybuild-devel
-------------------------------------------------------------------
> ldd your_work_dir/triqs.install/lib/libtriqs.so
For the version that I had now compiled with manually set GMP_LIBRARIES I get:

	linux-vdso.so.1 =>  (0x00007ffd20bae000)
	libpython2.7.so.1.0 => /share/apps/eb2/software/Python/2.7.15-foss-2018b/lib/libpython2.7.so.1.0 (0x00007f9c4f92c000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f9c4f709000)
	libmpi.so.40 => /share/apps/eb2/software/OpenMPI/3.1.1-GCC-7.3.0-2.30/lib/libmpi.so.40 (0x00007f9c4f600000)
	libopenblas.so.0 => /share/apps/eb2/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/lib/libopenblas.so.0 (0x00007f9c4e835000)
	libhdf5.so.103 => /share/apps/eb2/software/HDF5/1.10.4-foss-2018b-serial/lib/libhdf5.so.103 (0x00007f9c4e4a5000)
	libsz.so.2 => /share/apps/eb2/software/Szip/2.1.1-GCCcore-7.3.0/lib/libsz.so.2 (0x00007f9c4e48d000)
	libz.so.1 => /share/apps/eb2/software/zlib/1.2.11-GCCcore-7.3.0/lib/libz.so.1 (0x00007f9c4e475000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f9c4e271000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f9c4e054000)
	libhdf5_hl.so.100 => /share/apps/eb2/software/HDF5/1.10.4-foss-2018b-serial/lib/libhdf5_hl.so.100 (0x00007f9c4e030000)
	libgmp.so.10 => /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib/libgmp.so.10 (0x00007f9c4dfb7000)
	libgmpxx.so.4 => /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib/libgmpxx.so.4 (0x00007f9c4dfae000)
	libfftw3.so.3 => /share/apps/eb2/software/FFTW/3.3.8-gompi-2018b/lib/libfftw3.so.3 (0x00007f9c4de1f000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9c4db1d000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f9c4d919000)
	libstdc++.so.6 => /share/apps/eb2/software/GCCcore/7.3.0/lib64/libstdc++.so.6 (0x00007f9c4d780000)
	libgcc_s.so.1 => /share/apps/eb2/software/GCCcore/7.3.0/lib64/libgcc_s.so.1 (0x00007f9c4d768000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f9c4d3a4000)
	libopen-rte.so.40 => /share/apps/eb2/software/OpenMPI/3.1.1-GCC-7.3.0-2.30/lib/libopen-rte.so.40 (0x00007f9c4d2ec000)
	libopen-pal.so.40 => /share/apps/eb2/software/OpenMPI/3.1.1-GCC-7.3.0-2.30/lib/libopen-pal.so.40 (0x00007f9c4d224000)
	libhwloc.so.5 => /share/apps/eb2/software/hwloc/1.11.10-GCCcore-7.3.0/lib/libhwloc.so.5 (0x00007f9c4d1e1000)
	libnuma.so.1 => /share/apps/eb2/software/numactl/2.0.11-GCCcore-7.3.0/lib/libnuma.so.1 (0x00007f9c4d1d4000)
	libpciaccess.so.0 => /share/apps/eb2/software/libpciaccess/0.14-GCCcore-7.3.0/lib/libpciaccess.so.0 (0x00007f9c4d1ca000)
	libxml2.so.2 => /share/apps/eb2/software/libxml2/2.9.8-GCCcore-7.3.0/lib/libxml2.so.2 (0x00007f9c4d05f000)
	liblzma.so.5 => /share/apps/eb2/software/XZ/5.2.4-GCCcore-7.3.0/lib/liblzma.so.5 (0x00007f9c4d038000)
	libgfortran.so.4 => /share/apps/eb2/software/GCCcore/7.3.0/lib64/libgfortran.so.4 (0x00007f9c4ce61000)
	libgomp.so.1 => /share/apps/eb2/software/GCCcore/7.3.0/lib64/libgomp.so.1 (0x00007f9c4ce32000)
	/lib64/ld-linux-x86-64.so.2 (0x000055e89fa24000)
	libquadmath.so.0 => /share/apps/eb2/software/GCCcore/7.3.0/lib64/libquadmath.so.0 (0x00007f9c4cdf1000)

> printenv | grep LIBRARY

LIBRARY_PATH=/share/apps/eb2/software/HDF5/1.10.4-foss-2018b-serial/lib:/share/apps/eb2/software/Szip/2.1.1-GCCcore-7.3.0/lib:/share/apps/eb2/software/Clang/7.0.1-GCC-7.3.0-2.30/lib:/share/apps/eb2/software/Boost/1.68.0-foss-2018b-Python-2.7.15/lib:/share/apps/eb2/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/numpy-1.14.5-py2.7-linux-x86_64.egg/numpy/core/lib:/share/apps/eb2/software/Python/2.7.15-foss-2018b/lib:/share/apps/eb2/software/libffi/3.2.1-GCCcore-7.3.0/lib64:/share/apps/eb2/software/libffi/3.2.1-GCCcore-7.3.0/lib:/share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib:/share/apps/eb2/software/SQLite/3.24.0-GCCcore-7.3.0/lib:/share/apps/eb2/software/Tcl/8.6.8-GCCcore-7.3.0/lib:/share/apps/eb2/software/libreadline/7.0-GCCcore-7.3.0/lib:/share/apps/eb2/software/ncurses/6.1-GCCcore-7.3.0/lib:/share/apps/eb2/software/bzip2/1.0.6-GCCcore-7.3.0/lib:/share/apps/eb2/software/ScaLAPACK/2.0.2-gompi-2018b-OpenBLAS-0.3.1/lib:/share/apps/eb2/software/FFTW/3.3.8-gompi-2018b/lib:/share/apps/eb2/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/lib:/share/apps/eb2/software/OpenMPI/3.1.1-GCC-7.3.0-2.30/lib:/share/apps/eb2/software/hwloc/1.11.10-GCCcore-7.3.0/lib:/share/apps/eb2/software/libpciaccess/0.14-GCCcore-7.3.0/lib:/share/apps/eb2/software/libxml2/2.9.8-GCCcore-7.3.0/lib:/share/apps/eb2/software/XZ/5.2.4-GCCcore-7.3.0/lib:/share/apps/eb2/software/numactl/2.0.11-GCCcore-7.3.0/lib:/share/apps/eb2/software/zlib/1.2.11-GCCcore-7.3.0/lib:/share/apps/eb2/software/binutils/2.30-GCCcore-7.3.0/lib:/share/apps/eb2/software/GCCcore/7.3.0/lib64:/share/apps/eb2/software/GCCcore/7.3.0/lib
LD_LIBRARY_PATH=/share/apps/eb2/software/HDF5/1.10.4-foss-2018b-serial/lib:/share/apps/eb2/software/Szip/2.1.1-GCCcore-7.3.0/lib:/share/apps/eb2/software/Clang/7.0.1-GCC-7.3.0-2.30/lib:/share/apps/eb2/software/Boost/1.68.0-foss-2018b-Python-2.7.15/lib:/share/apps/eb2/software/Python/2.7.15-foss-2018b/lib/python2.7/site-packages/numpy-1.14.5-py2.7-linux-x86_64.egg/numpy/core/lib:/share/apps/eb2/software/Python/2.7.15-foss-2018b/lib:/share/apps/eb2/software/libffi/3.2.1-GCCcore-7.3.0/lib64:/share/apps/eb2/software/libffi/3.2.1-GCCcore-7.3.0/lib:/share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib:/share/apps/eb2/software/SQLite/3.24.0-GCCcore-7.3.0/lib:/share/apps/eb2/software/Tcl/8.6.8-GCCcore-7.3.0/lib:/share/apps/eb2/software/libreadline/7.0-GCCcore-7.3.0/lib:/share/apps/eb2/software/ncurses/6.1-GCCcore-7.3.0/lib:/share/apps/eb2/software/bzip2/1.0.6-GCCcore-7.3.0/lib:/share/apps/eb2/software/ScaLAPACK/2.0.2-gompi-2018b-OpenBLAS-0.3.1/lib:/share/apps/eb2/software/FFTW/3.3.8-gompi-2018b/lib:/share/apps/eb2/software/OpenBLAS/0.3.1-GCC-7.3.0-2.30/lib:/share/apps/eb2/software/OpenMPI/3.1.1-GCC-7.3.0-2.30/lib:/share/apps/eb2/software/hwloc/1.11.10-GCCcore-7.3.0/lib:/share/apps/eb2/software/libpciaccess/0.14-GCCcore-7.3.0/lib:/share/apps/eb2/software/libxml2/2.9.8-GCCcore-7.3.0/lib:/share/apps/eb2/software/XZ/5.2.4-GCCcore-7.3.0/lib:/share/apps/eb2/software/numactl/2.0.11-GCCcore-7.3.0/lib:/share/apps/eb2/software/zlib/1.2.11-GCCcore-7.3.0/lib:/share/apps/eb2/software/binutils/2.30-GCCcore-7.3.0/lib:/share/apps/eb2/software/GCCcore/7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0:/share/apps/eb2/software/GCCcore/7.3.0/lib64:/share/apps/eb2/software/GCCcore/7.3.0/lib:/share/apps/lib:/share/apps/lib

> —
> 
> Also, if you run the previous (problematic) version of your build script, what does the CMake configuration for triqs show in that case during the GMP detection?
> 
> ...
> -- -------- GMP detection -------------
> -- GMP libs: /usr/lib64/libgmp.so /usr/lib64/libgmpxx.so
> -- Found GMP: /usr/include  

If I don’t do anything:

-- -------- GMP detection -------------
-- GMP libs: GMP_LIBRARIES-NOTFOUND GMPXX_LIBRARIES-NOTFOUND
-- Could NOT find GMP (missing: GMP_INCLUDE_DIR GMP_LIBRARIES)

For the incorrectly set GMP_LIBRARIES and GMPXX_LIBRARIES variables:

-- -------- GMP detection -------------
-- GMP libs: /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib

For the manually set variables, which now works:

-- -------- GMP detection -------------
-- GMP libs: /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib/libgmp.so /share/apps/eb2/software/GMP/6.1.2-GCCcore-7.3.0/lib/libgmpxx.so



btw, the following tests failed:

Total Test time (real) = 202.71 sec

The following tests FAILED:
	198 - atom_diag_python (Failed)
	201 - operator_python2 (Failed)
	206 - gf_init (Failed)
	208 - gf_base_op (Failed)
	213 - pade (Failed)
	216 - hdf5_meshBZ (Failed)
	224 - block_matrix (Failed)
	225 - gf_tensor_valued (Failed)
	226 - histograms (Failed)
	229 - multivar (Failed)
	231 - g_k_om (Failed)
	232 - block2 (Failed)
	234 - wrap_a (Failed)
	237 - wrap_multivar (Failed)
Errors while running CTest
make: *** [test] Error 8


Looks like HDF5/h5py related errors. hdf5_meshBZ.err contains the following:

Traceback (most recent call last):
  File "/share/apps/TRIQS/TRIQS-2.1-foss2018b/triqs.src/test/pytriqs/base/hdf5_meshBZ.py", line 23, in <module>
    s['ek'] = ek
  File "/share/apps/TRIQS/TRIQS-2.1-foss2018b/triqs.build/pytriqs/archive/hdf_archive.py", line 194, in __setitem__
    for n,v in d.items() : SUB[n] = v
  File "/share/apps/TRIQS/TRIQS-2.1-foss2018b/triqs.build/pytriqs/archive/hdf_archive.py", line 184, in __setitem__
    val.__write_hdf5__(self._group,key)
TypeError: Internal error : invalid id from h5py !


Are these known problems with HDF5 1.10.4 ? I guess I should open a new issue on github..


Kind regards,
Rok

**Comment by rokzitko** [comment]
> On 27 Jun 2019, at 16:29, Rok Žitko <rok.zitko@ijs.si> wrote:
> 
> Are these known problems with HDF5 1.10.4 ? I guess I should open a new issue on github..

FYI, HDF5 1.10.2 seems to work fine, all tests pass.

Why is a serial version of HDF5 “preferred”, but considered a fatal error, making the build fail? I’ve commented out the following test and tried a parallel version of HDF5, and the build of TRIQS is successful and all tests pass.

if(HDF5_IS_PARALLEL)
 message(FATAL_ERROR "parallel(MPI) hdf5 is detected. The standard version is preferred.")
endif(HDF5_IS_PARALLEL)


Kind regards,
Rok

**Comment by Wentzell** [comment]
Hey Rok,

The findGMP module in triqs was indeed very primitive. I have updated it and it should now find the
library as long as you have the module loaded. Please try compiling the triqs unstable branch
on your cluster and let me know if that leads to any problems.

> Why is a serial version of HDF5 “preferred”, but considered a fatal error, making the build fail? I’ve commented out the following test and tried a parallel version of HDF5, and the build of TRIQS is successful and all tests pass.

This check has been there for a long time and was initially ported over from the ALPS cmake files.
It is not clear why the serial version was enforced back then, but I agree that the parallel version
does not lead to any test failures.

I have for now changed the message from ```FATAL_ERROR``` to ```WARNING``` on unstable and we will be testing with the parallel version of hdf5 on our testing machine including all applications very soon.

**Comment by rokzitko** [comment]
Dear Niels,

Both problems are now solved: GMP is detected properly and I can use our parallel HDF5 build. Thank you for assistance!

I've prepared an "easyconfig" file for EasyBuild build system (https://easybuild.readthedocs.io/en/latest/ <https://easybuild.readthedocs.io/en/latest/>). It takes care of installing all dependencies, builds and installs TRIQS, and produces a module file with all the required environment variables. It might be helpful for those that want to build TRIQS from sources. 
After next release of TRIQS, I can prepare an updated easyconfig that can be committed to EasyBuild's repository.
Also, as an added benefit, EasyBuild also makes it very easy to automatically create Singularity containers.

Kind regards,
Rok

**Comment by rokzitko** [comment]
[TRIQS-2.1.x-unstable-foss-2018b.eb.zip](https://github.com/TRIQS/triqs/files/3337968/TRIQS-2.1.x-unstable-foss-2018b.eb.zip)

**Comment by Wentzell** [comment]
Hey Rok,

Thank you for providing the EasyBuild script! Could you make a pull request that adds this file as
triqs-unstable.eb to the packaging directory of the TRIQS repository?

I had a quick look and the file and only noticed that you use ```2.1.0``` together with ```-unstable``` in the
filename for the sources. In principle the current unstable is TRIQS version ```2.2.0``` in development.
Maybe the filename could be ```TRIQS-unstable.tar.gz```, potentially including also the commit hash?

It would be great to add this to the EasyBuild repository for the upcoming release.

**Comment by Wentzell** [comment]
Hey Rok,

Would you do the PR or do you want me to just add the file for you?

Also, what would be necessary for you to be able to add the 2.1.1 release to the EasyBuild repository?
I could backport both the parallel hdf5 and gmp fixes to 2.1.x.

**Comment by rokzitko** [comment]
Dear Niels,
> Would you do the PR or do you want me to just add the file for you?
> 
> Also, what would be necessary for you to be able to add the 2.1.1 release to the EasyBuild repository?
> I could backport both the parallel hdf5 and gmp fixes to 2.1.x.
> 
> 

Sorry for not replying sooner, I am travelling.
Yes, it would make more sense to produce an EasyBuild config for a tagged release of TRIQS. If you produce 2.1.1 with the backported fixes, let me know, I’ll modify the EasyConfig, test it, and then I can do a PR to both TRIQS as well as EasyBuild package collection.

Kind regards,
Rok

**Comment by Wentzell** [comment]
Hey Rok,

I have updated the 2.1.x branch accordingly. Could you check that everything works with
EasyBuild for the 2.1.x branch?

It would be nice to include the triqs-2.1.1.eb file also in the 2.1.1 release itself.
Can you prepare the file and create a PR to unstable?
I will then replay the commit also on 2.1.x before tagging 2.1.1.

Best,

Nils

**Comment by rokzitko** [comment]
Dear Niels,

2.1.x branch works fine now. As for including the easyconfig file, it's a bit of a chicken and egg situation: for testing the eb file, it would be nice to already have a release ready (with a tag, so that the suitable file can be picked up from https://github.com/TRIQS/triqs/releases <https://github.com/TRIQS/triqs/releases>).  Nevertheless, I prepared a pull request, https://github.com/TRIQS/triqs/pull/723 <https://github.com/TRIQS/triqs/pull/723>

Kind regards,
Rok

**Comment by Wentzell** [comment]
Hey Rok,

I have created the 2.1.1 tag on my fork [github.com/Wentzell/triqs](github.com/Wentzell/triqs).
Could you try your EasyBuild script against this release and let me know if everything works?
I will then push the 2.1.1 tag to the main repo.

Best,

Nils

**Comment by rokzitko** [comment]
Dear Niels,

Yes, it works after a small fix to TRIQS-2.1.1-foss-2018b.eb:

20c20
< source_urls = ['https://github.com/TRIQS/triqs/archive/']
---
> source_urls = ['https://github.com/TRIQS/triqs/releases/']

Already committed & pushed to my triqs fork.

Kind regards,
Rok

**Comment by Wentzell** [comment]
Great! I have included your fix and tagged 2.1.1.
You can go ahead with the PR to the EasyBuild repository.

**Comment by Wentzell** [comment]
Thank you again for the effort!

**Comment by Wentzell** [comment]
@rokzitko Did you end up creating a PR to the EasyBuild repositories?
Would you mind writing up a small tutorial for the TRIQS website on how to use the build script?

**Comment by rokzitko** [comment]
Dear Niels,

That is still in progress, see here: https://github.com/easybuilders/easybuild-easyconfigs/pull/8835 <https://github.com/easybuilders/easybuild-easyconfigs/pull/8835>
I’ve fixed most minor issues, but the TRIQS test suite seems to fail on Intel Skylake. The logs show that the following two tests fail:

136/238 Test #136: g_om_nu_nup ......................***Exception: SegFault 0.27 sec
237/238 Test #237: wrap_multivar ....................***Failed 0.54 sec

(…)

99% tests passed, 2 tests failed out of 238
Total Test time (real) = 205.06 sec
The following tests FAILED:
136 - g_om_nu_nup (SEGFAULT)
237 - wrap_multivar (Failed)
Errors while running CTest


See here for details: https://gist.github.com/boegel/42d4413b6d8c98cac312f093b36dbe6f <https://gist.github.com/boegel/42d4413b6d8c98cac312f093b36dbe6f>

Kind regards,
Rok

**Comment by Wentzell** [comment]
Dear @rokzitko,

I tried to reproduce the failures on my skylake machine but couldn't.
Were you able to reproduce the failures yourself?

**Comment by rokzitko** [comment]
Works fine here on Opteron 63xx, Epyc 1, and Sandy Bridge. Also completed OK on Haswell and Broadwell on EasyBuild CI servers. Only Skylake was problematic.

**Comment by rokzitko** [comment]
I received a report that the same 2 tests failed on another Skylake machine. It’s certainly Skylake specific, but not necessarily related to TRIQS itself, it could be a problem in one of the dependencies.

**Comment by Wentzell** [comment]
I only did a conventional build from source on my skylake machine with `-march=skylake`.
I will look into actually building the easy build script as soon as I find time and let you know if I can
reproduce the problem then!

**Comment by rokzitko** [comment]
Ok. btw, I can prepare a documentation page about building TRIQS with EB. Can you point me to the documentation section where it would be located, so that I can match the style and level?

**Comment by Wentzell** [comment]
I was thinking to have a small section within the Installation page.
Something along the lines of the [singularity section](https://triqs.github.io/triqs/unstable/install.html#singularity) on the TRIQS website.
For this you would create a PR to the triqs unstable branch for the file [install.rst](https://github.com/TRIQS/triqs/blob/unstable/doc/install.rst).
If it ends up getting longer we can outsource it to a separate page.

Note that we have recently added some [useful instructions](https://triqs.github.io/triqs/unstable/contributing/documentation.html) on how to contribute to the doc pages.
