### ISSUE TITLE
JATIN19960

### ISSUE THREAD

**Issue by JATIN199604** [TRIQS/triqs#728]

**Comment by JATIN199604** [comment]
Dear Nils,
I did not resolve the make test errors, as I did not get enough information
to solve it. The make install run with out any error. Now I am runing the
program to find the magnetic properties of NiO. I am getting this error.

[jatin@MeghaMala NiO]$ dmftproj
bash: dmftproj: command not found...

How can I resolve the error.
I will be thankful for your suggestion.

Regards,
Jatin

**Comment by Wentzell** [comment]
dmftproj is not a triqs command, it is part of [dft_tools](https://github.com/triqs/dft_tools).
Since you are using Ubuntu 18.04 you should use the apt packages that we provide.

**Comment by JATIN199604** [comment]
Dear Nils,
I have successfully run the dmftproj program for compound  SrVO3. When I
initialize with help of the given python script, I am getting this error.
  jatin@jatin-HP-Laptop-14s-cr1xxx:~/SrVO3$ pytriqs SrVO3.py
pytriqs: command not found

I will be thankful for your suggestion.

Regards,
Jatin

**Comment by Wentzell** [comment]
You should not use the `pytriqs` command but rather just `python`.
Be sure that you have loaded your triqs installation previously with
```bash
source path_to_triqs_install_dir/share/triqsvars.sh
```

**Comment by JATIN199604** [comment]
Dear Nils,
I run the python script using python command. There is no any output by the
converter for the hdf5 file. Here I am giving the python scrip with the
commands.

jatin@jatin-HP-Laptop-14s-cr1xxx:~/SrVO3$ python SrVO3.py
Starting on 1 Nodes at : 2019-08-02 10:37:58.105760
jatin@jatin-HP-Laptop-14s-cr1xxx:~/SrVO3$ Converter.convert_dft_input()
>

Thank you for your quick suggestion.

Regards,
Jatin

**Comment by Wentzell** [comment]
Please address dft_tools related issues to the [triqs/dft_tools](https://github.com/triqs/dft_tools) issue list. Note that detailed set-by-step tutorials for dft_tools can be found [here](https://triqs.github.io/dft_tools/2.1.x/tutorials.html)
