### ISSUE TITLE
Unexpected behaviour / bug when printing Operators

### ISSUE THREAD

**Issue by hschnait** [TRIQS/triqs#729]
Dear all!

I found some unexpected behaviour when printing second-quantization operators (created using `h_int_slater`) with a complex U-Matrix (tested both with 2.1.x and unstable).

With a real-valued, real-type U-Matrix everything runs as expected
```
from pytriqs.operators.util import *
from pytriqs.operators.util.U_matrix import *
import numpy as np

U_real = np.full((3,3,3,3), 0)
U_real[0,1,1,0] = 1
U_real[2,1,1,0] = 1
U_real[0,1,1,2] = 1

print h_int_slater(['up'],range(3), U_real, off_diag=True, complex=True)
print h_int_slater(['up'],range(3), U_real, off_diag=True, complex=False)
```

> 0.5*c_dag('up',0)*c_dag('up',1)*c('up',2)*c('up',1) + -0.5*c_dag('up',0)*c_dag('up',1)*c('up',1)*c('up',0) + 0.5*c_dag('up',1)*c_dag('up',2)*c('up',1)*c('up',0)
> 
> 0.5*c_dag('up',0)*c_dag('up',1)*c('up',2)*c('up',1) + -0.5*c_dag('up',0)*c_dag('up',1)*c('up',1)*c('up',0) + 0.5*c_dag('up',1)*c_dag('up',2)*c('up',1)*c('up',0)

Now we take U as `np.complex` but leave the same (real) entries:
```
U_c0 = np.full((3,3,3,3), 0, np.complex)
U_c0[0,1,1,0] = 1
U_c0[2,1,1,0] = 1
U_c0[0,1,1,2] = 1

h = h_int_slater(['up'],range(3), U_c0, off_diag=True, complex=True)
print h
print h_int_slater(['up'],range(3), U_c0, off_diag=True, complex=False)

for elem in h:
    print elem
```

> (0.50j)*c_dag('up',0)*c_dag('up',1)*c('up',2)*c('up',1) + (-0.5-0j)*c_dag('up',0)*c_dag('up',1)*c('up',1)*c('up',0) + (0.50j)*c_dag('up',1)*c_dag('up',2)*c('up',1)*c('up',0)
>
> 0.5*c_dag('up',0)*c_dag('up',1)*c('up',2)*c('up',1) + -0.5*c_dag('up',0)*c_dag('up',1)*c('up',1)*c('up',0) + 0.5*c_dag('up',1)*c_dag('up',2)*c('up',1)*c('up',0)
>
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 2]), (False, ['up', 1])], (0.5+0j))
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 1]), (False, ['up', 0])], (-0.5-0j))
> ([(True, ['up', 1]), (True, ['up', 2]), (False, ['up', 1]), (False, ['up', 0])], (0.5+0j))

As you can see, even though the elements are all real, when printing the whole operator, `j`s are added for every positive (i guess...) coefficient.

When using a complex-valued U-matrix with some complex entries, the complex elements get printed correctly, while the real-valued (positive) elements still get an additional `j`:
```
U_c = np.full((3,3,3,3), 0, np.complex)
U_c[0,1,1,0] = 1
U_c[2,1,1,0] = 1j
U_c[0,1,1,2] = 1

h1 = h_int_slater(['up'],range(3), U_c, off_diag=True, complex=True)
print h1
for elem in h1:
    print elem
print h_int_slater(['up'],range(3), U_c, off_diag=True, complex=False)
```

> (0.50j)*c_dag('up',0)*c_dag('up',1)*c('up',2)*c('up',1) + (-0.5-0j)*c_dag('up',0)*c_dag('up',1)*c('up',1)*c('up',0) + (-0+0.5j)*c_dag('up',1)*c_dag('up',2)*c('up',1)*c('up',0)
> 
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 2]), (False, ['up', 1])], (0.5+0j))
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 1]), (False, ['up', 0])], (-0.5-0j))
> ([(True, ['up', 1]), (True, ['up', 2]), (False, ['up', 1]), (False, ['up', 0])], (-0+0.5j))
> 
> RuntimeError: Matrix elements of U are not real.  (as expected)

For reference, here is the output when running the script in 1.4:

> U_real
> 0.5*C^+(up,0)C^+(up,1)C(up,2)C(up,1) + -0.5*C^+(up,0)C^+(up,1)C(up,1)C(up,0) + 0.5*C^+(up,1)C^+(up,2)C(up,1)C(up,0)
> 0.5*C^+(up,0)C^+(up,1)C(up,2)C(up,1) + -0.5*C^+(up,0)C^+(up,1)C(up,1)C(up,0) + 0.5*C^+(up,1)C^+(up,2)C(up,1)C(up,0)
> 
> 
> U_c0
> (0.5,0)*C^+(up,0)C^+(up,1)C(up,2)C(up,1) + (-0.5,-0)*C^+(up,0)C^+(up,1)C(up,1)C(up,0) + (0.5,0)*C^+(up,1)C^+(up,2)C(up,1)C(up,0)
> 0.5*C^+(up,0)C^+(up,1)C(up,2)C(up,1) + -0.5*C^+(up,0)C^+(up,1)C(up,1)C(up,0) + 0.5*C^+(up,1)C^+(up,2)C(up,1)C(up,0)
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 2]), (False, ['up', 1])], (0.5+0j))
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 1]), (False, ['up', 0])], (-0.5-0j))
> ([(True, ['up', 1]), (True, ['up', 2]), (False, ['up', 1]), (False, ['up', 0])], (0.5+0j))
> 
> 
> U_c
> (0.5,0)*C^+(up,0)C^+(up,1)C(up,2)C(up,1) + (-0,-0.5)*C^+(up,0)C^+(up,1)C(up,1)C(up,0) + (0.5,0)*C^+(up,1)C^+(up,2)C(up,1)C(up,0)
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 2]), (False, ['up', 1])], (0.5+0j))
> ([(True, ['up', 0]), (True, ['up', 1]), (False, ['up', 1]), (False, ['up', 0])], (-0-0.5j))
> ([(True, ['up', 1]), (True, ['up', 2]), (False, ['up', 1]), (False, ['up', 0])], (0.5+0j))

**Comment by Wentzell** [comment]
Dear @hschnait,

Thanks for pointing this out!
I have fixed this in commit 5ac2c560
