### ISSUE TITLE
jupyter notebook fails in latest triqs images docker

### ISSUE THREAD

**Issue by ghost** [TRIQS/triqs#730]
In latest version of docker images, docker run command for jupyter notebook show empty folder and cannot create any new notebook nor use terminal within jupyter. please fix.

**Comment by Wentzell** [comment]
Hi @muhammadgaffar,

Thank you for pointing this out! I have corrected this issue in https://github.com/TRIQS/docker/commit/6283e0f6e792deace06801723356b7516af5dea7
You should be able to ```docker pull``` the corrected image in 30 minutes.
