### ISSUE TITLE
Error in make during TRIQS installation  

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/triqs#738]
Dear All,
I am getting this error during make.

/TRIQS/triqs.build$ make
[  1%] Built target cpp2py
[  2%] Built target gtest
[ 11%] Built target triqs
[ 12%] Linking CXX shared module block_matrix.so
/usr/bin/x86_64-linux-gnu-ld: /usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
pytriqs/arrays/CMakeFiles/block_matrix.dir/build.make:132: recipe for target 'pytriqs/arrays/block_matrix.so' failed
make[2]: *** [pytriqs/arrays/block_matrix.so] Error 1
CMakeFiles/Makefile2:470: recipe for target 'pytriqs/arrays/CMakeFiles/block_matrix.dir/all' failed
make[1]: *** [pytriqs/arrays/CMakeFiles/block_matrix.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I will be thankful for your suggestion.

Best Regards,
CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

Which version of triqs are you trying to compile and what is your operating system.

**Comment by cmtcl18** [comment]
Dear Sir,
Now I am following TRIQS version 2.1.x with operating system Ubuntu 18.04.3 LTS.
During make test, out of 239 tests 7 tests are not passed. I am getting this error now.

Errors while running CTest
Makefile:129: recipe for target 'test' failed
make: *** [test] Error 8

I will be thankful for your suggestion.

Best Regards,
CMTCL

**Comment by cmtcl18** [comment]
Dear Sir, 
For more information, I am giving the tests which are failed.

The following tests FAILED:
	159 - mpi_array_np2 (Failed)
	160 - mpi_array_np3 (Failed)
	161 - mpi_array_np4 (Failed)
	163 - mpi_gf_np2 (Failed)
	164 - mpi_gf_np3 (Failed)
	165 - mpi_gf_np4 (Failed)
	167 - mpi_histogram_np2 (Failed)
	168 - mpi_histogram_np3 (Failed)
	169 - mpi_histogram_np4 (Failed)
	171 - mpi_vector_np2 (Failed)
	172 - mpi_vector_np3 (Failed)
	173 - mpi_vector_np4 (Failed)
	174 - comm_split_np4 (Failed)
	175 - vector_zero_length_np4 (Failed)
	198 - atom_diag_python (Failed)
	204 - gf_imfreq (Failed)
	205 - gf_block (Failed)
	207 - gf_density (Failed)
	208 - gf_base_op (Failed)
	209 - gf_fourier (Failed)
	211 - g_tau_mul_py (Failed)
	212 - dos (Failed)
	216 - hdf5_meshBZ (Failed)
	219 - issue649 (Failed)
	220 - bug_tight_binding (Failed)
	221 - bug_bcast_mesh (Failed)
	222 - tail_issues (Failed)
	223 - gf_eval (Failed)
	225 - block_matrix (Failed)
	227 - histograms (Failed)
	228 - histogram_bcast (Failed)
	229 - brillouin_zone (Failed)
	232 - g_k_om (Failed)
Errors while running CTest
Makefile:129: recipe for target 'test' failed
make: *** [test] Error 8


Best Regards,
CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

For Ubuntu 18.04 please install the Ubuntu packages instead of compiling the source code yourself.
Follow the steps outlined here
https://triqs.github.io/triqs/2.1.x/install.html#ubuntu-debian-packages-experimental
If you run into any trouble installing the Ubuntu packages feel free to open a related issue.

Thank you!
