### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by cmtcl18** [TRIQS/triqs#740]
Dear Sir,
I install the Ubuntu packages.
 During cmake ../triqs.src -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX,  I am getting this error.

cmake ../triqs.src -DCMAKE_INSTALL_PREFIX=$/home/mayank/TRIQS/install
CMake Error at CMakeLists.txt:28 (message):
  CMAKE_INSTALL_PREFIX must be specified and must be an absolute path.
   There is no default.
   Current value : $/home/mayank/TRIQS/install

  .  e.g.  ...  -DCMAKE_INSTALL_PREFIX=$HOME/triqs_install

-- Configuring incomplete, errors occurred!

The output of CMakeLists.txt:28 is 

if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT OR (NOT IS_ABSOLUTE ${CMAKE_INSTALL_PREFIX}))
 message(FATAL_ERROR "CMAKE_INSTALL_PREFIX must be specified and must be an absolute path.\n There is no default.\n Current value : ${CMAKE_INSTALL_PREFIX}\n.  e.g. ... -DCMAKE_INSTALL_PREFIX=$HOME/triqs_install")
endif()

Thank you for your response.

Best Regards,
CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

You are not using our ubuntu packages!
You are instead trying to compile the code from source.

Please follow the steps outlined in the section [**Ubuntu Debian packages (experimental)**](https://triqs.github.io/triqs/2.1.x/install.html#ubuntu-debian-packages-experimental)

Do **NOT** run any of the commands in **Compiling TRIQS from source (Advanced)**.

**Comment by cmtcl18** [comment]
Dear Sir,
I followed the steps of Ubuntu Debian packages(experimental). Now I got this error.

sudo add-apt-repository "deb https://users.flatironinstitute.org/~ccq/triqs/$DISTRIB_CODENAME/ /"
Hit:1 http://linux.teamviewer.com/deb stable InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                
Hit:3 https://users.flatironinstitute.org/~ccq/triqs/bionic  InRelease           
Err:4 http://in.archive.ubuntu.com/ubuntu bionic InRelease
  500  Internal Server Error [IP: 103.123.234.254 80]
Err:5 http://in.archive.ubuntu.com/ubuntu bionic-updates InRelease
  500  Internal Server Error [IP: 103.123.234.254 80]
Hit:6 http://in.archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists... Done
W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/bionic/InRelease  500  Internal Server Error [IP: 103.123.234.254 80]
W: Failed to fetch http://in.archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease  500  Internal Server Error [IP: 103.123.234.254 80]
W: Some index files failed to download. They have been ignored, or old ones used instead.

Thanks and Regards,
CMTCL

**Comment by cmtcl18** [comment]
Dear Sir,
I resolved the above error. 
During cmake ../triqs.src -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX, I am getting this error

 cmake ../triqs.src -DCMAKE_INSTALL_PREFIX=$/home/mayank/TRIQS/install
CMake Error at CMakeLists.txt:28 (message):
  CMAKE_INSTALL_PREFIX must be specified and must be an absolute path.

   There is no default.
   Current value : $/home/mayank/TRIQS/install

  .  e.g.  ...  -DCMAKE_INSTALL_PREFIX=$HOME/triqs_install


-- Configuring incomplete, errors occurred!

 I have not run the  commands in  source (Advanced), still it is showing the same error.

Best Regards,
CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

I can only repeat myself...
You should **not** run the `cmake ../triqs.src` command which is part of the **Compile TRIQS from Source** section. Instead you should follow the steps in [**Ubuntu Debian packages (experimental)**](https://triqs.github.io/triqs/2.1.x/install.html#ubuntu-debian-packages-experimental).

The relevant commands
```bash
sudo apt-get update && sudo apt-get install -y software-properties-common apt-transport-https curl
source /etc/lsb-release
curl -L https://users.flatironinstitute.org/~ccq/triqs/$DISTRIB_CODENAME/public.gpg | sudo apt-key add -
sudo add-apt-repository "deb https://users.flatironinstitute.org/~ccq/triqs/$DISTRIB_CODENAME/ /"
sudo apt-get update && sudo apt-get install -y triqs
```
should be run on the command-line in the order provided.

**Comment by cmtcl18** [comment]
Dear Sir, 
I compiled TRIQS from Ubuntu Debian packages (experimental). Now I need to install DFTTools and CTHYB. For these installation, shall I compile  from source along with the command from  Debian packages or I need to follow the Debain packages only.  


Best Regards,
CMTCL

**Comment by Wentzell** [comment]
You should install the ubuntu packages
```bash
sudo apt-get install -y triqs_cthyb triqs_dft_tools
```

**Comment by cmtcl18** [comment]
Dear Sir,
As per your suggestion, I installed the Ubuntu packages for CTHYB and DFTTools. I want to run SrVO3. during dmftproj, I am getting the following error. 

wien2k_19/SrVO3$ dmftproj
Welcome in DMFTPROJ: PROJECTION TO LOCALIZED BASIS


This prgm will build the Wannier projectors to the
localized orbitals of an atom onto which DMFT will be applied.


You are performing a computation
without Spin-Orbit.
using Paramagnetic Wien2k input files.
=======================================
Sorts of atoms =   3
Equivalent sites per each sort: 3 1 1


-------------------------------------
For the sort  1 :
The orbital l= 0 is included.

-------------------------------------
For the sort  2 :
The orbital l= 0 is included.
The orbital l= 1 is included.
The orbital l= 2 is included.

-------------------------------------
For the sort  3 :
The orbital l= 0 is included.
The orbital l= 1 is included.


The Eigenstates are projected in an energy window from   -0.11000 Ry  to     0.14000 Ry around the Fermi level.


=======================================
Basis representation for each sort.

At line 140 of file /src/triqs_dft_tools/fortran/dmftproj/set_ang_trans.f
Fortran runtime error: Bad real number in item 1 of list input

Error termination. Backtrace:
#0  0x1484d39fe31a
#1  0x1484d39feec5
#2  0x1484d39ff68d
#3  0x1484d3b6cd42
#4  0x1484d3b6ead5
#5  0x1484d3b700f9
#6  0x561b4d583624
#7  0x561b4d57bec6
#8  0x561b4d576b2e
#9  0x1484d305db96
#10  0x561b4d576b69
#11  0xffffffffffffffff

I have not gone through the command from source for compilation. I do not have all necessary directories (like triqs.src, cthyb.src, dmftproj  ), that I could have obtained from the source compilation. 
Is it necessary to compile the source command to go into the directory:  /src/triqs_dft_tools/fortran/dmftproj/set_ang_trans.f?

Thank you for your response.

Best Regards,
CMTCL

**Comment by Wentzell** [comment]
Dear @cmtcl18,

You have successfully installed triqs as well as dft_tools and cthyb.
Your follow-up question is not related to the triqs library.
Please follow the [dft_tools tutorials](https://triqs.github.io/dft_tools/2.1.x/tutorials.html) closely.

I am closing this issue.
