### ISSUE TITLE
GMP and FFTW issues while compiling triqs-2.1.x

### ISSUE THREAD

**Issue by asubedi** [TRIQS/triqs#749]
I am trying to build triqs on montblanc.

The configure stage gives the following error:

-- -------- GMP detection -------------
-- Found GMP: /cm/shared/apps/gmp/6.1.0/lib  
CMake Error at triqs/CMakeLists.txt:201 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "gmp".

-- -------- FFTW detection -------------
CMake Error at triqs/CMakeLists.txt:211 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "fftw".

I have:
$ module list
Currently Loaded Modulefiles:
  1) slurm/14.03.0                3) boost/gcc/1.64.0             5) gmp/gcc/64/6.1.0
  2) gcc/7.3.0                    4) fftw3/openmpi/gcc/64/3.3.8

The cmake script is:
cmake  ../triqs.src \
       -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
       -DBOOST_ROOT=/cm/shared/apps/boost/1.64.0/ \
       -DHDF5_HL_INCLUDE_DIR=/home/subedi/miniconda3/envs/triqs/include/ \
       -DHDF5_hdf5_hl_LIBRARY_RELEASE=/home/subedi/miniconda3/envs/triqs/lib/libhdf5_hl.so \
       -DFFTW_INCLUDE_DIR=/cm/shared/apps/fftw/openmpi/gcc/64/3.3.8/include \
       -DFFTW_LIBRARIES=/cm/shared/apps/fftw/openmpi/gcc/64/3.3.8/lib/libfftw3.a \
       -DGMP_INCLUDE=/cm/shared/apps/gmp/6.1.0/include/ \
       -DGMP_LIBRARIES=/cm/shared/apps/gmp/6.1.0/lib/ \
       -DGMPXX_LIBRARIES=/cm/shared/apps/gmp/6.1.0/lib/ 

Can someone tell me how to fix the errors?

**Comment by Wentzell** [comment]
Dear @asubedi,

Can you try to specify gmp and fftw with
 `-DGMP_ROOT=/cm/shared/apps/gmp/6.1.0`
and
`-DFFTW_ROOT=/cm/shared/apps/fftw/openmpi/gcc/64/3.3.8`.

**Comment by asubedi** [comment]
> Can you try to specify gmp and fftw with
> `-DGMP_ROOT=/cm/shared/apps/gmp/6.1.0`
> and
> `-DFFTW_ROOT=/cm/shared/apps/fftw/openmpi/gcc/64/3.3.8`.

This does not work.  It actually degrades the situation.  I get the following error:
```
-- -------- GMP detection -------------
-- Found GMP: /usr/lib64/libgmp.so  
CMake Error at triqs/CMakeLists.txt:201 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "gmp".


-- -------- FFTW detection -------------
-- Found FFTW: /usr/lib64/libfftw3.so  
CMake Error at triqs/CMakeLists.txt:211 (install):
  install TARGETS given no LIBRARY DESTINATION for shared library target
  "fftw".
```

**Comment by Wentzell** [comment]
I see now whats happening. You are using a cmake version that is too old.
On the 2.1.x branch we had not properly set the minimum requirement unfortunately.
I have just fixed this in d1b84b76c. You will need cmake version `3.0.2` or later.

Note that installing a more recent cmake is very easy with pip

```
pip install --user cmake
```

You should then find the cmake executable in 
```
$HOME/.local/lib/python2.7/site-packages/cmake/data/bin
```

**Comment by asubedi** [comment]
Thanks.  I installed cmake from conda.  It works when I specify
DGMP_LIBRARIES, DGMPXX_LIBRARIES, DFFTW_LIBRARIES.

**Comment by Wentzell** [comment]
Good to hear that things are working for you now! All tests are passing?
Can we close this?

**Comment by asubedi** [comment]
We can close this.  I'm coming with more errors :-)
