### ISSUE TITLE
Returning tuple of Green's functions does not compile if converted to python

### ISSUE THREAD

**Issue by Stefan-Dienst** [TRIQS/triqs#755]
Using TRIQS 2.2.1 with hash 3e0ed6209d1cb855c2cf9d547a3b7aaf62bdae9e throws an error at compilation if I try to convert a function that returns a tuple of Green's functions to python.

I have setup an app4triqs skeleton with a minimal example: https://github.com/StefanKaeser/tests_for_triqs.
If I convert the function
```c++
std::tuple<g_wk_t, g_wk_t> test_tuple(g_wk_t g_wk) {
  
      return {g_wk, g_wk};
  }
```
in tests_for_triqs.cpp to python, using cpp2py, I can no longer compile.
Clang version 8.0.1 throws the following error:
```
In file included from /home/kaeser/my_triqs_installations/tests_for_triqs.build/python/tests_for_triqs/tests_for_triqs_module_wrap.cxx:28:
/home/kaeser/my_triqs_installations/triqs_2.2.x/include/cpp2py/converters/tuple.hpp:15:91: error: 
      conversion function from 'const __tuple_element_t<0UL,                                         
      tuple<triqs::gfs::gf<triqs::gfs::cartesian_product<triqs::gfs::imfreq,                         
      triqs::lattice::brillouin_zone>, triqs::gfs::matrix_valued>,    
      triqs::gfs::gf<triqs::gfs::cartesian_product<triqs::gfs::imfreq,            
      triqs::lattice::brillouin_zone>, triqs::gfs::matrix_valued> > >' (aka 'const
      triqs::gfs::gf<triqs::gfs::cartesian_product<triqs::gfs::imfreq, triqs::lattice::brillouin_zone>, triqs::gfs::matrix_valued>') to
'cpp2py::py_converter<triqs::gfs::gf_view<triqs::gfs::cartesian_product<triqs::gfs::imfreq,                    
      triqs::lattice::brillouin_zone>, triqs::gfs::matrix_valued> >::c_type' (aka                                    
      'gf_view<triqs::gfs::cartesian_product<triqs::gfs::imfreq,                                                     
      triqs::lattice::brillouin_zone>, triqs::gfs::matrix_valued>') invokes a deleted  
      function                                                                             
  ...std::array<pyref, sizeof...(Is)>{pyref(py_converter<Types>::c2py(std::get<Is>(t)))....
```

Can anyone reproduce this or knows what is going on here?

**Comment by Wentzell** [comment]
Hi Stefan,

Thank you for pointing out this problem! This is in fact a bug in C++2py

@parcollet 
In the tuple converter file `c2py` will take any tuple by `const &`, c.f. [cpp2py/converters/tuple.hpp:14](https://github.com/TRIQS/cpp2py/blob/master/include/cpp2py/converters/tuple.hpp#L14)
```c++
template <std::size_t... Is> static PyObject *c2py_impl(tuple_t const &t, std::index_sequence<Is...>) 
```

The example Stefan gave will thus trigger a conversion of a `gf const &` at [cpp2py/converters/tuple.hpp:14](https://github.com/TRIQS/cpp2py/blob/master/include/cpp2py/converters/tuple.hpp#L15)
which will try to construct a `gf_view`  from a `gf const &` which leads to the problem above.

Shouldn't the tuple converter provide a `&&` overload of `c2py`
```c++
template <std::size_t... Is> static PyObject *c2py_impl(tuple_t &&t, std::index_sequence<Is...>)
```
This seems to solve the problem above.

**Comment by Wentzell** [comment]
This is already fixed on triqs/unstable. TODO Add test

**Comment by Wentzell** [comment]
Test was added in 5b0a1006
