### ISSUE TITLE
Error while setting real time Green's function from real frequency Green's function

### ISSUE THREAD

**Issue by jkarp314** [TRIQS/triqs#756]
I'm using triqs version 2.1.1

Using the example code on the TRIQS website for building a real time Green's function from a real frequency Green's function, I get an error that the meshes are not compatible. The frequency and time meshes have the same size.

The code I'm running (straight from https://triqs.github.io/triqs/2.1.x/reference/gfs/py/block/GfReTime.html) is:

```python
from math import pi
from pytriqs.gf import *

gw = GfReFreq(indices = [1], window = (-5, 5), n_points = 1001, name = "egBlock")
gw << SemiCircular(2.0)

gt = GfReTime(indices = [1], window = (-5*2*pi*(100.0/101.0),5*2*pi*(100.0/101.0)), n_points = 1001, name = "egBlock")
gt << InverseFourier(gw)
```

The full error message I get is:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-0d0b7ac56166> in <module>()
      6 
      7 gt = GfReTime(indices = [1], window = (-5*2*pi*(100.0/101.0),5*2*pi*(100.0/101.0)), n_points = 1001, name = "egBlock")
----> 8 gt << InverseFourier(gw)

/usr/lib/python2.7/dist-packages/pytriqs/gf/gf.py in __lshift__(self, A)
    380             self.copy_from (lazy_expressions.eval_expr_with_context(e_t, A2) )
    381         elif isinstance(A, lazy_expressions.LazyExprTerminal): #e.g. g<< SemiCircular (...)
--> 382             self << lazy_expressions.LazyExpr(A)
    383         elif descriptors.is_scalar(A): #in the case it is a scalar ....
    384             self << lazy_expressions.LazyExpr(A)

/usr/lib/python2.7/dist-packages/pytriqs/gf/gf.py in __lshift__(self, A)
    378                 x(tmp)
    379                 return tmp
--> 380             self.copy_from (lazy_expressions.eval_expr_with_context(e_t, A2) )
    381         elif isinstance(A, lazy_expressions.LazyExprTerminal): #e.g. g<< SemiCircular (...)
    382             self << lazy_expressions.LazyExpr(A)

/usr/lib/python2.7/dist-packages/pytriqs/gf/lazy_expressions.py in eval_expr_with_context(eval_term, expr)
     93 def eval_expr_with_context(eval_term, expr ):
     94 
---> 95     if expr.tag == "T": return eval_term(expr.childs[0]) #eval the terminals
     96 
     97     if expr.tag == "F":

/usr/lib/python2.7/dist-packages/pytriqs/gf/gf.py in e_t(x)
    376                 if not isinstance(x, descriptors.Base): return x
    377                 tmp = self.copy()
--> 378                 x(tmp)
    379                 return tmp
    380             self.copy_from (lazy_expressions.eval_expr_with_context(e_t, A2) )

/usr/lib/python2.7/dist-packages/pytriqs/gf/descriptors.py in __call__(self, G2)
    179 
    180     def __call__(self,G2):
--> 181         G2.set_from_inverse_fourier(self.G, *self.args, **self.kw)
    182         return G2
    183 

/usr/lib/python2.7/dist-packages/pytriqs/gf/gf.py in _(self, *args, **kw)
     57 def add_method_helper(a,cls):
     58     def _(self, *args, **kw):
---> 59        return a(self, *args, **kw)
     60     _.__doc__ = 50*'-' + '\n' + a.__doc__
     61     _.__name__ = a.__name__

RuntimeError: .. Error occurred at Mon Nov 18 13:55:20 2019

.. Error .. calling C++ overload 
.. set_from_inverse_fourier(gf_view<retime,matrix_valued> g_out, gf_view<refreq,matrix_valued> g_in) -> void 
.. in implementation of function gf_fnt.set_from_inverse_fourier
.. C++ error was : 
.. Triqs runtime error at /src/triqs/triqs/gfs/transform/fourier_real.cpp : 110

Meshes are not compatible
.. Error occurred on node

**Comment by Wentzell** [comment]
I fixed the example above. C.f. https://triqs.github.io/triqs/unstable/documentation/manual/triqs/gfs/py/block/GfReTime.html
