### ISSUE TITLE
cmake can't locate MPI

### ISSUE THREAD

**Issue by JonasRigo** [TRIQS/triqs#758]
Dear Developers,
I had to build OpenMP (version 4.0.2) from source because of some issues related to NUMA memory allocation on Threadripper (OS: Ubuntu 18.04.3 LTS).
Now when configuring Triqs with cmake (version 3.10.2) i get the following error
```
-- -------- MPI detection -------------
-- Could NOT find MPI_C (missing: MPI_C_LIB_NAMES MPI_C_HEADER_DIR MPI_C_WORKS) 
-- Could NOT find MPI_CXX (missing: MPI_CXX_LIB_NAMES MPI_CXX_HEADER_DIR MPI_CXX_WORKS) 
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find MPI (missing: MPI_C_FOUND MPI_CXX_FOUND)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindMPI.cmake:1444 (find_package_handle_standard_args)
  triqs/CMakeLists.txt:70 (find_package)
```
I think the environment variables I've set for OpenMP should be correct
```
#OpenMP
export MPI_HOME=$HOME/ompi
export PATH=$PATH:$MPI_HOME/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$MPI_HOME/lib
```
I had no problems installing Openblas - is there something I've missed?

Thanks, Jonas

**Comment by the-hampel** [comment]
Hi Jonas,
exporting these variables should indeed do the job. Does `which mpirun` give you the correct executable (or `mpirun --version`)?  If this looks all good and it still does not work, you could try to give cmake more hints by specifying one of these variables shown here: https://cmake.org/cmake/help/v3.10/module/FindMPI.html . Something like 
```
cmake ... -DMPI_C_INCLUDE_DIRS=/home/.../ompi/include
```
I am using the same cmake version with a custom build MPICH and it works fine on ubuntu 18.04. So I think this should work somehow. 
Best,
Alex

**Comment by JonasRigo** [comment]
Hi Alex,
Thanks for the quick response!
`which mpirun` seems to point to the right executable.

I tried to include the flags, as suggested and even tried with cmake version 3.16.1 - always with the same error exit as before.

Is OpenMP 4.0.2 compatible?

Since you did a similar install: did you encounter any issues?

Best, Jonas

**Comment by the-hampel** [comment]
No for me it just worked out of the box. Did you run `ldconfig` after you installed openmpi? (You can check with `ldconfig -p` if the MPI library is in the cache) But this is more a shot in the blue. It should work as well without. Maybe the version has problems with this MPI version, but I don't know why this should happen.

I got now a bit confused. You mean openMPI 4.0.2? You wrote also OpenMP, which is something else. 

Anyway, I tried now to setup a minimal example, which should reproduce the error. Can you create in an empty folder a file called `CMakeLists.txt` with the following content:
```
cmake_minimum_required (VERSION 3.0)
project (Test C CXX)
find_package(MPI)
```
Does this shows the same error, by not detecting MPI when you run `cmake ./`? 

Can you then double check if you have somewhere the `libmpi.so`? If you have it we should be able to tell this cmake. I tried it, and for me:
```
cmake ./ -DMPI_mpi_LIBRARY=/usr/lib/libmpi.so -DMPI_mpicxx_LIBRARY=/usr/lib/libmpicxx.so
```
does the trick with the above CMakeLists.txt file in the same dir.

**Comment by JonasRigo** [comment]
Sorry for the confusion, of course I've meant OpenMPI 4.0.2

Indeed I didn't run `ldconfig` after the installation.

I ran the test file you kindly set up and it worked fine 

```
-- Found MPI_C: /home/jonas/ompi/lib/libmpi.so (found version "3.1") 
-- Found MPI_CXX: /home/jonas/ompi/lib/libmpi.so (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
```

Weirdly cmake seems to find version 3.1, I don't know if this has anything to do with the problem. Though the file located is in the right directory and it is found without me pointing to it.

I tried
```
cmake ./ -DMPI_mpi_LIBRARY=/usr/lib/libmpi.so -DMPI_mpicxx_LIBRARY=/usr/lib/libmpicxx.so
```
with triqs and I got the same error again.

**Comment by the-hampel** [comment]
Mh. This is indeed weird. I cannot see why it should not work then. Did you changed the path for your cmake call accordingly to your path? I mean:
```
-DMPI_mpi_LIBRARY=/usr/lib/libmpi.so -DMPI_mpicxx_LIBRARY=/usr/lib/libmpicxx.so
```
will not change anything. You need to put:
```
-DMPI_mpi_LIBRARY=/home/jonas/ompi/lib/libmpi.so -DMPI_mpicxx_LIBRARY=/home/jonas/ompi/lib/libmpi.so
```
as options then. Do you have alternatively the option to try an older openmpi release? 3.x.x? If I find some time I will try openmpi 4.x meanwhile.

**Comment by JonasRigo** [comment]
I tried openmpi 3.x.x and 2.x.x with the same error as before. In the process I had to reside to a backup of my dpkg and had to reinstall openmi 4.0.2. The test CMakeList.txt is working again and detecting the right openmpi. It was a bit of a detour, but all the other benchmark files I have tried worked perfeclty.

Now the news, I get a new error message from cmake

```
-- -------- Boost detection -------------
CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR serialization) (Required
  is at least version "1.53")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:2165 (find_package_handle_standard_args)
  triqs/CMakeLists.txt:109 (find_package)
```
Unfortunately I don't know how to resolve this and I can't tell if the MPI detection was successful.

**Comment by Wentzell** [comment]
Dear @JonasRigo,

Do I understand correctly that you cannot use the apt package we provide for triqs as
the ubuntu packaged OpenMPI version leads to problems with your CPU Model?

Regarding your latest error message:

> Now the news, I get a new error message from cmake
> 
> ```
> -- -------- Boost detection -------------
> CMake Error at /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>   Could NOT find Boost (missing: Boost_INCLUDE_DIR serialization) (Required
>   is at least version "1.53")
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/share/cmake-3.16/Modules/FindBoost.cmake:2165 (find_package_handle_standard_args)
>   triqs/CMakeLists.txt:109 (find_package)
> ```

It seems `boost` is not detected. Did you make sure to install all dependencies required for the compilation of TRIQS as listed [here](https://triqs.github.io/triqs/latest/installation/ubuntu.html)?

```
sudo apt-get install cmake g++ gfortran git hdf5-tools \
     libblas-dev libboost-all-dev libfftw3-dev libgfortran3 \
     libhdf5-serial-dev libgmp-dev liblapack-dev \
     python-dev python-h5py python-mako python-matplotlib \
     python-numpy python-scipy
```

MPI would usually be provided through `libopenmpi-dev` together with the python bindings in `python-mpi4py`. You will have to make sure that aside from your custom OpenMPI 4.0 setup you properly compile mpi4py.

```
pip install --user --no-binary=mpi4py mpi4py
```

**Comment by JonasRigo** [comment]
Thanks a lot!

Yes, I am doing this because the packaged version of OpenMPI seems not to be NUMA aware, which is necessary to get full performance on Threadripper.

Installing `boost` resolved the issue and installing `mpi4py` resolved many of the failed test during `make test`.
I'm now only left with the following failed test 
```
22 - nda_mpi_array_np2 (Failed)
	 23 - nda_mpi_array_np3 (Failed)
	 24 - nda_mpi_array_np4 (Failed)
	 88 - mpi_gf_np2 (Failed)
	 89 - mpi_gf_np3 (Failed)
	 90 - mpi_gf_np4 (Failed)
	128 - mpi_histogram_np2 (Failed)
	129 - mpi_histogram_np3 (Failed)
	130 - mpi_histogram_np4 (Failed)
	148 - mpi_chunk_np1 (Failed)
	149 - mpi_chunk_np2 (Failed)
	150 - mpi_chunk_np3 (Failed)
	151 - mpi_chunk_np4 (Failed)
	153 - mpi_custom_np1 (Failed)
	154 - mpi_custom_np2 (Failed)
	155 - mpi_custom_np3 (Failed)
	156 - mpi_custom_np4 (Failed)
	158 - mpi_string_np1 (Failed)
	159 - mpi_string_np2 (Failed)
	160 - mpi_string_np3 (Failed)
	161 - mpi_string_np4 (Failed)
	163 - mpi_vector_np1 (Failed)
	164 - mpi_vector_np2 (Failed)
	165 - mpi_vector_np3 (Failed)
	166 - mpi_vector_np4 (Failed)
	167 - comm_split_np4 (Failed)
```
Do you have an idea what causes this?

Thanks again for the support!

Best wishes,
Jonas

**Comment by Wentzell** [comment]
Dear @JonasRigo,

Could you run

```
ctest -V -R nda_mpi_array_np2
```

in your build directory and provide the output?

**Comment by JonasRigo** [comment]
Dear Nils,

Thanks for the help for the diagnosis.

When I run 

```
ctest -V -R nda_mpi_array_np2
```

the test runs perfectly

```
The following tests passed:
	nda_mpi_array_np2

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.28 sec
```

Though, when I run

```
sudo ctest -V -R nda_mpi_array_np2
```

I get 

```
0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.03 sec

The following tests FAILED:
	 22 - nda_mpi_array_np2 (Failed)
Errors while running CTest
```

Becuase mpi refuses to run as root (except when executed with `--allow-run-as-root`) . I execute `make test` as `sudo` to avoid the following failed tests
```
	 11 - nda_h5 (Failed)
	 26 - atom_diag_h5 (Failed)
	 30 - F7 (Failed)
	 31 - chain_call (Failed)
	 32 - function (Failed)
	 33 - general (Failed)
	 34 - lazy (Failed)
	 35 - lazy_function (Failed)
	 36 - lazy_method (Failed)
	 37 - math_functions (Failed)
	 42 - sum_functional (Failed)
	 52 - array_gf (Failed)
	 54 - block (Failed)
	 55 - block2 (Failed)
	 56 - bug1 (Failed)
	 67 - g_r_k (Failed)
	 69 - gf_base (Failed)
	 72 - gf_density (Failed)
	 79 - gf_retw (Failed)
	 91 - block_of_vertex (Failed)
	 92 - bubble (Failed)
	 95 - curry_and_fourier (Failed)
	 97 - g_k_om (Failed)
	 98 - g_nu_nup (Failed)
	 99 - g_om_nu_nup (Failed)
	100 - g_x_t (Failed)
	102 - issue288 (Failed)
	106 - partial_eval (Failed)
	108 - vertex (Failed)
	111 - issue_286 (Failed)
	112 - h5_io (Failed)
	113 - h5_variant (Failed)
	114 - optional_h5 (Failed)
	115 - hilbert_test (Failed)
	118 - tight_binding (Failed)
	119 - different_moves_mc (Child aborted)
	122 - operator_test (Failed)
	124 - histograms2 (Failed)
	125 - ising2d (Failed)
	134 - issue315 (Failed)
	135 - iterator_dressing (Failed)
	136 - iterator_dressing3 (Failed)
	139 - numeric_ops (Failed)
	140 - qmc_time_t_test (Failed)
	169 - py_operators (Failed)
	170 - py_atom_diag (Failed)
	171 - py_hdf5_bool (Failed)
	172 - py_hdf5_io (Failed)
	177 - py_gf_base_op (Failed)
	185 - py_hdf5_meshBZ (Failed)
	194 - py_block_matrix (Failed)
	195 - py_gf_tensor_valued (Failed)
	196 - py_histograms (Failed)
	199 - py_multivar (Failed)
	201 - py_g_k_om (Failed)
	202 - py_block2 (Failed)
	204 - py_wrap_a (Failed)
	206 - py_wrap_g (Failed)
	207 - py_wrap_multivar (Failed)
```
As far as I can tell there is nothing wrong at this point, is that right?
I'd say it is simply an execution issue.

Best regards,
Jonas

**Comment by the-hampel** [comment]
Hi Jonas,

I do not quite understand why the tests are running somewhere, where root access is needed, but I ran into similar issues when using docker container and openmpi. With `docker build` everything is executed as root, so my tests crashed with the same problem. I solved this by adding `-DMPIEXEC_PREFLAGS='--allow-run-as-root`  to the `cmake` command. Then also tests are automatically executed with this option and should pass. However, there are good reasons, why mpi should be not executed as root usually. So make sure, that this is only for the tests or in some virtual environments...

Best,
Alex

**Comment by Wentzell** [comment]
Hi @JonasRigo ,

Indeed mpi doesn't like to be run as root very much.
So all tests pass if you run them as a non-root user?
Can we close this?

@the-hampel 
> I solved this by adding `-DMPIEXEC_PREFLAGS='--allow-run-as-root` to the `cmake` command. 

This could indeed be a solution for a build in a docker container.
For our Jenkins builds we instead just add a new user `build` and switch to root only for the `install` step. C.f. https://github.com/TRIQS/triqs/blob/2.2.x/Dockerfile.build

**Comment by JonasRigo** [comment]
Hi @the-hampel  and @the-hampel,

This resolved all the issues, all tests passed as root though.

Thanks a lot for all the input, I will close the thread now.

Best wishes,
Jonas
