### ISSUE TITLE
TRIQS and CTHYB HPC install

### ISSUE THREAD

**Issue by phystd** [TRIQS/triqs#766]
Is it possible to install TRIQS and CTHYB using the Anaconda package in a HPC environment? Thanks.

**Comment by Wentzell** [comment]
Dear @phystd,

The libraries on HPC Cluster machines (mpi, fftw, ..) are usually optimized for those.
It is more advisable to compile against these optimized libraries when setting up TRIQS and CTHyb.
This will also allow you to enable compiler optimizations that are particular for the architecture of the
HPC Cluster (c.f.  `-march=...` [here](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html))

The Anaconda packages, while not giving optimal performance, should however be functional also in HPC environments.

**Comment by phystd** [comment]
Is it a problem if the cluster images are using python 3 - 3.6?

**Comment by Wentzell** [comment]
The latest TRIQS release 2.2.2 requires Python 2. We are working on a Python 3 port at the moment.

**Comment by Wentzell** [comment]
TRIQS 3.0.0 was released and provides full Python 3 support.
We provide instructions on how to install the release using [Anaconda](https://triqs.github.io/triqs/latest/install.html#anaconda) as well as [EasyBuild](https://triqs.github.io/triqs/latest/install.html#compiling-triqs-from-source-using-easybuild).

**Comment by Wentzell** [comment]
Note that cthyb can also be installed through Anaconda and EasyBuild (4.3.1).

```
conda install -c conda-forge install triqs_cthyb
```

or

```
eb -r TRIQS-cthyb-3.0.0-foss-2020a-Python-3.8.2.eb
```
