### ISSUE TITLE
Wrong signature of `c2py()` in cpp2py converter for `std::optional`

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#768]
I am trying to wrap a C++ function returning `std::optional`. Here is what I'm getting from the compiler,
```
/home/igor/Physics/TRIQS/2.2/installed/include/./cpp2py/py_converter.hpp:152:48: error: non-const lvalue reference to type 'optional<...>' cannot bind to a temporary of type 'optional<...>'
    return py_converter<std::decay_t<T>>::c2py(std::forward<T>(x));
                                               ^~~~~~~~~~~~~~~~~~
```

Turns out that changing
https://github.com/TRIQS/triqs/blob/f50f25f1105a295c51e435e917a7af7c93b97c0b/cpp2py/include/cpp2py/converters/optional.hpp#L8
to take the constant reference fixes the issue.

C.f. https://github.com/TRIQS/triqs/issues/755.

### Versions

`2.2.x` and `unstable`.

**Comment by Wentzell** [comment]
Dear @krivenko,

Thank you for pointing this out! This should be fixed on the cpp2py master branch in commit https://github.com/TRIQS/cpp2py/commit/3e4667a35e376e4fa5866a02e523cf33f6b2d7ab
Note however that the master branch of cpp2py is now compatible with Python3 only.
Feel free to create a PR to triqs/2.2.x backporting this fix if it is essential for your your application.
