### ISSUE TITLE
In python, real time Green function accepts data that is inconsistent with mesh.

### ISSUE THREAD

**Issue by CorentinB78** [TRIQS/triqs#770]
### Description

Real time Green function accepts data array with different number of points than in the mesh, silently.

### Steps to Reproduce

```
import numpy as np
from pytriqs import gf

# define a GF with 100 points in time mesh but only 50 in data:
g0_test = gf.GfReTime(mesh=gf.MeshReTime(-1., 1., 100), data=np.ones((50, 1, 1), dtype=complex))

print(g0_test(-0.5)) # returns 1 as expected
print(g0_test(0.5)) # returns 3.47824868e-310+3.47824868e-310j
```

**Expected behavior:** should raise an error at construction

**Actual behavior:** succeed in constructing GF, returns random numbers on part of the mesh that was not populated

### Versions
git hash f50f25f1, on branch 2.2.x
OS: fedora 31

**Comment by Wentzell** [comment]
This was fixed in 7c25232
