### ISSUE TITLE
One basic question on implementation of the DMFT code in the tutorial.

### ISSUE THREAD

**Issue by qintaophy** [TRIQS/triqs#804]
Hi, I tried to implement the code example in the tutorial "09-Single-orbital_Hubbard_with_CTQMC_solution.ipynb". In solution to exercise 1, I added the following at the end of the loop "for i in range(n_loops):"

 g2 = 0.5 * (S.G_iw['up'] + S.G_iw['down'])
 a1 =  np.sum(np.abs( g.data ));
 a2 =  np.sum(np.abs( g2.data ));
 print('i_loop= ', i_loop, 'Conv test: ',  np.abs(a1-a2))

I add the code above to test whether the DMFT loop will be convergent. What I obtained is as follows, I didn't see any trend to be convergent from the data in the last column. Anything wrong with my implementation? Thanks!

i_loop=  0 Conv test:  25.71080513155414
i_loop=  1 Conv test:  13.17350120054823
i_loop=  2 Conv test:  10.159278518183044
i_loop=  3 Conv test:  5.067274683944419
i_loop=  4 Conv test:  3.5470877796430216
i_loop=  5 Conv test:  1.7523481404962524
i_loop=  6 Conv test:  0.7211633576978613
i_loop=  7 Conv test:  0.030259689013689695
i_loop=  8 Conv test:  2.0485512840065496
i_loop=  9 Conv test:  3.2796496419113907

**Comment by Wentzell** [comment]
Dear @qintaophy,

The Green function obtained from QMC is noisy.

Your measure of convergence compares the sum of all noisy data points,
which will scale up the variance by the number of data points summed (2050 in the tutorial example).

Instead, I suggest you compare your quantity of interest,
e.g. the Self-Energy at first and second Matsubara frequency (w_0, w_1).

**Comment by qintaophy** [comment]
Dear Dr. Wentzell, 

Thanks a lot for your reply. Indeed, one can arrive at the convergence in this way. As far as I know, by default, in TRIQS for the matsubara frequency, -1025<= n <=1024. Therefore, for w_0, w_1, the frequency is quite large. My question is: should we look at physical quantities ( for example, self-energy) corresponding to the high or low frequency? I met a problem. When I look at physical quantities of w_1025 and w_1026, I cannot arrive at the convergence.

**Comment by Wentzell** [comment]
When inferring the self-energy from the measured Green function, as is done in TRIQS/cthyb,
you will always observe a very large noise level at large frequencies.
Compare the self-energy at small frequencies as suggested above.

**Comment by qintaophy** [comment]
Thanks for the comment. I agree that we should look at the physical quantities for the low frequencies. The point is that for TRIQS, in Omega_n, where is the low frequency? Is it at the n =0 or n=1025 by default?

**Comment by the-hampel** [comment]
Hi,

you can get a numpy array of the mesh of any Gf object like this: 
```
iw_mesh_np = np.array([w.value.imag for w in Gf.mesh])
```
then look at the frequencies. Typically it has both negative and positive values. The frequency closest to 0 would then be at: 
```
n_iw0 = int(0.5*len(iw_mesh_np))
```
Then you can look at the value of your Gf at that point:
```
print(Gf.data[n_iw0])
```
Also in principle your assumption is right to compare the norm of the Gf. Another option is to scale the norm on the gf bt frequency to weight lower frequencies higher, i.e. doing something like: 
```
def max_G_diff(G1, G2, wg = 0.5):
    diff = 0.0
        for block, gf in G1:
            #  calculate norm over all axis but the first one which are frequencies
            norm = abs(np.linalg.norm(G1[block].data - G2[block].data,axis=tuple(range(1, G1[block].data.ndim))))
            # scale by frequencies (change factor wg to something to scale different)
            # for Matsubara Gfs this gives more weight to smaller frequencies
            if type(G1.mesh) is MeshImFreq:
                 w_scal = np.array([abs(1/(abs(w.value)**wg)) for w in G1.mesh])
                 diff += np.dot(norm, w_scal)
    return diff
```

**Comment by Wentzell** [comment]
An easy way to retrieve the value for a specific Matsubara Index is to use the `Idx` helper
```python
G['up'][Idx(0)]
```
This should yield the same value as the `Gf.data[n_iw0]` suggested above.

**Comment by Wentzell** [comment]
The initial question of the issue was resolved. I am closing this now.
