### ISSUE TITLE
Product of GF evaluates differently as a lazy expression

### ISSUE THREAD

**Issue by CorentinB78** [TRIQS/triqs#805]
### Description

A product of real frequency GF produces different values whether it is built in a separate GF object or evaluated through a lazy expression.
It seems the correct result is given by the lazy expression.
I had the problem with both scalar_valued and matrix_valued.

An example will be more clear:
```
  using namespace triqs::gfs;
  using triqs::clef::placeholder;

  placeholder<0> w_;
  auto freq_mesh = gf_mesh<refreq>({-10., 10., 100});
  gf<refreq, scalar_valued> g(freq_mesh);
  gf<refreq, scalar_valued> f(freq_mesh);
  g(w_) << exp(1i * w_) / (1 + w_ * w_);
  f(w_) << exp(2i * w_) / (2 + w_ * w_);

  gf<refreq, scalar_valued> fg = f * g;
  std::cout << g(2.5) * f(2.5) << std::endl;
  std::cout << fg(2.5) << std::endl;
  std::cout << (f * g)(2.5) << std::endl;
```

**Expected behavior:**

Same outputs.

**Actual behavior:**

Different outputs:
```
(0.0058649,0.0154882)
(0.0059319,0.0152893)
(0.0058649,0.0154882)
```

### Versions

Triqs 3.0.x (bfdf5324)
fedora 32

**Comment by Wentzell** [comment]
Hey Corentin,

What you are most likely seeing here is that the order of operation matters.
In one case (fg) you are first taking the product and then perform linear interpolation,
resulting in `0.5 (f2 * g2) + 0.5 (f3 * g3)`, while the other two cases first perform the evaluation before taking the product,
which should result in `0.25 (f2 + f3) (g2 + g3)`. Could you check that this matches the values you provided?

**Comment by CorentinB78** [comment]
Ok I see.
I checked, it all works as you said.
Thank you and sorry for the false alarm!
