### ISSUE TITLE
issue with mpi when trying to build triqs unstable from source

### ISSUE THREAD

**Issue by jkarp314** [TRIQS/triqs#807]
Hi, 

I've built triqs unstable from source before. I pulled the latest version and am trying to rebuild it. 

When I try to build it I get the error: "mpi/monitor.hpp: No such file or directory"

Indeed, in my "/usr/include/mpi" directory there is no file called "monitor.hpp" 

I'm using ubuntu 18.04 on WSL. I used apt-get to install the latest packaged version of libopenmpi-dev. 
Typing "mpirun --version" gives:
 "mpirun (Open MPI) 2.1.1"
 
open mpi is listed as a requirement here:
 https://triqs.github.io/triqs/latest/installation/requirements.html#requirements
 but there is no information on the version needed. Do I need a newer version than that? If there is a minimum version required, can that be added to the website?

**Comment by Wentzell** [comment]
Dear @jkarp314,

Could you provide the full log of your cmake configuration?

Also, could you then please try to build triqs/unstable using `-DBuild_Deps=Always` in the cmake configuration step.

Thank you!

Best,

Nils
