### ISSUE TITLE
3d bravais lattice not implemented

### ISSUE THREAD

**Issue by MHarland** [TRIQS/triqs#81]
Hi,
I tried to run a simulation on a 3D-lattice and got the error '3d bravais lattice not implemented' from 'bravais_lattice_and_brillouin_zone.cpp'. Why has this not been implemented so far? Did any major difficulties come up trying it?

**Comment by krivenko** [comment]
Hi Michel,
Would you mind adding an independency check, like in this commit?

https://github.com/MHarland/triqs/commit/82f2d5721ba3ffc283c123183456aa30e7cd361b

**Comment by mferrero** [comment]
I didn't realize there was a fix already. Let me merge this immediately.
