### ISSUE TITLE
Syntax warning in generated cpp_api sphinx documentation

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#811]
### Prerequisites

* Please check that a similar issue isn't already filed: https://github.com/issues?q=is%3Aissue+user%3Atriqs

Done

### Description

Sphinx gives warnings

```
/home/hugstr/dev/triqs/cbuild/deps/h5_src/doc/cpp2rst_generated/h5.rst:31: WARNING: Error in "table" directive:
invalid option value: (option: "width"; value: '50% 50%')
not a positive measure of one of the following units:
"em" "ex" "px" "in" "cm" "mm" "pt" "pc" "%".

.. table::
   :width: 50% 50%
```
when formatting the auto generated `cpp_api` documentation.

The problem seems to be that two values, instead of one, is given in the auto generated docs.

The problematic files are:
```
./triqs/doc$ egrep -R "50% 50%" *
documentation/cpp_api/itertools.rst:   :width: 50% 50%
documentation/cpp_api/triqs/det_manip.rst:   :width: 50% 50%
documentation/cpp_api/triqs/gfs.rst:   :width: 50% 50%
documentation/cpp_api/triqs/statistics.rst:   :width: 50% 50%
documentation/cpp_api/triqs/atom_diag.rst:   :width: 50% 50%
documentation/cpp_api/triqs/hilbert_space.rst:   :width: 50% 50%
documentation/cpp_api/triqs/mc_tools.rst:   :width: 50% 50%
documentation/cpp_api/mpi.rst:   :width: 50% 50%
```

### Steps to Reproduce

1. Build Triqs@unstable including the documentation
2. Watch sphinx complain

### Versions

Please provide the version of the TRIQS library that you used.

Tested 2021-05-18 on the `unstable` branch on commit `1d77c081`

**Comment by Wentzell** [comment]
Dear @HugoStrand,
This issue has been resolved with commit https://github.com/TRIQS/cpp2py/commit/23d8f17dbb5f45b1847a58e5387333ea85b34d26
Thanks to @the-hampel for the fix.
