### ISSUE TITLE
[doc] Broken links on the documentation website(s)

### ISSUE THREAD

**Issue by krivenko** [TRIQS/triqs#853]
I noticed that all links to PNG / PDF / high resolution versions of plots generated by Sphinx's `plot` directive are broken.
Both TRIQS library and application websites are affected.

See, for example, the plot at the bottom of this page: https://triqs.github.io/cthyb/latest/guide/dmft.html

It looks like `plot_directive` misbehaves and/or is misconfigured: All generated links point to files in the source directory.

**Comment by Wentzell** [comment]
@krivenko This seems to be resolved on the website now, can you confirm?

**Comment by krivenko** [comment]
If I follow the link from my original message here and click on any of `(Source code, png, hires.png, pdf)`, I still get the 404 error page.

**Comment by Wentzell** [comment]
This has been fixed in triqs as well as app4triqs, and will thus be merged into all apps. 
C.f. https://github.com/TRIQS/app4triqs/commit/8afb22b7bfbad739932e529f44b9253165d03d4f

**Comment by Wentzell** [comment]
See https://triqs.github.io/cthyb/unstable/guide/dmft.html
