### ISSUE TITLE
Install pomerol2triqs on TRIQS Docker image!

### ISSUE THREAD

**Issue by abdelghany0** [TRIQS/triqs#879]
I am utilizing the Docker image of TRIQS for my current work and require the pomerol exact diagonalization solver. The installation instructions for pomerol2triqs are provided below:

```
$ source <path_to_triqs_install_dir>/share/triqs/triqsvars.sh
$ git clone https://github.com/pomerol-ed/pomerol2triqs.git pomerol2triqs.git
$ mkdir pomerol2triqs.build && cd pomerol2triqs.build
$ cmake ../pomerol2triqs.git -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<path_to_install_dir> -DPOMEROL_PATH=<path_to_pomerol_install_dir>
$ make
$ make test
$ make install
```
However, I am currently facing difficulty determining the appropriate value for `<path_to_triqs_install_dir>` within the Docker image.

**EDIT:**
I have faced the same problem with Ubuntu 22.04.2. I installed TRIQS using: 

`sudo apt-get update && sudo apt-get install -y triqs`

TRIQS works well, but I can not find triqsvars.sh file anywhere!

**Comment by Wentzell** [comment]
Dear @abdelghany0,

Within the docker image TRIQS is installed into the system directory `/usr`.
In this case TRIQS is automatically available in your environment and you don't need to
```
source <path_to_triqs_install_dir>/share/triqs/triqsvars.sh
```
As you point out correctly, the file is not even present.

**Comment by abdelghany0** [comment]
Thank you for the clarification, it works.
