### ISSUE TITLE
Missing h5write for indices of GfImTime?

### ISSUE THREAD

**Issue by tayral** [TRIQS/triqs#88]
Hi,
When diff-ing two h5 archives (one from 1.1, one from 1.2-dev) supposed to contain the same GfImTime, I get:

https://gist.github.com/tayral/0ba235e3aa24f5a06ecb

It seems that the field "indices" is missing in 1.2-dev.

**Comment by parcollet** [comment]
@tayral: still open ?

**Comment by tayral** [comment]
fixed.
