### ISSUE TITLE
FT G(omega)->G(tau)->G(omega) does not restore initial G(omega)

### ISSUE THREAD

**Issue by leopo** [TRIQS/triqs#90]
I tried a simple test starting from a bosonic GF then transforming it into G(tau) and then back to G(omega). The resulting G(omega) looks different from the initial one and exhibits some strange delta-peaks.

the test is in /home/leonid/dat/Iron/Fe-bcc/dynamic_U/fit_U/test_FFT on weiss

I use a lot of Matsubara points n_w (16000+) in the initial GF

**Comment by tayral** [comment]
In fact, this is working, provided the tails are correct.
Please see the following script:
```
from pytriqs.gf.local import *
from pytriqs.archive import *
from pytriqs.gf.local.gf import MeshImTime
from pytriqs.gf.local.descriptors import *
import numpy,scipy
from pytriqs.archive import *

HDFfile='Umats.h5'
n_tau=40001

ar = HDFArchive(HDFfile,'r')
g_iw=ar['Umats'].copy()
print "stat", g_iw.mesh.statistic

km=TailGf(1,1,1,1)
km[1]=[[0]]
g_iw.fit_tail(km,5,len(g_iw.mesh)/2,len(g_iw.mesh))

mesh_imt=MeshImTime(beta=g_iw.mesh.beta,S='Boson',n_max=n_tau)

g_tau= GfImTime(indices = [0], mesh=mesh_imt)
g_tau << InverseFourier(g_iw)

g_iw2=g_iw.copy()
g_iw2 << Fourier(g_tau)

g_tau2=g_tau.copy()
g_tau2 << InverseFourier(g_iw2)
```
g_tau and g_tau2 are the same.
