### ISSUE TITLE
make_gf_dlr does not work on Gf views

### ISSUE THREAD

**Issue by YannIntVeld** [TRIQS/triqs#913]
### Description

Calling make_gf_dlr on a slice of a mesh-product Green's function gives incorrect results.

### Steps to Reproduce

1. Construct a mesh-product Green's function `g0_Dwk`

```python
from triqs.lattice.lattice_tools import BrillouinZone, BravaisLattice
from triqs.gf import *

bl = BravaisLattice(units=[(1, 0, 0)], orbital_positions=[(0,0,0)])
bz = BrillouinZone(bl)
kmesh = MeshBrillouinZone(bz, [2, 2, 1])

beta = 100.0
wmax = 30.0
dlreps = 1e-10
wmeshDLR_f = MeshDLRImFreq(beta, 'Fermion', wmax, dlreps)

g_Dwk = Gf(mesh=MeshProduct(wmeshDLR_f, kmesh), target_shape=[1]*2)
for k in kmesh:
    g_Dwk[:,k] << inverse(iOmega_n + 0.5)
```

2. Slice at a certain k-point and interpolate using the DLR
```python
nw_equidist = 50
g_c = make_gf_dlr(g_Dwk[:,Idx([0,0,0])])
g_slice_w = make_gf_imfreq(g_c, nw_equidist)
```

3. As a comparison, create a new Green's function with the same data as the slice.

```python
g_Dw = Gf(mesh=wmeshDLR_f, target_shape=g_Dwk.target_shape)
g_Dw.data[:,0,0] = g_Dwk.data[:,0,0,0]
g_c = make_gf_dlr(g_Dw)
g_w = make_gf_imfreq(g_c, nw_equidist)
```

4. Now compare `g0_slice_w` and `g0_w`

```python
from triqs.plot.mpl_interface import oplot,plt
%matplotlib inline

oplot(g_w, '-', name='$G_{copy}$', linewidth=2)
oplot(g_slice_w, ':', name='$G_{view}$', linewidth=2)
```

This results on the following plot
![bugreportplot](https://github.com/TRIQS/triqs/assets/77014033/c5cf43d5-b647-4550-b6bc-d0b0e372f558)

**Expected behavior:** `g0_w` and `g0_slice_w` should be equal

**Actual behavior:** They are not equal

### Additional Information

@HugoStrand mentioned that this probably has to do with the fact that cppdlr requires data to be contiguous.

**Comment by Wentzell** [comment]
@YannIntVeld Could you reduce your example to not use functions from tprf?
Also, you are currently not defining mu and e_k. A self-contained example would be helpful

**Comment by YannIntVeld** [comment]
@Wentzell That indeed makes more sense. I just updated the example.

**Comment by Wentzell** [comment]
Thank you @YannIntVeld for updating the example. This was very helpful.

This helped find a bug in `cppdlr` for non-contiguous input data.
I have created a PR with a fix in https://github.com/flatironinstitute/cppdlr/pull/4

**Comment by Wentzell** [comment]
Fixed by https://github.com/flatironinstitute/cppdlr/pull/4

I also added a test in 814063980
