### ISSUE TITLE
Can not build docs on unstable, examples still import triqs.gf.meshes_desc

### ISSUE THREAD

**Issue by HugoStrand** [TRIQS/triqs#932]
### Description

The documentation does not build on `triqs/unstable` fe75d67b.

The documentation still expects the module `triqs.gf.meshes_desc` while this seems to have been renamed to `triqs.gf.meshes`.

### Steps to Reproduce

1. Compile and build documentation

**Actual behavior:** [What actually happens]

```
Failed to import triqs.atom_diag.atom_diag_desc.
Possible hints:
* AttributeError: module 'triqs.atom_diag' has no attribute 'atom_diag_desc'
* ModuleNotFoundError: No module named 'triqs.atom_diag.atom_diag_desc'
Warning: could not identify MPI environment!
Starting serial run at: 2024-01-26 15:50:37.358822
Failed to import triqs.random_generator.random_generator_desc.
Possible hints:
* ModuleNotFoundError: No module named 'triqs.random_generator.random_generator_desc'
* AttributeError: module 'triqs.random_generator' has no attribute 'random_generator_desc'
Failed to import triqs.gf.gf_fnt_desc.
Possible hints:
* AttributeError: module 'triqs.gf' has no attribute 'gf_fnt_desc'
* ModuleNotFoundError: No module named 'triqs.gf.gf_fnt_desc'
Failed to import triqs.lattice.lattice_tools_desc.
Possible hints:
* AttributeError: module 'triqs.lattice' has no attribute 'lattice_tools_desc'
* ModuleNotFoundError: No module named 'triqs.lattice.lattice_tools_desc'
Starting run with 1 MPI rank(s) at : 2024-01-26 15:50:37.628308
Failed to import triqs.gf.wrapped_aux_desc.
Possible hints:
* ModuleNotFoundError: No module named 'triqs.gf.wrapped_aux_desc'
* AttributeError: module 'triqs.gf' has no attribute 'wrapped_aux_desc'
Failed to import triqs.stat.histograms_desc.
Possible hints:
* ModuleNotFoundError: No module named 'triqs.stat.histograms_desc'
* AttributeError: module 'triqs.stat' has no attribute 'histograms_desc'
Failed to import triqs.gf.gf_factories_desc.
Possible hints:
* ModuleNotFoundError: No module named 'triqs.gf.gf_factories_desc'
* AttributeError: module 'triqs.gf' has no attribute 'gf_factories_desc'
Failed to import triqs.operators.util.extractors_desc.
Possible hints:
* AttributeError: module 'triqs.operators.util' has no attribute 'extractors_desc'
* ModuleNotFoundError: No module named 'triqs.operators.util.extractors_desc'
Failed to import triqs.operators.operators_desc.
Possible hints:
* AttributeError: module 'triqs.operators' has no attribute 'operators_desc'
* ModuleNotFoundError: No module named 'triqs.operators.operators_desc'
Failed to import triqs.gf.meshes_desc.
Possible hints:
* AttributeError: module 'triqs.gf' has no attribute 'meshes_desc'
* ModuleNotFoundError: No module named 'triqs.gf.meshes_desc'

Extension error (sphinx.ext.autosummary):
Handler <function process_generate_options at 0x1038c3eb0> for event 'builder-inited' threw an exception (exception: no module named triqs.gf.meshes_desc)
make[2]: *** [docs_sphinx] Error 2
make[1]: *** [doc/CMakeFiles/docs_sphinx.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by HugoStrand** [comment]
The same seems to apply to many more wrapped modules ending with `_desc` ...

**Comment by the-hampel** [comment]
Hi, 
interesting. The Jenkins CI that builds the Documentation did not have this error 2 days ago with the last push to unstable: https://jenkins.flatironinstitute.org/job/TRIQS/job/triqs/job/unstable/ (the ubuntu clang). However, I can reproduce the error on my machine. I will try to have a look.

**Comment by HugoStrand** [comment]
Dear @the-hampel,

Thank you for reproducing the issue. Is there hope of having this fixed in the near future? I need to be able to build the triqs doc in order to compile the documentation of TPRF, so this is holding me back.

Best, Hugo

**Comment by the-hampel** [comment]
Hi @HugoStrand ,

can you try the following and let me know how your error changes (or not changes): remove the temporary autodoc dirs in the triqs **source** dir: 
```
rm -r doc/documentation/cpp_api
rm -r doc/documentation/python_api
```
Those are weirdly located in the source dir and not the build dir. Hence, they are not cleaned by any mechanism automatically. For me the error disappeared after cleaning those and rebuilding the auto doc from scratch. But maybe I changed something else as well and this was coincidence. But my doc build now looks okay, apart from 100+ warnings.

**Comment by Wentzell** [comment]
> Dear @the-hampel,
> 
> Thank you for reproducing the issue. Is there hope of having this fixed in the near future? I need to be able to build the triqs doc in order to compile the documentation of TPRF, so this is holding me back.
> 
> Best, Hugo

Dear @HugoStrand,

The TRIQS Documentation is no longer required to build the documentation for the applications.

**Comment by HugoStrand** [comment]
Dear @the-hampel and @Wentzell,

Thank you for the feedback. Cleaning the two folders solves all my problems. 👍 

Cheers, Hugo
