### ISSUE TITLE
Making triqs installable with pip

### ISSUE THREAD

**Issue by TheAlaskanPhysicist** [TRIQS/triqs#939]
Hello! I've been having significant issues getting TRIQs to work on Windows, since that is our primary operating system.

I would like if a feature would be added so that I can do `pip install triqs` since both using conda and straight-from-source hasn't been successful on my machine.

Thanks!
Stanley G. (Rochester Institute of Technology)

**Comment by Wentzell** [comment]
Dear @stanieldev,

Thank you for your interest in the TRIQS software.

The TRIQS software depends on various scientific libraries, such as `BLAS/Lackack`, `HDF5` and `FFTW`.
These binary dependencies can unfortunately not be handled within pip.

For Windows we recommend you use the [Windows Subsystem for Linux](https://learn.microsoft.com/en-us/windows/wsl/install), which allows you to install the most recent LTS Version of the Ubuntu Linux distribution.

You can then follow our install instructions for [Ubuntu debian packages](https://triqs.github.io/triqs/latest/install.html#ubuntu-debian-packages) within you embedded Linux environment.
