### ISSUE TITLE
Warning from cmake for the 1.2 branch

### ISSUE THREAD

**Issue by lmessio** [TRIQS/triqs#95]
I have cmake version 2.8.12.2, and get :

 CMake Warning (dev) in CMakeLists.txt:
  Syntax Warning in cmake code at

    /users/lptl/messio/PROGRAMMATION/TRIQS/sources/LIB/CMakeLists.txt:430:253

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by parcollet** [comment]
Still open ?
